### ISSUE TITLE
Hash characters in data URL - support will be removed from Chrome soon

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1001]
When loading the site on a new Chrome you see:

```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
```

We need to find where that's coming from. There's a lot of `data:` URIs used in GoldenLayout, maybe there?

**Comment by RabsRincon** [comment]
What does this mean for older urls. Will they keep working? 🤔

**Comment by mattgodbolt** [comment]
I don't think this refers to our URLs. I think the data URLs (of the form `data:base64thing`) are used in some of our third party dependencies. I did a `git grep` but couldn't find them.

**Comment by jaredwy** [comment]
Webpack does inline some stuff. I need to upgrade webpack anyway.

I can dig in when I have time to do that.
I’m just under the hammer for the next two weeks until feature freeze :(

**Comment by mattgodbolt** [comment]
This doesn't appear to happen any more, either as we've changed things around, or else Chrome decided to keep this misfeature after all...
