### ISSUE TITLE
Embedded view Save/Load doesn't work

### ISSUE THREAD

**Issue by Noviv** [mattgodbolt/compiler-explorer#1006]
Hello - rookie here!

I believe I discovered that the embedded view of CE doesn't actually support Save/Load. For example, on [this post](https://xania.org/201611/compiler-explorer-now-supports-embedded-view) neither view seems to do anything upon clicking Save/Load. I've also tried a local HTML file and the button still didn't work.

Is this a feature I'm oblivious to? Or just a bug? A meaningless button seems like a waste of space for the embedded view.

**Comment by RabsRincon** [comment]
Hi @Noviv Sorry we took so long to get back to you, it's been a busy week!

There is no reason why the embed loadSave would not work, so I'm marking this as a bug. I'll investigate and get back to you in a few days once it's been fixed (If not done by someone else in the meantime!)

Thanks for your patience! :)

**Comment by RabsRincon** [comment]
After some thought and asking Matt about it, we should not even show the loadSave button in the embed view!

I've also disabled the policies getting on the way on the embed view (And assuming that those views on the embed mode do not consent to the cookie policy)

Thanks again for bring this up so we could improve it
