### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by IHackPy** [mattgodbolt/compiler-explorer#1007]
Kindly enhance the more **Language Support**.

**Comment by Noviv** [comment]
I'm not a contributor on this project (just an avid observer), but what compiled output are you looking for with Python? This project is meant to make it easy to examine the output of a compiled language, which Python most definitely is not.

**Comment by phuclv90** [comment]
Until now even JITted languages are still not supported as you can see in #999, let alone an interpreted language like Python.

If you want to see the Python bytecode or compiled pyc output then just go ahead and try adding a new compiler as per the document <https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md>. I doubt that anyone would do this because there are already a lot of compiler adding requests right now

**Comment by IHackPy** [comment]
@Noviv thanks for reviewing & I'm agree with you but I came to that project when I was looking for online compiler and got this one I didn't see any docs So I'm not aware about it is only for compiled Languages .

**Comment by Noviv** [comment]
Sure thing @IHackPy - as @phuclv90 stated, there is actually a discussion about adding JIT languages like C#, but for now Python is probably much lower on the contributors' priorities. Hopefully, that closes your issue!

**Comment by mattgodbolt** [comment]
@IHackPy thanks for your suggestion. You're right that the documentation doesn't explicitly say we're only targeting compiled languages: the project name of "Compiler Explorer" is the only hint of our intent!

Python bytecode support is possible and I'd happily accept PRs to add Python support (if only as a "toy" feature), but it's not high on this project's priorities. https://opensource.com/article/18/4/introduction-python-bytecode has a few notes on the bytecode should that be useful.

**Comment by RobRoseKnows** [comment]
It's also possible to compile Python to C using Cython. That could potentially be useful for comparing languages.

**Comment by mattgodbolt** [comment]
See #503 for Cython. #1612 was merged in, but is'nt 100% there yet: see #1658. Closing this in favour of those issues.
