### ISSUE TITLE
Share/Other dropdowns overlap

### ISSUE THREAD

**Issue by Noviv** [mattgodbolt/compiler-explorer#1011]
Hello, I'm back! Super low priority, but there's a small problem with the Share and Other/Policies dropdown. Basically, if you click Share, then click Other, the Share menu overlaps the Other menu (same with Policies). It sometimes works fine in the other direction.

Since this seems like a fairly simple issue, so if a contributor could just point me in the right direction I'd love to take a crack at this!

**Comment by RabsRincon** [comment]
Hi @Noviv! Thanks for your contunied interest in making CE a better site!

How would you go about fixing it?
The code you're interesed in is in some places:

The `views/index.pug` file represents the structure of the page. You're looking for the `ul.nav.navbar-nav.navbar-right` at line 31 as the parent element for the 3 dropdown menus

The `static/sharing.js` file, specifically the `initShareButton` function on line 115 contains the code that handles opening the share popover (The dropdown menus are handled by bootstrap)
Let us know if you have any other questions

**Comment by Noviv** [comment]
@RabsRincon thanks for the direction, I believe I fixed it (or possibly broke everything) in that PR!

**Comment by dhardy** [comment]
Is this an issue again? I can't see the `Share` button. (It did briefly show at one point, but has gone again.)

**Comment by partouf** [comment]
Can you share some more info on what you're seeing? I don't see any issues live.

**Comment by dhardy** [comment]
Um.. just that I don't see a "Share" button (nothing between "Sponsors" and "Other", nor any space).

**Comment by partouf** [comment]
What browser, OS, any special settings? Screen/window size? Can you also share a screenshot

**Comment by dhardy** [comment]
Fedora 32, Firefox 83. Same behaviour any window size I try; default is about 1250×1440 (half screen minus taskbar) but same fullscreen.
![Screenshot_20201205_162650](https://user-images.githubusercontent.com/134893/101254700-b925c300-3716-11eb-879b-62ec285ca1c8.png)

**Comment by partouf** [comment]
Any javascript errors logged in your developer console?

**Comment by dhardy** [comment]
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. godbolt.org
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “fs_uid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite vendor.v4.f9e1a2e300eefab5a509.js:2:3118160
Cookie “cookieconsent_status” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite vendor.v4.f9e1a2e300eefab5a509.js:2:3118160
```

**Comment by partouf** [comment]
hmm, nothing out of the ordinary there.

**Comment by partouf** [comment]
Can you see what happens when you close the tab on the right called "#1 with rustc 1.48.0"? (guessing a tool that failed to produce output?) and then refresh?

**Comment by dhardy** [comment]
Same. Even if I remove the editor and compiler windows completely, I don't get a "Share" button.

**Comment by partouf** [comment]
@mattgodbolt can you see what you get, I don't have a Linux desktop setup, and Firefox 83 on Windows doesn't show this issue.

**Comment by mattgodbolt** [comment]
Using Ubuntu 20.04 Firefox 83, I see:

![Screenshot from 2020-12-05 11-32-57](https://user-images.githubusercontent.com/633973/101259294-ad71d680-36ed-11eb-9a2d-41f6e99c462b.png)

@dhardy do you have any adblocker plugins?

**Comment by dhardy** [comment]
@mattgodbolt yes, I have uBlock Origin (and a few other tools). Disabling uBlock fixes this — sorry I didn't check earlier, but it claims not to block anything on the page. Weird.

**Comment by mattgodbolt** [comment]
It's just a `<div id="share">` so I don't know what's going on, sorry.

**Comment by dhardy** [comment]
Me neither. Sorry to bother you.

**Comment by mattgodbolt** [comment]
No worries! Are there specific things on the page you /do/ block, btw? Or is just because uBlock is on all the time by default?

**Comment by dhardy** [comment]
Just on by default. It says it's blocking nothing there. I didn't tweak the ruleset, just default behaviour (I think).
