### ISSUE TITLE
See compiler stdout as well stderr

### ISSUE THREAD

**Issue by travisdowns** [mattgodbolt/compiler-explorer#1016]
Compilers sometimes put interesting output on stdout as well as stderr, e.g., gcc with options such as `--help=target`. It would be nice to see be able to see this output in godbolt (it appears to me that it currently only shows stderr).

**Comment by mattgodbolt** [comment]
Do you have an example link? We process both stdout and stderr, as best I can tell. There appears to be a separate problem where if the compiler doesn't output a file CE gives a `Compiler returned: ENOENT`, which I'll file separately: #1019

**Comment by travisdowns** [comment]
@mattgodbolt - sure, [here is an example](https://godbolt.org/g/irWiFr).

Confusingly, that is an example of it *working*. I never got it to work before (this would give exactly the `ENOENT` message you mentioned above), so you've fixed it in #1019 I guess, thanks! 

A weird note, now that I can see the output, I can see that `-march=native` in my example above shows gcc detecting `-march` as KNL. I'm pretty sure you're not running this stuff on KNL so that must be a weird gccism or bug. I does mean that users who use `-march=native` on goldbolt might sometimes get some weird codegen at least on that version (although I haven't noticed it doing anything crazy personally).
