### ISSUE TITLE
suppress Wine errors

### ISSUE THREAD

**Issue by Trass3r** [mattgodbolt/compiler-explorer#1017]
https://godbolt.org/g/oBouwM

```
003c:fixme:msvcrt:_configure_wide_argv (2) stub
003c:fixme:msvcrt:_initialize_wide_environment stub
003c:fixme:ntdll:EtwEventRegister ({3124649c-36c0-5879-4b0e-fe163528322b}, 0x14002e264, 0x14005e870, 0x14005e890) stub.
003c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x140056a7c, 28) stub
...
```
Looks like `WINEDEBUG=-all` could do the trick.
https://wiki.winehq.org/Wine_Developer%27s_Guide/Debug_Logging#Controlling_the_debugging_output

**Comment by mattgodbolt** [comment]
Great stuff: I was doing some (ineffective!) filtering of the output. Thanks!

**Comment by Trass3r** [comment]
Thank you for Compilet Explorer! :)

**Comment by Trass3r** [comment]
Nice it works!
Now the only reason msvc is marked yellow in the conformance view is the printed source filename example.cpp. Looks like that can't be disabled and needs to be filtered: https://stackoverflow.com/questions/1453767/prevent-cl-exe-from-printing-the-compiled-source-file
(or a missing -nologo switch, maybe that could be passed automatically)

**Comment by mattgodbolt** [comment]
Opened #1034 to track this (also was confused by the above note that @RabsRincon referenced the bug in a change I committed? weird!)
