### ISSUE TITLE
Compiler options presets

### ISSUE THREAD

**Issue by TomSmartBishop** [mattgodbolt/compiler-explorer#1024]
I tried adding presets for compiler options. My current idea is to use a HTML datalist, so that you can either type your options or just select one from the drop down. Ideally these presets would be specified in a properties files (maybe tied to the compiler?) but so far I couldn't figure out where /how the data from the properties files comes in and how I could populate the empty datalist with that data. Any ideas?

**Comment by RabsRincon** [comment]
@partouf great addition of popular aguments fill this need pretty good
