### ISSUE TITLE
Asm doc assumes that the output ISA is always x86 on any targets

### ISSUE THREAD

**Issue by phuclv90** [mattgodbolt/compiler-explorer#1025]
Even if we change the compiler to MIPS, ARM, PPC or any other architectures, asm doc still interprets the instructions as x86 instructions and shows the x86 description for `add`, `nop`... or "This token was not found in the documentation. Sorry!" for others

We should disable asm doc on non-x86 compilers at first. In the future it'll be great to add asm doc support for other architectures

**Comment by RabsRincon** [comment]
Hi! I've just pushed a change which stops the tooltip form being shown if we know that Intel asm mode is not supported by the current compiler. Note that this solution is not perfect, but it should help with the most glaring arch missmatches. We will eventually come up with a more precise solution, but those things will take some time.

Thanks for taking the time to file this issue :)

Closed by ba5661931c6c3fdf0d2175bab0adb882343cbb24
