### ISSUE TITLE
Compile time exceeded for Blaze include

### ISSUE THREAD

**Issue by dbeurle** [mattgodbolt/compiler-explorer#1028]
See https://godbolt.org/g/dncMgd

Is it possible to extend the compilation limit for this library?

**Comment by mattgodbolt** [comment]
It is...but...it's a slippery slope. See mattgodbolt/compiler-explorer-image#95 - running a simple test takes 22 seconds to build anything including Blaze :(

This is a problem with our shared network drive solution. We are trying to come up with a solution to this (see mattgodbolt/compiler-explorer-image#53 and https://groups.google.com/forum/#!topic/compiler-explorer-development/NYhr_cYKpe8

If we bump the timeout we (currently) have to do it globally. Putting it up to ~30s would:

* Leave the site wide open to an accidental DoS
* Not really be the interactive experience CE is trying to be

However, I'm open to doing so, but need to think about it and how we might mitigate the DoS thing.

**Comment by dbeurle** [comment]
Thanks for the info, and sorry for the delay on a reply - I somehow missed the notification on this.  Just simply including Blaze is relatively slow on my local machine, especially in comparison to Eigen which works without a hitch on CE.  I'm not held up by this not working - so no pressure from my side.  If you have any suggestions for improving the parsing performance I am happy to pass those along in a bug to Blaze.

I'll close this bug and follow the referenced bug.

**Comment by mattgodbolt** [comment]
Work in compiler-explorer/infra#445 means this might become achievable

**Comment by mattgodbolt** [comment]
(A test locally took ~3-4s to build with the squashfs stuff on vs nearly 30s otherwise)
