### ISSUE TITLE
Asm doc works even on non-instruction words

### ISSUE THREAD

**Issue by phuclv90** [mattgodbolt/compiler-explorer#1030]
It seems that the asm doc works on a single token. Therefore if we [name a label/function the same as an instruction][ret] it'll still show the man page for that instruction

Instructions after the prefix like `repz retq` also work due to the same reason. However asm doc doesn't work for the REPx prefixes

  [ret]: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:1.0749542399999998,j:1,lang:c%2B%2B,source:'void+ret()+%7B%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:30.568256041802748,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,filters:(b:'0',binary:'0',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'1',trim:'0'),lang:c%2B%2B,libs:!(),options:'',source:1),l:'5',n:'0',o:'x86-64+gcc+(trunk)+(Editor+%231,+Compiler+%232)+C%2B%2B',t:'0')),k:69.43174395819726,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by RabsRincon** [comment]
Hi @phuclv90 thanks for the report :)
Unfortunately, we depend on what Monaco editor asm tokenizer tells us the current token is. 
If it gets confused and reports an incorrect `keyword.asm`, there's nothing we can do. 

Note that it's not happening for me in your current example. Can you try again? Maybe it got automagically fixed!

**Comment by phuclv90** [comment]
It's still happening. If you put the cursor on the ret function and press Ctrl+F8, the RET man page will open

**Comment by RabsRincon** [comment]
Thanks for the info. We might be able to fix it downstream somehow. I've also just pushed a change that will stop showing the docs when the intel mode is disabled by the compiler config :)

We'll try to see what can be done

**Comment by danilaml** [comment]
Hm, I experience the opposite: the documentation only shows up for the first token on the line, i.e. for `lock cmpxchgq` it'll only be available for `lock` but not for `cmpxchgq`. If I remove `lock` I can then view doc for the latter instruction.
