### ISSUE TITLE
Remove header code from MSVC Assembler Output

### ISSUE THREAD

**Issue by ubsan** [mattgodbolt/compiler-explorer#1031]
Example implementation [here][example-impl]

Basically, unlike GCC and clang, MSVC outputs assembler for inline functions in headers. It would be nice to be able to not output that assembler, because as one can see [here][example-iostream], there's a bunch of unnecessary output.

Would this be a thing people are willing to change?

[example-impl]: https://github.com/ubsan/compiler-explorer/tree/hide-header-code
[example-iostream]: https://godbolt.org/g/3ptR6J

**Comment by mattgodbolt** [comment]
Discussed with @ubsan over Discord and she is going to move her branch into this project for further tweaking. There are some other considerations, we'll discuss in a PR.
