### ISSUE TITLE
 32-bit or cross-compiled Rust option

### ISSUE THREAD

**Issue by MagaTailor** [mattgodbolt/compiler-explorer#104]
It would be nice to be able to emit 32-bit code too.

For pure library code this could be achieved with e.g. `--target=i686-unknown-linux-gnu` and availability of a separate set of crates. No cross-tools would even need installing.

This method could also enable ARM output, etc. The crates can be got from the official distribution channel:
http://static.rust-lang.org/

**Comment by CryZe** [comment]
If you use no_core and copy the relevant stuff from libcore into the code, this already works with all rustc's predefined targets:

https://godbolt.org/g/Dw8Dpn

Most of these should work (not all though, like wasm and asmjs, as the nightly is too old for those):

- aarch64-linux-android
- aarch64-unknown-linux-gnu
- arm-linux-androideabi
- arm-unknown-linux-gnueabi
- arm-unknown-linux-gnueabihf
- arm-unknown-linux-musleabi
- arm-unknown-linux-musleabihf
- armv7-linux-androideabi
- armv7-unknown-linux-gnueabihf
- armv7-unknown-linux-musleabihf
- asmjs-unknown-emscripten
- i586-pc-windows-msvc
- i586-unknown-linux-gnu
- i686-apple-darwin
- i686-linux-android
- i686-pc-windows-gnu
- i686-pc-windows-msvc
- i686-unknown-dragonfly
- i686-unknown-freebsd
- i686-unknown-haiku
- i686-unknown-linux-gnu
- i686-unknown-linux-musl
- le32-unknown-nacl
- mips-unknown-linux-gnu
- mips-unknown-linux-musl
- mips-unknown-linux-uclibc
- mips64-unknown-linux-gnuabi64
- mips64el-unknown-linux-gnuabi64
- mipsel-unknown-linux-gnu
- mipsel-unknown-linux-musl
- mipsel-unknown-linux-uclibc
- powerpc-unknown-linux-gnu
- powerpc64-unknown-linux-gnu
- powerpc64le-unknown-linux-gnu
- s390x-unknown-linux-gnu
- thumbv6m-none-eabi
- thumbv7em-none-eabi
- thumbv7em-none-eabihf
- thumbv7m-none-eabi
- wasm32-unknown-emscripten
- x86_64-apple-darwin
- x86_64-pc-windows-gnu
- x86_64-pc-windows-msvc
- x86_64-rumprun-netbsd
- x86_64-sun-solaris
- x86_64-unknown-bitrig
- x86_64-unknown-dragonfly
- x86_64-unknown-freebsd
- x86_64-unknown-fuchsia
- x86_64-unknown-haiku
- x86_64-unknown-linux-gnu
- x86_64-unknown-linux-musl
- x86_64-unknown-netbsd
- x86_64-unknown-openbsd

**Comment by CryZe** [comment]
A general solution would be to either just download the compiled libcores or use xargo to build them on the fly (which would slow down everything though)

**Comment by MagaTailor** [comment]
It seems due to rust hype I mistakenly believed the missing features were important, at the same time underestimating the amount of work required.

**Comment by BohdanM-AVISPL** [comment]
I don't know if that was the case when this Issue was created, but now it jsut wors if you add mentioned `--target=i686-unknown-linux-gnu` to compiler options in Godbolt.

Adding this comment, in case anybody stumbles on this Issue from Google search as I did.

Example:
![image](https://user-images.githubusercontent.com/90767530/236182921-2bf99b1e-2e2a-4e27-8acb-6ef45d8ce8ac.png)
