### ISSUE TITLE
stdexcept missing when compiling in 32-bit mode with clang-trunk

### ISSUE THREAD

**Issue by pps83** [mattgodbolt/compiler-explorer#1041]
stdexcept [can be included](https://godbolt.org/g/EwfhW7) when compiling using clang-trunk, however, when you use `-m32` to compile in 32-bit mode stdexcept [becomes missing](https://godbolt.org/g/stn7z6) and the error output is:

```<source>:1:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
1 error generated.
Compiler returned: 1```

**Comment by cpplearner** [comment]
Per #431, you need `-stdlib=libc++`. (If you need to use libstdc++, `--gcc-toolchain=/opt/compiler-explorer/gcc-snapshot` seems to do the trick.)

**Comment by mattgodbolt** [comment]
Seems to have become fixed along the way.
