### ISSUE TITLE
Sanitize short URL POSTed input to make sure it looks like CE state

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1048]

**Comment by mattgodbolt** [comment]
@RabsRincon - any thoughts on this? It's the last open issue to do with link shortening :) I can take a look unless you have an idea?

**Comment by partouf** [comment]
To check for format and some kind of code, you could use the clientstate facilities now. Shouldn't be too slow, I think. So something like /resetlayout does, except for the goldenifier stage instead check if there's code.

**Comment by mattgodbolt** [comment]
Thanks @partouf that was a great lead. However, I spent some time thinking about this: anything we do will have to be a super trivial check or else risk people not being able to save their short links. And anything we do will be trivially easy to get past, just by implementing enough JSON storage to "fool" the checks we put in place.

So: I think I'm going to close this one. If we ever suspect people are using us for storage bad things we can take another look at this. Thanks all!
