### ISSUE TITLE
favicon mentioned in short link expansion is wrong

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1049]
http://iframely.com/debug?uri=https%3A%2F%2Fgodbolt.org%2Fbeta%2Fz%2FMGQxYj

icon comes out as: https://godbolt.org/beta/z/favicon.ico?v=1

**Comment by RabsRincon** [comment]
I'm seeing a totally different behaviour., for https://godbolt.org/beta/z/YjhhOT:
Beta favicon points to `https://godbolt.org/favicon.ico?v=1`
Same with `vs/loader.js` and `vs/editor/editor.main.*`
Which means we're using prod scripts. Note that the assets such as social icon do properly use `/beta/` paths

**Comment by mattgodbolt** [comment]
With that link I see `/undefined?v=1` being fetched as the favicon (checked just now)

**Comment by mattgodbolt** [comment]
```<!DOCTYPE html><html lang="en"><head><base href="/beta"><script src="vs/loader.js"></script><link rel="icon" href="undefined?v=1">```

**Comment by mattgodbolt** [comment]
Shell golf :grinning: :

```
~ $ curl -s 'https://godbolt.org/beta/z/YjhhOT' | grep -oE '\<link[^>]+'
link rel="icon" href="undefined?v=1"
link href="/beta/dist/main.ae50d40bf5416bcaad172f711899ea65.css" rel="stylesheet"
linked code lines on hover</label
```

**Comment by mattgodbolt** [comment]
Closing: I'm pretty sure the site I linked is wrong.
