### ISSUE TITLE
zig support

### ISSUE THREAD

**Issue by shawnl** [mattgodbolt/compiler-explorer#1060]
https://ziglang.org/

zig is built upon llvm. You should probably just track master right now, as the language is changing.

**Comment by andrewrk** [comment]
I don't think @tiehuis ever made a PR but I believe he got it working: https://github.com/tiehuis/compiler-explorer

Let me know if there are any command line interface adjustments I can make; happy to cooperate with the compiler-explorer team.

**Comment by RabsRincon** [comment]
Hi! Sorry for taking so long to get back to you! 
For this to be viable, we would need:

- A way to either build trunk daily, or a place to get the binaries from (That would be a PR on the sister repo at https://github.com/mattgodbolt/compiler-explorer-image)

- The fork you mention has most of the elements needed to make it run here, so a PR with that should not need too many changes (At first glance)

Let us know if you need any help

**Comment by andrewrk** [comment]
One thing we have is this URL: https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz
This URL redirects to master branch builds that passed CI. The build is a 100% self-contained static linux binary (even libc is static), so you can just untar and run it, and it's about 25MiB.

**Comment by RabsRincon** [comment]
That's great!
So: The fork you showed is almost-ok to get merged (Will discuss it further once it actually gets opened)
As for the server side one, I can point you at https://github.com/mattgodbolt/compiler-explorer-image/pull/45 and https://github.com/mattgodbolt/compiler-explorer-image/pull/60/files (Both by @partouf ) as examples, which added  languages/compilers.

In short, you need to add some lines to https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh that install it in an appropiate place

Thanks again for doing it for us, we're short of time around here :)

**Comment by andrewrk** [comment]
For the benefit of whoever is working on the PR, here is an example command line to get desired results:

`test.zig`:

```zig
export fn add(a: i32, b: i32) i32 {
    return a + b;
}
```

command line:

```
zig build-obj test.zig --strip --release-fast --emit asm
```

This creates `./zig-cache/test.s`:

```asm
	.text
	.file	"test"
	.globl	add
	.p2align	4, 0x90
	.type	add,@function
add:
	leal	(%rdi,%rsi), %eax
	retq
.Lfunc_end0:
	.size	add, .Lfunc_end0-add


	.section	".note.GNU-stack","",@progbits
```

**Comment by tiehuis** [comment]
My original branch was working fine last I checked but it is a bit behind right now. Some extra things to do on top of those changes would be:
 - Update the syntax highlighting
 - Add a dummy panic handler `while (true)` so the debug codegen is nicer. Unlike say, Rust, we inline std even in debug and so the panic handler and all its dependencies (formatting parsing etc) are otherwise pulled in.

Otherwise, should be straightforward.

**Comment by andrewrk** [comment]
> Add a dummy panic handler

I think I would recommend this for the dummy panic handler:

```zig
extern fn zig_panic() noreturn;
pub inline fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    zig_panic();
}
```

Of course, `zig_panic` will never be defined, but it won't matter because we're only doing `build-obj`.

**Comment by monouser7dig** [comment]
> zig build-obj test.zig --strip --release-fast --emit asm

tried and works great 👍

**Comment by RabsRincon** [comment]
That looks great!
We would welcome a PR at any moment. 
And again, we're sorry that we lack the time to implement it for ourselves. If someone gets on it, please do let us know :)

**Comment by tiehuis** [comment]
That's not a problem, happy to implement this. I've got an updated branch but I'm just working through an issue where temporary directories aren't being created. Expect a PR shortly.

https://github.com/tiehuis/compiler-explorer/tree/zig-support

**Comment by cosineblast** [comment]
It seems one can only generate output with `export` functions, which is a little bit annoying when working with non `export` structs and unions. Is there a known workaround for this?

**Comment by andrewrk** [comment]
it's how zig works - there is only one compilation unit. This has nothing to do with the compiler-explorer project. If you want to learn more I suggest making a post in one of the zig communities, such as https://ziggit.dev/
