### ISSUE TITLE
Conformance Viewer doesn't appear to work with library code

### ISSUE THREAD

**Issue by rparolin** [mattgodbolt/compiler-explorer#1061]
The conformance view throws an error about missing EASTL header files that succeeds in the regular workflow.  

Example:
https://godbolt.org/beta/z/voEsaM

**Comment by RabsRincon** [comment]
Good catch. It did not cross my mind that it would be needed!

I'm adding a library dropdown to the conformance view shared between every compiler you add.

**Comment by rparolin** [comment]
Excellent!  Thanks in advance.
