### ISSUE TITLE
Non-ascii in short URLs doesn't work

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1064]
From Twitter: "@mattgodbolt Sharing of code containing non-ASCII codepoints with a short URL seems to be broken, see e.g. https://t.co/ExqRXIw6a9 (should be Чебышёв)."

**Comment by eggrobin** [comment]
To clarify, it used to work, and indeed the goo.gl-based short URLs still work, e.g., https://godbolt.org/g/yJyAly from 2016.
The new shortening doesn't: https://gcc.godbolt.org/z/57ZG0A for the same, where `U+066D ARABIC FIVE POINTED STAR (٭)` gets turned into `U+00D9 LATIN CAPITAL LETTER U WITH GRAVE (Ù)` `U+00AD SOFT HYPHEN (­)`.
The misencoding is the classic UTF-8 interpreted as Latin-1 (`U+066D` is `D9 AD` in UTF-8).

**Comment by RabsRincon** [comment]
Ey @eggrobin! Thanks for the report, it helps a lot :)

The good part is that we're correctly storing it, and it gets as far as being transmitted properly, as you can see the proper characters in the meta descriptions used for social sharing unfurlings on  `<head>`

We have to check where it gets all confused, but once we do that, it should not be a problem to get every link to work retroactively :)

**Comment by RabsRincon** [comment]
Thanks again for the report. It has now been fixed on master with c7f54643a90222c712cdae055ce474cf7371133d. It should hit the live site this week :)
