### ISSUE TITLE
iframe "edit in Compile Explorer" button is not working

### ISSUE THREAD

**Issue by hanickadot** [mattgodbolt/compiler-explorer#1065]
The buttons opens default page with Compile Explorer and not my code. Probably issue with new url shortener. The link is just "https://compiler-explorer.com/#version:4". There is no information in the link.

**Comment by RabsRincon** [comment]
Hi @hanickadot, great catch! It's a bit embarassing that I did not check the link before releasing the new shortener stuff.
I'll try to see if it can be fixed. Thanks for the report :)

**Comment by mattgodbolt** [comment]
Also, note that `compiler-explorer.com` isn't properly set up yet (my fault!) -- will fix... did you hit compiler-explorer.com for the original link?

**Comment by hanickadot** [comment]
Yep, it's from compiler-explorer.com I think :)

**Comment by mattgodbolt** [comment]
Thanks Hana, I didn't realise people were using that! I'll fix that (but I don't think that';s the cause of this bug)

**Comment by RabsRincon** [comment]
Turns out, it was working when we first released the short links! But I broke it when implementing the dynamic url changes!
Thanks again! :D
