### ISSUE TITLE
Disassembly for UD Instruction doesn't work!?

### ISSUE THREAD

**Issue by gerschdn** [mattgodbolt/compiler-explorer#1071]
I have the following short example that givs a non-POD type argument to an ellipsis (...):

https://gcc.godbolt.org/z/anihTD

The disassembler in compiler-explorer gives me the following output:

        push    ebp
        mov     ebp, esp
                .value  0x0b0f

If I compile it on my local machine and disassemble with objdump I get the following:

   0:	55                   	push   %ebp
   1:	89 e5              	mov    %esp,%ebp
   3:	0f 0b               	ud2a  

The "value" 0x0b0f is actual an UD2 instruction for intel processors.

It seems as if compiler-explorer is not able to disassemble the UD instruction :-(

**Comment by mattgodbolt** [comment]
Hi @gerschdn! Thanks for the report. Compiler Explorer doesn't disassemble the code (by default): it shows the assembly output of the compiler. It seems GCC 4.4.7 doesn't emit the "UD2" instruction to the assembler in this case: perhaps the assembler back then didn't support it.

To see the actual code, hit the `11010` button which compiles, links and then disassembles. That yields: https://gcc.godbolt.org/z/A2dt5p which shows the `ud2`.

(It's not clear to me why the compiler would emit a UD2 here, as later versions of the compiler don't. Even putting `__builtin_unreachable()` doesn't generate a UD2.)
