### ISSUE TITLE
movbe is undocumented

### ISSUE THREAD

**Issue by gsauthof** [mattgodbolt/compiler-explorer#1072]
Example:

https://godbolt.org/z/a16fXy

Part of the assembler output is movbe, i.e.:

     movbe   eax, DWORD PTR [rdi]

It's documentation isn't reachable from the explorer, i.e. I don't get any hint and when I explicitly select 'View x86-64 opcode doc' I get:

    Compiler #1: This token was not found in the documentation.Sorry!

However, it's part of the felixcoutier.com pages that are usually linked:

http://www.felixcloutier.com/x86/MOVBE.html

**Comment by gsauthof** [comment]
Btw, SHR isn't documented, as well: https://godbolt.org/z/00PWGZ

Altthough SHL is documented.

**Comment by mattgodbolt** [comment]
Thanks! We derive all our documentation from a hacky parse of Felix's stuff, so something must be going wrong there!

**Comment by mattgodbolt** [comment]
Closing and adding these missing instructions to #362
