### ISSUE TITLE
MSVC compiler fails with /analyze option due to missing DLL

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1075]
With the /analyze option set, Compiler Explorer produces the following
error output:

```
<source>: fatal error C1108: unable to find DLL: 'mspft140.dll'
Internal Compiler Error in Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64_x86\cl.exe.
You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64_x86\cl.exe'
Please choose the Technical Support command on the Visual C++ Help menu,
or open the Technical Support help file for more information
Compiler returned: 2
```

`mspft*.dll` implement "PREFast", which is turned on with /analyze.

Seems it's probably missing from the hacky WINE install, see https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_nonfree_compilers.sh#L39

**Comment by ubsan** [comment]
This'll be fixed when MSVC is run on top of windows.

**Comment by partouf** [comment]
With the introduction of the Windows remote, I think we can consider this issue to be resolved.
