### ISSUE TITLE
GoldenLayout config came with bad "maximisedItemId" key

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1077]
As reported by Chandler Carruth on Twitter (https://twitter.com/chandlerc1024/status/1042496240724926465) , https://gcc.godbolt.org/z/FoAF4T fails to load, with the cause initially looking like a faulty `"maximisedItemId"` value in the stored state config.

For most states we have `"maximisedItemId":null`, but this specific case had `"maximisedItemId":"__glMaximised"`. I'm guessing that it being a string is not something that should happen, but alas!

We need to check if this is something other than a 1 time off error, if it's an error on our side somehow, else let the people at GoldenLayout know (@mattgodbolt ), as they might know what's up.

**Comment by mattgodbolt** [comment]
Sentry issue: [COMPILER-EXPLORER-3A5](https://sentry.io/compiler-explorer/compiler-explorer/issues/454120205/)

**Comment by mattgodbolt** [comment]
Chandler doesn't recall doing anything specific with minimised or maximised links beforehand.

**Comment by mattgodbolt** [comment]
Some sort of mentions of this in https://github.com/golden-layout/golden-layout/issues/253, possibly unrelated.

**Comment by mattgodbolt** [comment]
Ok! So if you do maximise a pane (e.g. https://godbolt.org/z/U7DbOr ) and look at `window.compilerExplorerOptions.config.maximisedItemId you'll see it is in fact `"__glMaximised"`

But...this link works. I wonder what triggered Chandler's link to have this (when he doesn't recall doing any maximise), and also why does it not work in his case?

**Comment by mattgodbolt** [comment]
reprod! Maximise the window, then close it!

https://godbolt.org/z/_sxC3L

**Comment by mattgodbolt** [comment]
Full repro steps:

* Reset UI
* Maximise ASM window
* Close ASM window
* Make short link
* Follow short link
* See crash!

Looks like it's a fault in GL though. We can try and catch it and work around though. I don't much fancy opening up the GL update can of worms...

**Comment by mattgodbolt** [comment]
There's already a bug in GL: https://github.com/golden-layout/golden-layout/issues/384 is the actual issue (not the one I linked earlier)

**Comment by partouf** [comment]
Even when you have a working maximized link, adding a window/compiler does some weird things until you un-maximize.

When you maximize a window, it gives the stack an id property with value "__glMaximised" and references to that in config.maximisedItemId. But when you close the windows it doesn't set config.maximizedItemId to null anymore.

So the workaround fix that works is to set: config.maximisedItemId = null;
The question is whether to just always do this or only when there is no stack that has that id...

**Comment by partouf** [comment]
There's now a workaround active on the site that resets every layout that has this or possible any future problems.

Considering goldenlayout's original repo seems rather inactive, perhaps it's an idea to make our own fork and merge this PR https://github.com/golden-layout/golden-layout/pull/469 to actually fix the problem?
