### ISSUE TITLE
Zig encounters some problems when compiling

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1083]
So Zig is now on the beta nodes, and it seems to be having a hard time when running from the site (@mattgodbolt has already confirmed it runs fine if ran directly on the nodes)
A simple repro link: https://godbolt.org/beta/z/U0YoIU

The compiler emits:
```
unable to open example.h: Read-only file system
/compiler-explorer/c-preload/compiler-wrapper: line 21:  3158 Aborted                 (core dumped) "$@"
Compiler returned: 134
```
CC @tiehuis & @andrewrk - What example.h is it trying to load?

**Comment by mattgodbolt** [comment]
https://godbolt.org/beta/z/HEfbrT that gives an error of `Unexpected extra parameter`. @andrewk you can play around a bit on the beta site (godbolt.org/beta) and see if you can help. The sandbox environment tries to prevent output to locations the compiler "shouldn't" be writing to. Looks like the header file is dumped unconditionally to the current directory?

**Comment by andrewrk** [comment]
When I mouse-over the information icon it shows this:

`build-obj --cache-dir /tmp/compiler-explorer-compiler118823-54-gg2917.fjvz7 --output /tmp/compiler-explorer-compiler118823-54-gg2917.fjvz7/output.s --emit asm -mllvm --x86-asm-syntax=intel /dev/null /tmp/compiler-explorer-compiler118823-54-gg2917.fjvz7/example.zig`

It's missing the `--output-h` parameter, which I think means that it is included in the "filter" set. It should be filtered as well as hard coded to be `/dev/null` in the configuration.

**Comment by andrewrk** [comment]
By the way I think it would be a better user experience if filtered options generated a user-visible error rather than being silently stripped. As one argument for this, the status quo behavior confused @mattgodbolt.
