### ISSUE TITLE
Consider adding all C++ compilers to C as well.

### ISSUE THREAD

**Issue by farrrb** [mattgodbolt/compiler-explorer#1102]
I would like to propose to add all C++ compilers for C as well.

I'm doing a lot of work on the ARM platform in C and for now i always change to language to C++ because the arm gcc is not listed. It is not really a problem but at first I found it to be quite confusing.

**Comment by RabsRincon** [comment]
Hi, thanks for bringing this to our attention! Sorry for the inconvenience that the lack of arm is causing.

I'll be sure to check which compilers we are missing and ensure they get their C counterpart in the next prod release. :)

**Comment by farrrb** [comment]
Hey, that's great news. I really like the compiler explorer, keep up the good work!

**Comment by RabsRincon** [comment]
Sorry for taking so long! The site should receive an update during the weekend, which will include every cross gcc version available on C++
Thanks again for bringing this to our attention! :)
