### ISSUE TITLE
Move privacy & cookie consents storage location

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1109]
Privacy and cookie consent are currently stored on localStorage, which means subdomains get a different version, thus showing the popups even though the user has already agreed. 

By storing it on cookies, we will be able to hold only one copy of the consent. We might be able to time it with a policy change so we dont have to create additional fallback handlings

**Comment by RabsRincon** [comment]
Yes, using the cookie upstream version should work, but note that it needs to be forked still, as their "consent" status can not be configured to use a hash instead of a static string, or so it was when I first added it (After talking with them it seems like it is a conscious decision, so it probably has not changed in that regards)

**Comment by mattgodbolt** [comment]
Understood! We'll wind forward your forked version and use that :) And then merge into #1125 too
