### ISSUE TITLE
Button to run "clang-format" on code

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#111]
Suggestion via John Regehr

**Comment by mattgodbolt** [comment]
Also requested by chedy najjar on C++ slack

**Comment by mattgodbolt** [comment]
Chedy suggests breaking each statement (or sub-statement) on a new line to allow for better colourisation. https://godbolt.org/g/vCgL0e for exampe

**Comment by mattgodbolt** [comment]
This might be quite straightforward and self-contained now. Basic idea would be to add a new POST endpoint which runs `clang-tidy` (now available in `/opt/compiler-explorer/clang-5.0.0/bin/clang-format` amongst other clang locations). Upon receiving the response, one can replace the text (provided it has not changed since the request was made). Configuration would be another issue, of course.

**Comment by RabsRincon** [comment]
I did implement most of this back in the day (See the `formatting` branch if you need some inspiration!) 
And the trickier part is the UI actually! 
Anyone who tries to finish this, you're welcome to either doing it from scratch or picking up from where the format library left it

**Comment by mattgodbolt** [comment]
Wow! I forgot you did that @RabsRincon :)

**Comment by devjgm** [comment]
+1 to this feature request. In my dreams, clang-format is run automatically, perhaps each time the compile is run. Bonus points for having a setting in the UI to set the [clang-format `--style` argument](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#clang-format-style-options).

**Comment by ricco19** [comment]
Just a button with the default `clang-format` style would be fantastic, it's particularly nice for when people post code to websites like stackoverflow in some horrendous format, and you are just trying to figure out what is going on. Being able to format it in a sane way whilst at the same time seeing compiler output would be incredibly useful.

**Comment by RabsRincon** [comment]
Hi! This is already an implemented feature as of e5ee5a2 (Sorry, we missed tagging this issue!). Right clicking on the code editor, and pressing the "Format code" (Or F9 as a keyboard shortcut) will clang-format it based on your preferred clang-format style, which you can define in the Settings, which can be found in `More > Settings`

:)

**Comment by pwuertz** [comment]
Hi! I'm having trouble with configuring the code formatting feature on a local compiler explorer instance.
I tried adding the following sections to `c++.defaults.properties`:
```
tools=clangformat
tools.clangformat.exe=/usr/bin/clang-format-10
tools.clangformat.name=clang-format
tools.clangformat.type=independent
tools.clangformat.class=clang-format-tool
```
and/or
```
formatters=clangformat
formatter.clangformat.name=clang-format
formatter.clangformat.exe=/usr/bin/clang-format-10
formatter.clangformat.styles=Google:LLVM:Mozilla:Chromium:WebKit
```
Trying to format the code gives me a bottom-right error bubble though:
```
We ran into some issues while formatting your code: Tool not supported
```
The list of `formatters` in `formatting.js` `Formatter` never seems to be populated.

Any hint on how to activate clang-format?

**Comment by mattgodbolt** [comment]
HI @pwuertz.

The ctrl-F9 feature is controlled by the `formatter`s options (the second block). That's part of the `compiler-explorer` properties, so you'll need to edit `compiler-explorer.*.properties` and add the `formatters=` there.

As an aside, rather than editing the `defaults` or similar (which leads to potential problems if you `git pull`), you can create a fresh new `compiler-explorer.local.properties` and just put overrides in that. For example, you could put just the block you have above in that file to get the formatting working. This `*.local.properties` is configured to be ignored by git so you won't have issues down the line.

Hope that helps and solves your problem!

**Comment by pwuertz** [comment]
Works like a charm. Also thanks for the `.local.properties` overrides :)

**Comment by mattgodbolt** [comment]
Fantastic! Glad it worked out!
