### ISSUE TITLE
Auto-convert gcc/clang options when trying MSVC

### ISSUE THREAD

**Issue by jorgbrown** [mattgodbolt/compiler-explorer#1135]
Example: https://gcc.godbolt.org/z/3LUyj1

It looks like "-O2" is automatically converted to "/O2" if the compiler is MSVC, which is great.

"-std=c++17" should automagically convert to "-std:c++17"  ( i.e. https://gcc.godbolt.org/z/5U6UN8 )

**Comment by partouf** [comment]
I'm afraid -O2 is just recognized by the MSVC compiler, CE doesn't convert anything at the moment

**Comment by mattgodbolt** [comment]
This is a lovely idea: but I don't think it's our place to try and solve the general compatibility of flags between compilers. Thanks for the suggestion; happy to argue more but this is so low on priorities for us that I think it's best to close rather than offer false hope it'll be attended to.
