### ISSUE TITLE
Make it possible to copy the compilation options

### ISSUE THREAD

**Issue by Lectem** [mattgodbolt/compiler-explorer#1140]
If you display the "all compilation options", you can not select the text to copy it.
It would be nice if we could either select the text for copy and/or have a button to copy it!
![ce-cantcopy](https://user-images.githubusercontent.com/6024225/47662659-a3d72580-db9b-11e8-8741-c08fabfe5bf6.gif)

**Comment by RabsRincon** [comment]
Quite the oversight from my part. I'll fix it for the next release. Thanks for reporting it :)
