### ISSUE TITLE
Run escape analysis for GO

### ISSUE THREAD

**Issue by igmor** [mattgodbolt/compiler-explorer#1142]
It would be an incredibly useful addition to the tool! 
`go run -gcflags '-m -l'`

**Comment by mattgodbolt** [comment]
We don't run `go` directly, and we don't run the executables we build (which I am guessing is what `go run` does?). Help is apprecaite to work out how to run the `go` compiler with the appropriate flags :)

**Comment by igmor** [comment]
You can get escape analysis with go build as well. `go run -gcflags '-m -l'`

**Comment by RabsRincon** [comment]
Did you mean to type different options on your second message @igmor? I can't see the `go build` I'd expect

**Comment by partouf** [comment]
Just tested this.
We can do 'go tool compile -m -l -o output.o file.go without -S, and then stdout will be things like:

```
/tmp/go/test.go:28:13: isZero x does not escape
/tmp/go/test.go:32:11: leaking param: x
/tmp/go/test.go:33:10: new(Number) escapes to heap
/tmp/go/test.go:38:11: leaking param: x to result ~r1 level=1
/tmp/go/test.go:42:10: leaking param: x
/tmp/go/test.go:42:13: add y does not escape
/tmp/go/test.go:49:10: mul x does not escape
/tmp/go/test.go:49:13: mul y does not escape
/tmp/go/test.go:56:11: fact n does not escape
/tmp/go/test.go:73:12: count x does not escape
/tmp/go/test.go:86:14: i escapes to heap
/tmp/go/test.go:86:18: "! =" escapes to heap
/tmp/go/test.go:86:18: f escapes to heap
/tmp/go/test.go:86:14: main ... argument does not escape
```

With the -S that CE does it's printed on top of the assembly, but it's filtered out

**Comment by partouf** [comment]
Hi @igmor 
In the GL Go (not GccGo) you can now enter as parameters -m -l to show the escape analysis.

For example: https://godbolt.org/z/vuoSTl

I hope that's sufficient for now.

**Comment by partouf** [comment]
Calling this resolved for now, but if you have any more suggestions, please do create a new issue!
