### ISSUE TITLE
MSVC ICE after fatal error C1004: unexpected end-of-file found

### ISSUE THREAD

**Issue by izbyshev** [mattgodbolt/compiler-explorer#1148]
I've discovered that after any input that causes `unexpected end-of-file found` error (such as a single `(`) all MSVCs on goldbolt ICE after emitting the error:
```
example.c
<source>(3): fatal error C1004: unexpected end-of-file found
Internal Compiler Error in Z:\opt\compiler-explorer\windows\19.00.24210\bin\amd64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'Z:\opt\compiler-explorer\windows\19.00.24210\bin\amd64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
Compiler returned: 2
```

I couldn't reproduce this behavior with my local VS 2010, 2015 and 2017, so it seems to be something godbolt-related. This is certainly not a major issue, but it's interesting how MSVC manages to ICE :)

**Comment by mattgodbolt** [comment]
(I think I'm going to close this as not fixable: I don't want to dig into why WINE isn't working here...)

**Comment by izbyshev** [comment]
Thanks for the quick response, Matt! I've checked https://godbolt.org/beta right now, but couldn't find any difference from the usual godbolt: the list of MSVC compilers is the same, and the output is exactly the same, including the compiler path (e.g. `Z:\opt\compiler-explorer\windows\19.14.26423\bin\Hostx64\x64\cl.exe`). Am I missing something?

**Comment by mattgodbolt** [comment]
Hi! Thanks for following up: confusingly the beta site has both the WINE-based compilers (for backward compatibility, at least for now), and new Windows compilers.

Try one of the compilers listed near the very bottom under "Visual C++" e.g. https://godbolt.org/beta/z/swHYO6

**Comment by izbyshev** [comment]
I did try to find other compilers when I checked last time, but there were none. I even tried Shift + click to refresh to avoid browser caching. However, now that I've followed your link, those new compilers appeared, and they work as expected. Not sure what the problem was. Thank you, Matt!
