### ISSUE TITLE
Automatically enable binary mode when execute is selected

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#1150]
On either clientside or serverside; automatically set binary to true when execute is true.

Ideally it would be serverside in the compilehandler, I think.

**Comment by mattgodbolt** [comment]
Ideally we wouldn't need to pick binary mode at all to do execution. That way the display of the ASM output is independent of whether you are executing it or not. That would mean the client potentially sends the compile request twice, admittedly

**Comment by mattgodbolt** [comment]
Or the server might need to execute the compiler twice, once with binary output and once to get the executable. Or it should run the linker and assembler. Or something :). This is one reason I've not looked at this: should the "execute" be related in any way to the existing asm window? Perhaps not? But something would be better than nothing; forcing binary mode would be a start :)

**Comment by partouf** [comment]
In conclusion from conversations on Slack:
- We implement it clientside to enable binary if not enabled when pressing a.out,
 and we undo when eventually we have a better implementation for execution.

**Comment by partouf** [comment]
this is now separated and people can now select a.out individually without needing binary mode
