### ISSUE TITLE
Clarify how to add new source

### ISSUE THREAD

**Issue by wimo7083** [mattgodbolt/compiler-explorer#1162]
Currently you can add a source by clicking the `Editor` button:
![image](https://user-images.githubusercontent.com/10781353/48214780-f05df600-e33d-11e8-8634-8f2d21d333da.png)

Unless you're familiar this is not intuitive and as I'm a new user of CE, I always forget how to add a second source. I usually resort to finding a previous url with two sources or look for a presentation that Matt has uploaded. 

I think it would be helpful to either add a `+ Add New Source` or `+ duplicate source` on the bar or even something as simple as change `Editor` at the top to `Duplicate Editor` or `Add Editor`

**Comment by RabsRincon** [comment]
Note that there is alreadyna "Duplicate source button" under the Add new dropdown in the editors

**Comment by RabsRincon** [comment]
You're right, sorry for the missundestanding. I've linked @wimo7083 PR with this issue, and I'll try to merge it now if I'm left with enough time :)
