### ISSUE TITLE
Rust nightly broken

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1165]
`std` crate not found: https://godbolt.org/z/FyuZHY

**Comment by TheIronBorn** [comment]
Could be multiple/old versions of rust lying around: https://stackoverflow.com/questions/24417183/cant-find-crate-for-std-compiler-error-with-trivial-code

**Comment by hellow554** [comment]
This is still broken!

**Comment by BeatButton** [comment]
Nightly compiler is working for me as of right now.

**Comment by hellow554** [comment]
You're right, it's working again! I think this can be closed?
