### ISSUE TITLE
Base tool abstraction needs a way to add additional input

### ISSUE THREAD

**Issue by steveire** [mattgodbolt/compiler-explorer#1166]
In order to be able to add `clang-query` to CE as a tool, we need to be able to allow the user to populate an input field additional to the source.

![image](https://user-images.githubusercontent.com/37486/48344067-f9b3cf00-e66b-11e8-8c75-0c5b7e6eb9c6.png)

`clang-format` as a tool would also benefit from this so that users can experiment with the clang-format configuration.

**Comment by RabsRincon** [comment]
Isn't it what the Tool options input does? Or am I missreading it?

**Comment by partouf** [comment]
> Isn't it what the Tool options input does? Or am I missreading it?

The tool input options is in this case for command line parameters, but the extra input is for a query language input, for clang-format it could be the json with formatting rules.

**Comment by steveire** [comment]
As far as I know, tools options are command line options sent to the tool. 

Some tools (I mentioned clang-query and clang-format already) take additional input. You can try it out here if it helps: http://ec2-52-14-16-249.us-east-2.compute.amazonaws.com:10240/

**Comment by partouf** [comment]
Things I would ideally like to see in the end-design:

* make the UI not feel cluttered (maybe something using https://getbootstrap.com/docs/4.1/components/collapse/ ?)
* make clear what it is (maybe a help button?)
* have an initial example that works in most cases
* bonus points: some kind of syntax highlighting

**Comment by steveire** [comment]
The behavior of the example at https://golden-layout.com/examples/#849a1cd2afcc95b474f621635ef5b590 seems to be what I'm looking for - The panes are resizable but not detachable relative to each other. They stick together. Presumably this means they can also be moved as a unit, but I haven't seen that in the goldenlayout examples.

**Comment by mattgodbolt** [comment]
Those panes are resizable but not moveable. They can't be moved as a unit as far as I know: they're only immovable as they have no title bar to drag them around with.

**Comment by steveire** [comment]
Just updating this with some feedback from here: https://github.com/steveire/compiler-explorer/commit/d28d7dc6f9a696b1188d4235fd885badb5d227c3 and a slack thread: https://cpplang.slack.com/archives/C7ETT0ZRP/p1554281017034000.

It seems the way forward is for tools like this to be similar to compile panes. These panes have no need for the assembly view for example.
