### ISSUE TITLE
Windows MSVC installations lack libraries

### ISSUE THREAD

**Issue by Quincunx271** [mattgodbolt/compiler-explorer#1168]
I noticed that the options for MSVC have changed; there are now non-WINE options. However, these MSVC installations don't have access to the libraries: https://godbolt.org/z/N0FaBk

(with "Boost 1.68.0"):

```c++
#include <boost/optional.hpp>
```

```
<source>(1): fatal error C1083: Cannot open include file: 'boost/optional.hpp': No such file or directory
```

**Comment by mattgodbolt** [comment]
This is something we're hoping Microsoft can address: maybe not for all libraries but at least things like boost.

**Comment by partouf** [comment]
I remembered I did something with this and took a deep dive into my stale branches:
https://raw.githubusercontent.com/partouf/compiler-explorer/azureagain/etc/scripts/install_libraries.ps1

Perhaps useful

**Comment by mattgodbolt** [comment]
Being asked about this on Slack too. Ping anyone from MS?

**Comment by mattgodbolt** [comment]
Ping @Rastaban -- is there a good point of contact we can reach at MS to help us with this?

**Comment by ajcaruana** [comment]
Would it be a solution to just add the path to the correct header files as "Additional Include Directories"? I believe that the compiler option would be /I"C:\Full\Path\To\My\Headers"

I may be missing something, but IMHO you could have all the libraries extracted to different locations on disk and have the compiler explorer just substitute the correct path when calling the compiler.

**Comment by tiagomacarios** [comment]
@TartanLlama Can we help here?

**Comment by mattgodbolt** [comment]
After speaking with Ian Bearman, he suggested filing a feature request: https://developercommunity.visualstudio.com/idea/541911/library-support-for-compiler-explorer.html 

To help MS prioritise, anyone interested in this, please upvote this request! Thanks!

**Comment by gc435** [comment]
Would the issue be resolved if @mattgodbolt had a Windows system?  I'm coming late to this issue.  It appears Compiler Explorer only uses Linux compilation hosts, and library support doesn't work under WINE.

**Comment by mattgodbolt** [comment]
@gc435 I've asked to not be responsible for a Windows system: I don't have the skills to administrate and run a public-facing internet site on Windows. Microsoft have stepped up to the plate and both administrate, secure, monitor *and* install compilers upon a Windows host in Azure for Compiler Explorer (www.godbolt.ms lets you see their site directly). CE proxies requests for Windows compilations to this host.

WINE is only used for some legacy compilers (which also don't support libraries; though that would be slightly easier to implement).

**Comment by gc435** [comment]
Thanks for the clarification.  I didn't realize Microsoft already operated part of CE in Azure.  My first interpretation was that MSVC ran on WINE on Linux, and I thought donating a Windows PC to you would help.

**Comment by ubsan** [comment]
This is now complete! Check out the finished product! https://godbolt.org/z/1WqKoP

**Comment by mattgodbolt** [comment]
@ubsan this is absolutely amazing. THANK YOU (and Microsoft ®)SO MUCH! :)

**Comment by danilaml** [comment]
Hi. Sorry for bumping this closed issue but I wasn't able to find the proper way to raise issues w.r.t. to old libs for MSVC (i.e. VCPKG is 2019.07 when 2019.09 is out). How one is expected to report them? GitHub issues still or through some MS platform? Adding this info into issue template/FAQ would be helpful.

**Comment by rhalbersma** [comment]
> This is now complete! Check out the finished product! https://godbolt.org/z/1WqKoP

Doesn't work with Boost.Test, I added a comment here: https://developercommunity.visualstudio.com/idea/541911/library-support-for-compiler-explorer.html

**Comment by partouf** [comment]
@rhalbersma please refer to the current issue https://github.com/mattgodbolt/compiler-explorer/issues/1816 about this

**Comment by Cazadorro** [comment]
Has this regressed? the "success" link no longer can find the libraries. I'm trying to link to catch2 to test a bug MSVC has, but can't because it can't find any libraries period. 

Actually, it seems like it can't pull from latest or something, works when I don't use trunk for catch2

**Comment by partouf** [comment]
> Has this regressed? the "success" link no longer can find the libraries. I'm trying to link to catch2 to test a bug MSVC has, but can't because it can't find any libraries period.
> 
> Actually, it seems like it can't pull from latest or something, works when I don't use trunk for catch2

appears so, seems windows/msvc specific

**Comment by partouf** [comment]
> Has this regressed? the "success" link no longer can find the libraries. I'm trying to link to catch2 to test a bug MSVC has, but can't because it can't find any libraries period.
> 
> Actually, it seems like it can't pull from latest or something, works when I don't use trunk for catch2

Now fixed, thank you for the comment
