### ISSUE TITLE
`f.out` file created during startup

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1169]
I've noticed a mysterious `f.out` file created in the `compiler-explorer` directory during the initial startup/running of all the compilers. The file is empty.

**Comment by mattgodbolt** [comment]
This was annoying me so I busted out `strace`. For anyone following along, this is what I did:

```
$ strace -o /tmp/narg -f make run EXTRA_ARGS=--debug
```

then

```
$ grep 'f\.out' /tmp/narg
29127 openat(AT_FDCWD, "f.out", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
```

then finally:

```
$ grep '^29127 ' /tmp/narg | grep exec
29127 execve("/usr/bin/python3", ["/usr/bin/python3", "-m", "ppci.cli.cc", "--target-help"], 0x55eafacdc350 /* 1 var */ <unfinished ...>
29127 <... execve resumed> )            = 0
```

So, it's the `ppci.cli.cc` compiler. Will follow up with more info shortly...

**Comment by mattgodbolt** [comment]
It seems that bugs in `ppci.cli.cc` cause the default output name to be created if there's an error on the command-line.

To repro:

```
~/d/compiler-explorer (master|✚1) $ rm f.out 
~/d/compiler-explorer (master|✚2) $ env PYTHONPATH=/opt/compiler-explorer/ppci-0.5.5 python3 -m ppci.cli.cc --not-an-option
usage: cc.py [-h] [--log log-level] [--report report-file]
             [--html-report html-report-file] [--text-report text-report-file]
             [--verbose] [--version]
             [--machine {arm,avr,example,mcs6500,mips,msp430,or1k,riscv,stm8,x86_64,xtensa}]
             [--mtune option] [--output output-file] [-g] [-S] [--ir] [--wasm]
             [-O {0,1,2,s}] [-I dir] [-D macro] [--trigraphs]
             [--std {c89,c99}] [--super-verbose] [-E] [--ast] [-c]
             source [source ...]
cc.py: error: the following arguments are required: source
~/d/compiler-explorer (master|✚1) $ ls -l f.out 
-rw-r--r-- 1 matthew matthew 0 Nov 12 16:34 f.out
```

I guess this remains super-low priority, but one day may bite us (e.g. if we make the directory we run the app out of read-only, which it really should be...).

**Comment by partouf** [comment]
@windelbouwman can you help with this? (also, I see there's a new version?)

**Comment by windelbouwman** [comment]
Aw snap, finally I am bitten by this. I noticed this as well, but I thought I took care of removing the file. I will change this in ppci itself, and make a new release, someday!

**Comment by apmorton** [comment]
confirmed that `env PYTHONPATH=/opt/compiler-explorer/ppci-0.5.5 python3 -m ppci.cli.cc --not-an-option` still results in `f.out` being dumped into the cwd, but I think this is a non-issue for us these days because we run all compilers in a sandbox with a writable cwd
