### ISSUE TITLE
Intel Syntax does not work for gcc

### ISSUE THREAD

**Issue by bkin** [mattgodbolt/compiler-explorer#1176]
GCC compiler output shows operands in AT&T sequence, even when Intel output is selected.  clang looks ok.

Case in point:
https://www.godbolt.org/z/rpujEP

**Comment by partouf** [comment]
This is unfortunately just the way it is with assembly output in combination with manual asm in code. There have been other similar issues raised.

I’m not sure if there’s a way to “fix” this.

The 11010 output will be without this inconsistency, of course.

**Comment by mattgodbolt** [comment]
As @partouf says, this is not a Compiler Explorer issue as such. The underlying GCC outputs the `asm` block as text, without attempting to parse it. Clang, on the other hand, parses the asm and re-outputs it.

Consider this: https://www.godbolt.org/z/ZLRWL_ for example. I'm going to close this as I don't have a good solution for this that doesn't involve compiler hackery.

**Comment by bkin** [comment]
Ok, I understand, thanks for the explanation. I thought that the assembler output works by 'objdump -d'ing the object files, hence I was worried about a miscompilation.
