### ISSUE TITLE
Slow Theme CSS rendering

### ISSUE THREAD

**Issue by wimo7083** [mattgodbolt/compiler-explorer#1183]
When the page is loading, the top bar has unrendered CSS content, it looks like it's only CSS stylings related to the theme. 

![image](https://user-images.githubusercontent.com/10781353/48789690-d8299780-ecaa-11e8-8b9d-1f6d71bdb6e7.png)

![image](https://user-images.githubusercontent.com/10781353/48789693-dbbd1e80-ecaa-11e8-9d74-b8aeb38b908e.png)

**Comment by RabsRincon** [comment]
This might be solved by the work being done by @jaredwy, but that might take a while to be finished

**Comment by mattgodbolt** [comment]
I _think_ our changes already made (and planned) should heavily mitigate this. Thanks for filing (feel free to reopen if you spot it again!)
