### ISSUE TITLE
Hash of Assembly output

### ISSUE THREAD

**Issue by kogutenko** [mattgodbolt/compiler-explorer#1192]
Suggesion of a new feature - it will be great if somewhere (for example, on the bottom panel) will display the hash of the Assembly output.

**Comment by kogutenko** [comment]
For example, you can compare the machine code of a program with different source codes. This helps you understand if two different sections of code are equivalent.

**Comment by jaredwy** [comment]
Hi @kogutenko there is a diff view that may suit your needs. Open two editors (click the add new button to add a second editor/compiler) then on the top menu bar click add and select the diff view.

**Comment by mattgodbolt** [comment]
Going to close this: I think the diff view subsumes the need to have a specific hash.
