### ISSUE TITLE
x86-64 gcc 4.9.4 broken

### ISSUE THREAD

**Issue by crynsane** [mattgodbolt/compiler-explorer#1195]
Building with x86-64 gcc 4.9.4 is broken as it cannot find crt1.0. The compiler output is:
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
Compiler returned: 1

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. We have been having some problems with the installations of some compilers (Which are hopefully now solved) so you might have had a bit of bad luck on your timing as we were updating some things, as I can't repro the issue.

We'll make sure to keep an eye on compilers not working in the future :)
