### ISSUE TITLE
Increase opt/llc variants available from https://godbolt.org/

### ISSUE THREAD

**Issue by harinvidia** [mattgodbolt/compiler-explorer#1196]
godbolt.org already has the capability to take IR as input and run opt/llc on them. But, currently, only 4.0/5.0/trunk opt/llc options are available. It will be useful to extend the list of llvm versions available here (from 3.0 to 7.0).

**Comment by RabsRincon** [comment]
Hi! Thanks for the suggestion. I have added every llc/opt binary we have available. I hope you find it useful! :)

**Comment by harinvidia** [comment]
Ruben,
Thanks for the real quick response!

I still only see the 3 versions as before. Does it take time for your change to be reflected on the public website?

**Comment by RabsRincon** [comment]
Yes! Sorry for not mentioning it. We manually update the site at least once a week, if needed. I'll make sure to notify you when the changes hit the live site :)
