### ISSUE TITLE
zig trunk has id `trunk`

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1199]
We might have to break URLs here: it's a ticking time-bomb for the `zig` compiler's trunk build be ID `trunk` . Really we need a better ID strategy but...hey ho.

Thoughts anyone? I could just unilaterally change it to `zig_trunk` and then anyone linking to zig trunk would get defaulted, which might be ok.

**Comment by RabsRincon** [comment]
Yes it is ok to change it. I'm sorry this flew under my radar back when I merged
