### ISSUE TITLE
Compressed full link option

### ISSUE THREAD

**Issue by phuclv90** [mattgodbolt/compiler-explorer#120]
Sometimes a full link is slightly too long for a post and may contain disallowed characters (like parentheses when use in markdown) whereas a short link may be not the thing desired because it can rot anytime. In this case a compressed full link works great.

The full options in the link would be compressed with some algorithm and then the output is encoded in base64 (or [base85](https://github.com/noseglid/base85) which produces shorter result). A new button (e.g. _"compressed full link"_) will be put between full link and short link, or a drop down for the user to choose between compressed and non-compressed forms. If the result is longer than the full link then just output the full link.

**Comment by mattgodbolt** [comment]
Hi, thanks for the thoughts.

Are you thinking of the whole thing being compressed? e.g. a link looking like godbolt.org/f/BASE85ENCODEDTHING where if one un-base85--encoded one would get a compresesd json structure? That could work, I think.

That said; if you're worried about parentheses in markdown, base85 isn't safe: it will generate all manner of brackets and quotes and things. Unless I'm mistaken, base64 is the most succinct, URL-safe encoding.

I've not seen any indications from Google that they'll start deleting old goo.gl links (indeed: https://support.google.com/faqs/answer/190768?hl=en&rd=1 suggests it'll never go away). Do you have any thoughts on why a compressed, non-human-readable base-64 encoded link is better than a short URL? I like to use the short ones when they remain human-readable (so it's clearer what you're clicking on is actually a source fragment).

**Comment by mattgodbolt** [comment]
With the new UI for sharing, having an option to do this should be a lot easier.

**Comment by mattgodbolt** [comment]
Closing this issue: don't think there's a general solution to this. We already compress and use rison when the compression yields savings.
