### ISSUE TITLE
please don't disable Clang's backends

### ISSUE THREAD

**Issue by nickdesaulniers** [mattgodbolt/compiler-explorer#1222]
This makes it difficult to debug certain arch specific flags.  In general, I consider it a GCC/binutils-ism to have only a single backend per compiler binary, and an antipattern.  One of the great benefits of Clang is having multiple cross compilers out of the box in one binary.  I recognize this slows down the build of Clang itself and makes the binary larger, but it's worthwhile IMO.

**Comment by mattgodbolt** [comment]
Hi! Do you have an example where we have "disabled" a clang backend? I don't recall doing so, and we build nightly from source with no special flags to do so.

**Comment by nickdesaulniers** [comment]
PEBKAC 👍 

Was testing `-march=armv7-a` but was getting an error and list of x86_64 micro architectures.

I need to set `--target=arm-linux-gnu` first to get the proper `-march=` list!

Maybe the dropdown list doesn't need to be "x86_64 clang" then as clang has all backends enabled by default?  Clang could be built for other host architectures, but it's kind of irrelevant since it can still target many others no matter the host arch.
