### ISSUE TITLE
llvm-mca not working when compiling to llvm-ir

### ISSUE THREAD

**Issue by DavidFarago** [mattgodbolt/compiler-explorer#1226]
I am using the compiler options -S -emit-llvm. Then I add tool LLVM MCA. I expected some useful MCA output in the new window, but got a ton of error messages. The first ones are:

<source>:1:14: error: missing expression

; ModuleID = '/tmp/compiler-explorer-compiler1181118-60-4olpbo.mebd/example.cpp'

             ^

<source>:3:19: error: unexpected token in argument list

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

                  ^

**Comment by bugwelle** [comment]
Example on godbolt.org: https://godbolt.org/z/pZg44-

**Comment by mattgodbolt** [comment]
Agreed: the input to `llcm-mca` needs to be assembly code, not LLVM IR. By its very nature, `llvm-mca` uses specific machine code instruction rules to determine what specific processors do. If you want to see both MCA and IR, use the new IR view: https://godbolt.org/z/6VpQxD
