### ISSUE TITLE
add Threading Building Blocks library (C++)

### ISSUE THREAD

**Issue by anton-potapov** [mattgodbolt/compiler-explorer#1233]
TBB is well known library for C++ data parallelism. 

https://github.com/01org/tbb , http://threadingbuildingblocks.org/

**Comment by RabsRincon** [comment]
Hi! Sorry about the month delay! I just got around finally adding it. It should hit the live site once the new version is pushed (Which should happen before the end of the week)

Sorry again about the delay :)
