### ISSUE TITLE
Add support for WebAssembly

### ISSUE THREAD

**Issue by mbebenita** [mattgodbolt/compiler-explorer#125]
It would be nice if we could add support for WebAssembly to the gcc-explorer. There are several steps to this:
1. Use [Emscripten](https://github.com/kripken/emscripten) / [Binaryen](https://github.com/WebAssembly/binaryen) to compile C/C++ to [WebAssembly](https://github.com/webassembly).
2. Use a custom build of SpiderMonkey/V8 to dump the raw x86 assembly for the generated WebAssembly. (I can help with this).

I'm imagining the following input -> output combinations:
- C/C++ -> WebAssembly (via LLVM / Emscripten / Binaryen)
- C/C++ -> WebAssembly -> x86 (via LLVM / Emscripten / Binaryen and then V8 and/or SpiderMonkey)
- WebAssembly -> x86 (via V8 and/or SpiderMonkey)

**Comment by mattgodbolt** [comment]
Has also been requested a few times over twitter and email.

**Comment by cor3ntin** [comment]
In case this is still of interest, I believe clang-trunk could do that without Emscripten nowadays ( see https://gist.github.com/yurydelendik/4eeff8248aeb14ce763e )

**Comment by mattgodbolt** [comment]
We have at least https://godbolt.org/z/9fgaDB "WebAssembly trunk" clang now, and the asm parser and syntax highlighting works well enough (for me anyway!). I'm going to close this: if people want specific other compilers please file a new issue!

**Comment by Matheus28** [comment]
@mattgodbolt any way we could have it compile under emscripten, so we have access to the C++ std library?
