### ISSUE TITLE
https://gcc.godbolt.org/ no more works with MSIE 11

### ISSUE THREAD

**Issue by ardi69** [mattgodbolt/compiler-explorer#1258]
I like Compiler Explorer. Nice to see what the compiler does. Useful for optimizing C code

But recently compiler explorer stopped working with MSIE 11.
At work i am forced to use MSIE 11. 

I also have no access to the developer options to see what goes wrong.

Please help

**Comment by partouf** [comment]
There are no errors in the console about this, so I think we'll have to see from what commits it stopped working.

I'm sorry you have to use MSIE :(
