### ISSUE TITLE
Support RISC-V pseudo-instructions

### ISSUE THREAD

**Issue by Serentty** [mattgodbolt/compiler-explorer#1262]
RISC-V, in order to minimize the number of instructions taking up opcode space, omits certain instructions such as loading an immediate value into a register (since this is the same as adding an immediate value to zero, and then storing the result in that register). In order to make its assembly language easier for humans to read, these patterns have been assigned mnemonics despite not corresponding to a real instruction. For example, one can write:

`li a0, 2`

instead of 

`addi a0, zero, 2`

This is part of the core standard, and the former syntax is even used by disassemblers sub as GNU's `objdump`. If Compiler Explorer showed the former syntax instead of the latter (and did the same for other pseudo-instructions), it would make the assembly code much more readable.

**Comment by Serentty** [comment]
I've noticed that these pseudo instructions work with GCC, and I was only testing LLVM. Perhaps this is up to the compiler, and not related to the scope of this project at all.

**Comment by mattgodbolt** [comment]
I'm afraid that's absolutely the case: we show what the compiler emits when you ask it to generate text asm output. For some compilers we can compile and link, and then disassemble (which would let us choose how this is shown, if the disassembler has the option). Currently we don't support that for RISC-V though.

Closing, as it's not something we can easily fix. Thanks for filing, and for updating with the new info. And sorry it took so long to get even this!

**Comment by Serentty** [comment]
Thanks! I appreciate what you do with this site, and use it all the time.
