### ISSUE TITLE
Incorrect syntax highlighting when space is after hash

### ISSUE THREAD

**Issue by sirzooro** [mattgodbolt/compiler-explorer#1265]
When space is added after hash, syntax highlighter treats following part of line as a C code instead of proprocessor instructions, e.g.:

```c
# if !defined Generator_h
# define Generator_h
# endif
```

**Comment by RabsRincon** [comment]
Hi! Sorry it took so long to address this issue. Our editor solution was a bit outdated up until a few days ago. The newer versions treats the preprocessor much better. Thanks for the report anyways, and sorry again about taking so long! :)
