### ISSUE TITLE
avr-gcc compiler to old for C++17?

### ISSUE THREAD

**Issue by ozra** [mattgodbolt/compiler-explorer#1266]
It should be possible to compile Arduino/Atmel code in C++17-mode by now — I'm pretty sure. It would be cool if it were part of compiler-exporer, since every byte counts when coding those 8-bit boards, so it would be an invaluable help in tweaking byte shavings...

**Comment by pixxon** [comment]
I'm currently working on this.  
Had to modify the generic gcc build to remove code duplication, but eventually I will get there.

**Comment by fabiocannizzo** [comment]
@pixxon : That is great new. Looking forward to see that deployed.

**Comment by mattgodbolt** [comment]
Just looked into this: we can build the avr-gcc but have not built and installed them (!).

Something like:
```
ce builder exec -- sudo docker run --rm --name gcc.avr -v/home/ubuntu/.s3cfg:/root/.s3cfg:ro mattgodbolt/gcc-builder bash build-avr.sh 9.2.0 s3://compiler-explorer/opt/
```

is what we need, plus the installer (this is a note to ourselves).

**Comment by mattgodbolt** [comment]
Pending:
* [x] Build avr 9.2.0
* [ ] Deploy to site
* [ ] Update config

**Comment by mattgodbolt** [comment]
```
Nov/12 05:36 admin-node~/compiler-explorer-image (master|✔) 2.5m $ /opt/compiler-explorer/avr/gcc-9.2.0/bin/avr-g++ --version
avr-g++ (Compiler-Explorer-Build) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mattgodbolt** [comment]
This will go live in the next site release (probably later this week).

**Comment by ozra** [comment]
Awesomeness++!

**Comment by mattgodbolt** [comment]
This is now live.
