### ISSUE TITLE
Add support for Go 1.6

### ISSUE THREAD

**Issue by eloff** [mattgodbolt/compiler-explorer#127]
The Go compiler changed a lot (rewrite from C to Go, new GC) so being able to see the output for 1.6 would be great. 1.7 will change things a lot as well, since that's when the new SSA backend should land. Apparently the generated code is a LOT cleaner but not much faster (since superscalar xeons do a great job of executing code with extra instructions.)

**Comment by rakyll** [comment]
I think this issue is pretty outdated now. Supporting 1.7 would be great to have.

**Comment by mattgodbolt** [comment]
Cool; I've made it a bit easier to upgrade compilers so will take a look at what this entails.

**Comment by mattgodbolt** [comment]
Go 1.8 is out now...

**Comment by rakyll** [comment]
The Go compiler has rewritten a few times since 6g. Please consider fixing this issue, the current output might be significantly misleading.

**Comment by mattgodbolt** [comment]
Understood. It's low on my priorities at the moment but I hope to get to
it. Patches are always welcomed though, should anyone else be motivated to
do so (I don't ever use the go site myself)

**Comment by RabsRincon** [comment]
Ey @rakyll I'm currently on the process of adding some newer Go versions, and it would be really interesting to hear about how the current output might be misleading!

**Comment by RabsRincon** [comment]
We now support 1.4, 1.7, 1.8 & 1.9! Thanks for being so patient!
