### ISSUE TITLE
Add thumbv7neon-unknown-linux-gnueabihf Rust target

### ISSUE THREAD

**Issue by gnzlbg** [mattgodbolt/compiler-explorer#1271]

**Comment by RabsRincon** [comment]
Hi! Sorry for taking so long to get back to you.
This is something we can totally do, but I do not see from which version it's available from.

Ideally, we would just add it to the right place in https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_rust_compilers.sh, but I'm not able to figure exactly where from my (very limited!) Experimentation :)

**Comment by hsivonen** [comment]
> This is something we can totally do, but I do not see from which version it's available from.

It was introduced in 1.33.0.
