### ISSUE TITLE
MSVC does not have Eigen

### ISSUE THREAD

**Issue by R2RT** [mattgodbolt/compiler-explorer#1272]
There is an include error for all MSVCs available:
```
example.cpp

<source>(2): fatal error C1083: Cannot open include file: 'Eigen/Sparse': No such file or directory

Compiler returned: 2
```

https://godbolt.org/z/o8jUSR

**Comment by RabsRincon** [comment]
Hi! We are aware of this problem. The msvc compilers are hosted by Microsoft and need extra work to have access to most libraries. It is a bit hard to coordinate with them, so the process is progressing super slow.

We are sorry for any inconvenience!
P.S: You can include files from the internet with ```#include <url>``` given that the url has a permissive enough Access-Control. This works great for single header libraries while we fix this issue

**Comment by RabsRincon** [comment]
Hi! Sorry that this took so long. MSVC now supports EIgen along with some other libraries :) https://godbolt.org/z/kCN7EY
