### ISSUE TITLE
Intel Assembly Output Seems Incorrect Sometimes

### ISSUE THREAD

**Issue by imallett** [mattgodbolt/compiler-explorer#1274]
For example, consider the following code:

    inline float my_rsqrt(float x) {
    	float result; asm( //Note AT&T order
    		"vrsqrtss %1, %1, %0"
    		: "=x"(result)
    		: "x"(x)
    	); return result;
    }
    float my_hypot(float a, float b) {
    	return my_rsqrt( a*a + b*b );
    }

With ICC 19.0.1 (`-O3 -mavx`), this compiles to:

    my_hypot(float, float):
    	vmulss    %xmm0, %xmm0, %xmm2                           #30.24
    	vmulss    %xmm1, %xmm1, %xmm3                           #30.30
    	vaddss    %xmm3, %xmm2, %xmm4                           #30.30
    	vrsqrtss  %xmm4, %xmm4, %xmm0                           #23.0
    	ret

With AT&T syntax, we have:
`vaddss    %xmm3, %xmm2, %xmm4`
`vrsqrtss  %xmm4, %xmm4, %xmm0`

Whereas when Intel syntax is selected, we have:
`vaddss    xmm4, xmm2, xmm3`
`vrsqrtss xmm4, xmm4, xmm0`

We can see that the operands for `vaddss` have reversed, as-expected. Shouldn't the operand order for `vrsqrtss` reverse also? (N.B. I have seen this on a bunch of instructions, not just `vrsqrtss`).

**Comment by partouf** [comment]
Inline assembly with just the asm view is a bit of a free for all, GCC has a similar behaviour in where it just outputs whatever you inlined and remove the % signs. If you click the 11010 option you'll see what it will actually compiles to and disassembles as.

**Comment by mattgodbolt** [comment]
I think @partouf 's answer closes this. Happy to discuss further if necessary.
