### ISSUE TITLE
lib.f filter sometimes filters out too much

### ISSUE THREAD

**Issue by PlasmaHH** [mattgodbolt/compiler-explorer#1285]
Looking at https://godbolt.org/z/Z1PN-q and enabling the lib.f filter, it removes the function that the code is about and its first instruction

**Comment by partouf** [comment]
Thanks for the bugreport!

Not sure yet how to solve this, but we shall figure something out

**Comment by Alcaro** [comment]
I encountered this one too. https://godbolt.org/z/f9erit

#1229 is similar, but was fixed two months ago. Maybe 1229 only works if the first opcode in the function is non-library?

**Comment by mattgodbolt** [comment]
https://godbolt.org/z/pBEwAS similarly filters out too much (with reference to https://twitter.com/jorgbrown/status/1118584121163255808 )
