### ISSUE TITLE
API seems to ignore options

### ISSUE THREAD

**Issue by maep--** [mattgodbolt/compiler-explorer#1286]
Based on the example in the API documentation, the options parameter appears to be ignored.

Fox example, the -O3 flag has no influence on the output:
```bash
curl 'https://godbolt.org/api/compiler/g82/compile?options=-O3' --data-binary 'int foo(int x) { return x*x; }'
```

It would also be nice if the documentation mentioned how to pass multiple compiler flags.

**Comment by partouf** [comment]
Thanks for filing the bug. The ignoring of the options is definitely not intentional, we will try to fix this.

Btw You can send multiple options by using %20 or + between the options, so for example ?options=-O3+-Wall

**Comment by RabsRincon** [comment]
After testing dae84d1 in beta, it seems to confirm that we are stripping the options of api calls.

**Comment by mattgodbolt** [comment]
Testing locally and it works, which means either `nginx` or CloudFront are eating up the query (I think)

**Comment by mattgodbolt** [comment]
ahem. It's cloudfront. Fixing.

**Comment by mattgodbolt** [comment]
Fixed in cloudfront. Terraform updated, still rolling out but my local test worked:

```
~/d/o/c/terraform (master|✔) $ curl 'https://godbolt.org/api/compiler/g82/compile?options=-O3' --data-binary 'int foo(int x) { return x*x; }'
# Compilation provided by Compiler Explorer at https://godbolt.org/
_Z3fooi:
        imul    edi, edi
        mov     eax, edi
        ret
~/d/o/c/terraform (master|✔) $ curl 'https://godbolt.org/api/compiler/g82/compile?options=-O0' --data-binary 'int foo(int x) { return x*x; }'
# Compilation provided by Compiler Explorer at https://godbolt.org/
_Z3fooi:
        push    rbp
        mov     rbp, rsp
        mov     DWORD PTR [rbp-4], edi
        mov     eax, DWORD PTR [rbp-4]
        imul    eax, DWORD PTR [rbp-4]
        pop     rbp
        ret
```
