### ISSUE TITLE
Remote requests seem to screw with the source

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1289]
When using remote compilers (`compilers=www.godbolt.org@443`) and using the API call style, the source seems to get an extra pair of double quotes which break the code to be compiled.

```bash
~ » curl 'http://localhost:10240/api/compiler/g72/compile?options=-O3' --data-binary 'int foo(int x) { return x*x; }'
# Compilation provided by Compiler Explorer at https://godbolt.org/
<Compilation failed>
# Compiler exited with result code 1
Standard error:
<source>:1:1: error: expected unqualified-id before string constant
 "int foo(int x) { return x*x; }"
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note that this same call, but using a local version of the compiler, returns without any problem the compiled result.

See also #1286 for a releated error, but that one affects _every_ api call, not just those with remote compilers

**Comment by mattgodbolt** [comment]
Well, isn't this a weird one!

**Comment by mattgodbolt** [comment]
Seems to be some interaction with https://www.npmjs.com/package/http-proxy and the JSON or text parser. Somehow on the way out I think the "string" `req.body` is being turned into a JSON string (with quotes...)

**Comment by mattgodbolt** [comment]
I had a quick hack at trying to keep the `rawBody` and then re-stream that out like in the example in the npm docs for http-proxy but had to give up before I got it working.

**Comment by mattgodbolt** [comment]
Finding some fun at: https://github.com/nodejitsu/node-http-proxy/issues/180

**Comment by mattgodbolt** [comment]
Doesn't quite work:
```
            if (contentType === 'application/x-www-form-urlencoded') {
                bodyData = queryString.stringify(req.body);
                logger.info("ooh", bodyData);
                logger.info("aah", req.body);
            }
```
bodyData is empty. I think maybe we're not actually encoding properly...but we need to make this work :)

**Comment by mattgodbolt** [comment]
And if we hack it, we get "Whoops, Can't set headers after they are sent."

**Comment by mattgodbolt** [comment]
AHA! we're using a "restreamer" in app.js which used to "fix" the problem but now maybe is the source of the problem. Rapidly running out of time for tonight, but commenting out the restreamer helped in this case.
