### ISSUE TITLE
Short links should avoid including any obvious bad words

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1297]
With reference to https://twitter.com/jorgbrown/status/1103009357409611776

Not quite sure the best approach to handle this, but we can give a different short URL out for ones matching some list of "bad" words I guess. Finding such a list will be interesting. I'd guess there's a package for this kind of thing.

**Comment by mattgodbolt** [comment]
Or we could pad the document with a random value and re-hash.

**Comment by mattgodbolt** [comment]
https://www.npmjs.com/package/profanities amongst others look doable

**Comment by olafurw** [comment]
Detecting stuff like this can be quite the rabbit hole, I've helped with usernames on our platform. 

If you have a nice list, then go for it but people are still going to find something even with a good list. If you can avoid the big EFIGS bad words you are like 80-90% fine.

In your case you can also structure the ID part of the URL differently for future URL's so making up bad words is harder. Never more than 2 a-zA-Z in a row for example. URL's might then become a little longer but they are pretty short anyway currently.

**Comment by mattgodbolt** [comment]
Thanks! In this case the URLs are SHA prefixes so it's unlikely we will have too much trouble with folks crafting deliberately naughty ones. But...some time in the future we may allow user defined link names (though for a trusted few)
