### ISSUE TITLE
Rust: rustc 1.33.0 and rustc beta compilers fail to compile

### ISSUE THREAD

**Issue by Hentropy** [mattgodbolt/compiler-explorer#1302]
Setting the compiler to rustc 1.33.0 fails, claiming it "cannot find crate `core` which `std` depends on"
[Example](https://godbolt.org/z/S7syQY)
Setting the compiler to rustc beta fails, claiming it "cannot find crate `panic_unwind` which `std` depends on"
[Example](https://godbolt.org/z/kHD2aK)

**Comment by partouf** [comment]
Hi, thanks for the bugreport. Seems something botched the installation. We reinstalled it and it should be fine now. Be aware of the caching of the error message.

**Comment by Hentropy** [comment]
The 1.33.0 compiler is working now, but the beta compiler is giving the same error as before.

**Comment by partouf** [comment]
Sorry, forgot about that one! Is now fixed
