### ISSUE TITLE
/celibs/boost_1_68_0/stdc-predef.h: Permission denied

### ISSUE THREAD

**Issue by Alcaro** [mattgodbolt/compiler-explorer#1303]
x86-64 gcc 8.3 randomly (~20-40% of the time) errors out, citing "/celibs/boost_1_68_0/stdc-predef.h: Permission denied". Any change whatsoever, including flags or whitespace, can break or repair it. I haven't seen this issue on other compilers, but I haven't proven they're safe either.

I suspect one or more of your servers is misconfigured, or somehow managed to glitch up, and it works or breaks depending on who the load balancer chooses.

Sample (which may or may not have fixed itself by the time anyone reads this): https://godbolt.org/z/FN78N2, x86-64 gcc 8.3, flags -O3

```
#include <stdlib.h>

void init(int* h);
void use(int* h);

void test()
{
}
```

```
cc1plus: fatal error: /celibs/boost_1_68_0/stdc-predef.h: Permission denied
compilation terminated.
Compiler returned: 1
```

**Comment by partouf** [comment]
It takes a while for Boost to be synced into newly launched CE instances. This makes Boost things actually compile, but while it's still being synced this obviously causes errors that are aggressively cached by various caching mechanisms. (for example, the link you gave gives the error, but when you change the source slightly by even a space or an enter, it will compile without errors)

We obviously need to find a solution, but it might not happen soon.
