### ISSUE TITLE
notice: the zig command line API changed just now

### ISSUE THREAD

**Issue by andrewrk** [mattgodbolt/compiler-explorer#1304]
In https://github.com/ziglang/zig/commit/1e634a384ccc0ae57e0343369f7adb0b1b4b9875 the command that compiler-explorer uses to call Zig will no longer work.

Old API:

`zig build-obj --cache-dir <dir_path> --output <example.s> --output-h /dev/null --emit asm -mllvm --x86-asm-syntax=intel --strip --release-fast <example.zig>`

New API:

`zig build-obj --cache-dir <dir_path> --output-dir <dir_path> --name <example> --disable-gen-h --emit asm -mllvm --x86-asm-syntax=intel --strip --release-fast <example.zig>`

Output file will be guaranteed to be `<dir_path>/<example>.s`

**Comment by partouf** [comment]
This affects 'zig trunk' https://godbolt.org/z/1Ysx7y

**Comment by RabsRincon** [comment]
Hi! Sorry this took so long to fix. There were 2 bugs in 1 here and it took me a while to have the free time to look for it. Thanks for your patience. It should hit the live site soon! :)

**Comment by andrewrk** [comment]
Thanks! I'm sorry that it didn't work for you to test it locally. Is there some reason the binaries on https://ziglang.org/download/ didn't work? The master branch ones are updated automatically by the CI server when the tests pass.

**Comment by RabsRincon** [comment]
Oh no, don't worry about that! I just didn't test it locally intially! Once I did (today) it became clear what the problem was. Thank you! :)

**Comment by RabsRincon** [comment]
Fix is now live https://godbolt.org/z/7oJGuA :)
