### ISSUE TITLE
Function name gets hidden when using <cmath> functions

### ISSUE THREAD

**Issue by lisyarus** [mattgodbolt/compiler-explorer#1307]
https://godbolt.org/z/NJsiJN

The function name `testfunc` is not present in the compiler output. Furthemore, labels `.LC0`, `.LC1` and `.LC2` are not used anywhere, and it is strange that the argument gets into `xmm1` (I thought it should go to `xmm0`, though I'm not sure).

The code doesn't change at all if `std::floor` is replaced with `std::ceil`, strongly suggesting that something important is stripped. Using `std::sqrt` produces a different output with the same problems.

**Comment by partouf** [comment]
This is related to the [lib.f] filter. Thanks for the bugreport!

**Comment by lisyarus** [comment]
Update: the `lib.f` option ("Filter functions from other libraries from the output") seems to be the cause. Disabling it gives the full output: https://godbolt.org/z/zCS5Og
