### ISSUE TITLE
Rust wasm32-unknown-unknown target not available on nightly toolchains

### ISSUE THREAD

**Issue by gnzlbg** [mattgodbolt/compiler-explorer#1322]
It is available on stable, beta, and Rust 1.33.0 at least, but it is not available on nightly for some reason (I suspect this is an oversight).

**Comment by mattgodbolt** [comment]
https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_rust_compilers.sh#L182 is the code that installs all the rust compilers. As far as I can tell we add `wasm32-unknown-unknown` to the list of target to install for all rusts 1.24 and above: including nightly. Any ideas on this?

**Comment by RabsRincon** [comment]
It has now been working as expected for a while, so I'll close this and hope it does not come back :P . It might have been an error on the installation step. There have been some talks to move towards rustup, but nothing mas materialized yet. Thanks again for the report :)
