### ISSUE TITLE
Support RV64GC with Rust

### ISSUE THREAD

**Issue by Serentty** [mattgodbolt/compiler-explorer#1329]
As far as I can tell, the only RISC-V toolchains for Rust that are installed are RV32IMC and RV32IMAC. However, Rust supports RV64GC (which is currently the most full-featured version of the RISC-V ISA). Installing this would make it possible to see RISC-V code using 64-bit integers and floating point numbers.

**Comment by RabsRincon** [comment]
I think that the linked PR plus https://github.com/mattgodbolt/compiler-explorer-image/pull/189 has resolved this issue, right?

**Comment by Serentty** [comment]
Yes, this is resolved now.
