### ISSUE TITLE
Rust nightly is missing?

### ISSUE THREAD

**Issue by breeswish** [mattgodbolt/compiler-explorer#1330]
I remembered that Compiler Explorer supports Rust nightly, but.. I cannot find it any more?

![image](https://user-images.githubusercontent.com/1916485/55338336-180f4f80-54d3-11e9-8239-dcffc4d4cf1a.png)

**Comment by mattgodbolt** [comment]
Our scripts to update and maintain the nightly rust must be faulty. We'll take a look

**Comment by mattgodbolt** [comment]
Should be back: sorry for the inconvenience!

**Comment by breeswish** [comment]
Thanks a lot!
