### ISSUE TITLE
refuses to work with node 10 due to buggy version detection

### ISSUE THREAD

**Issue by shawnl** [mattgodbolt/compiler-explorer#1332]
```
Compiler Explorer needs node v8.x, but v10.15.2 was found.
```

**Comment by shawnl** [comment]
LOL 
```
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm notice created a lockfile as package-lock.json. You should commit this file.
```

**Comment by mattgodbolt** [comment]
The message "Compiler Explorer needs node v8.x" is part of the `etc/scripts/find-node` and is correct as far as I can tell. We only support and test against node 8, and this is only a warning (unless the script exits). We warn on newer versions but don't error (or shouldn't).

The second message is part of `npm` - the package manager that comes with `node`. I have no idea why it's complaining about the version incompatibility there.

Can you confirm whether Compiler Explorer's `find-node` script is exiting or not?

**Comment by shawnl** [comment]
No, this is the error message for a version less than. If it is greater than it should print out the greater than string, and continue.
```
if test ${NODE_MAJOR_VERSION} -gt ${NODE_VERSION_USED}; then
    >&2 echo Compiler Explorer needs node v${NODE_VERSION_USED}.x, but ${NODE_VERSION} was found.
    >&2 echo The higher node version might work but it has not been tested.
fi
```

**Comment by shawnl** [comment]
And if you remove that check it fails again on the version, because of an inability to realize 10 > 9
```
Internal Compiler Explorer error: TypeError: Invalid Version: 
    at new SemVer (/home/shawn/git/compiler-explorer/node_modules/semver/semver.js:305:11)
    at compare (/home/shawn/git/compiler-explorer/node_modules/semver/semver.js:578:10)
    at Function.gt (/home/shawn/git/compiler-explorer/node_modules/semver/semver.js:607:10)
    at ZigCompiler.optionsForFilter (/home/shawn/git/compiler-explorer/lib/compilers/zig.js:58:56)
    at ZigCompiler.prepareArguments (/home/shawn/git/compiler-explorer/lib/base-compiler.js:186:28)
    at tempFileAndDirPromise.then.info (/home/shawn/git/compiler-explorer/lib/base-compiler.js:449:34)

Compiler returned: -1
```

**Comment by mattgodbolt** [comment]
Thanks for the quick reply. The `bash` script I can fix, as it's part of Compiler Explorer. The second part is some of `node`'s own tooling, `npm` (its package manager). Can you run other `node`-based projects OK?

**Comment by mattgodbolt** [comment]
I'm going to install node 10 and test: it seems we're rather behind on versions! (10.15.3 is the current LTS version!)

**Comment by mattgodbolt** [comment]
@shawnl I see the message for a higher-but-ok message:

```
~/d/compiler-explorer (master|✔) $ make
Haskell language support disabled
D language support disabled
Compiler Explorer needs node v8.x, but v10.15.3 was found.
The higher node version might work but it has not been tested.
+ yarn@1.15.2
```

Followed by the app running just fine. I wonder what's going on here!

If you run `node --version` and `npm --version` what do you see?

I get `v10.15.3` and `6.4.1` respectively.  NB I install my `node` and `npm` to `/opt/compiler-explorer/node/` which is special-cased in the script: it's possible there's an issue with this!

**Comment by shawnl** [comment]
The second error is the verzion of zig so it is unreleated. Perhaps it was working and I thought it wasn't becfause the webpack.js takes so long....

**Comment by mattgodbolt** [comment]
Thanks for replying and letting us know what's going on! This has been super useful for us: we'll be upgrading the `node` version shortly so the warnings should go away too =)
