### ISSUE TITLE
Old goo.gl links no longer expand

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1334]
https://papertrailapp.com/groups/1243314/events?q=failed%20to%20expand&focus=1049748516228579329

```
Apr 02 06:38:31 ip-172-30-0-239 unified: error: Failed to expand http://goo.gl/cAaSDr - Got response 403 : {
```

According to Google they were meant to keep this service forever, but...as of April 1st seems _all_ requests are 403.

@malcolmr er...any ideas?

**Comment by mattgodbolt** [comment]
Twitter thread: https://twitter.com/mattgodbolt/status/1113130749903978498

Now seeing 404s. Google said before that we could download CSVs but that was user-generated links. We don't have a user (an API key) so were unable to. But the post implied we could still use them.

Sadly the API we used to ensure the link was actually a CE link before redirecting has been removed it seems. Trying to reach out to Google to work out what we might be able to do.

**Comment by mattgodbolt** [comment]
Workaround for now: take a URL `godbolt.org/g/ABCDEF` and manually type `goo.gl/ABCDEF` in your browser to convert. Save new link.

We may consider doing this automatically. We avoided this in the past as it could turn godbolt.org into a "laundering" site for evil goo.gl links, hiding the fact it's a bad redirect. We currently check the redirect is to our own site before forwaring it, which is apparently the problem.

**Comment by mattgodbolt** [comment]
Suggested on slack:

```
Ew, maybe it would be better to redirect users of `/g/` links to a page that explains the problem, so that they can decide whether or not they want to continue? That does seem really dangerous to just blind redirect
```

**Comment by mattgodbolt** [comment]
Also suggested on slack:

```
@Matt Godbolt you could also load the goo.gl link in some js to follow the redirect and see if its origin is indeed your site
```

**Comment by malcolmr** [comment]
(Minor correction to the above: the [original announcement](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html) did say that the API was turning down 2019-03-30; it's the HTTP redirector that's sticking around.)

I've reached out to people internally, but if you're able to implement a workaround in the meantime, that's probably a good idea.

**Comment by mattgodbolt** [comment]
Thanks @malcolmr . I didn't think through that the API turndown would affect us!

Our workaround is to `HEAD goog.gl` from the server and hope we don't hit rate limits. We aggressively cache these so hopefully we'll be ok.

Thanks, and sorry for the panic!

**Comment by mattgodbolt** [comment]
We now have our own dynamodb of these links...as comprehensive as we can make it anyway
