### ISSUE TITLE
Resizeable machine code column

### ISSUE THREAD

**Issue by creaothceann** [mattgodbolt/compiler-explorer#1344]
Hi, I've noticed that the machine code column (when disassembling is enabled) can't be resized. Would it be possible to add that feature?

Also, the syntax highlighting is applied to comments.

![godbolt](https://user-images.githubusercontent.com/1885014/55671051-faa00400-588b-11e9-8344-7694c13905a0.png)

**Comment by mattgodbolt** [comment]
Hi! We'd love to! It's unfortunate but we're (ab-)using the line number column to do this in our choice of editor (MS's monaco editor). It doesn't support this feature, unfortunately.

**Comment by creaothceann** [comment]
Mmmh... oh well.

Any idea regarding the syntax highlighting issue then?
