### ISSUE TITLE
Missing libraries menu context after switching between languages

### ISSUE THREAD

**Issue by hanickadot** [mattgodbolt/compiler-explorer#1347]
Hi, when I switch from CPPX to C++ language, the libraries menu is empty.
![Screenshot 2019-04-10 at 14 19 06](https://user-images.githubusercontent.com/6557263/55877981-c1250c80-5b9b-11e9-8762-4529988eb8cd.png)

**Comment by RabsRincon** [comment]
Hmm. This one is supprising, as I can't repro it in the live site nor locally. I wonder how this happened

**Comment by hanickadot** [comment]
1) Set to CPPX language
2) refresh whole page (you should be at CPPX)
3) check there are no libraries (they shouldn't be)
4) switch language to C++
5) check there are no libraries (they should be)

(refresh between 4 and 5 will fix it)

I'm using safari on latest mac os 10.14.4, but it's happening in chrome too. I don't have any other browser to check it.
