### ISSUE TITLE
bug: syntax highlighting is applied to comments

### ISSUE THREAD

**Issue by creaothceann** [mattgodbolt/compiler-explorer#1352]
(Pascal source code)

![godbolt Pascal comments](https://user-images.githubusercontent.com/1885014/56093123-dfa14580-5ec4-11e9-9c19-4bf65f0acdf4.png)

**Comment by partouf** [comment]
Pascal commenting rules are literally the worst, feel free to try and implement them @ https://github.com/mattgodbolt/compiler-explorer/blob/master/static/modes/pascal-mode.js
