### ISSUE TITLE
Add ISPC v1.11.0

### ISSUE THREAD

**Issue by pbrubaker** [mattgodbolt/compiler-explorer#1358]
Hey Matt, the new version of ISPC was released today.  Can it be added to the list of compilers?

http://ispc.github.io/downloads.html

Thanks!

**Comment by mattgodbolt** [comment]
On it! Thanks :)

**Comment by mattgodbolt** [comment]
The site is just updating to include the new compiler. Have fun!

**Comment by pbrubaker** [comment]
Thanks Matt!
