### ISSUE TITLE
_Fract / _Sat / _Accum don't work with gcc on arm

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#136]
From a personal email from "Josh":

"i just got done seeing why a friend couldn't use it either, and found out it is enabled by default on mips and arm, and not x86/other targets

i cross checked with the arm-none-eabi toolchain from gnu arm embedded, and it does have it enabled, my host x86 compiler doesn't

ohsix@krang:/tmp$  gcc -c test2.c
test2.c:1:1: error: fixed-point types not supported for this target
ohsix@krang:/tmp$  arm-none-eabi-gcc -c test2.c
ohsix@krang:/tmp$

it would be cool if it worked on all the targets (explicitly enabled) but just the arm target as default would be very helpful"

**Comment by ohsix** [comment]
[ohsix@pro tmp]$  cat test.c
_Sat long _Accum bar;
long _Accum foo;
long _Fract baz;


int main(int argc, char* argv[])
{
	return 0;
}
[ohsix@pro tmp]$  arm-none-eabi-gcc -c test.c 
[ohsix@pro tmp]$  gcc -c test.c
test.c:1:11: error: fixed-point types not supported for this target
 _Sat long _Accum bar;
           ^~~~~~
test.c:2:6: error: fixed-point types not supported for this target
 long _Accum foo;
      ^~~~~~
test.c:3:6: error: fixed-point types not supported for this target
 long _Fract baz;
      ^~~~~~

(unrelated, disconnect.me breaks the url shortening/linking)
https://godbolt.org/g/5rU6GQ

seems the same

**Comment by mattgodbolt** [comment]
Thanks for the info.The link you gave is compiling this as C++, which gives a different error (it's not valid C++). However, passing `-x c` fixes it: https://godbolt.org/g/LeUA4G 

CE always compiles using `g++` but can be put in C mode with `-x c` -- sorry that wasn't clear.  I tested the newer ARM compilers and they all seem to work; closing this. Let me know if this isn't a good fix for you :)

**Comment by ohsix** [comment]
ah, i'd forgotten, also the command line passing is new; thanks for looking into it
