### ISSUE TITLE
Incomplete AST view for global variables

### ISSUE THREAD

**Issue by pgoodman** [mattgodbolt/compiler-explorer#1360]
```c
extern int a, b, c;
int *x = &b;
```

produces the following:

```
TranslationUnitDecl
|-VarDecl <line:1:1, col:12> col:12 a 'int' extern
```

**Comment by mattgodbolt** [comment]
@TartanLlama do you happen to know if this is a CE problem or a clang issue? Thanks!

**Comment by steveire** [comment]
It is a CE issue. The cause is probably in the same place as https://github.com/mattgodbolt/compiler-explorer/issues/1346. I'd even call this issue a duplicate of that one.

**Comment by mattgodbolt** [comment]
Closing as a duplicate (if only to keep the bug count down!)
