### ISSUE TITLE
What happened to the include paths?

### ISSUE THREAD

**Issue by eyalroz** [mattgodbolt/compiler-explorer#1361]
I can't see the include path in the installed library listing - what happened to it?

https://godbolt.org/admin/libraries.html

... oh, it seems now we don't need to manually add the include path, just use the "Libraries" button. But - the Wiki should be updated to explain this, I think.

**Comment by RabsRincon** [comment]
You are right! We should improve the documentation, and also how we express the fact that the include paths are handled automatically.

**Comment by RabsRincon** [comment]
Sorry that we dropped the ball here and went silent for so long. I have now improved the wording a bit on the wiki. I'll close the issue even though we currently don't show where the libraries are currently hosted to be able to manually include them, but this is less of an issue as time goes on and the _new_ dropdown catches on

Thanks again for the report and for your patience :)
