### ISSUE TITLE
Tooltip for movups instruction incorrect

### ISSUE THREAD

**Issue by GSPP** [mattgodbolt/compiler-explorer#1376]
The tooltip for `movups` says:

> Note: VEX.vvvv and EVEX.vvvv is reserved and must be 1111b otherwise instructions will #UD.

Repro: https://godbolt.org/z/U_XKrO

**Comment by GSPP** [comment]
Maybe there is some truncation going on. The tooltip for `haddps` displays the first paragraph from https://www.felixcloutier.com/x86/haddps but not the others. Is this intentional? It was confusing to me as a user.

**Comment by mattgodbolt** [comment]
We have to truncate somewhere: currently the first paragraph is all we show from Felix's site. It's not intentional, but we don't have a better idea currently.

**Comment by GSPP** [comment]
I see. Maybe you can add the full text into the tooltip with a scrollbar.

**Comment by Sawwave** [comment]
Just closed my duplicate issue citing the vmovdqa opcode, referenced above. 

I just looked up both movups and vmovdqa, in the Intel 64 and IA-32 Architectures software Developer's Manual that Felix scrapes for his site, and the Note-At-Top ordering of paragraphs is present in this manual.

Asking Intel to amend their manual would certainly solve the problem, but I have no idea how long that might take, or if they would even follow through.

As a stop gap, what do you think of a system like as follows:
     "Include every full paragraph until you have displayed at least 250 characters in the tooltip"
That would likely fix these opcode tooltips by including the notes at the top in addition to the actual descriptive documentation.

I'm sure that would an annoying edge-case to implement, so I don't know if it'd be worth the trouble.

**Comment by mattgodbolt** [comment]
Please do note you can get the full popup from the context menu (as the tooltip says). If the source is wrong, there's not too much we can do (though we're thinking of other sources too)
