### ISSUE TITLE
Compilation failed on x86 gcc 1.27

### ISSUE THREAD

**Issue by softwareguycoder** [mattgodbolt/compiler-explorer#1383]
I put the C code 
```
// Type your code here, or load an example.
int killproc(int pid) {
    pid = pid - 9;
    return pid;
}

int main() {
    return killproc(1337);
}
```
in the left hand side using the menu option "C" in the Language drop-down.  it works fine with x64 gcc selected in the Compiler drop-down but says ```<Compilation failed>``` when ```x86 gcc 1.27``` is the selected compiler.

**Comment by cpplearner** [comment]
That's because ancient C does not support single line comment (`//`). What's the problem?

**Comment by partouf** [comment]
Indeed this gcc version only supports /* */ comments.
You can see the actual error message when you click the Output button.

I understand this seems weird that even the example fails because of this, but be aware that this compiler is from 1988.

**Comment by softwareguycoder** [comment]
Thanks for the assistance.  I tried to compile the following code:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char* theString = "Hello, world!\n";

int main() {
  for (int i = 0; i < strlen(theString); i++) {
    if (theString[i] < 0x61 || theString[i] > 0x7A) {
      continue;
    }
    theString[i] -= 0x20;
  }
  return 0;
}
```
As can be seen, there are no wrong comments.  Now what does it not like?  Here is the output:
```
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stdarg.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
/usr/include/sys/sysmacros.h:62: warning: parameter name starts with a digit in #define
/usr/include/sys/sysmacros.h:62: badly punctuated parameter list in #define
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
cpp: Value too large for defined data type for `/opt/compiler-explorer/gcc-1.27/lib/gcc-include/stddef.h'
Compiler returned: 1
```
I am not sure if the error is in my code, or faulty system include files.

**Comment by mattgodbolt** [comment]
I suspect the system header files on a modern Linux system (such as Compiler Explorer runs on) use features not supported on such an old compiler.

GCC 1.27 is really only here as an historic homage to the way compilers used to be. I wouldn't expect it to be able to compile any modern code.

That said; the headers you're including are - for the most part - unnecessary. I had to make a few changes (for example you can't define variables in the `for` statement in older C): https://godbolt.org/z/WkGhge

**Comment by softwareguycoder** [comment]
The only reason why I only selected that is i am working on x86 assembly programming exercises for school, but I "think in C" since I am very experienced in C.  So, I am trying to find a way to make GodBolt.org show me the corresponding assembly with 32-bit extended registers and, e.g., 4-byte integers etc. only, as opposed to RAX, RBX, and 8-Byte integer types.

**Comment by softwareguycoder** [comment]
mattgodbolt said:
> GCC 1.27 is really only here as an historic homage to the way compilers used to be.

Is there an example(s) of code that WILL compile on that stuff?

**Comment by mattgodbolt** [comment]
I linked an example of code that does compile in my comment above.

GCC 1.27 is _ancient_. If you're trying to see modern C code, but built for 32-bit CPUs, try adding `-m32` to the command-line options to choose 32-bit CPU output. For example, this link shows your original code, built on GCC 9.1 with optimisation: https://godbolt.org/z/tpWXTx
