### ISSUE TITLE
Difference between GCC 7.4 on ubuntu and godbolt

### ISSUE THREAD

**Issue by dtmoodie** [mattgodbolt/compiler-explorer#1389]
I have a bug that I'm working through with gcc 7.4 on ubuntu 18.04.  I was using godbolt to test when it gets fixed, to my surprise I found that gcc 7.4 on godbolt compiles my example code correctly.  Can you link the output of gcc -v for 7.4.  I'm currently trying to build with your https://github.com/mattgodbolt/compiler-explorer-image/blob/master/gcc/build/build.sh but I'm not sure how to invoke it.

**Comment by RabsRincon** [comment]
Sure! 
```
May/20 17:57 admin-node~ $ /opt/compiler-explorer/gcc-7.4.0/bin/g++ -v                                   
Using built-in specs.                                                                                    
COLLECT_GCC=/opt/compiler-explorer/gcc-7.4.0/bin/g++                                                     
COLLECT_LTO_WRAPPER=/opt/compiler-explorer/gcc-7.4.0/bin/../libexec/gcc/x86_64-linux-gnu/7.4.0/lto-wrapper                                                                                                        
Target: x86_64-linux-gnu                                                                                 
Configured with: ../gcc-7.4.0/configure --prefix=/opt/compiler-explorer/gcc-build/staging --build=x86_64-
linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-bootstrap --enable-multiarch --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --enable-clocale=gnu --enable-languages=c,c++,fortran --enable-ld=yes --enable-gold=yes --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-linker-build-id --enable-lto --enable-plugins --enable-threads=posix --with-pkgversion=GCC-Explorer-Build                                                                                                        
Thread model: posix                                                                                      
gcc version 7.4.0 (GCC-Explorer-Build) 
```

**Comment by apmorton** [comment]
perhaps the issue you are facing in gcc is part of the linker step?
godbolt doesn't run the linker by default - maybe click the "11010" button in the compiler pane to enable linking and see what happens.

**Comment by dtmoodie** [comment]
Thanks for the reply!
@apmorton 
Unfortunately this is during compilation and not linking; but I did try your recommendation and still no issues with compiler explorer. My ubuntu gcc is built with many more flags so I have someplace to start looking.

**Comment by mattgodbolt** [comment]
I'm going to close this: @dtmoodie please do let us know if you need anything more to track this down. Closing, but feel free to reopen.
