### ISSUE TITLE
Can't run llvm-mca on assembly

### ISSUE THREAD

**Issue by umanwizard** [mattgodbolt/compiler-explorer#1392]
It is great that you added the llvm-mca tool, however I think usually people would want to run it on assembly snippets directly, not on compiler output. There's no way to do that AFAICT -- when selecting "Assembly" from the language dropdown, all tools are disabled

**Comment by partouf** [comment]
Hi, we added the Analysis language to the website even before adding Tools. https://godbolt.org/z/SrcjQK
You can paste/type assembly right there and see the analysis.
