### ISSUE TITLE
Consecutive newline characters are discarded in output window

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1397]
When execution outputs consecutive new lines, they're scrunched up.

**Comment by RabsRincon** [comment]
This comes from the parsing of the output when trying to treat it as compiler output so we can link back to source lines at https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/base-compiler.js#L161
I think we probably don't want that, and the program output should not be touched too much, if at all

**Comment by reuvenab** [comment]
Following for your advice crafted solution below
Will think how to fix tabs

--- a/lib/base-compiler.js
+++ b/lib/base-compiler.js
@@ -813,7 +813,8 @@ Please select another pass or change filters.`;
  return this.execPostProcess(result, postProcess, outputFilename, maxSize);
                 } else {
                     return this.readFile(outputFilename).then(contents => {
-                        result.asm = contents.toString();
+                        var new_contents = contents.toString().split('\n').flatMap(x => x.split('{')).join('\n');
+                       result.asm = new_contents;
                         return Promise.resolve(result);
                     });


**Output**
```

square(int):
        PUSHM.W #1, R4
        MOV.W   R1, R4
        PUSH.W sr 
 DINT 
 NOP 
 MOV.W R12, &0x0132 
 MOV.W R12, &0x0138 
 MOV.W &0x013A, R12 
 MOV.W &0x013C, R13 
 POP.W sr
        POPM.W  #1, r4
        RET
```

**Comment by mattgodbolt** [comment]
This also affects diagnostic output from the compiler: e.g. https://cppx.godbolt.org/z/wT98jM

we should probably "just" fix up the postprocess

**Comment by RabsRincon** [comment]
Empty lines should now not be discarded after 52b977bb1d6571e331f2736fae04ba5aabaa947e
