### ISSUE TITLE
In the beta version, ellcc 2017-07-16 fails to find libc++ and doesn't execute code

### ISSUE THREAD

**Issue by bstaletic** [mattgodbolt/compiler-explorer#1406]
https://godbolt.org/beta/z/1dBTWl

The other two versions of ELLCC can execute something simple like `std::cout<<"foo";` (I haven't tried anything beyond that.)

**Comment by mattgodbolt** [comment]
Seems related to #1399

**Comment by bstaletic** [comment]
It does seem related. I also managed to make GCC "lose" libstdc++ with a similar error message sometime late last night..

**Comment by partouf** [comment]
this isn't resolved with the current ldpath defaults, but I think it should be solved with something like compiler.ellcc170716.ldPath=/opt/compiler-explorer/clang-5.0.0/lib
as it looks like it's using clang-5.0.0

**Comment by partouf** [comment]
Ok that doesn't work, gives an error saying "Error loading shared library libc++.so: Exec format error"

Checking other paths

**Comment by partouf** [comment]
will be fixed by https://github.com/mattgodbolt/compiler-explorer/commit/90aafb7878c4e04ccb0c37a472a261eff8f140e1

**Comment by partouf** [comment]
fix is live
