### ISSUE TITLE
zig execution fails

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1409]
https://godbolt.org/staging/z/J9wESc (if staging isn't up, remove `/staging/`).

```
Internal Compiler Explorer error: TypeError: Cannot read property 'code' of undefined
    at getOrBuildExecutable.then.buildResult (/compiler-explorer-image/.deploy/lib/base-compiler.js:387:33)

Compiler returned: -1
```

**Comment by RabsRincon** [comment]
@tiehuis I think this might be because we can't find the generated executable. Any ideas here? :)

**Comment by tiehuis** [comment]
Not sure of anything of the top of my head that has changed. Will have a closer look tomorrow.

**Comment by tiehuis** [comment]
This is still on my radar. Just haven't yet had the chance to get to this.
