### ISSUE TITLE
pahole support for C and non-x86 targets

### ISSUE THREAD

**Issue by cibyr** [mattgodbolt/compiler-explorer#1417]
Right now it seems like the site only allows the use of `pahole` with C++ on x86-64 gcc compilers. `pahole` works on any ELF binary with DWARF2 symbols, so hopefully this should be a simple UI change to allow it to be enabled.

**Comment by partouf** [comment]
pahole has been added to most of the C compilers in production now.
The non-x86 is because of linking issues usually not possible, but if there's one that we can build and link with the 11010 option and missing the pahole tool, please let us know.
