### ISSUE TITLE
Could not type in code in the source code edit pane while using Chrome

### ISSUE THREAD

**Issue by loveyoupeng** [mattgodbolt/compiler-explorer#1424]
it is wired i could not edit the source code in the editor pane, only tabs/arrow/delete keys works, all the other character keys could not type in, i tried on my chromebook/windows desktop/linux laptop/android phone, all chrome has the same issue, if i switched to firefox, everything works well without any issue.

**Comment by partouf** [comment]
I only test the website with chrome on windows desktop and have never seen this kind issue. Can you try to  click on More -> Reset code and UI layout  -  and see if the problem persists?

**Comment by loveyoupeng** [comment]
Sorry for the late reply, I have tried to reset the layout, no luck, still could not edit the code, my chrome is Version 74.0.3729.159 (Official Build) (64-bit)

following are the error message from chrome console hope it helps

Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.e.selectedText (editor.main.js:31)
    at f (editor.main.js:31)
    at HTMLTextAreaElement.<anonymous> (editor.main.js:31)
    at HTMLTextAreaElement.o (helpers.js:69)

breadcrumbs.js:158 POST https://sentry.io/api/102028/store/?sentry_key=8e4614f649ad4e3faf3e7e8827b935f9&sentry_version=7 429 (TOO MANY REQUESTS)

**Comment by mattgodbolt** [comment]
Do you have any Chrome extensions? Can you try this in an "Incognito" window please, and see if the problem continues? Thanks!

**Comment by mattgodbolt** [comment]
As we've not heard back on this, I'm going to close. Thanks for taking the time to report and don't hesitate to reopen or comment if youre still having trouble!
