### ISSUE TITLE
Weird gcc output for arm targets

### ISSUE THREAD

**Issue by ithinuel** [mattgodbolt/compiler-explorer#1427]
Using `arm gcc >= 6.3` yields weird result when compiling this with `-mtune=cortex-m0 -mthumb -mcpu=cortex-m0 -Os` :
```c
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// forward declaration of a foo
struct foo_s;
typedef int8_t foo_bar_t;

typedef struct foo_s {
    struct foo_s* next;
    foo_bar_t bar;
} foo_t;

extern foo_t* a_foo;
extern foo_t *a_list_of_foos;
extern bool baz;

void foo_do_stuff(foo_t* foo);
bool bar_as_bool(bool *);
void do_stuff();

void foo_do_stuff(foo_t* foo)
{
    foo_t *prev = a_list_of_foos;
    while ((prev != NULL) && (prev->bar >= foo->bar)) {
            prev = prev->next;
    }
    foo->next = prev->next;
    prev->next = foo;

     if (!bar_as_bool(&baz)) {
         return;
     }
     if (foo->bar > a_foo->bar) {
         do_stuff();
     }
 }
```

![image](https://user-images.githubusercontent.com/4605303/58788220-4f899d80-85e3-11e9-8d77-31db9c47c68b.png)

**Comment by ThadHouse** [comment]
You're not null checking `foo`, so it's generating a trap in that scenario. I've seen that happen in other cases with more arm compilers as well.

**Comment by ithinuel** [comment]
I see, .L8 has a `.inst 0xdeff`. However, address 0 is not an invalid address on a microcontroller. GCC is being too smart in that case :/
