### ISSUE TITLE
Dropdown menu clipped/cutoff when at edge of container

### ISSUE THREAD

**Issue by jameshamm** [mattgodbolt/compiler-explorer#1441]
![image](https://user-images.githubusercontent.com/10179936/59362148-df89be80-8d2a-11e9-96df-7af5bb06ef16.png)

The dropdown menu can sometimes be clipped if it is on the edge of a container. For example in the above image the "add new" dropdown cuts off. ([Link](https://godbolt.org/z/bqBjGC) to layout I had at the time)

(Possible) steps to reproduce the clipped menu

1. Start a new session on compiler explorer.
2. Drag separator/splitter to the right so the compiler output pane only has a tiny portion of the screen.
3. Click the "+ add new" dropdown button.

![image](https://user-images.githubusercontent.com/10179936/59362616-ad2c9100-8d2b-11e9-99df-35ee152c5fb6.png)

This is without any changed settings from the default for the (live version of the) site. This may be related to [issue 358](https://github.com/mattgodbolt/compiler-explorer/issues/358) or [issue 364](https://github.com/mattgodbolt/compiler-explorer/issues/364).

**Comment by mattgodbolt** [comment]
This is likely a "feature" of the windowing system we're using (Golden Layout). I'm not sure what we can do about it, but will track progress here.
