### ISSUE TITLE
We seem to have lost codecov

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1451]
Codecov has not been working for a while now, and the project page seems to return some kind of error

**Comment by sdrees** [comment]
@mattgodbolt  I suggest to check the settings here in the github project for this. I had to switch to the github app for codecov to establish the badge feedback again. Befor I had used the github Services option which is deprecated. HTH, Stefan

**Comment by RabsRincon** [comment]
It looked like it was broken for a while now due to some missconfiguration, but it's now back up. Thanks for the tip too @sdrees :)
