### ISSUE TITLE
__ldg intrinsics not recognized in CUDA

### ISSUE THREAD

**Issue by VinInn** [mattgodbolt/compiler-explorer#1453]
```
__global__ void square(int const * in, int * out, int n) {
    int tid = blockIdx.x;
    if (tid < n)
        out[tid] = __ldg(in+tid) * in[tid];
}
```

produces
```
<source>(4): error: identifier "__ldg" is undefined
1 error detected in the compilation of "/tmp/tmpxft_00000007_00000000-6_example.cpp1.ii".
Compiler returned: 1
```

**Comment by mattgodbolt** [comment]
According to https://stackoverflow.com/questions/24069524/error-using-ldg-in-cuda-kernel-at-compile-time you need to supply a command-line parameter to NVCC to enable an architecture that supports this intrinsic: https://godbolt.org/z/FySS6Z

**Comment by VinInn** [comment]
ah, ok.
Thanks for the fast suggestion and sorry for the noise
