### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by Vm900** [mattgodbolt/compiler-explorer#1456]
Hi folks,
I am trying to run make from msys and i keep getting this error:
fatal: not a git repository(or any of the parent directories): .git
etc/scripts/find-node:lime 28: /c/Program:No such file or directory
make: *** [.node-bin] Error 1
=======+================================+=============
Help thanks

**Comment by mattgodbolt** [comment]
Hi there!

It seems like you're trying to run on Windows. Compiler Explorer does work on Windows, but the tooling around developing and running is very different (and mostly not supported). There's a HOWTO document here: https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/WindowsNative.md - as you can see it mostly means running some steps the `Makefile` does manually (the `Makefile` is very specific to UNIX-like operating systems).

That said we might be able to fix some of the scripts: seems the space in `Program Files` is upsetting the `find-node` script.
