### ISSUE TITLE
`-lblah` options should be placed after the input filename

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1459]
Consider https://gcc.godbolt.org/z/O4aVOC - this fails with a linker error: `undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'`

It was pointed out on discord that if the executable comes first, the link succeeds, i.e. this is a link order issue.

Specifically: 

```
/opt/compiler-explorer/gcc-8.3.0/bin/g++ -g -o /tmp/output.s -masm=intel -fdiagnostics-color=always -O3 -std=c++17 /tmp/test.cc -lstdc++fs
```

works but

```
/opt/compiler-explorer/gcc-8.3.0/bin/g++ -g -o /tmp/output.s -masm=intel -fdiagnostics-color=always -O3 -std=c++17 -lstdc++fs /tmp/test.cc
```

does not.

**Comment by mattgodbolt** [comment]
The easiest way to achieve this is of course to "just" put the input filename last in the computed command-line.

**Comment by apmorton** [comment]
`-Wl,--start-group` is also an option here. It could be unconditionally placed before any user provided arguments when linking.

```/opt/compiler-explorer/gcc-8.3.0/bin/g++ -g -o /tmp/output.s -masm=intel -fdiagnostics-color=always -Wl,--start-group -O3 -std=c++17 -lstdc++fs /tmp/test.cc```

**Comment by jwakely** [comment]
I came here to report the same issue, after being told GCC 8's `std::filesystem` code gives linker errors: https://www.reddit.com/r/cpp/comments/c87o36/clang_800_and_stdcfs_doesnt_work_with_o3/esnlsbg

On reddit I gave `-Wl,--whole-archive -lstdc++fs -Wl,--no-whole-archive` as a workaround that can be used to make it work until this is fixed.

**Comment by partouf** [comment]
From the reddit link it seems this statically links to a .a file?

For most link libraries the order doesn't matter except if those libraries depend on each other, so I don't really understand why this needs to be at the end at all. But that's another story.

I guess we can probably fix this by making std::filesystem a C++ library and making a specific rule for that.

Are there any other not-by-default-available libraries we need to be able to link to?

**Comment by jwakely** [comment]
> From the reddit link it seems this statically links to a .a file?

Right. There is no dynamic version of `libstdc++fs`, only a static lib.

> For most link libraries the order doesn't matter except if those libraries depend on each other, so I don't really understand why this needs to be at the end at all.

Because that's how static linking works. http://c-faq.com/lib/libsearch.html

If `foo.o` depends on symbols in `libstdc++fs.a` and you do `g++ -lstdc++fs foo.o` then nothing from `libstdc++fs.a` will get added to the executable, because no undefined references have been seen until `foo.o` is processed.

**Comment by partouf** [comment]
Ah right, that makes a lot of sense. Ok, thank you.

**Comment by partouf** [comment]
Fixed with https://github.com/mattgodbolt/compiler-explorer/commit/ba7d53572cbfbd6d0d4f36f6e9cc1bac9094917f
Not live yet.

**Comment by partouf** [comment]
This is now live

**Comment by jwakely** [comment]
Thanks!
