### ISSUE TITLE
Deadcode warnings and no assembly generated for Rust

### ISSUE THREAD

**Issue by aserebryakov** [mattgodbolt/compiler-explorer#1460]
The following code causes dead code warning and no assembly output generated in Rust:
```
fn iterate_with_boxed_iterator<'a, T: std::fmt::Display>(iter: Box<dyn Iterator<Item = T> + 'a>) {
    for x in iter {
         println!("{}", x);
    }
}

fn main() {
    let test = String::from("test");
    iterate_with_boxed_iterator(Box::new(test.chars()));
}

```

Compiler output:
```
warning: function is never used: `iterate_with_boxed_iterator`

 --> <source>:1:1

  |

1 | fn iterate_with_boxed_iterator<'a, T: std::fmt::Display>(iter: Box<dyn Iterator<Item = T> + 'a>) {

  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  |

  = note: #[warn(dead_code)] on by default

warning: function is never used: `main`

 --> <source>:7:1

  |

7 | fn main() {

  | ^^^^^^^^^

Compiler returned: 0
```

**Comment by CryZe** [comment]
You need pub fn for a function to be export out of the module in Rust. Godbolt compiles Rust code as a library, so fn main() { ... } is not the actual main function.

**Comment by aserebryakov** [comment]
@CryZe, `pub` solved the issue. Is it possible to run Rust code as we have for C++?

**Comment by CryZe** [comment]
It seems like C and C++ automatically switch between executable and library based on whether a main function is found, while with Rust you have to specify it in the rustc arguments. At the moment Compiler Explorer always passes that it wants to compile a library. I'm not sure what the best way is to integrate executable and therefore execution support in Compiler Explorer for a language like Rust. One way would be to simply parse the AST and see if a `fn main() { ... }` is defined and then pass different arguments to the compiler.

**Comment by aserebryakov** [comment]
@CryZe In general I think that this issue should be closed and for execution should be opened another one.
