### ISSUE TITLE
Program output diff

### ISSUE THREAD

**Issue by cjdb** [mattgodbolt/compiler-explorer#1463]
We've got compiler output diff: would it be possible to get program output diff-mode as well please? I often find it very difficult to track minor changes in program output, and having a tool to assist in this regard would be splendid.

**Comment by kisielk** [comment]
I was in the midst of filing a new issue for this, but found this one. Here's what I wrote:

**Is your feature request related to a problem? Please describe.**
It's not easy to see what changes occur to the binary as a result of changing the source code. One way to do it is to create two versions of the same function in one file and then visually compare the output, but it's not as easy as it could be.

**Describe the solution you'd like**
It would be great if the diff view supported diffing the output of two different files, not just two different compilers. Then it would be easy to visually compare the differences.

**Comment by partouf** [comment]
This feature is now live
