### ISSUE TITLE
Demangler doesn't demangle things inside call ptr [*]

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#1468]
For example https://godbolt.org/z/UGgrp_ as described in https://github.com/mattgodbolt/compiler-explorer/pull/1466

**Comment by partouf** [comment]
regex /call[q]?.*ptr\s\[[a-z]*\s\+\s([.a-z_$][a-z0-9$_@.]*)\]/
will recognize the mangled identificer in
"         call    qword ptr [rip + _ZN3std2io5stdio6_print17ha4c0b9f4da5c9e13E@GOTPCREL]"

**Comment by cpplearner** [comment]
It probably should also recognize cases like (https://godbolt.org/z/D6l5NY)
```
        call    *_ZN3foo3bazE+8(%rip)
        callq   *_ZN3foo3bazE+8(%rip)
        call    [QWORD PTR _ZN3foo3bazE[rip+8]]
        call    qword ptr [rip + _ZN3foo3bazE+8]
```
or corresponding tail calls (https://godbolt.org/z/zzggXQ)
```
        jmp     *_ZN3foo3bazE+8(%rip)
        jmpq    *_ZN3foo3bazE+8(%rip)   # TAILCALL
        jmp     [QWORD PTR _ZN3foo3bazE[rip+8]]
        jmp     qword ptr [rip + _ZN3foo3bazE+8] # TAILCALL
```
