### ISSUE TITLE
Privacy Policy – GDPR compliance

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [mattgodbolt/compiler-explorer#1472]
From the privacy policy:
> The Compiler Explorer team believes the Compiler Explorer site is compliant with the EU's General Data Protection Regulation (GDPR).

I can tell you: **It is not.**

Art. 13 (1) lit. e clearly states to inform about all recipients of personal data. By loading `https://s3.dualstack.us-east-1.amazonaws.com/compiler-explorer/motd/motd-prod.json` personal data of the data subject is transferred to Amazon. Personal data in that case is: ip address, user agent and so on – a usual http request.

Possible solutions are:
1. Don't load this file at all or change it in a way so it is loaded directly from godbolt.org. (**better choice**, privacy-wise)
2. In the privacy policy, state that by loading this site the user's ip address, user agent etc. is transferred to Amazon. You basically have two possible legal foundations for doing that: Art. 6 (1) lit. a or lit. f.
2.1 For letter a you need the user's consent. This would also require the website to _not_ send a request to Amazon until consent is given. If consent is _not_ given the website needs to work, too, otherwise the consent is not freely given.
2.2 Letter f requires you to inform the user about your legitimate interests pursued (Art. 13 (1) lit. d) and e. g. how long the personal data is saved. There's the problem: maybe "forever", because Amazon.

Although very common in the interwebs, number 2 is basically not possible. It is very safe to say that it will conflict Art. 5 and some others too. You cannot make sure the personal data is only kept as long as necessary (Art.5 (1) e). Also you have to make sure a user can make use of his rights of access (Art. 15) and erasure (Art. 17). I wish you good luck trying to do that, once the user's personal data has sunk into the depths of (the) Amazon.

Therefore I strongly suggest number 1. I hope this is somehow possible and not too much of a hassle.

Thanks for your time and the work on this project.

**Comment by apmorton** [comment]
Are you aware that the entire godbolt.org site is hosted by Amazon?

The site uses CloudFront, backed by S3 for static data (the same bucket that the motd file is loaded from) and EC2 instances for dynamic content.

How does this impact your observations? From the very first request to godbolt.org Amazon is involved.

**Comment by mattgodbolt** [comment]
Thanks Austin. I agree with his observations. The whole site is hosted on Amazon's infrastructure and as such your IP address et al are visible to Amazon. Unless I'm missing something, there's no way to prevent this. We have Amazon logging configured to keep information for a very short amount of time only, to the best of our understanding of what information we log. All of this is visible in the terraform configuration in the compiler explorer image repository.

We'd appreciate any help with this. We took as much advice as we could and the current set up is a good faith attempt to comply with GDPR.

**Comment by RabsRincon** [comment]
Also to note, Amazon AWS claims to also be GDPR compilant https://aws.amazon.com/compliance/gdpr-center/

**Comment by ArneBab** [comment]
If you only keep information needed to run your system but nothing to track users additionally, then you should be GDPR compliant.

https://gdpr.eu/cookies/ → *Strictly necessary cookies — These cookies are essential for you to browse the website and use its features, such as accessing secure areas of the site. Cookies that allow web shops to hold your items in your cart while you are shopping online are an example of strictly necessary cookies. These cookies will generally be first-party session cookies. While it is not required to obtain consent for these cookies, what they do and why they are necessary should be explained to the user.*

**Comment by h88e22dgpeps56sg** [comment]
I had a quick look at how AWS implements the GDPR including the CISPE code of conduct. They claim to just provide the infrastructure and only do what the customer (i. e. you) tells them to do. I can see no obvious GDPR violation in this. On the contrary, the issue I brought up here was.

Thanks a lot for changing it.

**Comment by mattgodbolt** [comment]
Thanks for taking the time to help us ensure we're not only doing the right thing, but are staying within the law too! It's appreciated.
