### ISSUE TITLE
[REQUEST] Change API to name libraries

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1478]
API users are forced to know the flags and paths needed to include libraries.

Ideally there should be a way of saying "I need library X version Y" in the API request and have the server figure out the command-line options.

This was brought up in Slack by @Quuxplusone and @apmorton

**Comment by Quuxplusone** [comment]
I ended up computing `-I` options like this: https://github.com/Quuxplusone/coro/blob/master/test/compile-on-godbolt.py#L26-L36
It's not bad, actually. I *was* surprised that it required so many intermediate steps; but really, if the API had told me to write this code, I wouldn't have complained at all. The bigger problem IMHO is that [the API documentation](https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/API.md#post-apicompilercompiler-idcompile---perform-a-compilation) doesn't currently explain anything about libraries or include paths.

Documenting the names of all the individual `"filters"` would also be useful.

**Comment by partouf** [comment]
I think we wanted to do this API change a while ago. I'm gonna get on this. (btw `-I` is not used for every compiler, but I trust it's good enough for your use-case @Quuxplusone )
