### ISSUE TITLE
[BUG] C++ Syntax Highlighting fails for [[qualifier]] used twice in one line

### ISSUE THREAD

**Issue by Zyranivia** [mattgodbolt/compiler-explorer#1491]
As you can see on [https://godbolt.org/z/vDjnOw](https://godbolt.org/z/vDjnOw), in this line of code
`[[nodiscard]] void a([[maybe_unused]] int b)`
they gray coloring meant for the [[qualifier]] starts at the first `[[` and stops at the last `]]`. I fiddled a bit with invalid syntax and suppose this is the general rule, so instead of stopping at the next `]]`, it always stops at the last `]]` in a line.

 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by RabsRincon** [comment]
Good catch! Thanks for the report :)
It's an issue on the Monaco editor project which I'll report shortly, but we can fix it locally while an upstream fix is published.
