### ISSUE TITLE
[BUG] CORS issue with MOTD on compiler-explorer.com

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#1500]
**Describe the bug**
* Access to XMLHttpRequest at 'https://godbolt.org/motd/motd-prod.json' from origin 'https://compiler-explorer.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
* bundle.b6d471d203e93beed2ce.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://godbolt.org/motd/motd-prod.json with MIME type binary/octet-stream. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**To Reproduce**
* Go to compiler-explorer.com

**Desktop (please complete the following information):**
 - Chrome

**Comment by mattgodbolt** [comment]
Nice!

I wonder if https://sentry.io/organizations/compiler-explorer/issues/1109955254/?environment=amazon&project=102028&query=is%3Aunresolved is related? I've not been able to work out what's going on there (despite ineffective attempts to log more info)
