### ISSUE TITLE
[REQUEST] Highlight matching angle brackets

### ISSUE THREAD

**Issue by Predelnik** [mattgodbolt/compiler-explorer#1508]
Since writing templates and checking compilation is quite popular usage of compiler explorer it would be nice if matching angle brackets were highlighted. Resharer C++ does this and it's incredibly convenient.

I don't know if it requires some code changes in editing component or just a switch in its settings, in case of latter it would be really nice to just enable it.

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. I've implemented the change, but as it modifies internal bits of our editor solution, I've made a PR so it can get a bit of test before merging. If everything goes smoothly, it should not take long for it to get merged and released.

Thanks for taking the time to open an issue with your request :)
