### ISSUE TITLE
[BUG] Not able to do AST Dump from clang (trunk)

### ISSUE THREAD

**Issue by schwarzschild-radius** [mattgodbolt/compiler-explorer#1511]
Description:
    I am not able to dump AST from clang (trunk), but for the other versions of clang it is possible.

To Reproduce:
https://godbolt.org/z/pDbEHR

Expected Behavior
I should be able to get the AST output if I am not wrong.

Platform:
 - OS: Windows
 - Browser: Chrome
 - Version 75

**Comment by apmorton** [comment]
Thanks for reporting this!
clang-trunk just bumped to 10.0, and our version check broke.

This should get resolved on the live site in the near future.
