### ISSUE TITLE
[BUG] Completely unable to use save button

### ISSUE THREAD

**Issue by GabrielRavier** [mattgodbolt/compiler-explorer#1514]
Pressing the button with the save icon does nothing.

Steps to reproduce the behaviour :
- Press the save icon on the top left

This does nothing, when it should open the save menu.

Godbolt after refreshing the page twice, refreshing while clearing the cache, restarting Firefox and finally attempting a system reboot (twice) and pressing the save icon ~50 times each : ![image](https://user-images.githubusercontent.com/31440290/62155724-eb950400-b309-11e9-920f-ca6b20ba54e8.png)

 - OS : Linux, Fedora 30 (64-bit) (core-4.1-amd64) (Linux kernel version 5.1.8-300 x86_64)
 - Browser : Firefox Nightly 67.0.2 (64-bit) for Fedora

Encountered this while trying to load some old code I was working with.

**Comment by partouf** [comment]
Hi, thanks for reporting this, we have totally missed this bug! We'll get on it

**Comment by GabrielRavier** [comment]
Every other button works btw, this is the only thing I'm having trouble with

**Comment by RabsRincon** [comment]
Sorry about this, and thanks for the report. The fix should hit the live site in the next minutes :)

**Comment by GabrielRavier** [comment]
Thanks for the fix !
