### ISSUE TITLE
[BUG] Typo in the compiler selection list: "DJGGP"

### ISSUE THREAD

**Issue by lunakid** [mattgodbolt/compiler-explorer#1516]
![image](https://user-images.githubusercontent.com/698307/62220052-b17e3d80-b3af-11e9-97ae-7d03b767749f.png)

(Note: it was already mistyped in the title of #1244, too, as well as in the corresponding branch name, apparently. But not in the original #844, FWIW.)

**Comment by Patil2099** [comment]
Can I work on this ?

**Comment by RabsRincon** [comment]
Sure! Feel free to open up a PR with the changes and let us know if you have any questions! :)
