### ISSUE TITLE
[REQUEST] Add ARM gcc 8.3.1 (none)

### ISSUE THREAD

**Issue by AlexSkrynnyk** [mattgodbolt/compiler-explorer#1517]
The currently available `ARM gcc 7.2.1 (none)` has no support for C++2a and limited support for template argument deduction for class templates [(P0512R0)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0512r0.pdf)

The latest `ARM gcc 8.3.1 (none)` is available [here](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)

It would be greatly appreciated!

**Comment by apmorton** [comment]
Should be live now
