### ISSUE TITLE
[BUG] Pascal has gone missing!

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1528]
We just spotted that Pascal has vanished from the live site!

**Comment by partouf** [comment]
Probably this commit https://github.com/mattgodbolt/compiler-explorer/commit/e52f66017c7972d1ab3b507e545aee6191a31b52

Resulting in this error at startup
`warn: Unable to stat fpc304 compiler binary: Cannot find module '../demangler-pascal' {"code":"MODULE_NOT_FOUND","stack":"Error: Cannot find module '../demangler-pascal'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at new BaseCompiler (/opt/compiler-explorer/ce/lib/base-compiler.js:72:35)\n    at new FPCCompiler (/opt/compiler-explorer/ce/lib/compilers/pascal.js:35:9)\n    at CompileHandler.create (/opt/compiler-explorer/ce/lib/handlers/compile.js:110:37)"}
`
