### ISSUE TITLE
[REQUEST] Add support for CS50

### ISSUE THREAD

**Issue by pileon** [mattgodbolt/compiler-explorer#1533]
[CS50](https://en.wikipedia.org/wiki/CS50) is a rather popular (for beginners) on- and off-line introductory course about computer programming.

Sometimes it could be useful to build examples using this library.

The source for this library can be found on https://github.com/cs50/libcs50

While the course itself is rather language-agnostic, the main target is C.

**Comment by AMS21** [comment]
Since its a non header only library and as far as I know only these are supported, I guess it would be difficult.
[Reference](https://github.com/mattgodbolt/compiler-explorer/issues/1471#issuecomment-509617865)

**Comment by partouf** [comment]
This library is now live on the C side.

Be aware it's probably best to use execution, but also note that it really doesn't allow of a lot of interaction exception for a 1time stdin pass;
https://godbolt.org/z/A-Z5Qm
