### ISSUE TITLE
Can't run app.js using node

### ISSUE THREAD

**Issue by saiftali** [mattgodbolt/compiler-explorer#1538]
When I try to run app.js using node on terminal (node app.js) it gives the error that it cannot find manifest.json.

**Comment by saiftali** [comment]
I looked at the code for the app.js and it's mentioned there, but it's not in the folder so it can't find that module.

**Comment by partouf** [comment]
To run node app.js separately you still have to first run:
- npm install
- npm run start

Once the first run and the webpacking is done, you should be able to run node app.js on its own.

If that doesn't help, can you provide the full error message?

**Comment by mattgodbolt** [comment]
I'm going to close this as we've not heard back for a few months. @saiftali if you still are having trouble getting the site to run, feel free to comment here and we will help as much as we can.
