### ISSUE TITLE
New boost libraries would be nice

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#154]
Reported over email by user "KrzaQ"

**Comment by mattgodbolt** [comment]
It was suggested on slack that we could just grab the headers only. Probably a bit easier!

**Comment by mattgodbolt** [comment]
https://godbolt.org/g/e1Pm0H -- now boost_1_64 is available with a slightly nasty `-I..` command-line. Maybe selectable include paths? But another bug

**Comment by CvRXX** [comment]
Would be cool if there was a drop down to select some often used libraries

**Comment by akriti-tripathi** [comment]
Adding <optional> would be really helpful.

_/home/insights/insights.cpp:2:10: fatal error: 'boost/optional.hpp' file not found
#include <boost/optional.hpp>_
