### ISSUE TITLE
[BUG] Problem with VMOVDQU8 opcode

### ISSUE THREAD

**Issue by Sawwave** [mattgodbolt/compiler-explorer#1540]
In the assembly window, hovering the mouse over the VMOVDQU8 opcode does not give actual documentation on the opcode. Instead, the hover text says:

"Note: VEX.vvvv and EVEX.vvvv are reserved and must be 1111b otherwise instructions will #UD"

When right clicked and the opcode doc is selected, this note is above the actual documentation. I think this note needs to be moved below the doc to show up on hover.

**Comment by cpplearner** [comment]
see #1376
