### ISSUE TITLE
[BUG] Weirdly verbose MSVC output on later commits

### ISSUE THREAD

**Issue by ubsan** [mattgodbolt/compiler-explorer#1542]
**Describe the bug**
In the version of the compiler explorer Microsoft uses internally (the one which is running on godbolt.ms for godbolt.org to call out to), the output is far cleaner than the output at master. See the screenshots.

**Screenshots**
Old output, after including `<absl/container/flat_hash_map.h>`:
![old](https://user-images.githubusercontent.com/3479021/63197726-69a51a80-c02d-11e9-974c-7100bc0e7b28.png)

New output, after including `<absl/container/flat_hash_map.h>`:
![new](https://user-images.githubusercontent.com/3479021/63197729-6e69ce80-c02d-11e9-9772-63aa784e760c.png)

**Additional Information**
Technically, I'm not on master; I'm on commit `452193112016d5c8d7e7d69ba39326cbd39c3842`. However, I don't think it's likely that it would've changed in the past 15 days.

**Comment by partouf** [comment]
This is my current view, which is stranger, but at least still got line information;
For abseil I used the master version on github.

![image](https://user-images.githubusercontent.com/442630/63210349-9d477980-c0ed-11e9-8db9-0479479706a7.png)

**Comment by partouf** [comment]
Ah ok, this behaviour shows up when you're using compilerType=win32 instead of compilerType=win32-vc
Make sure it's on the latter

**Comment by ubsan** [comment]
@partouf hmm! lemme check some stuff out then, thanks :D

**Comment by ubsan** [comment]
@partouf hmm, I have it correctly set to `compilerType=win32-vc`

**Comment by partouf** [comment]
maybe an overriding compilerType property in .win32.properties or .local.properties?

**Comment by ubsan** [comment]
@partouf given that I'm using `c++.local.properties` to set these things, it seems unlikely?

**Comment by partouf** [comment]
I'm not sure what the problem is then.. I can't reproduce.. Maybe put some logger.info's in asm-parser-vc.js ?

**Comment by ubsan** [comment]
yeah, I'll figure it out.

**Comment by ubsan** [comment]
It looks like it was an issue with timeouts, sorry y'all
