### ISSUE TITLE
Only C implementation

### ISSUE THREAD

**Issue by DanielVenturini** [mattgodbolt/compiler-explorer#1551]
Hi.
Is there any `branch` or `release` or something like this that contains only the `C` implementation?

Thanks.

**Comment by RabsRincon** [comment]
Hi! Wht do you mean by the "C implementation". Do you mean a version that only has the C language/compilers?

**Comment by DanielVenturini** [comment]
Yes, this is it.

Currently, this project works to various languages such as `C, C++, Rust, Go, D, Haskell, Swift, Pascal (and some more!)`

Is this implementations of each compiler separated into `branchs`?

**Comment by RabsRincon** [comment]
Each language only requires some lines to be added, so it would not make sense to separate each into its own branch, as they all share the same logics.
If you want to run the site with _only_ the C language/compilers, you can do so by running the site with some extra arguments, in this case:
`make run EXTRA_ARGS="--language C"`

Please let me know if this solves your issue :)

**Comment by DanielVenturini** [comment]
Hi.
It's working.

Thanks for support.
