### ISSUE TITLE
Adding two GCC IR views works, but ties them to the same pass

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1564]
See: 
http://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(fontScale:2.23,j:1,lang:c%2B%2B,source:'int+sumOverArray(const+int+*input,+unsigned+length)+%7B%0A++input+%3D+static_cast%3Cconst+int+*%3E(%0A++++++__builtin_assume_aligned(input,+64))%3B%0A++if+(length+%26+63+%7C%7C+length+%3D%3D+0)+%7B%0A++++__builtin_unreachable()%3B%0A++%7D%0A%0A++int+sum+%3D+0%3B%0A++for+(int+i+%3D+0%3B+i+%3C+length%3B+%2B%2Bi)+%7B%0A++++sum+%2B%3D+input%5Bi%5D%3B%0A++%7D%0A++%0A++return+sum%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:gccdump,i:(_compilerid:1,_editorid:1,fontScale:2.23,rtlDump:'0',selectedPass:'008t.lower',treeDump:'0'),l:'5',n:'0',o:'x86-64+gcc+9.1+GCC+Tree/RTL+Viewer+(Editor+%231,+Compiler+%231)',selectedPass:'010t.ehopt',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0'),(g:!((g:!((h:compiler,i:(compiler:g91,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:2.23,lang:c%2B%2B,libs:!(),options:'-march%3Dhaswell+-O3',source:1),l:'5',n:'0',o:'x86-64+gcc+9.1+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:gccdump,i:(_compilerid:1,_editorid:1,fontScale:2.23,rtlDump:'0',selectedPass:'010t.ehopt',treeDump:'0'),l:'5',n:'0',o:'x86-64+gcc+9.1+GCC+Tree/RTL+Viewer+(Editor+%231,+Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

It would be useful if one could select different passes in each pane, but selecting in one selects in both. If this is not supported, then we should disallow a second view.

**Comment by RabsRincon** [comment]
Fixed by https://github.com/mattgodbolt/compiler-explorer/commit/d348c89225b4368de16ec7d0b70ba2d043892eb4
