### ISSUE TITLE
When running local instance missing compiler options

### ISSUE THREAD

**Issue by amit-raut** [mattgodbolt/compiler-explorer#1566]
Hi there,

Thank you for this wonderful tool. I really love it. :+1: 
I tried to run compiler explorer locally and I was able to run it just by navigating to `http://localhost:10240` but I was presented with just one compiler option `/usr/bin/gcc` :(

My question is though I can see different properties files in `compiler-explorer/etc/config/` why I'm not seeing them in the web interface? Sorry If I'm missing something obvious.

Please let me know how can have other compiler options when I'm running compiler explorer locally.

Thank you,
Amit

**Comment by mattgodbolt** [comment]
Hi Amit,

Thanks for your comments. Compiler Explorer does not come with any compilers of its own: it uses only the compilers it finds on your system.

To configure Compiler Explorer to use your own compilers, you'll need to create and edit a `etc/config/c++.local.properties`. This is something we're missing in the documentation, but follow the patterns in some of the other `c+.*.properties` files. If you look at the `etc/config/c++.defaults.properties` you'll see the compilers we look for by default (/usr/bin/g++-4.4 etc)

Anything you put in a `local` file overrides things read from the other files, so something like:

```
compilers=&gcc
group.gcc.compilers=g7:g8
compiler.g7.exe=PATH TO YOUR GCC 7
compiler.g7.name=g++ 7.x
compiler.g8.exe=PATH TO YOUR GCC 8
compiler.g8.name=g++ 8.x
```

Hope that helps! Let us know if you manage to get it working OK.

**Comment by amit-raut** [comment]
Thank you for your quick response and guidelines Matt. :-)

I'll try it out today and confirm if everything worked out as expected.

Thank you,
Amit
