### ISSUE TITLE
We've lost all google analytics

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1569]
![Screenshot from 2019-09-04 09-29-56](https://user-images.githubusercontent.com/633973/64264287-a8c0e000-cef6-11e9-89c0-fadc02b83efa.png)

Either _everyone_ opted out of cookies in August, or we have a bug on our side :)

**Comment by partouf** [comment]
Seems there's no mention of analytics in the sourcecode. Only when you click (or click again) Consent, there's a little bit of communication with google, but thats it..

**Comment by partouf** [comment]
Oh wait there is, it seems that the enabled setting doesn't stick?

**Comment by partouf** [comment]
should be fixed by https://github.com/mattgodbolt/compiler-explorer/commit/dd2b414f75ca59ade58bc4026c1db8e30016f46c , not live just yet

**Comment by partouf** [comment]
fix is live

**Comment by apmorton** [comment]
I don't think this is fixed.

At least for me, if I clear cookies and local storage, and then reload the page I do not get a cookie consent dialog, my cookie status is denied, and I get no network traffic to google.

If I manually open the cookie consent dialog and accept then it starts talking to google, and persists across page reloads.

**Comment by partouf** [comment]
I know it's fixed for the case where it's actually on but not initialized, its now initialized so that analytics are actually sent.

For your case, this is not something I had considered.

**Comment by RabsRincon** [comment]
Closes by #1574
