### ISSUE TITLE
[BUG] Compiler Explorer doesn't populate libraries from external instances

### ISSUE THREAD

**Issue by ubsan** [mattgodbolt/compiler-explorer#1572]
**Describe the bug**

On https://godbolt.ms, we have our own library dropdown with the libraries we support, and their versions -- however, in https://godbolt.org, on the MSVC compilers, you get the default libraries view.

**To Reproduce**

Go to the website, click the libraries drop down while on an MSVC compiler.

**Expected behavior**

The libraries drop down on https://godbolt.org should reflect the libraries installed on the instance which runs the compiler.

**Link**

https://godbolt.org/z/1WqKoP

https://www.godbolt.ms/z/6ykvLL

**Screenshots**

godbolt.ms: ![library dropdown screenshot, showing MSVC libraries](https://user-images.githubusercontent.com/3479021/64387278-52d06300-cff0-11e9-9583-f875ff7551c7.PNG)

godbolt.org: ![library dropdown screenshot, showing default CE libraries](https://user-images.githubusercontent.com/3479021/64387300-68de2380-cff0-11e9-80b3-871d33815aa9.png)

**Comment by partouf** [comment]
Libraries currently are linked to the Language, and not per compiler. I agree that there needs to be a solution for these kinds of things.
Not sure yet how though.
