### ISSUE TITLE
Can you please boost library for the compiler explorer

### ISSUE THREAD

**Issue by reemuskumar** [mattgodbolt/compiler-explorer#1576]
Can you please boost library for the compiler explorer.

**Comment by RabsRincon** [comment]
Hi. Could you please elaborate a bit more as to what is it exactly that you need? It's not totally clear right now. :)

**Comment by mattgodbolt** [comment]
Hi @reemuskumar  - if you're looking for boost library support: we already have it! Click the "Libraries" button on the compiler toolbar and pick the version of boost you want from the dropdown.

![Screenshot from 2019-09-10 08-18-57](https://user-images.githubusercontent.com/633973/64617201-a8678f80-d3a3-11e9-8a49-bedd49a4621b.png)

**Comment by reemuskumar** [comment]
Hi @mattgodbolt ,
Compiler Explorer  is a great and cool tool, thank you for creating such tool.

I'm really sorry for not being clear. I'm trying madduci/docker-compiler-explorer docker. I'm not able to include Boost Library and Haskell into it.

I'm not able to pull docker pull mattgodbolt/compiler-explorer docker

reemuskumar@reemuskumar-vm:~$ docker pull mattgodbolt/compiler-explorer
Using default tag: latest
Error response from daemon: manifest for mattgodbolt/compiler-explorer:latest not found
reemuskumar@reemuskumar-vm:~$

Sorry, I'm naive in docker. 

Is there any way I could pull a minimum compiler-explorer and I want to add or remove compilers and libraries at my will. 

I don't find much documents on it.

**Comment by reemuskumar** [comment]
I'm able to create base docker from the Docker file https://hub.docker.com/r/mattgodbolt/compiler-explorer/dockerfile now. 

Please let me know how to add compilers and libraries.

**Comment by mattgodbolt** [comment]
Hi @reemuskumar - the docker files are something we use only for our site, we wouldn't suggest using them locally. They tie into a lot of Amazon infrastructure whic you won't have.

madduci/docker-compiler-explorer docker is not supported by us, you'll need to ask @madduci for help there.

We support running Compiler Explorer as described in the readme: https://github.com/mattgodbolt/compiler-explorer#developing . You'll need to provide your own compilers and libraries; we do not ship all the compilers (they come to around 300GB of data).

If you need to install the compilers there's some of them at github.com/mattgodbolt/compiler-explorer-image -- you can install them there (although it is not all that easy; we will work on this).

> Is there any way I could pull a minimum compiler-explorer and I want to add or remove compilers and libraries at my will.

Follow the steps in the README to get a minimal CE. Add and remove compilers by installing them on your system and editing the configuration (`etc/config/c++.local.properties` and so on) https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md#configuration has some info on the configuration language for compilers, https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALibrary.md#configuration for libraries.
