### ISSUE TITLE
Add ISPC v1.12.0 to list of ISPC compilers.

### ISSUE THREAD

**Issue by pbrubaker** [mattgodbolt/compiler-explorer#1579]
We've released a new version of ISPC (v1.12.0) and would like to have it added to the list of compilers.

Here is the location to download the latest release.

http://ispc.github.io/downloads.html

Thanks again CE team!

**Comment by RabsRincon** [comment]
Hi! Thanks for the heads up. I've now updated the installation scripts and the new version should hit the live site some time this weekend. :)
