### ISSUE TITLE
[REQUEST] **Document old encoding**

### ISSUE THREAD

**Issue by bpringlemeir** [mattgodbolt/compiler-explorer#1580]
**Is your feature request related to a problem? Please describe.**
I have an OLD URL and it has an HTTP request with,

  `"sourcez"%3A"`... encoding. in the URL.

The encoding is "[0-9][A-Z][a-z]%"  I don't know the map to decode this.  I want to get the old URL source to make a new URL.

**Describe the solution you'd like**
Document the encoding somewhere in the wiki FAQ.

**Describe alternatives you've considered**
I tried random 8 bit clean decoding algorithm.
https://en.wikipedia.org/wiki/Binary-to-text_encoding#Encoding_standards

**Comment by apmorton** [comment]
Its LZMA compressed and then base64 encoded: https://github.com/mattgodbolt/compiler-explorer/blob/master/static/url.js#L39

Having said that, the URL should still work just fine and we have no plans to break old URL formats.
If it doesn't work it would be great if you could share the URL so we can investigate.

If it is working, you should be able to "convert" it to the latest format by opening the page and then clicking share. (If it is an embedded url, click the "edit on compiler explorer" link in the lower right first).

**Comment by bpringlemeir** [comment]
Hmm. I guess write it was base64, but I did think about compressing it.  That makes sense.  From a short URL http://goo.gl/WFzVX1, I have this URL,

> https://gcc.godbolt.org/#%7B%22version%22%3A3%2C%22filterAsm%22%3A%7B%22labels%22%3Atrue%2C%22directives%22%3Atrue%2C%22commentOnly%22%3Atrue%7D%2C%22compilers%22%3A%5B%7B%22sourcez%22%3A%22KYDwLsBOB2AECW0ywFYBoDWaA2aC2a0A3AFAmLIDm2A9gEYCG2AFAG43wAmAlLAN4lYQyMDABXGKlgBqWBhmxsCvAuIkAviQDOYSGIDGVWnX6ChFWAyIIksOtYv6Htzs%2BTBS60hZ17DE4GZ9GmgdWF8DI3pYACoAB14BYVEJODiAWgA%2BBgUMzJNZPP1crM4SzI8NEiAA%22%2C%22compiler%22%3A%22%2Fusr%2Fbin%2Farm-linux-gnueabi-g%2B%2B-4.6%22%2C%22options%22%3A%22-O3%20-mthumb%22%7D%5D%7D

I had to change two '%2B' to a escaped plus (+) and base64 -d seem ok with this.  I tried `unlzma` from a linux shell, but it didn't like the binary.  Here is `od -x`

0000000 8029 2ef0 4ec0 6007 0904 326d 56c0 a001
0000020 9a35 6603 d982 00ad 01dc 9840 03b2 609b
0000040 803d 0246 601b 0005 376e 09c0 9480 0db0
0000060 56e2 c810 c0c0 7105 968a 6a00 1858 c666
0000100 afc0 e202 0224 90f8 e60c 1812 c680 6955
0000120 e8d7 4528 0c58 2288 0e4b 8bb5 1efa ecdc
0000140 30f9 eb52 5948 b0d7 e0c4 7d66 681a 581d
0000160 035f 7a23 0058 002a 5e07 6101 0951 3838
0000200 5a80 3e00 0506 cc0c 5993 fd3c ac5c 12ce
0000220 8fcc 120d 0020

Maybe it is actually an outdated compiler or something.

**Comment by apmorton** [comment]
It is indeed an issue with an old compiler - here is a fixed url for you: https://gcc.godbolt.org/z/-7dBUP

The issue isn't actually part of the LZMA data - here is the urldecoded version of your url:
```
https://gcc.godbolt.org/#{"version":3,"filterAsm":{"labels":true,"directives":true,"commentOnly":true},"compilers":[{"sourcez":"KYDwLsBOB2AECW0ywFYBoDWaA2aC2a0A3AFAmLIDm2A9gEYCG2AFAG43wAmAlLAN4lYQyMDABXGKlgBqWBhmxsCvAuIkAviQDOYSGIDGVWnX6ChFWAyIIksOtYv6Htzs+TBS60hZ17DE4GZ9GmgdWF8DI3pYACoAB14BYVEJODiAWgA+BgUMzJNZPP1crM4SzI8NEiAA","compiler":"/usr/bin/arm-linux-gnueabi-g++-4.6","options":"-O3 -mthumb"}]}
```

Near the end there is:
`"compiler":"/usr/bin/arm-linux-gnueabi-g++-4.6"`

Generally we try not to break these kinds of things - but it appears this compiler slipped through the cracks.  To fix the url I changed it to:
`"compiler":"armg464"`

@mattgodbolt it seems like `armg464` already has an alias set - so I'm not sure exactly how to fix this - any ideas?

**Comment by mattgodbolt** [comment]
@apmorton great diagnosis! Looks like there alias is broken though! The alias should be set to:

```
compiler.armg464.alias=/usr/bin/arm-linux-gnueabi-g++-4.6
```

unless I'm mistaken! I wonder how many aliases are the "wrong way around". `git grep '\.alias'` picks up a few, so we should fix this! Thanks all!

**Comment by partouf** [comment]
the original link should now work as expected in production

**Comment by bpringlemeir** [comment]
For example, many link at this URL now work,

 https://stackoverflow.com/questions/23834823/does-using-global-variables-increase-or-decrease-performance-in-c-code-compiled/23837444#23837444
