### ISSUE TITLE
[BUG] Red error text too dark to see in dark theme

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1583]
**Describe the bug**
When using the dark theme, the ANSI red colour used by GCC and other compilers to indicate error is too dark to see.

**To Reproduce**
Choose dark theme and type anything that doesn't compile. Observe the dark error message.

**Expected behavior**
More visible error indicators.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/633973/64910731-06afad80-d6d7-11e9-9437-962ae663b902.png)

Reported by @mpusz on slack.

(Matt notes: this might be a tweak in general to the ANSI colour codes in dark mode, though some colours might be tricky to get).

**Comment by RabsRincon** [comment]
Never let a colourblind fiddle around with this kind of stuff I guess :man_shrugging: hahaha

**Comment by porglezomp** [comment]
I think this is made worse by the fact that the compiler output uses a lighter background color than the rest of the code windows, which makes all the contrast even lower.

**Comment by partouf** [comment]
I think this is mostly resolved
