### ISSUE TITLE
[REQUEST] Templight for template debugging

### ISSUE THREAD

**Issue by kunaltyagi** [mattgodbolt/compiler-explorer#1587]
**Problem**
Template debugging. Templight is a promising tool but setting it up is a pain.

**Preferred solution**
An option to choose templight as the compiler to view the output. Templight debugger would be perfect since it's all compile time

**Describe alternatives you've considered**
Compiling templight from source.

**Comment by RabsRincon** [comment]
Hi. Sorry about the radio silence. I've begun to investigate how to best implement templight and some more releated compiler perf stats features into the site. I'll close this issue in favour of #1186 and post an update there when something's ready

Thanks again for your patience :)
