### ISSUE TITLE
[BUG] Intel asm for Rust code not generated properly

### ISSUE THREAD

**Issue by JOE1994** [mattgodbolt/compiler-explorer#1592]
**Describe the bug**
Only a very small portion of the Rust code is compiled down to Intel asm.
Rest of the Rust code is not generated to Intel asm.

**To Reproduce**
Accessing the below link will reproduce the behavior:
https://godbolt.org/z/ETMCMo

I used rustc 1.36.0 (options : -O)

The original code is from the link below:
https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-rust-7.html

**Expected behavior**
I expected the asm code for the entire Rust code to be generated,
but only a very small portion of the Rust code is generated to assembly.

**Link**
https://godbolt.org/z/ETMCMo

**Screenshots**
![rust_compiler_explorer_bug](https://user-images.githubusercontent.com/10286488/65203632-8cc25000-da59-11e9-84fe-0e27150cc61d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Google Chrome
 - Version : 76.0.3809.132

**Additional context**

**Comment by partouf** [comment]
According to the Output log most code isn't used. I'm not a Rust expert, but when I made main public (pub fn main() {), that was resolved and everything was compiled as intended. https://godbolt.org/z/Na5LbG

**Comment by JOE1994** [comment]
> According to the Output log most code isn't used. I'm not a Rust expert, but when I made main public (pub fn main() {), that was resolved and everything was compiled as intended. https://godbolt.org/z/Na5LbG

Wow you are right ! I also tried the same thing (pub fn main()) and now it works! Thanks a lot :)

**Comment by JOE1994** [comment]
Before closing the issue, I'm just curious whether this is an intended behavior of compiler-explorer.
I tried compiling a very simple Rust code as below
`fn main() {
    let a = 1 + 2;
}`
and again, no asm is generated unless I add "pub".

**Comment by partouf** [comment]
We show asm for rust code in similar ways we show for most other languages, as in we generate assembly without linking. And for just an object file there's no requirement for there to be a main function (only for the whole executable), but that also, unfortunately, means it won't recognize main needs to be compiled.
So only public functions will be exposed and generated asm for in the case of Rust.

**Comment by JOE1994** [comment]
> We show asm for rust code in similar ways we show for most other languages, as in we generate assembly without linking. And for just an object file there's no requirement for there to be a main function (only for the whole executable), but that also, unfortunately, means it won't recognize main needs to be compiled.
> So only public functions will be exposed and generated asm for in the case of Rust.

Thank you so much :) Now I'll close the issue.
