### ISSUE TITLE
[BUG] Both MSVC architectures are listed as x86 in UI

### ISSUE THREAD

**Issue by jackgerrits** [mattgodbolt/compiler-explorer#1593]
**Describe the bug**
In the compiler drop down both MSVC architectures are x86

**To Reproduce**
Open compiler drop down

**Expected behavior**
Top block should be x64

**Screenshots**
![image](https://user-images.githubusercontent.com/7558482/65294856-c019e300-db1c-11e9-8ceb-fe2035168e62.png)

**Desktop (please complete the following information):**
 - OS: Win10 1903
 - Browser: Firefox 
 - Version 69.0

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to open an issue.
This problem comes from the compilers provided by Microsoft, so they are the ones who have to fix it on their end, as we just delegate the Windows stuff directly to them.
 I've pinged @ubsan (I hope that it's ok to ping you here too :smile:) to see if it can be fixed

**Comment by ubsan** [comment]
oops! that's probably me being a dummy, but I can't fix it right now. cc @Rastaban?

**Comment by mattgodbolt** [comment]
Ping @Rastaban -- would love to get this fixed as we get told about this about twice a week...

**Comment by Rastaban** [comment]
I have moved to another team and an no longer involved in the MS compiler-explorer instance.  @dan-shaw, who has taken over.

**Comment by mattgodbolt** [comment]
Thanks @Rastaban - Apologies for pinging you again.

@dan-shaw : This is one of the more annoying bugs we get asked about and it's "only" a couple lines change in a config file. We'd really appreciate a fix as it's confusing our users!

**Comment by mattgodbolt** [comment]
@dan-shaw - please please can we address this? I really appreciate if you can make the simple change to fix it.

**Comment by RabsRincon** [comment]
Fixed now! 👍
