### ISSUE TITLE
[BUG] clang-query view triggers full recompilation for no reason

### ISSUE THREAD

**Issue by FredTingaud** [mattgodbolt/compiler-explorer#1594]
While typing in the clang-query view, the code seems to recompile in real time like if I were changing the code.
No change is done to the source nor compilation parameters and the resulting binary will not change, so these recompilations are useless.
I wouldn't want you to pay for nothing as I fumble around on my matchers!

**Comment by RabsRincon** [comment]
Hi!
Thanks for letting us know about this. While it's true that we're wastefully compiling the code every time the tool is changed, it's something which we don't care much about. 

We could try to add some logic to handle such cases, but it would just complicate the code.
Plus, compilations are relatively cheap anyway, so don't worry about it! Keep on fumbling around :P

Thanks again for taking the time to file an issue

**Comment by RabsRincon** [comment]
If anyone running a local instance find themselves not wanting to waste power on useless compilations in cases like this, please do feel free to raise an issue and we'll gladly add support for it (We'll also be happy to receive PRs addresing it too haha)
