### ISSUE TITLE
[REQUEST] Add latest version of Go (1.13)

### ISSUE THREAD

**Issue by marigonzes** [mattgodbolt/compiler-explorer#1603]
First of all, thanks for this amazing tool.
Earlier this month, Go 1.13 was officially [released](https://blog.golang.org/go1.13), so I was wondering if it could be included in compiler explorer.

**Comment by RabsRincon** [comment]
Hi! Thanks for the heads up, we did not notice the new version coming out. I've now added it to the site configs, so it should hit the live site in the next few days :)
