### ISSUE TITLE
[REQUEST] Don't clear source code when switching languages

### ISSUE THREAD

**Issue by eliasdaler** [mattgodbolt/compiler-explorer#1604]
Hello.

Sometimes I type some C++ code to realize that "C" language was chosen. I then switch to "C++", but instead of preserving the code I've just written, compiler-explorer inserts a basic C++ example. In my opinion, this is not very intuitive.

**Comment by partouf** [comment]
Although C++ and C are somewhat compatible, most languages that we support are not, so it wouldn't make sense to transfer the code to something that's definitely not going to compile.

You should be able to switch back to C (code is remembered per language), copy the code, switch back and paste. You can also save the sourcecode with ctrl+s or use the load/save dialog.

**Comment by eliasdaler** [comment]
It's not immediately clear that switching back to a language returns the code, for me if something disappears from a text box, it's lost forever. 

So I think it's not an intuitive design - if I start to write "X" language code and then realize I forgot to switch to the "X" language, I should be able to do so without losing the contents of input widget, in my opinion.

**Comment by mattgodbolt** [comment]
Thanks for your comments @eliasdaler . We'll try and think of something to improve this, but as you noted you can return to the previous language to recover your code. This is not ideal, but I think it's worse than folks having C++ code in their Fortran window when they switch (and losing the "example" code facility).

One idea would be to have a popup but...it's another peice of popup UI, which in my experience is usually worse than the cure. Maybe a little "reset to example code?" popup would be ok?

**Comment by eliasdaler** [comment]
* "Reset to example code" would be nice. I'm not really sure how often this example code gets used (personally, I'm always writing code from scratch)
* It's not clear from anything that returning to a previous language restores your code, because I assume that there's one input box for all languages. Right now I'm not sure how this can be made clear.

I also frequently do something like this:
1) Write code in C
2) Switch to C++ 
3) Rewrite C code in C++ code (this is done by modification of C code, not from scratch)
And I'm sure that the same thing can be done for C to Fortran switch, that's why losing code is not an ideal behavior for me.

**Comment by mattgodbolt** [comment]
Perhaps we can have a popup or something when one changes language: or at least make this an option (default to keep existing behaviour), so that @eliasdaler can at least keep the behaviour he wants.

**Comment by RabsRincon** [comment]
Hi! Sorry this took so long to get addressed. I've now added an option on the settings pane (Disabled by default) _"Keep editor source on language change"_ that makes the editors behave as you detailed.

Thanks for taking the time to request this and again, sorry it took so long to get implemented. The change should hit the live site shortly :)

**Comment by eliasdaler** [comment]
Thanks!

**Comment by partouf** [comment]
This change is now live
