### ISSUE TITLE
[REQUEST] Display SASS output for CUDA files

### ISSUE THREAD

**Issue by OlivierNV** [mattgodbolt/compiler-explorer#1607]
The output of cuobjdump -sass, eg: actual instructions executed by the HW would be more useful than the intermediate ptx output in many cases.

**Describe the solution you'd like**
Have a way to dump the output of cuobjdump -sass as an option.

**Describe alternatives you've considered**
Could not find a way around that.

**Additional context**
https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#cuobjdump

**Comment by partouf** [comment]
For the Nvidea cuda's we have very recently added support for Binary mode (the IIOIO button)
Is this similar to what you're looking for?

**Comment by OlivierNV** [comment]
Oh yeah, never mind, that's exactly what I was looking for.
