### ISSUE TITLE
[BUG] key-bindings setting does not persist

### ISSUE THREAD

**Issue by marcomagdy** [mattgodbolt/compiler-explorer#1622]
**Describe the bug**
checking vim in keybindings under settings works only for the current session.

**To Reproduce**
1. Set keybindings to vim
1. ensure that the editor is indeed using vim (reflecting the earlier setting)
1. close the browser
1. open the browser and navigate to godbolt.com
1. vim is not visibly selected and the key-bindings are not set to vim.

**Expected behavior**
Expected vim key bindings to be set.

**Comment by mattgodbolt** [comment]
`godbolt.com` is not the right URL :) I presume you meant `godbolt.org`

I can repro: the setting _is_ persisted (if you open the Settings again you'll see that "Vim" is ticked). But it's not applied to the current window.

**Comment by partouf** [comment]
I blame @RabsRincon but I'm not sure it's not his fault

**Comment by marcomagdy** [comment]
> `godbolt.com` is not the right URL :) I presume you meant `godbolt.org`

bah! I never type it in the browser that's why, autocomplete spoiled me. I'm sorry.

>I can repro: the setting is persisted (if you open the Settings again you'll see that "Vim" is ticked). But it's not applied to the current window.

Yes, exactly. The bindings are applied between sessions. Apologies for the confusion.

**Comment by partouf** [comment]
Just to be sure, we all have our cookies on here?

**Comment by marcomagdy** [comment]
Yes

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. I've now fixed the missing behaviour of the editor getting into vim mode when the settings said so. Note that editors can't remember if they were or were not in vim mode when you last visited the page, as that would make that behaviour shareable between links, and that's not something we want.

But from now on, if it's enabled on the settings pane (You can find it in the "More" dropdown) every new editor will start with the vim keybindings
