### ISSUE TITLE
[BUG] Machine code no longer displays.

### ISSUE THREAD

**Issue by max0x7ba** [mattgodbolt/compiler-explorer#1626]
**Describe the bug**
When clicking on 11010 icon I expect to see the machine code bytes.

**To Reproduce**
Go to https://gcc.godbolt.org/z/lE4o3-
Click on 11010 icon.

**Expected behavior**
The machine code is displayed.

**Actual behavior**
Nothing is displayed.

**Link**
https://gcc.godbolt.org/z/lE4o3-

**Additional context**
It used to work.

**Comment by partouf** [comment]
Hi, if you click on the "Output (0/7)" button you'll see the errors given by the compiler during linking.

The implementations for f, h and k are missing. (You only declared prototypes for the functions)
