### ISSUE TITLE
[REQUEST] Assembly Literal to Hexadecimal Conversion (for the REST API)

### ISSUE THREAD

**Issue by BullyWiiPlaza** [mattgodbolt/compiler-explorer#1635]
**Is your feature request related to a problem? Please describe.**
I don't like to see decimal literals in assembly code when using `GCC`.

**Describe the solution you'd like**
I would like to have an option for the `REST API` to control whether I want decimal or hexadecimal literals, for example as [filters option](https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/API.md#post-apicompilercompiler-idcompile---perform-a-compilation).

**Describe alternatives you've considered**
I considered implementing the parsing and replacing of decimal literals manually. This seems to work for a specific architecture (`PowerPC` with register names) but not in general for all architectures I suppose. Maybe there is a simpler way?

**Comment by mattgodbolt** [comment]
So far Compiler Explorer doesn't "understand" the output of the compiler: the compilers generate decimals. We have a hacky UI solution on mouse overs of *anything* that looks like a number to convert it to hex, but we don't know which things are decimals values and which are hex (or just strings...).

If the compilers had flags to change their output we could support this. I'm not aware of a general way to do this though.

Thoughts?

**Comment by BullyWiiPlaza** [comment]
Unfortunately, there does not seem to be an easy way besides parsing each architecture manually or modifying [`GAS`](https://en.wikipedia.org/wiki/GNU_Assembler). I asked a similar question [here](https://stackoverflow.com/questions/57923232) but even for the well-known Java parser generator [`ANTLR`](https://www.antlr.org) nobody currently made a decent grammar for parsing just `x86 assembly`. After parsing, outputting the `AST` with hexadecimal literals instead of decimal would be a fairly easy task.

The best option would be to modify `GAS` how it seems.

**Comment by mattgodbolt** [comment]
I'd be happy to reopen this if the upstream tools we rely on support it. But for now I'm afraid I'm going to close this as it's beyond the scope of the project as it currently stands. Sorry!
