### ISSUE TITLE
[BUG] Webpack takes too much RAM on lower spec machines

### ISSUE THREAD

**Issue by ggnkua** [mattgodbolt/compiler-explorer#1639]
Hi,

**Describe the bug**
With recent CE versions, webpack takes more than 700MB of RAM, thus bringing a machine that has 1GB of RAM and little swap space to a grinding halt. We're talking about the machine refusing to respond to anything, drops all connections, refuses to be ssh'd to and the only way to fix this is to power cycle the machine.

**To Reproduce**
Just run CE in a machine with 1GB of RAM.

**Expected behavior**
Should not bring the machine to a grinding halt.

**Link**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Linux

**Additional context**
As a workaround I simply comment out the webpack rule from the Makefile - CE seems to run fine after that.

I also tried to force node into using less RAM but this just results in node exiting with out of RAM message.

**Comment by mattgodbolt** [comment]
We can take a look, but sadly this will be a low priority issue: 1GB is not a lot of RAM these days, and though it pains me to say it, there's not a lot we can do. I'm really sorry.

**Comment by apmorton** [comment]
Also, webpack should only need to run *once* to create the dist files - not every time you start CE.

I'm not sure if the make rules are causing it to run every time you "make run", but if this is the case you should be able to start the node app without using the makefile after running webpack once.

**Comment by ggnkua** [comment]
This reminds me - is there a way to run webpack on another machine with more resources and then copy the output to the other CE install? If I understand this correctly webpack generates js code in the end, so maybe this is a way to bypass the issue.

**Comment by mattgodbolt** [comment]
Absolutely yes: this is how we run the site. `make dist` will put everything you need into `out/dist` and that can be copied to another host. Then to run the site on the other host:

```
$ node app.js --static <PATH_TO_OUT_DIST>
```

or something similar

**Comment by mattgodbolt** [comment]
(I may be misremembering some step or other though: the live CE site is a little more complex)

**Comment by ggnkua** [comment]
D'oh, I almost forgot that windows 10 now has a working linux install! Just tried this and deployed to the target machine and it seems to work a treat :)

So I guess you can feel free to close this with wontfix or something :)

**Comment by ggnkua** [comment]
If anyone's interested... here's a quick 2 line script I made to automate the process:

```
make dist
scp -rp out <user>@<destination>:/path/to/compiler-explorer
```

**Comment by mattgodbolt** [comment]
Thanks @ggnkua . This may change in the next few weeks as we change the way we distribute Compiler Explorer; but something like this will always work. Just a headsup. Thanks for your understanding.

**Comment by ggnkua** [comment]
Hello,

Sorry to dig up an old issue, but I just tried to update my version of CE to the latest. I pretty much used what has been said above. On my linux machine I did

```
make dist
scp -rp out <user>@<destination>:/path/to/compiler-explorer
```

And on the machine that actually runs CE I do

```
export NODE_ENV=production
node app.js --static out/dist
```

I updated node to v12.22.1 as suggested before running but I still get the following error:

```
(node:18889) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/path/to/compiler-explorer/app.js:29
import child_process from 'child_process';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Does anyone have an idea of what might be happening?

Thanks!

**Comment by partouf** [comment]
> ```
> node app.js --static out/dist
> ```

We have modernized our code a while ago which affects the way we have to start it as well.

This command should now be `node -r esm app.js --static out/dist`

**Comment by ggnkua** [comment]
Thanks for the reply. Here's what I got after running your suggestion:

```
$ node -r esm app.js --static out/dist
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'esm'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:74:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}```

Any suggestions welcome.

**Comment by partouf** [comment]
Sounds like your packages aren't up to date.. maybe try `npm i`?

**Comment by ggnkua** [comment]
That seemed to have done the trick. Thanks!
