### ISSUE TITLE
[REQUEST] Endpoint for "just the text" of a short URL

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1640]
Requested in slack by Darrell Wright.

```
Is there a way to query the text of CE short url.  Say I wanted to #include <https://gcc.godbolt.org/z/SOMEID>
```

Ideally we'd give an endpoint like the existing RESTful one that "just" yields the editor text. Not sure what it should do if there's more than one editor, pick lowest ID? Error?

**Comment by partouf** [comment]
Maybe make it explicit via an extra parameter? so like /api/shortlinkinfocode/abc123/1

**Comment by mattgodbolt** [comment]
Great idea, thanks @partouf

**Comment by apmorton** [comment]
If you will allow me to run to the bikeshed real quick, `/z/:id/code/:editor?` is a much nicer route for this given the original use case of being able to #include someone else's link code.

Just slap `/code` onto the link and it will spit back the plaintext for the first editor.

If there are multiple editors you should still get the first if you don't specify any editor explicitly.

**Comment by partouf** [comment]
Is nicer maybe yes, but not in api.js which annoys me :/
But worth considering
