### ISSUE TITLE
node_env fallout issues

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1642]
See: https://github.com/mattgodbolt/compiler-explorer/commit/106361067d331eafe347d32750361d248ec1db9e#r35626723

 - [x] fix up prod/local check (probably use `process.env.NODE_ENV !== 'production'` as the check)
 - [ ] decide if the default 'dev' mode is appropriate 
 - [x] check for any other instances of "what mode are we in" are at odds with each other

**Comment by partouf** [comment]
I think we can close this now?

**Comment by mattgodbolt** [comment]
I think so : thanks for noticing @partouf :)
