### ISSUE TITLE
[BUG] std::cout with msvc compiler leads to unreadable gibberish | Regression

### ISSUE THREAD

**Issue by Zyranivia** [mattgodbolt/compiler-explorer#1644]
As you can see in https://godbolt.org/z/o7xYm3, a simple C++ Hello World program compiled with the latest (and any, as far as I tested) MSVC compiler leads to a lot of assembly (?) containing the words error and failure a few times too often. (I can’t read this, so it might be legit output normally hidden by Compiler Explorer.)

I encountered this while opening an old godbolt link of mine which used to output somewhat sensible assembly, so this seems to be a regresssion affecting older compiler versions, too.

If you can’t reproduce the bug, get back at me and I’ll add Screenshots etc.

 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by partouf** [comment]
A little bit more functions are hidden if you use the [lib.f] filter, it's on by default but old links might have them disabled like it has here.

Other than that, this is just what happens when you use iostream.

**Comment by Zyranivia** [comment]
> Other than that, this is just what happens when you use iostream.

That might be, but I’d expect a version as readable as the gcc one, and it definitely used to be this way. Even when using the [lib.f] filter, I get a whopping 500 lines of assembly …

**Comment by mattgodbolt** [comment]
This is mainly an issue with the way MSVC generates its code. We need to do extra work to filter "unused" functions, but that's non-trivial, as you might imagine!

**Comment by mattgodbolt** [comment]
> it definitely used to be this way

We've never changed anything in the filter code for Windows: we've never supported filtering the verbose output of MSVC and unless MS have changed their compiler output this ought not to have ever been anything other than super-verbose :(

**Comment by partouf** [comment]
> This is mainly an issue with the way MSVC generates its code. We need to do extra work to filter "unused" functions, but that's non-trivial, as you might imagine!

I believe only data symbols are shown in this example when lib.f is active, so it works as intended to hide excess functions.

**Comment by Zyranivia** [comment]
> We've never changed anything in the filter code for Windows: we've never supported filtering the verbose output of MSVC and unless MS have changed their compiler output this ought not to have ever been anything other than super-verbose :(

Well, it seems more likely that I have a wrong memory than that MS changed their compiler output recently … Thanks for caring, I wouldn’t have had reported it if I didn’t think of this as a regression. There are definitely better ways to improve Compiler Explorer than fixing assembly rarely seen (although the usage of iostream might increase due to the code execution feature).

From my side this issue is resolved.

**Comment by mattgodbolt** [comment]
Many thanks! I'm 99% sure we didn't change anything (will let any other CE contributors chime in if not!).

Thanks! Happy to improve things on our side (@AndrewPardoe wrote a `perl` script once that removed some of the extraneous stuff but we never integrated it...perhaps we should?)

**Comment by mattgodbolt** [comment]
Cheers: going to close. Note also maybe the #1407 issue might help too? Maybe give that a go and see if that helps?
