### ISSUE TITLE
[REQUEST] Support non-absolute paths for compiler exe correctly

### ISSUE THREAD

**Issue by apmorton** [mattgodbolt/compiler-explorer#1649]
With a line like the following:
```
compiler.python36.exe=python3.6
```

Even when `python3.6` doesn't exist on the system path, the compiler will still be created and simply fail at runtime.

It would be nice if (perhaps as an opt in?) it would be possible to have the above line treated as if `$(which python3.6)` was written.

- if compiler doesn't exist on path, log error, disable compiler, and move on
- if compiler does exist, run it to gather the version and proceed with init like normal

The offending logic is here: https://github.com/mattgodbolt/compiler-explorer/blob/69a43f7feecc898add18de670a8d9c705e03e687/lib/handlers/compile.js#L100

**Comment by mattgodbolt** [comment]
Seems fair enough!
