### ISSUE TITLE
LLVM/Clang trunk should be built from the github not the old svn

### ISSUE THREAD

**Issue by RKSimon** [mattgodbolt/compiler-explorer#1651]
LLVM/Clang upstream development has now moved to github:

https://llvm.org/docs/GettingStarted.html

The trunk builds of all LLVM/Clang tools (llc, opt, llvm-mca etc) should be built against master on

https://github.com/llvm/llvm-project.git

and the "Full compiler version" info button SVN trunk id replaced with the relevant GIT hash.

**Comment by partouf** [comment]
Also -image issue https://github.com/mattgodbolt/compiler-explorer-image/issues/275

**Comment by mattgodbolt** [comment]
@zygoloid pointed this out too .. we're a bit out of date!

**Comment by mattgodbolt** [comment]
Fixed
```
$ /opt/compiler-explorer/clang-trunk/bin/clang++ --version
clang version 10.0.0 (https://github.com/llvm/llvm-project.git e25bc5e0247141cb31093a370e22fe3249bdbb05)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
```
