### ISSUE TITLE
[REQUEST] **Link with Google Test**

### ISSUE THREAD

**Issue by adambadura** [mattgodbolt/compiler-explorer#1652]
**Is your feature request related to a problem? Please describe.**
When adding Google Test library and executing I'm getting a linker error for missing Google Test libs.

**Describe the solution you'd like**
When adding Google Test library add not only include paths but also link libraries or at least proper link directory so that I can easily add libraries myself. (The option makes much sense - I might either want to write my own `main` or link with the one provided by Google Test.)

**Describe alternatives you've considered**
I tried to add proper path and libraries myself by guessing them based on include paths but it didn't work. Probably I didn't guess them right or they are not there in the first place.

**Additional context**
Failure ilustration: https://godbolt.org/z/qPWW4v.

**Comment by mattgodbolt** [comment]
Hi: I'm afraid we currently have only vague plans to support linking with third party libraries: we don't build third party dependencies, only get their headers.

 It's a little too much in general as we have so many combinations of compilers, libraries and compiler flags to be able to support this. That said; I'm going to raise an issue to track this: #1662
