### ISSUE TITLE
[BUG] python3.7 and python3.8 not found

### ISSUE THREAD

**Issue by seb-mtl** [mattgodbolt/compiler-explorer#1658]
Hi,

**python3.6** works fine, but the executables for **python3.7** and **python3.8** are missing.

```
Error: no suitable python3.7 executable found
Compiler returned: 1
```

https://python.godbolt.org/z/OlLWVN

Thanks!

**Comment by apmorton** [comment]
Yep - this is a combination of #1649 and the site being updated today to publish other changes.

Python 3.6 is live as a side effect - the rest will come soon.

**Comment by apmorton** [comment]
closing; python 3.5, 3.6, 3.7, and 3.8 have all been live on the site for some time now
