### ISSUE TITLE
[REQUEST] Add custom font size

### ISSUE THREAD

**Issue by tawmoto** [mattgodbolt/compiler-explorer#1660]
At the moment, AFAIK, one can choose only the following font sizes in this range: ...13, 15, 18, 22.... 
For me 15 is too small and 18 is too big, I would like to use the size 16 or 17.
Perhaps it's a hidden option that I could not find
Thanks.

**Comment by RabsRincon** [comment]
Hi!
Thanks for the suggestion. I've now changed the font scale dropdown to show the full 8-30 range in a better way than before. It should hit the live sit in the next few days. :)
