### ISSUE TITLE
[REQUEST] Use only distinct characters for URLs

### ISSUE THREAD

**Issue by stephenatwork** [mattgodbolt/compiler-explorer#1661]
Sometimes link URLs need to be typed (e.g. when one sees a link on slides or in a video).
This can be frustrating if the link contains codepoints which are easily confused such as "oO0" "1lI".

It would be friendly to disallow easily confused codepoints from links.

BTW the motivation for this came from the deck:
https://software.intel.com/en-us/videos/advanced-single-instruction-multiple-data-simd-programming-with-intel-implicit-spmd-program

**Comment by mattgodbolt** [comment]
I like the idea! Thanks. We'll have to ensure whatever we do is of course backwards compatible with older URLs but this should "just work"™ if we change the algorithm.

**Comment by mattgodbolt** [comment]
Whoah that was quick @RabsRincon ! A new record...!
