### ISSUE TITLE
[BUG] Configurable tab size doesn't work in Chromium 73 on Linux

### ISSUE THREAD

**Issue by safinaskar** [mattgodbolt/compiler-explorer#1671]
**Describe the bug**
Configurable tab size doesn't work in Chromium 73 on Linux

**To Reproduce**
* Open Chromium 73, open guest window (to make sure that installed extensions and installed cookies will not alter behavior, note that guest window and incognito window are different things)
* Open godbolt.org , you will see privacy policy, because cookies are clean
* Close privacy policy
* More -> Settings
* Change tab width to 2
* Delete code (i. e. press Ctrl-A, then Delete), press "{", then "Enter"

**Expected behavior**
Cursor should move by 2 characters to the right

**Actual behavior**
Cursor moved by 4 characters to the right

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 9
 - Browser: Chromium
 - Version: 73.0.3683.75

**Comment by RabsRincon** [comment]
Hi! Great catch, thanks for the report!
It turns out that tab width were not respected at all. I've now fixed it and it should hit the live site in the next few days :)
