### ISSUE TITLE
[BUG] Potential UBsan Issue

### ISSUE THREAD

**Issue by Thomspoon** [mattgodbolt/compiler-explorer#1680]
**Describe the bug**

Hello, I recently found that when running with `-fsanitize=undefined` the following code will throw runtime errors:

```
#include <iostream>

int main() {
    std::cout << "This is a bug on x86-64 gcc 8.1+ and any version of Clang!" << std::endl;
}
```

**To Reproduce**

Visit https://godbolt.org/z/pfES2V or copy the code above to a new C++ instance and use x86-64 GCC 8.1+ or any version of x86-64 Clang.

**Expected behavior**

There should've be any errors.

**Desktop (please complete the following information):**
 - OS: CentOS 7.5
 - Browser Firefox
 - Version 60.0.7

**Comment by apmorton** [comment]
closing as duplicate - see #1675 and #1636
