### ISSUE TITLE
[BUG] Configurable tab size is reset when I click "reset code and UI"

### ISSUE THREAD

**Issue by safinaskar** [mattgodbolt/compiler-explorer#1684]
Fix for https://github.com/mattgodbolt/compiler-explorer/issues/1671 is broken. There are still problems with configurable tab size. Here is steps to reproduce this brokenness:

**To Reproduce**
* Open Chromium 73, open guest window (to make sure that installed extensions and installed cookies will not alter behavior, note that guest window and incognito window are different things)
* Open godbolt.org , you will see privacy policy, because cookies are clean
* Close privacy policy
* More -> Settings
* Change tab width to 2
* Click "Reset code and UI layout"
* Delete code (i. e. press Ctrl-A, then Delete), press "{", then "Enter"

**Expected behavior**
Cursor should move by 2 characters to the right

**Actual behavior**
Cursor moved by 4 characters to the right (but settings still shows that tab is 2 characters)

**Desktop (please complete the following information):**
OS: Debian GNU/Linux 9
Browser: Chromium
Version: 73.0.3683.75

**Comment by mattgodbolt** [comment]
Just tried this and confirmed. Though I also noticed "new editors" created after editing the setting don't get the setting applied either: there's no need to "reset code". I suspect it's not actually being persisted at all.

**Comment by safinaskar** [comment]
It seems that the bug is fixed now. Please, close

**Comment by RabsRincon** [comment]
Thanks for letting us know :)
