### ISSUE TITLE
[BUG] LLVM library is missing the generated `.inc` files

### ISSUE THREAD

**Issue by rconde01** [mattgodbolt/compiler-explorer#1687]
**Describe the bug**

https://github.com/llvm/llvm-project/blob/release/9.x/llvm/examples/HowToUseLLJIT/HowToUseLLJIT.cpp

Both gcc and clang give
```
In file included from /opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/IR/Module.h:23,

                 from /opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/ExecutionEngine/Orc/Core.h:20,

                 from /opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/ExecutionEngine/Orc/IndirectionUtils.h:20,

                 from /opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h:23,

                 from /opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/ExecutionEngine/Orc/LLJIT.h:16,

                 from <source>:9:

/opt/compiler-explorer/libs/llvm/9.0.0/include/llvm/IR/Attributes.h:73:14: fatal error: llvm/IR/Attributes.inc: No such file or directory

   73 |     #include "llvm/IR/Attributes.inc"

      |              ^~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

Compiler returned: 1
```
msvc doesn't compile either - but for a different (weird) reason.

**To Reproduce**
https://godbolt.org/z/vWZ68X

**Expected behavior**
Compiles and run

**Link**
https://godbolt.org/z/vWZ68X

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by mattgodbolt** [comment]
It's not in our installation:
```
Dec/03 04:24 admin-node~/compiler-explorer-image (master|✔) $ 
find /opt/compiler-explorer/libs/llvm/9.0.0/ -name Attributes.inc
Dec/03 04:25 admin-node~/compiler-explorer-image (master|✔) 1.2s $ 
```

I'll try and work out why the llvm library installation isn't picking up these files.

**Comment by mattgodbolt** [comment]
Seems like the hacky way we install LLVM doesn't include tablegen'd files. I really don't want to have to rebuild LLVM each time (as we build LLVM daily; so I'm searching for a decent solution. It wasn't a simple one.

Do you have any ideas what might create `Attributes.inc` specifically?

**Comment by mattgodbolt** [comment]
`make install-llvm-headers` seems to do the needful

**Comment by mattgodbolt** [comment]
Seems to be fixed. I updated LLVM 9 manually. Trunk should update tomorrow.

Does slow down the nightly library install rather.
