### ISSUE TITLE
[BUG] Zig >0.3.0 does not have ASM output

### ISSUE THREAD

**Issue by LiterallyVoid** [mattgodbolt/compiler-explorer#1689]
**Describe the bug**
Zig compiler versions after 0.3.0 show `<No output file>` when trying to view the assembly output.

**To Reproduce**
- Reset Code and UI layout.
- Change language from C++ to Zig.

**Expected behavior**
The assembly code appears in the assembly output pane.

**Link**
https://godbolt.org/z/fbEhzT

**Screenshots**
Using Zig 0.3.0: ![screenshot_2019-11-19_11:00:20](https://user-images.githubusercontent.com/23141100/69177120-ce07c800-0abb-11ea-926b-45763ff153da.png)

Using Zig trunk: ![screenshot_2019-11-19_10:57:54](https://user-images.githubusercontent.com/23141100/69176972-9567ee80-0abb-11ea-8d5b-6bc8f9b45db1.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
Zig 0.3.0 works: https://godbolt.org/z/ekv8D3

**Comment by LiterallyVoid** [comment]
`zig build-obj --name` appears to expect a path without the extension, whereas [compiler explorer](https://github.com/mattgodbolt/compiler-explorer/blob/044621a7b26beeda124e92ce21fcc0fecc3a0340/lib/compilers/zig.js#L68) gives it a path with the extension.

**Comment by andrewrk** [comment]
Related: #1304

**Comment by andrewrk** [comment]
I haven't tested this, but it should fix it, if compiler explorer is passing an `outputFilename` that ends in `.s`:

```diff
-                '--name', path.basename(outputFilename));
+                '--name', path.basename(outputFilename).replace(/\.s$/, ""));
```
