### ISSUE TITLE
including files from urls

### ISSUE THREAD

**Issue by Trass3r** [mattgodbolt/compiler-explorer#1690]
Is that feature documented anywhere? If not please do.

It took a while to figure out how to make raw links work for Github as the links you get from them don't: https://github.com/[user]/[repo]/raw/[branch]/[path]

You need to replace the base url with https://raw.githubusercontent.com and remove the /raw/ part.
Not sure if compiler-explorer can do anything about that.

**Comment by RabsRincon** [comment]
Compiler Explorer also has the ability to include raw text to your source, by abusing the #include directive.

#include <url_to_text_to_include>
...

(See this link a live example: https://godbolt.org/z/Pv0K0c)

Note that the URL has to allow for cross domain requests for this to work.
