### ISSUE TITLE
[REQUEST] Support GCC static analyzer branch (experimental)

### ISSUE THREAD

**Issue by davidmalcolm** [mattgodbolt/compiler-explorer#1691]
**Is your feature request related to a problem? Please describe.**
I'm a GCC developer, and I'm working on adding a static analysis pass to GCC:
https://gcc.gnu.org/wiki/DavidMalcolm/StaticAnalyzer
This code is currently in a branch.

**Describe the solution you'd like**
Is it possible for Compiler Explorer to build my experimental branch of GCC and make it available? (rather like the coroutines and modules branches).

The branch in question is the git-only branch "dmalcolm/analyzer" on the gcc git mirror: 
https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/heads/dmalcolm/analyzer

It needs the configure-time option:
 --enable-plugins=analyzer

**Describe alternatives you've considered**
Ideally this feature would get merged for GCC 10, but I suspect that it's too ambitious for the GCC 10 release cycle, at least.  Having it on Compiler Explorer will make it easier for the curious to try out the code (and there's an element of shameless self-promotion here, I guess :) )

**Additional context**
The branch is likely to get rebased; is that an issue for your build processes?
Would I need to do anything to trigger a rebuild, or do you have a cron job monitoring the branch?

**Comment by partouf** [comment]
Hi, this sounds interesting!

We do a couple of builds nightly, (https://godbolt.org/admin/builds.html)
But it depends on how much you do changes to the codebase I guess.

Rebase is no problem I think.

We do this with a couple of scripts in this repo: https://github.com/mattgodbolt/compiler-explorer-image

So;
1. https://github.com/mattgodbolt/compiler-explorer-image/blob/master/admin-daily-builds.sh
2. https://github.com/mattgodbolt/compiler-explorer-image/blob/master/gcc/build/build.sh

If you could provide a PR or explanation on how to setup the build for your branch in that context, that would be great.

(Poking @mattgodbolt to make sure I got this right)

Secondly the compiler would need to be added to https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/c%2B%2B.amazon.properties

**Comment by davidmalcolm** [comment]
Thanks; I'm experimenting with the build.sh file you linked to.

**Comment by davidmalcolm** [comment]
I've filed https://github.com/mattgodbolt/compiler-explorer-image/pull/288 to cover building the branch

**Comment by davidmalcolm** [comment]
BTW, does Compiler Explorer implement its own colorization of the output based on regexes, or does it rely on the colorization codes emitted by the compiler?  (The branch extends GCC's diagnostic output in various ways; see e.g. https://dmalcolm.fedorapeople.org/gcc/2019-11-13/test.html which I ran through an SGR->HTML script)

**Comment by partouf** [comment]
im not entirely sure how it works, but i believe we use at least this script for it  https://github.com/mattgodbolt/compiler-explorer/blob/master/static/ansi-to-html.js

**Comment by davidmalcolm** [comment]
Thanks, it sounds like that ought to work

**Comment by apmorton** [comment]
Color codes from compiler output will be preserved.

The only catch is that the default foreground color for stderr is set to red instead of black, so if the compiler is using fancy colors in stderr, it might look a bit odd.

**Comment by davidmalcolm** [comment]
https://github.com/mattgodbolt/compiler-explorer-image/pull/288 is merged, and appears to have successfully built.

Presumably the next step is to add some config entry so that the UI shows the new compiler.
Notes to self:

- adding "std::embed gcc" was https://github.com/mattgodbolt/compiler-explorer/commit/17e9e35945874cb6a1e2b7c586f74d7cfca03bad

- adding GCC 9.1 was https://github.com/mattgodbolt/compiler-explorer/commit/cb0f2d1504e55d56d7fd1b5f77cf21ace0ac5e38

**Comment by davidmalcolm** [comment]
To test the branch, try compiling

```
#include <stdlib.h>
void test (void *ptr)
{
   free (ptr);
   free (ptr);
}
```
with `--analyzer` (though I'm looking at changing the option to `-fanalyzer` based on feedback on the mailing list).

You ought to get:

```
test.c: In function ‘test’:
test.c:5:4: warning: double-‘free’ of ‘ptr’ [CWE-415] [-Wanalyzer-double-free]
    5 |    free (ptr);
      |    ^~~~~~~~~~
  ‘test’: events 1-2
    |
    |    4 |    free (ptr);
    |      |    ^~~~~~~~~~
    |      |    |
    |      |    (1) first ‘free’ here
    |    5 |    free (ptr);
    |      |    ~~~~~~~~~~
    |      |    |
    |      |    (2) second ‘free’ here; first ‘free’ was at (1)
    |
```

**Comment by davidmalcolm** [comment]
...and more interesting examples can be seen in the upstream testsuite [here](https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=gcc/testsuite/gcc.dg/analyzer;hb=refs/heads/dmalcolm/analyzer) (e.g. the [interprocedural example](https://gcc.gnu.org/git/?p=gcc.git;a=blob_plain;f=gcc/testsuite/gcc.dg/analyzer/malloc-ipa-8-unchecked.c;h=a3a3909f01d3287e9f943dfa36b3325e373e92e9;hb=refs/heads/dmalcolm/analyzer) on the wiki)

**Comment by mattgodbolt** [comment]
@davidmalcolm absolutely; yes - a config change to the main repo like those should do the trick. Whatever you have locally to be testing this already is probably just ok copied to the c++.amazon.properties :)

**Comment by davidmalcolm** [comment]
Looks like the config is live now, and working - thanks!

I took the liberty of sending a [message](https://gcc.gnu.org/ml/gcc/2019-12/msg00152.html) about this to the GCC mailing list, with some pre-canned examples.  Hope that's OK.

Thanks again for everyone's help with this, and for the great project.

**Comment by mattgodbolt** [comment]
Thank you @davidmalcolm ! :)
