### ISSUE TITLE
[BUG] Modern MSVC missing

### ISSUE THREAD

**Issue by GabrielRavier** [mattgodbolt/compiler-explorer#1693]
The recent versions of MSVC (such as v19.22 and other recent versions) are missing from godbolt.org

**To Reproduce**
- Go to [godbolt](godbolt.org)
- Search for "MSVC" in the list of compilers
- See that only old WINE MSVC versions are available

**Expected behavior**
Expected to be able to use modern MSVC

**Machine configuration information**
 - OS : Fedora 31, kernel version 5.3.11
 - Browser : Firefox Nightly
 - Version : 72.0a1

**Additional comments**
I know this is most likely a temporary problem, but it's still an issue however temporary it may be

**Comment by partouf** [comment]
The MS site seems to be suffering from a 502 - @dan-shaw can you help?

**Comment by mattgodbolt** [comment]
Thanks to our friends at MS this is now fixed!
