### ISSUE TITLE
[BUG] Unable to use Go compiler at tip

### ISSUE THREAD

**Issue by marigonzes** [mattgodbolt/compiler-explorer#1697]
**Describe the bug**
If I try to compile any code with the Go compiler at tip (for example, [this](https://godbolt.org/z/EkuQTX)), I get the following error in the console:
```
fatal error: failed to reserve page bitmap memory

runtime stack:
runtime.throw(0xa489b1, 0x24)
	/root/master/go/src/runtime/panic.go:1106 +0x72 fp=0x7ffcb86df070 sp=0x7ffcb86df040 pc=0x433dd2
runtime.(*pageAlloc).init(0xebacc8, 0xebacc0, 0xed33b8)
	/root/master/go/src/runtime/mpagealloc.go:239 +0x18a fp=0x7ffcb86df0d0 sp=0x7ffcb86df070 pc=0x42957a
runtime.(*mheap).init(0xebacc0)
	/root/master/go/src/runtime/mheap.go:694 +0x274 fp=0x7ffcb86df0f8 sp=0x7ffcb86df0d0 pc=0x4266d4
runtime.mallocinit()
	/root/master/go/src/runtime/malloc.go:469 +0xff fp=0x7ffcb86df128 sp=0x7ffcb86df0f8 pc=0x40cb2f
runtime.schedinit()
	/root/master/go/src/runtime/proc.go:545 +0x60 fp=0x7ffcb86df180 sp=0x7ffcb86df128 pc=0x4373e0
runtime.rt0_go(0x7ffcb86df1b8, 0x7, 0x7ffcb86df1b8, 0x0, 0x7f0f82fed0ca, 0x7, 0x7ffcb86dfdba, 0x7ffcb86dfddf, 0x7ffcb86dfde4, 0x7ffcb86dfdec, ...)
	/root/master/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7ffcb86df188 sp=0x7ffcb86df180 pc=0x460ca5

Compiler returned: 2
```

**To Reproduce**
- Go to https://godbolt.org/z/EkuQTX
- Observe the reported error

**Expected behavior**
I expected the code to be compiled without any problems

**Link**
https://godbolt.org/z/EkuQTX

**Comment by partouf** [comment]
This will probably resolve itself tomorrow, we'll see and perhaps investigate then.

**Comment by marigonzes** [comment]
I'm still experiencing this issue.

**Comment by mattgodbolt** [comment]
@partouf any thoughts on why this might have been resolved? Seems like the `go` compiler is trying to allocate a lot of memory and our sandbox environment is preventing it.

**Comment by partouf** [comment]
they made a change concerning memory things on some of the commits on that day it broke, I would’ve assumed they would magically see the error in their ways 🙄

**Comment by apmorton** [comment]
provided link no longer reproduces - I think its safe to call this fixed
