### ISSUE TITLE
[REQUEST] Docker image

### ISSUE THREAD

**Issue by sandorex** [mattgodbolt/compiler-explorer#1701]
**Describe the solution you'd like**
A Dockerfile for running compiler-explorer easily

**Comment by mattgodbolt** [comment]
Hi!

What kind of thing were you hoping for here? There are third-party Compiler Explorer docker images (e.g. https://github.com/madduci/docker-compiler-explorer) but we don't support one ourselves. We used to use docker but the 400GB+ of compilers we support makes docker too unwieldy.

I appreciate a "small selection" of compilers might be useful, but I have no strong opinions about what those compilers should be, plus not much appetite for keeping it up to date as well as all the other stuff :) But I'll listen to any reasonable arguments!

**Comment by sandorex** [comment]
Oh i didn't think it was that big i thought it would be easier to install especially on windows but 400GB is a bit too much, anyways im closing it
