### ISSUE TITLE
[BUG] MSVC not working

### ISSUE THREAD

**Issue by DanielLangr** [mattgodbolt/compiler-explorer#1704]
Choosing MSVC compiler results in the following error:

`<Compilation failed: Request failed: HTTP error code 502>`

Applies for both 32-bit and 64-bit versions of MSVC.

**Comment by mattgodbolt** [comment]
Thanks. MS are aware

We're seeing:

```
Nov 25 12:47:38 ip-172-30-1-91 amazon warn: Failed www.godbolt.ms:443 : Error: connect ENETUNREACH 255.255.255.255:443 - Local (0.0.0.0:0), retrying 
```

**Comment by mattgodbolt** [comment]
Disabling MS compilers now (CC @dan-shaw) - the change from 500 to ECONN has taken down Compiler Explorer.

**Comment by sasha2048** [comment]
Looks like that happens again.

**Comment by mattgodbolt** [comment]
Yeah. We're waiting on hearing back from MS. Sorry. Will put a MOTD up
