### ISSUE TITLE
[BUG] Output panel sometimes empty when opening a link

### ISSUE THREAD

**Issue by lunasorcery** [mattgodbolt/compiler-explorer#1713]
**Describe the bug**
When loading a shared link, Output views may sometimes be detached from their associated compiler, and appear empty.

**To Reproduce**
Add a second Compiler panel, and open its associated Output panel. Close the first Compiler panel, leaving you with Compiler #<span></span>2 and Output #<span></span>2. Create a shortlink for the page and visit it. When the page opens, the Compiler #<span></span>2 panel will now be labeled as Compiler #<span></span>1, and the Output panel will be labeled "#<span></span>2" and have no contents.

**Expected behavior**
Compiler #<span></span>2 to remain named as such, and for the Output #<span></span>2 panel to maintain its association and display the output from Compiler #<span></span>2.

**Link**
https://gcc.godbolt.org/z/5MAB8D

**Comment by RabsRincon** [comment]
Thank you for taking the time to find a way to reproduce this, it is going to be super useful! :)

**Comment by RabsRincon** [comment]
The linked commit should have fixed the issue. Thanks for the report and for taking the time to find a reproducible step by step guide :)
It should hit the live site shortly
