### ISSUE TITLE
[BUG] ISPC default options to remove --target flag

### ISSUE THREAD

**Issue by dbabokin** [mattgodbolt/compiler-explorer#1716]
Current ``ISPC`` compiler default flags on compiler explorer contain ``--target=sse2-i32x4``. This is reasonable, as by default ``ISPC`` targets host platform. If user wants to generate for different target, they can add another ``--target=`` and the later overwrites the first one.

I'm considering changing this ``ISPC`` behavior to at least warn on multiple ``--target=`` options on the command line. So I have a couple questions:
 (1) what are expectation on host platforms where compiler explorer runs? I assume this is some AVX2 or AVX512 capable hardware, right? Is there any expectations on the consistency of host hardware? If this is the case, we can probably drop default ``--target=`` swtich.
 (2) have you encountered this problem with other compilers, which by default target "host" hardware, for example icc?

**Comment by jsheard** [comment]
AWS hardware isn't homogenous, so the default behavior of targeting the host CPU caused unpredictable results. At the time I implemented ISPC support it would randomly flip between AVX1 or AVX2 depending on which AWS node happened to serve the request, and today it would probably sometimes generate AVX512 code as well.

Hard-coding the target flag was intended to enforce consistent behavior across nodes.

**Comment by dbabokin** [comment]
Ok, then we need to keep allowing multiple `--target` options on the command line and use the latest one. Thank you.
