### ISSUE TITLE
[REQUEST] Increase the size of tab headers on mobile

### ISSUE THREAD

**Issue by porglezomp** [mattgodbolt/compiler-explorer#1717]
**Is your feature request related to a problem? Please describe.**
The tab layout is close to being the most usable type of layout on mobile, since it lets you dedicate almost the full screen to one thing at a time. Unfortunately, it's difficult to use since the tab headers are so small, they're difficult to tap.

**Describe the solution you'd like**
On small screens, the tab headers should be displayed larger.

**Describe alternatives you've considered**
This is a partial solution towards improving mobile support, it would likely be better to do more dramatic redesigns of mobile UI, but that requires more engineering work.

Related to #176.

**Comment by porglezomp** [comment]
I've begun doing some work on this.

**Comment by mattgodbolt** [comment]
Thank you so much! Let us know if we can help in any way!
