### ISSUE TITLE
[BUG] LLVM-IR emission not working

### ISSUE THREAD

**Issue by fvrmatteo** [mattgodbolt/compiler-explorer#1729]
**Describe the bug**
The **-S -emil-llvm** compiler options applied to clang are not working properly on clang versions newer than 3.6.

**To Reproduce**

1. Open Compiler Explorer and make sure the C++ default example is loaded
2. Select the **x86-64 clang 9.0.0** compiler
3. Use the **-S -emit-llvm** compiler options
4. The **No output** string should appear in the output view, instead of the output LLVM-IR

**Expected behavior**
The expected behaviour is to obtain the output LLVM-IR (like shown in the clang 3.6 example in the link section).

**Link**
The issue is present using clang 9.0.0: https://godbolt.org/z/TWEWsE
The issue is not present using clang 3.6: https://godbolt.org/z/Di6Nc9

**Desktop**
 - OS: MacOS Catalina 10.15.1
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by mattgodbolt** [comment]
Confirmed; and I ran the command manually on the server and it is working there:

```
Dec/11 17:18 admin-node~ $ /opt/compiler-explorer/clang-9.0.0/bin/clang++ -g -o /tmp//output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics -O3 -S -emit-llvm /tmp/example.cc 
Dec/11 17:18 admin-node~ $ less /tmp/output.s 
; ModuleID = '/tmp/example.cc'
source_filename = "/tmp/example.cc"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: norecurse nounwind readnone uwtable
define dso_local i32 @_Z6squarei(i32) local_unnamed_addr #0 !dbg !7 {
  call void @llvm.dbg.value(metadata i32 %0, metadata !13, metadata !DIExpression()), !dbg !14
  %2 = mul nsw i32 %0, %0, !dbg !15
  ret i32 %2, !dbg !16
}

; Function Attrs: nounwind readnone speculatable
declare void @llvm.dbg.value(metadata, metadata, metadata) #1
...
```

**Comment by DeepakRajendrakumaran** [comment]
Looks like the same issue in ispc when trying to emit llvm IR- https://ispc.godbolt.org/z/SxSZEr

**Comment by ThomasRaoux** [comment]
One workaround to this problem is to add -g0 to the command line. The following command line works for me:
-g0 -O2 -emit-llvm

**Comment by LebedevRI** [comment]
Also hitting this.
As a consequence, it is no longer possible to diff the IR.

**Comment by partouf** [comment]
Fix is now live
