### ISSUE TITLE
[BUG] LD_LIBRARY_PATH for compilation environment is overwritten

### ISSUE THREAD

**Issue by Grulfen** [mattgodbolt/compiler-explorer#1733]
**Describe the bug**
LD_LIBRARY_PATH for the compilation environment is set to [] even though it looks like it should be passed through from the environment that start compiler explorer https://github.com/mattgodbolt/compiler-explorer/blob/87fea44d6ad9edf68a06dea3d1cd11dfb829a94b/lib/compilation-env.js#L63

**To Reproduce**
`LD_LIBRARY_PATH=something make EXTRA_ARGS=--debug`

**Expected behavior**
See `LD_LIBRARY_PATH="something"` in logs 
Execution `{"type":"executing", ... ,"env":{"LD_LIBRARY_PATH":[], "PATH":"/usr/bin"...`

**Desktop (please complete the following information):**
 - OS: ubuntu 19.10

**Additional context**
the PATH and HOME environment variables are passed through successfully.

It looks like this code
https://github.com/mattgodbolt/compiler-explorer/blob/87fea44d6ad9edf68a06dea3d1cd11dfb829a94b/lib/exec.js#L50-L52
overwrites LD_LIBRARY_PATH

**Comment by mattgodbolt** [comment]
Oh blast! Good spot, thanks for noting and taking the time to investigate.

**Comment by gnarlie** [comment]
Just bitten by this - or something similar - myself. Looks like `ldPath` is always `[]`, despite some support for specifying an `ldPath` option in the properties files. The option is being overwritten by `getSharedLibraryPathsAsLdLibraryPaths` .

Happy to create a different issue if its best to track separately.
