### ISSUE TITLE
[BUG] {fmt} is broken

### ISSUE THREAD

**Issue by acgetchell** [mattgodbolt/compiler-explorer#1749]
**Describe the bug**
No version of the {fmt} library works.

**To Reproduce**
Add format library, include it, and compile.

**Expected behavior**
No errors.

**Link**
https://godbolt.org/z/gGRZPL

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Browser Safari 13.04 and Firefox 71.0
 
**Additional context**
It's been broken for at least a month.

**Comment by apmorton** [comment]
This is working as intended - libraries in general are not currently supported when linking/executing user code.

See #1662
