### ISSUE TITLE
[REQUEST] [Rust] add colors in compiler output

### ISSUE THREAD

**Issue by robinmoussu** [mattgodbolt/compiler-explorer#1755]
Adding `--color=always` improves the readability of the output of the compiler.

Note: `--color=auto` doesn't add any color (I guess it's the current setting).

**Comment by RabsRincon** [comment]
Thanks for the suggestion! I've now implemented this for every rustc compiler that supports it and the change is already available on the live site. :)
Let us know if there's anything else we can do.

**Comment by robinmoussu** [comment]
Nice ;)
