### ISSUE TITLE
[BUG] Nim language does not properly compile

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1760]
As seen in https://godbolt.org/beta/z/ULzZgQ nim does not currently compile

@DaemonSnake do you have any ideas?

**Comment by DaemonSnake** [comment]
@RabsRincon there seems to have a '\n' in the file path, that's weird. I'm looking into it

**Comment by DaemonSnake** [comment]
I believe I have located the issue.

The format of the name of the output object file has changed since my local version of nim.
Instead of `$nimcache/$module_name.$lang_extension.o` it's now 
`$nimcache/@m${module_name}.$lang_extension.o'`
It seems like a recent change.

**Comment by RabsRincon** [comment]
The fix looks good. I've confirmed that it now compiles so I've updated the live site with the latest changes. Thanks again for all the work you've put into getting nim support into the site :)
