### ISSUE TITLE
[BUG] **Eigen-trunk (master) changed its repository**

### ISSUE THREAD

**Issue by chhtz** [mattgodbolt/compiler-explorer#1763]
**Describe the bug**
It appears that godbolt.org fetches Eigen-master from an outdated repository. As bitbucket will remove all their mercurial repositories, we migrated to git and also changed the host to https://gitlab.com/libeigen/eigen.git

The following repositories still work, but are not updated anymore:
* https://github.com/eigenteam/eigen-git-mirror
* https://bitbucket.org/eigen/eigen

**To Reproduce**
Try compiling anything which requires any recent fix of Eigen-master

**Expected behavior**
Eigen-trunk should use the newest Eigen version from
https://gitlab.com/libeigen/eigen.git

**Link**
https://godbolt.org/z/8ymWj-

**Screenshots**
N/A

**Desktop (please complete the following information):**
Irrelevant

**Additional context**
Came up due to a report on stackoverflow:
https://stackoverflow.com/questions/59573043/eigen-linspaced-deprecated-copy-warning

Also related (this is a bug which is fixed on eigen-master):
https://gitlab.com/libeigen/eigen/issues/1788

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. We'll update the library to point to the new repository. Sorry that we missed it :)

**Comment by RabsRincon** [comment]
Closed by https://github.com/mattgodbolt/compiler-explorer-image/commit/da687551bc79bc72c3293cdc3e6fbd71a6ebc2d3 It should hit the live site in the next 24 hours :)

**Comment by chhtz** [comment]
Thanks for looking into this, but it appears not to be updated yet.

Note that the new repository is not compatible to the old github mirror, because we changed all references/hashes inside commit messages. I.e., simply pulling into the existing check-out using the new url will very likely fail (maybe unless some `--force` parameters are involved, but the simpler solution would be to once manually delete the existing repository).

**Comment by apmorton** [comment]
fixing now - should be up and running sometime soon here

**Comment by chhtz** [comment]
Great, works as expected now. Thanks a lot!
