### ISSUE TITLE
[BUG] Go compilation results in JS error

### ISSUE THREAD

**Issue by balasanjay** [mattgodbolt/compiler-explorer#1765]
**Describe the bug**
When I compile https://godbolt.org/z/roCvhv, I see the following "compiler" error: 

```
Internal Compiler Explorer error: TypeError: (intermediate value) is not iterable
    at /compiler-explorer-image/.deploy/lib/base-compiler.js:731:39

Compiler returned: -1
```

**Comment by mattgodbolt** [comment]
Also reported over email. Thanks for digging in to this. Seems to affect all `gc` compilers

**Comment by mattgodbolt** [comment]
Separately; this server-side error isn't getting to `sentry.io` so we weren't notified of it earlier
