### ISSUE TITLE
Highlight/auto scroll to assembly

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#177]
Various comments:

* Highlight the asm region corresponding to the region the source cursor is in. And/or the mouse pointer is over.
* Auto scroll the assembly to show the region the cursor is in

**Comment by RabsRincon** [comment]
Closed by #283 !

**Comment by mattgodbolt** [comment]
Indeed: thanks Rubén! :) Your changes are live on the beta site, btw

**Comment by mattgodbolt** [comment]
Fixed. I think perhaps this is a little too subtle still, but we can work on the presentation.
