### ISSUE TITLE
Run CompilerExplorer as commandline tool

### ISSUE THREAD

**Issue by wimalopaan** [mattgodbolt/compiler-explorer#179]
It would be great to use compiler explorer as a commanline tool, that produces the very same output on stdout. Then it would be possible to have some test cc files and preserve the output of compiler explorer (the nice filtered asm output) in files.

**Comment by mattgodbolt** [comment]
Are you thinking for a local run of CE or to shell out to the remote server? The latter should be fairly straightforward using the (undocumented!) REST API that CE website uses.

**Comment by mattgodbolt** [comment]
Were you thinking to run CE locally, or to have a command-line client to use the gcc.godbolt.org (etc) site?

**Comment by wimalopaan** [comment]
First I thought of running CE local and use its output. But using it locally or remote via the REST API should be the same, I suppose ?

**Comment by mattgodbolt** [comment]
Running locally means:

Pros:
- more control of the compiler version
- able to include local files
- no extra load on the gcc.godbolt.org servers
- works with no network access

Cons:
- no access to other compilers
- more set up required

**Comment by mattgodbolt** [comment]
I'm going to close this for now: it's not on my roadmap and I think the tools exist to be able to use the REST interface either on a local instance or the public one.
