### ISSUE TITLE
Fix CI builds failing because a new Sentry release could not be built

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1791]
Sentry is making the ci builds appear as if they failed but the only "bad" section turns out to be the new release registration stuff.

**Comment by mattgodbolt** [comment]
Argh! thanks Rabs

**Comment by mattgodbolt** [comment]
Do you have a link to a failing CI step? I can't see where it's appearing failed

**Comment by RabsRincon** [comment]
Latest Ewavr PR  build as an example https://travis-ci.org/mattgodbolt/compiler-explorer/builds/637072529#L1481

**Comment by mattgodbolt** [comment]
Ah right! It's just external PRs that are failing (https://travis-ci.org/mattgodbolt/compiler-explorer/builds for me is all green! :))  Will fix; thanks!

**Comment by mattgodbolt** [comment]
(this is a feature so external PRs can't get access to the secrets! :))

**Comment by mattgodbolt** [comment]
I think I fixed it...

**Comment by RabsRincon** [comment]
New error. Again, Ewavr PR as an example: https://travis-ci.org/mattgodbolt/compiler-explorer/builds/637072529#L1482

**Comment by mattgodbolt** [comment]
argh, /bin/sh vs /bin/bash! Fixing...

**Comment by RabsRincon** [comment]
Fixed! :)

**Comment by mattgodbolt** [comment]
Amateur hour from me, sorry!!
