### ISSUE TITLE
[BUG] 'Execute the binary' truncating return value to 1-byte

### ISSUE THREAD

**Issue by CraigHutchinson** [mattgodbolt/compiler-explorer#1795]
**Describe the bug**
'Execute the binary' truncating return value to 1-byte visible by returning **'65356'** from main() which prints "Program returned: **76**"

**To Reproduce**
1. Execute this code:
```
int main() { return 256; } 
```
2. Observe result **returned 0**:
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
```
3. Change to output 257, 258, 259 etc

**Expected behaviour**
Expected to return 255, 256, 257, 258, 259 etc
But actually got 255, 0, 1, 2, 3 etc..

**Link**
https://godbolt.org/z/7DrDaQ

**Screenshots**
<img src="https://user-images.githubusercontent.com/54269136/72599583-e94f5200-3909-11ea-9a25-a90be01e0210.png" width="480"/>
<img src="https://user-images.githubusercontent.com/54269136/72599497-bad17700-3909-11ea-9cc9-74b8637a1c68.png" width="480"/>
<img src="https://user-images.githubusercontent.com/54269136/72599606-f409e700-3909-11ea-8018-3c7556b3716a.png" width="480"/>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 44.18363

**Additional context**

**Comment by partouf** [comment]
Hi, this is mostly how Linux works, so we can't really "fix" that.
If you want to convey something in the output with bigger numbers you should use stdout instead of the exitcode.

**Comment by CraigHutchinson** [comment]
@partouf Thankyou for clarifying this issue
