### ISSUE TITLE
Cannot find module 'debug'

### ISSUE THREAD

**Issue by Vm900** [mattgodbolt/compiler-explorer#1803]
Hi,
Just been playing aroung and trying to run it on WSL (ubuntu 18) windows 10.
First time running it went well with just warnings and at the time I had installed the latest version and not version 12.However,in trying to change to version 12 I clobbered it.
Now after reinstalling everything all over again i'm getting this error message.
![compilerexplorerError1](https://user-images.githubusercontent.com/9399631/72954662-129c3200-3d91-11ea-836f-5601220f81ba.png)

**Comment by apmorton** [comment]
This is a known issue that we will need to fix at some point, but for now you can work around it by running `npm install` before `make`.

**Comment by Vm900** [comment]
Hi
Just ran it again and now it's stuck on the line:
rm -rf out/dist/static out/dist/manifest.json
./node_modules/webpack-cli/bin/cli.js

**Comment by Vm900** [comment]
Solved
