### ISSUE TITLE
[BUG] xtensor library is not working with gcc and clang

### ISSUE THREAD

**Issue by Yulivee01** [mattgodbolt/compiler-explorer#1805]
I tried to write some code, using the xtensor library.
Neither gcc nor clang is working. I tried all versions of the library in both compilers.

Here is what I tried:
https://godbolt.org/z/Cwv38L

**Comment by apmorton** [comment]
Add the xtl library as well.

Trunk gives me some other build errors, but 0.5.3 works with the example you gave.

**Comment by Yulivee01** [comment]
Ah, thanks. I missed that one. msvc is working without xtl.
