### ISSUE TITLE
[REQUEST] Add hedley single-header lib to libraries

### ISSUE THREAD

**Issue by travisdowns** [mattgodbolt/compiler-explorer#1807]
I would like to see the [hedley single header library](https://nemequ.github.io/hedley/api-reference.html) ([github](https://github.com/nemequ/hedley)) available in the libraries menu of compiler explorer.

This library abstracts over many "non standard" features of C and C++ compilers, allowing you to call them in a compiler-independent way. I use this all the time in real life, and in a CE scenario, it is exactly what I often need when I want to use "likely" macro or "assume" across compilers (in particular, with MSVC which does't support any of the gcc-style builtins).

I don't know what the library approval process is. This isn't a really heavily used library (just judged by the star count), but it super useful especially when comparing across compilers.

I am willing to do the work to add it.

---

I deleted all the template questions because I think it would be faster for you to read it this way.

**Comment by travisdowns** [comment]
@RabsRincon - let me know if there is anything I can help out with here. I think the author @nemequ would also be happy to answer any questions.

**Comment by nemequ** [comment]
Of course.

I'm willing to help with the work, too.  I use Compiler Explorer a lot and this would be a huge improvement for me since most of my code relies pretty heavily on Hedley, so if there is anything I can do please let me know.

**Comment by RabsRincon** [comment]
Hi! Sorry for the delay - I've been running short on time lately and have not had time to finish the PR up until now. I've now done the necessary changes, and after I confirm that everything works ok, I'll push the update to the live site tonight.

Sorry again for keeping you waiting, thanks for your patience! :)

**Comment by nemequ** [comment]
Awesome, it's working, thank you!

I notice that it's only available for C++; is it possible to add it for C as well?  It's designed to work well from both languages.

It also looks like the libraries available for Windows are different; the WINE MSVC compilers have Hedley, the normal ones don't.  What would need to change for that to work?

FWIW I'd be willing to make the changes and file a PR, I would just need a bit of guidance on what to change…

**Comment by RabsRincon** [comment]
Sure! The C++ version was added with https://github.com/mattgodbolt/compiler-explorer/commit/2079ec1184eac0159595a829aa98df1cb0521379 , which adds it to the list of libraries for that language, and then adds the necessary info. To add more than 1 version, see some other libraries that have them as an example.

So to add C, the same process has to be done in the C file at etc/config/c.amazon.properties

Let me know if there's anything else you want to know

As for the MSVC compilers, they are run by microsoft so changes there take more time

**Comment by nemequ** [comment]
Thanks, I was looking at the first patch to try to figure out what to do.  The second was a lot more helpful, I opened up a PR.

> As for the MSVC compilers, they are run by microsoft so changes there take more time

So there is nothing I should be doing, it should just be a matter of time until they pull it in automatically?  I don't mind waiting, just want to make sure nothing is waiting on me.

**Comment by RabsRincon** [comment]
Yes, there's nothing to worry about on your end :)
