### ISSUE TITLE
[BUG] Typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nemequ** [mattgodbolt/compiler-explorer#1815]
The second word of the first paragraph should be "off", not "of".

Other than that, though, this is the perfect way to start contributor documentation.  Would you mind if I stole it for a few of my projects (and changed "Compiler Exprorer" to the relevant project, of course)?

I deleted the template because it doesn't really make sense for this type of issue.

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to open the issue. 
Do feel free to use the paragraph as you see fit :)
