### ISSUE TITLE
Rename a.out to Execute

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#1818]
It's not the first time we get a question about not being able to excute code on the site nor locally. I think a big reason is naming. This could be left open until we get around reworking the ui, but maybe it's worth to go for the low hanging fruit first?

**Comment by apmorton** [comment]
> "Give me ~liberty~ ./a.out, or give me death!"
> Patrick Henry - March 23, 1775

Bad history memes aside, I agree.

We should probably think about how to rework that entire filters UI since it is problematic on mobile as well.

**Comment by mattgodbolt** [comment]
yeah, agreed. `./a.out` is easy to understand for one person only...me...and so we should make it something else.

**Comment by apmorton** [comment]
closed by #1873
