### ISSUE TITLE
[REQUEST] Option for natural tabs in code input

### ISSUE THREAD

**Issue by kazblox** [mattgodbolt/compiler-explorer#1819]
Forcing natural tabs to be the only option isn't fine, but forcing the conversion of tabs to spaces to be the only option isn't fine either. Please make a consideration of giving us the ability to switch between both options.

**Comment by RabsRincon** [comment]
Thanks for your suggestion! I've added a way to select what to use for identation in the settings panel. The change will hit the live site later today :)
