### ISSUE TITLE
gcc trunk is not up to date (following svn to git migration on gcc side)

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [mattgodbolt/compiler-explorer#1820]
Hi,

It looks like gcc trunk (found in Compiler Explorer) is currently at version 10.0.0 from 11th January, while now the actual gcc trunk is on stage 4, version 10.0.1. On 11th January the gcc team did migrate from svn to git. You shall update your config to now clone master branch of this repo: https://gcc.gnu.org/git/?p=gcc.git;a=summary:

```
URL | git://gcc.gnu.org/git/gcc.git
-- | --
  | ssh://gcc.gnu.org/git/gcc.git
  | https://gcc.gnu.org/git/gcc.git
```

Cheers,
Romain

**Comment by apmorton** [comment]
Thanks for the heads up - I have updated our build scripts.

Will leave this open until we see how the next round of daily builds goes.

**Comment by mattgodbolt** [comment]
Looks like an issue:
```
https://gcc.gnu.org/git/gcc.git
+ rm -rf gcc-trunk-20200210
+ git clone -q --depth 1 --single-branch -b master https://gcc.gnu.org/git/gcc.git gcc-trunk-20200210
fatal: dumb http transport does not support shallow capabilities
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/compiler-explorer-image/bin/lib/ce.py", line 899, in main
    globals()[cmd + "_cmd"](kwargs)
  File "/home/ubuntu/compiler-explorer-image/bin/lib/ce.py", line 199, in builder_cmd
    dispatch_global('builder', args)
```
will investigate! Thanks both.

**Comment by mattgodbolt** [comment]
Seems to be building ok now! thanks both :)
