### ISSUE TITLE
[BUG] this.compiler.disabledFilters is undefined

### ISSUE THREAD

**Issue by thenewvu** [mattgodbolt/compiler-explorer#1828]
![Screen Shot 2020-02-10 at 13 05 56](https://user-images.githubusercontent.com/6092585/74124805-20154100-4c06-11ea-991e-6a71ce007b9a.png)

```
13:02:30.660 TypeError: this.compiler.disabledFilters is undefined compiler.js:1159:4
    updateButtons compiler.js:1159
    b compiler.js:170
    compilerFactory hub.js:187
    b hub.js:88
    Component goldenlayout.js:3706
    createContentItem goldenlayout.js:828
    _createContentItems goldenlayout.js:3599
    AbstractContentItem goldenlayout.js:3104
    Stack goldenlayout.js:4381
    createContentItem goldenlayout.js:828
    _createContentItems goldenlayout.js:3599
    AbstractContentItem goldenlayout.js:3104
    RowOrColumn goldenlayout.js:3848
    <anonymous> self-hosted:909
    createContentItem goldenlayout.js:828
    _createContentItems goldenlayout.js:3599
    AbstractContentItem goldenlayout.js:3104
    Root goldenlayout.js:3761
    _create goldenlayout.js:1383
    init goldenlayout.js:706
    b hub.js:152
    <anonymous> main.js:337
    jQuery 2
    t helpers.js:71
```

- OS: OSX
- Browser: Firefox 72.0.2

**Note:** Tried to reload browser without caching.
**Note:** Tried to disable addons.

**Comment by mattgodbolt** [comment]
Thanks for this! We pushed a big change and testing in our staging environment but didn't see this issue.

For now we've rolled the site back (thanks @apmorton ) and will work on a fix.

**Comment by mattgodbolt** [comment]
We're going with the theory that an old instance was still running when the update hit and a file was cached at the wrong version; and will try an upgrade again tonight. Much more closely monitored this time!

**Comment by mattgodbolt** [comment]
Have pushed latest again and haven't observed this. Closing although we aren't 100% sure why it happened...

**Comment by thenewvu** [comment]
Just tried again, everything seems to be ok now, thanks to you all for great work!

**Comment by mattgodbolt** [comment]
thanks for filing the issue! :)
