### ISSUE TITLE
[BUG] `etc/scripts/pre-commit` does not fail when linter fails

### ISSUE THREAD

**Issue by apmorton** [mattgodbolt/compiler-explorer#1835]
Not sure when this changed, but `etc/scripts/pre-commit` runs `make check`, which runs `npm run lint`, which runs `npm run lint-client && npm run lint-server`, each of which passes `--fix` to `eslint`.

This behavior makes sense for `make check`, since it will automatically fix trivial issues.
It does not make sense for the pre-commit script, since if it fixes all the trivial issues it will exit with status 0, the commit is not aborted, *but the fixes don't make it into the commit*.

The pre-commit script should probably `npm run ci-lint`.

**Comment by mattgodbolt** [comment]
I never realised `make check` had `--fix` ! I think it's probably my fault a ways back...sorry!
