### ISSUE TITLE
[BUG] Wrong sandbox configuration causes unreadable exception

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#1848]
This line https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/exec.js#L199

Is displayed as:
`error: Exception while processing compilers: {"0":"B","1":"a","2":"d","3":" ","4":"s","5":"a","6":"n","7":"d","8":"b","9":"o","10":"x","11":" ","12":"t","13":"y","14":"p","15":"e","16":" "}`

(indexed array saying "Bad sandbox type ")

This happens when you set "executionType=" instead of  "executionType=none"

**Comment by mattgodbolt** [comment]
Whoops :) Thanks @partouf

**Comment by mattgodbolt** [comment]
Now we get:
```
error: Exception while processing compilers:Bad sandbox type  {"stack":"Error: Bad sandbox type \n    at Object.execute (/home/matthew/dev/compiler-explorer/lib/exec.js:388:15)\n    at DefaultCompiler.execCompilerCached (/home/matthew/dev/compiler-explorer/lib/base-compiler.js:114:33)"}
```
which should get reported correctly in both papertrail and sentry.
