### ISSUE TITLE
[BUG] zig compiler-rt functions missing from debug pane

### ISSUE THREAD

**Issue by daurnimator** [mattgodbolt/compiler-explorer#1852]
**Describe the bug**
compiler-rt functions are not showing up in the debug pane.

**To Reproduce**
Use the following zig code (use zig trunk)
```zig
export fn sum(N: u64) u64 {
    var s: u64 = 0;
    var i: u64 = 0;
    while (i < N) : (i += 1) {
        s +%= i;
    }
    return s;
}
```

Compiler options: `-target riscv64-freestanding --release-fast -mcpu=generic_rv64 --bundle-compiler-rt`
Note that the debug pane only contains:
```asm
sum:
  addi sp, sp, -16
  sd ra, 8(sp)
  sd s0, 0(sp)
  beqz a0, .LBB0_2
  mv s0, a0
  addi a0, a0, -1
  addi a2, s0, -2
  mv a1, zero
  mv a3, zero
  call __multi3
  slli a1, a1, 63
  srli a0, a0, 1
  or a0, a0, a1
  add a0, a0, s0
  addi a0, a0, -1
  ld s0, 0(sp)
  ld ra, 8(sp)
  addi sp, sp, 16
  ret
.LBB0_2:
  mv a0, zero
  ld s0, 0(sp)
  ld ra, 8(sp)
  addi sp, sp, 16
  ret
```

**Expected behavior**
The debug pane should show the `__multi3` function somewhere

**Link**
https://godbolt.org/z/6wKzpk

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**

Local attempt:
```
$ cat test2.zig 
export fn sum(N: u64) u64 {
    var s: u64 = 0;
    var i: u64 = 0;
    while (i < N) : (i += 1) {
        s +%= i;
    }
    return s;
}
$ ./zig build-obj test2.zig --release-fast -target riscv64-freestanding --bundle-compiler-rt
$ ~/local/llvm9-release/bin/llvm-objdump -d test2.o  | grep multi3
Disassembly of section .text.__multi3:
0000000000000000 __multi3:
```

**Comment by andrewrk** [comment]
The command that Godbolt uses is covered by zig's test suite here:

https://github.com/ziglang/zig/blob/907c5589ae20d1b2a73acf26c9d67139dfe3bfb9/test/cli.zig#L117-L124

When I do this locally, the resulting assembly file does not contain the assembly for compiler-rt. The output assembly contains the generated asm for the zig root source file only.

normally, compiler-rt is generated as a separate object and in the case of `--bundle-compiler-rt` it is merged with the object coming from the zig root source file, and any other assembly files, object files, or c source files provided on the command line.

To merge them as assembly files would be an esoteric use case and probably won't get supported.
