### ISSUE TITLE
[BUG] Popular compiler arguments list is truncated on the right

### ISSUE THREAD

**Issue by valiko-ua** [mattgodbolt/compiler-explorer#1863]
Popular compiler arguments list is truncated on the right side if the compiler pane is right-most. It does not depend on a browser window maximized state.
Tested in Firefox and Chrome.
Screenshot:

![truncation](https://user-images.githubusercontent.com/13869060/75482108-d28e2780-59ac-11ea-87d8-3db9ad96b79c.png)

**Comment by mattgodbolt** [comment]
Thanks for filing this; yes it does seem to be a problem!

**Comment by valiko-ua** [comment]
I still observe the same bug. Nothing changed. Both in Chrome and Firefox.

**Comment by apmorton** [comment]
the fix is in master, but has not been deployed to the live site yet.
Whenever we deploy next you should see the fix.

**Comment by mattgodbolt** [comment]
We should be deploying later today. Thanks for your patience.
