### ISSUE TITLE
[BUG] Execute binary with LDC >= 1.19 cannot find 'cc'

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#1872]
Using execute binary works with LDC < 1.19.
With LDC >= 1.19 it no longer works, with the error: `Error: failed to locate cc`. This is because of https://github.com/ldc-developers/ldc/pull/3202 . LDC >= 1.19 defaults to calling `cc` if the environment variable `CC` is not defined. Previously, `gcc` was used on CE's platform. The temporary fix is to explicitly add `-gcc=gcc` to the compiler arguments.
Probably best to specify `CC=gcc` in the container?

**Comment by mattgodbolt** [comment]
HI @JohanEngelen ! We don't have a container as such any more: I'd suggest we pass `-gcc=<path_to_a_known_gcc>` in either the `compiler/ldc.js` or in the settings for the ldc compilers. Probably the latter for best (we do this e.g. for `clang` : https://github.com/mattgodbolt/compiler-explorer/blob/08772b98041f88142c15861fec53c04c7d5f2e40/etc/config/c%2B%2B.amazon.properties#L124 for example
