### ISSUE TITLE
[BUG] Wedged compiler cause /tmp/ to fil up

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1875]
**Describe the bug**
During a run a wedged compilation step prevented the `/tmp` cleaner from running. The machine eventually ran out of disk space.

**To Reproduce**
Unclear

**Expected behavior**
The compilation should not have wedged.

**Link**
https://my.papertrailapp.com/systems/ip-172-30-5-85/events?focus=1172219773141667845&q=Skipping%20temporary%20file%20clean%20up%20as%20compiler%20environment%20is%20busy&selected=1172219773141667845

**Additional context**
@apmorton has the affected machine isolated off for investigation.

**Comment by partouf** [comment]
Wasn't this sort of fixed?

**Comment by mattgodbolt** [comment]
I think so! Will close :) thanks for doing some issue gnoming :)
