### ISSUE TITLE
make fails on debian stable

### ISSUE THREAD

**Issue by django013** [mattgodbolt/compiler-explorer#188]
after installing the prerequesites make cyclically throws this error message:

/usr/local/src/gcc-explorer/app.js:64
var gitReleaseName = child_process.execSync('git rev-parse HEAD').toString().t
                                   ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/usr/local/src/gcc-explorer/app.js:64:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Program /usr/bin/nodejs ./app.js --language C++ exited with code 8

**Comment by mattgodbolt** [comment]
Thanks: seems I'm inadvertently using new node behaviour. I'm not sure when `execSync` was introduced into node. I'll see about alternatives and/or workarounds. For now you can try grabbing a more recent nodejs and then putting that in your path.

**Comment by 0x1100** [comment]
A quick and dirty workaround is to simply comment out the calls to `execSync`.

```diff
diff --git a/app.js b/app.js
index cafbf13..ceef712 100755
--- a/app.js
+++ b/app.js
@@ -60,7 +60,7 @@ var env = opts.env || ['dev'];
 var hostname = opts.host || os.hostname();
 var port = opts.port || 10240;
 var staticDir = opts.static || 'static';
-var gitReleaseName = child_process.execSync('git rev-parse HEAD').toString().trim();
+var gitReleaseName = ""//child_process.execSync('git rev-parse HEAD').toString().trim();
 
 var propHierarchy = _.flatten([
     'defaults',
diff --git a/lib/compile.js b/lib/compile.js
index 2330345..c85c284 100644
--- a/lib/compile.js
+++ b/lib/compile.js
@@ -197,7 +197,7 @@ Compile.prototype.runCompiler = function (compiler, options, inputFilename, need
 
 Compile.prototype.getMultiarch = function () {
     try {
-        var multi = child_process.execSync("gcc -print-multiarch").toString().trim();
+        var multi = ""//child_process.execSync("gcc -print-multiarch").toString().trim();
         if (multi) {
             logger.info("Multiarch: " + multi);
             this.multiarch = multi;
```

**Comment by bluehood** [comment]
I'm also affected.
The patch @0x1100 posted does not apply cleanly anymore (`lib/compile.js` is not there anymore).

This one seemed to solve for me:

```diff
diff --git a/app.js b/app.js
index 676677f..19f7f14 100755
--- a/app.js
+++ b/app.js
@@ -66,7 +66,7 @@ var hostname = opts.host;
 var port = opts.port || 10240;
 var staticDir = opts.static || 'static';
 var archivedVersions = opts.archivedVersions;
-var gitReleaseName = child_process.execSync('git rev-parse HEAD').toString().trim();
+var gitReleaseName = ""//child_process.execSync('git rev-parse HEAD').toString().trim();
 
 var propHierarchy = _.flatten([
     'defaults',
diff --git a/lib/compilation-env.js b/lib/compilation-env.js
index 29ca331..dfc575b 100644
--- a/lib/compilation-env.js
+++ b/lib/compilation-env.js
@@ -47,7 +47,7 @@ function CompilationEnvironment(gccProps, compilerProps) {
     this.compileQueue = new Queue(gccProps("maxConcurrentCompiles", 1), Infinity);
     this.multiarch = null;
     try {
-        var multi = child_process.execSync("gcc -print-multiarch").toString().trim();
+        var multi = ""//child_process.execSync("gcc -print-multiarch").toString().trim();
         if (multi) {
             logger.info("Multiarch: " + multi);
             this.multiarch = multi;
```

**Comment by mattgodbolt** [comment]
Thanks. I'd love to come up with a more lasting solution; but at some point I may wish to drop support for older node.js versions in order to use even more features anyway...

**Comment by mattgodbolt** [comment]
Since around befef987000243e3cd612b6342b4f1b0a115c3bc we now error if node isn't v8 or higher. This - while somewhat annoying for older debian/ubuntu users - means that the `make` process fails with a useful error if you have a version of `node` which doesn't work with CE.
