### ISSUE TITLE
[REQUEST] cc65 library support

### ISSUE THREAD

**Issue by bunder2015** [mattgodbolt/compiler-explorer#1886]
**Is your feature request related to a problem? Please describe.**
cc65 comes bundled with several libraries installed to `/usr/share/cc65/include`, but it is not possible to include them, `-I` returns a "bad option" error, `--include-dir` works but using `#include <nes.h>` for example still can't find the library file.

**Describe the solution you'd like**
could we please get access to the libraries in CE?

**Describe alternatives you've considered**
n/a

**Additional context**
great website, thanks for adding cc65 support.

**Comment by mattgodbolt** [comment]
Thanks: will be fixed when we next do a site update!

**Comment by bunder2015** [comment]
Looks good, thanks!
