### ISSUE TITLE
Limits to number of "copy compiler" you can have

### ISSUE THREAD

**Issue by Gabidal** [mattgodbolt/compiler-explorer#1894]
I think this screenshot can tell everything you need :)
![image](https://user-images.githubusercontent.com/41587318/77252374-2b737780-6c5c-11ea-9d70-815fbb286f90.png)

What i did was just spamming the "copy compiler" button until i got that mess.

The feature im refering to is some kind of limit to how many "copy compiler"'s you can have.

**Comment by apmorton** [comment]
Nothing we implement client side could effectively mitigate potential denial of service vectors. A malicious user could simply open multiple tabs to circumvent any limit, or more likely capture and replay valid web requests from a script to cut the web browser out of the equation entirely.

I don't believe we have ever experienced a malicious DoS, and in general I would say we are pretty low risk on that regard - there just isn't really much to be gained by bringing our site down.

If we were concerned we could implement server side rate limiting using Amazon's WAF offering, but until it's proven to be needed we would just be flushing money down the toilet.

**Comment by RabsRincon** [comment]
Hi! Thanks for your report, we really appreciate that you took the time to let us know about it, but as @apmorton said, it's very unlikely that we'd add a client-side solution for this, as it's a really low priority issue. - Also note that simply spamming the clone button does not do much by itself, as every subsequent compilation should hit the cache.
That said, we'd gladly accept any PR addressing this, for anyone interested. :)
