### ISSUE TITLE
[BUG] Compilation failed for armv7-a clang 9 with vst1q_f32_x4 intrinsics

### ISSUE THREAD

**Issue by jianliang79** [mattgodbolt/compiler-explorer#1906]
**Describe the bug**
    gotbolt will fail to compile code with vst1q_f32_x4 intrinsics for armv7-a clang 9
    If I remove vst1q_f32_x4 intrinsics build will succeed

**To Reproduce**
    To reproduce the issue, simply compile the following code for armv7-a clang 9:

```
#include <stddef.h>
#include <arm_neon.h>

void AddBias(float *dst, const float *bias, size_t area, size_t biasNumber)
{
    float32x4_t bias4;
    const float *biasZ = bias;
    const int groupCount = int(area / 4);
    const int tailCount = int(area & 3);
    for (int z = 0; z < int(biasNumber); ++z) {
        bias4 = vld1q_f32(biasZ);
        biasZ += 4;

        for (int i = 0; i < groupCount; ++i) {
            float32x4x4_t v = vld1q_f32_x4(dst);
            v.val[0] = vaddq_f32(v.val[0], bias4);
            v.val[1] = vaddq_f32(v.val[1], bias4);
            v.val[2] = vaddq_f32(v.val[2], bias4);
            v.val[3] = vaddq_f32(v.val[3], bias4);
            vst1q_f32_x4(dst, v);
            dst += 16;
        }

        for (int i = 0; i < tailCount; ++i) {
            const float32x4_t v = vld1q_f32(dst);
            vst1q_f32(dst, vaddq_f32(v, bias4));
            dst += 4;
        }
    }
}
```

**Expected behavior**
    Compilation succeeded

**Link**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Microsoft Edge (chromium based)
 - Version 80.0.361.109

**Additional context**

**Comment by jianliang79** [comment]
I should add that I build the code with -Oz option

**Comment by apmorton** [comment]
This seems like a compiler bug, not an issue with CE.

The compiler is segfaulting, and I can reproduce it locally without any sandboxing.
https://godbolt.org/z/6HpLm-

It happens on the trunk build for me as well.

**Comment by jianliang79** [comment]
Yes, I should be bug of clang
