### ISSUE TITLE
[BUG] nlhomann::json library glibc++ missing with Clang

### ISSUE THREAD

**Issue by mhammerc** [mattgodbolt/compiler-explorer#1909]
**Describe the bug**
When nlohmann::json is enabled, I can not successfully link (run binary enabled). I get this error:

    ./output.s: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./output.s)

It does happen only with Clang (tested with 10 and 9).

Compiling hello-world using Clang and no libraries works (only iostream).

It works with GCC (9.3 and 9.2).

I am not sure if I missed a configuration or if this is a bug. Assembler is generated fine.

**To Reproduce**
![image](https://user-images.githubusercontent.com/5982507/78673578-9f5f8200-78e2-11ea-885a-916e0df1b1eb.png)
![image](https://user-images.githubusercontent.com/5982507/78673598-a7b7bd00-78e2-11ea-9a91-5be28f217384.png)
![image](https://user-images.githubusercontent.com/5982507/78673623-b1412500-78e2-11ea-8588-a5fceaef127e.png)

**Expected behavior**
Links then run.

**Link**
https://godbolt.org/z/qRkxsP

If it is confirmed as a bug, and if you have no time, tell me a quick summary of how to fix it. I'll do it!

*Edit: as I said in the past, compiler-explorer is a very great tool. Thanks for the good work! That kind of tool really help to move humanity forward*

**Comment by apmorton** [comment]
closing as dup of #1780 

For now there is a workaround in that thread, example here: https://godbolt.org/z/s3ogpE
