### ISSUE TITLE
[BUG] clang-tools-extra tools not showing up in C

### ISSUE THREAD

**Issue by AaronBallman** [mattgodbolt/compiler-explorer#1911]
When you select C++ as the source language and Clang as the compiler, the `Add Tool` menu includes tools like clang-tidy, clang-format, and clang-query. However, when you select C as the source language and Clang as the compiler, these tools are not available under the `Add Tool` menu.

It would be useful to provide the tools in C mode as well, as all of them work in C mode.

**Comment by RabsRincon** [comment]
Thanks for the heads up and taking the time to report it to us! I've added all three you mentioned now and they'll show up on the next site update :)
