### ISSUE TITLE
Different result on my PC and on the website.

### ISSUE THREAD

**Issue by iddq** [mattgodbolt/compiler-explorer#1913]
**Describe the bug**
Different result on my PC and on the website.

**To Reproduce**
int main() {
    unsigned char a;
    unsigned short b;
    b = (a& 0xf0);
    b |= (unsigned short)(a& 0xf0);
    return 0;
}

COMPILER OPTION: -Wconversion

**Expected behavior**
gcc -otest test.c -Wconversion
test.c: In function ‘main’:
test.c:8:10: warning: conversion from ‘int’ to ‘short unsigned int’ may change value [-Wconversion]
     b |= (short unsigned int)(a& 0xf0);
          ^
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 

**Link**
https://godbolt.org/z/Lnkbcz

**Screenshots**

**Desktop (please complete the following information):**
Debian GNU/Linux 10

**Additional context**

**Comment by partouf** [comment]
I'm confused as to why your own compiler would give out this warning. Are you sure this is the same code?

**Comment by iddq** [comment]
Good question. This was the "original" code:

> int main() {
>     unsigned char a;
>     unsigned short b;
>     b = (a& 0xf0);
>     b |= (a& 0xf0);
>     return 0;
> }

gcc gives warning clang doesn't.

**Comment by partouf** [comment]
That warning would be expected with that code, yes. The OR acts differently from the assignment.

Why Clang doesn't give a warning, I'm not sure.

I don't think this is a bug either way.

**Comment by iddq** [comment]
Can you please try the first case on your PC? I've tested it on Debian and Ubuntu

**Comment by partouf** [comment]
On `gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008` I only get a warning if the cast to (unsigned short) doesn't happen. So same as on the godbolt.org
