### ISSUE TITLE
[BUG] Tools pane has an empty font size selector menu

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1914]
**Describe the bug**
The font size dropdown is empty

**To Reproduce**
Open a tool window. Click the font dropdown. See it's a weird zero-sized thing.

**Expected behavior**
A normal dropdown.

**Link**
https://godbolt.org/z/wLtahX

**Screenshots**
![Screenshot from 2020-04-11 17-51-49](https://user-images.githubusercontent.com/633973/79056547-35feac80-7c1d-11ea-93bd-178b563ce7d8.png)

**Comment by RabsRincon** [comment]
It was not empty, just not allowed to fully extend its height. Fixed now :)
