### ISSUE TITLE
[BUG] Undo rendering of raw instruction bytes & other data between instruction lines

### ISSUE THREAD

**Issue by eyalroz** [mattgodbolt/compiler-explorer#1918]
**Describe the bug**
At some point in recent months, the raw hexadecimal byte values of instructions began to show up between lines of assembly code in the compiler output panes. There are also additional lines of text, like the `std::ios::base::etc. etc.` in the example below.

**To Reproduce**
Just compile any program.

**Expected behavior**
Assembly instructions appear on consecutive lines with nothing but whitespace between lines.

**Screenshots**
![screen](https://user-images.githubusercontent.com/8672255/79126062-e39dc700-7da7-11ea-8ea3-2ff39ec7b565.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
It's distracting, breaks the visual sequence of lines, and can't even be changed with some preference. Please either put it on the side, or within the arrow-expandable box between lines, or at least make it default-invisible.

**Comment by RabsRincon** [comment]
Hi! Sorry that this is bothering you. What you're seeing is already turned off by default - You must have "Compile to binary" checked under the "Output" dropdown

**Comment by eyalroz** [comment]
@RabsRincon : Ah, I didn't realize that's what "compile to binary" does.
