### ISSUE TITLE
[REQUEST] Add support for ARM GCC 9

### ISSUE THREAD

**Issue by dingari** [mattgodbolt/compiler-explorer#1921]
Hi, thanks for the amazing work on CE!

[ARM GCC version 9](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) has been available since November 2019, but I don't see it listed in CE. It would be greatly appreciated to have it added.

**Comment by mattgodbolt** [comment]
Will push to the site shortly
