### ISSUE TITLE
[BUG] clang10/trunk weird <compare> behavior

### ISSUE THREAD

**Issue by libboze** [mattgodbolt/compiler-explorer#1922]
**Describe the bug**
https://godbolt.org/z/8toG8G

**Expected behavior**
I would expect that including compare makes the program compile.
It is possible this is a clang bug, but it would be pretty bizare that they have error msg reporting to include nonimplemented header, so please check.

Also I looked here, it looks like libc++ does contain the header:
https://releases.llvm.org/download.html

**Comment by apmorton** [comment]
This is all working as intended. Clang on linux uses libstdc++ by default and you can pass `-stdlib=libc++` to override this behavior.

https://godbolt.org/z/AJo55L

**Comment by libboze** [comment]
doh :) 
At least somebody googling for this before libstdc++ implements <compar> may find the explanation.
Thank you for a quick response.
