### ISSUE TITLE
[BUG] zapcc license has expired

### ISSUE THREAD

**Issue by danilaml** [mattgodbolt/compiler-explorer#1924]
**Describe the bug**
Just tried to compile some simple code on zapcc and got:
```
zapcc error: 

License for 'Matt Godbolt-Compiler Explorer' expired

Please visit http://zapcc.com to purchase zapcc.
```

**To Reproduce**
Choose zapcc compiler.

**Expected behavior**
The example compiles.

**Link**
https://godbolt.org/z/APGH3w

**Comment by mattgodbolt** [comment]
Thanks: I think zapcc is now "open source" so it seems like we need to rebuild it at the same version. https://github.com/yrnkrn/zapcc is the source by the look of it.

**Comment by mattgodbolt** [comment]
With a little help we've been able to keep the current compiler as-is and extend the license.
