### ISSUE TITLE
[BUG] clang installation missing omp.h

### ISSUE THREAD

**Issue by JimCownie** [mattgodbolt/compiler-explorer#1926]
The clang compilers all seem to be missing the omp.h header, even though OpenMP has been a standard part of clang and clang++ for a while now.

**To Reproduce**
https://godbolt.org/z/qfD-fi 
If you switch compiler to gcc or icc this code compiles fine.

**Expected behavior**
#include <omp.h> should work.

**Desktop (please complete the following information):**
Irrelevant...

**Additional context**

**Comment by apmorton** [comment]
closing as dup of #795 

For now you can use clang trunk with openmp
