### ISSUE TITLE
[REQUEST] Allow disabling auto-indent in the editor

### ISSUE THREAD

**Issue by fuzxxl** [mattgodbolt/compiler-explorer#1937]
**Is your feature request related to a problem? Please describe.**

When I hit enter on a line that is indented, the cursor starts with the same indent on the next line.  This is confusing and irritating but there doesn't seem to be any way to turn this behaviour off.

**Describe the solution you'd like**
Provide a switch to turn this behaviour off such that the cursor starts in the first column of a new line when you hit enter.

**Describe alternatives you've considered**
Disable this behaviour entirely.

**Additional context**
Many editors (including the one I use) don't behave the way the compiler explorer's editor does on line breaks, so it's really uncomfortable with respect to muscle memory having to avoid entering a tab on new line.

**Comment by mattgodbolt** [comment]
Wow: I though we had an option for this, but apparently not! Thanks for the suggestion, we'll see if it's an easy and quick add.

**Comment by fuzxxl** [comment]
Thanks!  Greatly appreciated.

**Comment by mattgodbolt** [comment]
Will be fixed in an upcoming site release (though annoyingly the editor we use needs a reload to notice the change; hopefully that's not enough of a problem!) Option will be in More->Settings when it's there (probably in the next few hours)

**Comment by fuzxxl** [comment]
Nice, thanks!
