### ISSUE TITLE
[BUG] Demangle C++20 spaceship operator

### ISSUE THREAD

**Issue by kosak** [mattgodbolt/compiler-explorer#1942]
Hello, it looks like Compiler Explorer doesn't yet know how to demangle the C++20 spaceship operator.

Repro: https://gcc.godbolt.org/z/B-D4EY

In the example, the call to the operator is rendered as `call    _ZNK3FoossERKS_`

rather than `call Foo::operator<=>(Foo const&) const`

**Comment by partouf** [comment]
It seems that the gcc trunk's c++filt (which we use for demangling) doesn't know it either.

I think the place to report this is at https://sourceware.org/bugzilla/buglist.cgi?component=binutils&product=binutils

**Comment by mattgodbolt** [comment]
We're currently using `c++filt` from the latest release of `bintuils` (2.34) - https://www.gnu.org/software/binutils/ 

Looking through the code commits there it seems no support is currently included. I'll file a bug there (as I have an account, and I think they aren't accepting new registrations).

**Comment by mattgodbolt** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=25876 filed!

**Comment by mattgodbolt** [comment]
Now re-filed as:https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94797

**Comment by kosak** [comment]
Thank you! Sorry for filing to the wrong place :-)

**Comment by mattgodbolt** [comment]
libiberty just been updated! https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=76458c912b0cdda59e094fa64b98aea9ffee214a

We'll need to point our c++filt at trunk to pick this up too (once merged etc)

**Comment by mattgodbolt** [comment]
```
Fixed.  Might take a while before it gets propagated into binutils.
```

is jakub@redhat.com's comment. Yay though!

**Comment by partouf** [comment]
It was included 6 days ago in the binutils master branch https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=56b1e56d2c2fa7611dc87192f26aac1da9fc63df

**Comment by apmorton** [comment]
this is now fixed on the live site
