### ISSUE TITLE
Point trunk c++filt at trunk

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1946]
See #1942 for why...as compilers start to implement `<=>` we'll need to use the latest demangler.

**Comment by partouf** [comment]
I think for this we need to build binutils from trunk as well instead of using the sources from FTP https://github.com/compiler-explorer/gcc-builder/blob/master/build/build.sh#L165

**Comment by partouf** [comment]
partouf@partouf-VB3:~/Documents/staging/bin$ ./c++filt _ZNK3FoossERKS_
Foo::operator<=>(Foo const&) const

With git clone --depth=1 https://sourceware.org/git/binutils-gdb.git
and basically the gcc-builder's build.sh

**Comment by partouf** [comment]
@apmorton has committed changes to build binutils trunk when gcc trunk builds. So when that is available we might be able to use that c++filt.
I was wondering however how we're going to handle the situation when the trunk fails to build or produces a bad build.

**Comment by apmorton** [comment]
I think the plan is to only use trunk c++filt for trunk compilers, so it should be a relative non issue.

Presumably by the time any stable compiler supports the spaceship operator there should be a new stable release of binutils to match.

For completeness sake:
If trunk fails to build nothing bad happens - the site just continues to use the last successful trunk build.

If trunk produces a botched build (for example if all binaries segfault or depend on a missing shared library) - the botched build will get installed and blow things up, but reverting to the previous nightly build is as simple as changing a symbolic link.

**Comment by partouf** [comment]
Makes sense, thanks.
So I think all there's left to do is to check the current snapshot and change the property file to reflect trunk c++filt for gccsnapshot and clangtrunk

**Comment by partouf** [comment]
Works on the admin node;
`May/05 16:46 admin-node~ $ /opt/compiler-explorer/gcc-snapshot/bin/c++filt _ZNK3FoossERKS_
Foo::operator<=>(Foo const&) const`
