### ISSUE TITLE
Restrict library versions to be visible only when using specific compilers

### ISSUE THREAD

**Issue by notfoundry** [mattgodbolt/compiler-explorer#1949]
**Is your feature request related to a problem? Please describe.**
I'm setting up a local compiler explorer instance for my company. We have several product versions, each of which ships with a compiler capable of targetting several architectures, and each of those architectures has their own set of static libraries available to them.

I am trying to create a workflow where a user can select compilers targetting different architectures from the compiler dropdown menu, and depending on which architecture their compiler is specified as targetting, different static library paths will be chosen for libraries they choose to add. My rationale for this is that it would be helpful to have an accurate representation of what the generated code looks like when compiling with the "Compile to Binary" option enabled, without making the user have to select their target architecture more than once.

**Describe the solution you'd like**
In a perfect world I'd like to have a configuration option exposed to limit the libraries available for a given compiler to a subset of the libraries defined under `libs`.

For instance, if a library `widget` existed with library versions `trunk-x86_64` and `trunk-aarch64` defined, a compiler `gcc_x86_64` could be restricted to only have the x86_64 version of the library visible through `compiler.gcc_x86_64.libs=widget.trunk-x86_64`.

**Describe alternatives you've considered**
Issue #1590 mentions that "we already [have] libraries per compiler", and it seems like some mechanism is in place to allow external compiler explorer instances to integrate their own compilers with unique library versions together (as seems to be the case with godbolt.ms from godbolt.org), but using a model like that in this case seems like it would lead to a full compiler explorer instance running per product version, per architecture, which in our case could mean hundreds of servers running. That seems very inefficient way to filter a list of file path strings. I admit that I haven't been able to figure out how that integration works yet by looking at the code, so I might be missing some straightforward solution to this.

One solution that comes to mind is making library versions for all architectures visible in the library version selection list, and relying on the user to choose the right library for their architecture of choice. This seems error-prone, since for every library a user might want to include, they would have to select the right choice from a (potentially quite long) list of similar-looking architectures, and possibly silently causing the wrong behaviour if they choose the wrong one.

Another solution I've considered is bumping up the level of abstraction, giving each product version its own compiler explorer instance and making each language in the instance qualified by the architecture its compilers will be targetting, which would allow the desired behaviour to exist (since libraries can be defined per-language). it might work t, but it doesn't seem like a good idea, since it's using compiler explorer features in ways that aren't really related to how they're supposed to work, and in this case it would make the compiler selection dropdown basically useless since there would only ever be one item available.

**Additional context**
If anyone has any suggestions about existing ways to solve this problem, I'm more than happy to hear them. I might be totally missing something in the CE codebase that supports this use case!

**Comment by partouf** [comment]
Interestingly enough we're actually working on supporting multiple architectures https://github.com/mattgodbolt/compiler-explorer/pull/1945 , but that's a little more complicated than your suggestion, I think.

I've definitely thought about having libraries per compiler, and with the PR you mentioned that was merged in mostly to support the MS compilers. But there's currently no mechanism to setup a library only for specific compilers.

For Tools we have an exclusion model, so whatever compiler tested incompatible with a tool we would say for example; tools.x86to6502.exclude=avr:rv32:arm:aarch:mips:msp:ppc:cl19:cl_new:djggp:riscv:wasm:frc2019:raspbian:arduino

But that's probably the opposite of what's useful.
So I'm thinking maybe a .compilers= property for libraries, that if it's not defined, it applies to all compilers, and if mentioned, it will load only for the compilers mentioned?

**Comment by partouf** [comment]
Now that I'm thinking about it, specifying the supported libraries on the compiler is probably a bad idea - as it would keep you from being able to say that none of the selected libraries are supported. I think.

**Comment by partouf** [comment]
Hi, so as you can see the changes have been merged into master. It's however not documented yet, but the implementation is mostly as you have suggested.

The property is called supportsLibraries and can be added to a compiler group or the compiler itself. It can all the library versions by just naming the library id, or you can do libid.versionid for a specific version.
The mentioned libraries can be separated with a :
