### ISSUE TITLE
Make command fails on OS X

### ISSUE THREAD

**Issue by afrighetto** [mattgodbolt/compiler-explorer#196]
When launching `make` on OS X 10.12 it falls into an endless loop:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 53.71.52.58:10240
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
Program /usr/local/bin/node ./app.js --language C++ exited with code 1
```

This happens while configuring the server to listen on port 10240, I guess you're supposing that `os.hostname()` returns a valid local DNS name (with `.local`suffix), but, especially on OS X, this is not actually mandatory to be.

**Comment by Arimish** [comment]
53

**Comment by Arimish** [comment]
53

**Comment by Arimish** [comment]
Bbb

**Comment by mattgodbolt** [comment]
Probably passing an empty string to 'listen' should do the trick.

**Comment by afrighetto** [comment]
Is there a particular reason to why not just bind the server to listen on the loopback address `127.0.0.1` instead of retrieving local hostname? Awesome project by the way.

**Comment by mattgodbolt** [comment]
If I bind to local host then it doesn't listen on an external interface; so only local connections work. Obviously in some cases (eg GCC.godbolt.org) it needs to allow external connections. Passing an empty string seems to bind to INADDR_ANY which seems to be what we want.

**Comment by mattgodbolt** [comment]
(Thanks for your kind words about the project btw!)

**Comment by afrighetto** [comment]
That's true. Then yes, should make sense binding it to all interfaces.

**Comment by unjello** [comment]
@afrighetto tried to reproduce this, on 10.12.6, but no luck. Tried with hostname set to `test`, `test.local`, ` ` (space) and `invalid.com`. I don't think there's a way to set it to empty, as `sysctl_io_string` returns `EPERM` if string has length of `0`. In all cases, the latest `master` works.

**Comment by mattgodbolt** [comment]
Thanks @unjello for looking in to this! I don't have a Mac so this kind of thing gets broken (and inadvertantly fixed) all the time :) I suspect this has gone away but let's hope @afrighetto can confirm.
