### ISSUE TITLE
[BUG] ARM gcc 9.2.1 disappeared from compiler list

### ISSUE THREAD

**Issue by timblakely** [mattgodbolt/compiler-explorer#1964]
Looks like the ARM gcc 9.2.1 compiler that was available yesterday is no longer. Was the removal intentional?

[This link](https://godbolt.org/z/RiY7on) pointed to ARM gcc 9.2.1 yesterday, but now redirects to ARM gcc 4.5.4 with the same content.

**Comment by partouf** [comment]
Hi, Sorry! We've been having some issues with the compiler installations. I am working on fixing this arm install. Thanks for the heads up!

**Comment by timblakely** [comment]
No worries! Looks like it's back now, much appreciated!
