### ISSUE TITLE
Show output of running command

### ISSUE THREAD

**Issue by luxe** [mattgodbolt/compiler-explorer#198]
Is it possible to see the actual output from a program that prints to stdout?  
When testing UB it would be helpful to see if the output changes between optimizations and compilers/versions.   

I'm not sure if compiler explorer even has an environment to run binaries.  I'm assuming it only compiles.  
I would jump over to ideone, but their compiler is not as up-to-date.

**Comment by mattgodbolt** [comment]
It is not possible; no. Many times I don't even generate the final binary,
so would have nothing to run. It's a commonly-asked feature though; so will
leave this bug open.

**Comment by RabsRincon** [comment]
This is now possible! https://godbolt.org/z/df8vWL
We will be improving the feature of the coming weeks, but it's finally here!

**Comment by Ma-XX-oN** [comment]
Main issue is how do I get this pane up?  Not intuitive.

**Comment by apmorton** [comment]
There are some UX improvements on the way, but for now click the `./a.out` button in the compiler window, and then expand the compiler output window (where the compiler warnings and errors normally appear).

**Comment by pkeir** [comment]
Did the GUI change? I don't see the `./a.out` button.

**Comment by partouf** [comment]
> Did the GUI change? I don't see the `./a.out` button.

It's now in the Output menu, called "Run the compiled output".
And if you click on Add new -> Executor from this, you can also pass arguments and stdin to your program.
