### ISSUE TITLE
PowerPC64 and 64LE support

### ISSUE THREAD

**Issue by ajdlinux** [mattgodbolt/compiler-explorer#205]
Would be very nice to get some 64-bit PPC compilers - both big and little endian. ppc64le is the primary target of all of IBM's POWER8/POWER9 Linux work these days.

**Comment by androm3da** [comment]
`ellcc` could cover this and several other targets.  See http://ellcc.org/

**Comment by ajdlinux** [comment]
@androm3da thanks, never heard of `ellcc`! What exactly are the differences between ellcc and clang? I note that the list of targets on the website only lists ppc32, but it looks like there are release tarballs for ppc64 and ppc64le.

`gcc` and `clang` can also target ppc64 and ppc64le.

**Comment by mattgodbolt** [comment]
It's pretty easy to write PRs to add new compilers: https://github.com/mattgodbolt/gcc-explorer-image/pull/7 for example installed the LDC compilers, and then a patch to add it to `etc/config/*.properties` is all that's needed.

**Comment by ajdlinux** [comment]
I'll have a look at it soon, thanks!

**Comment by ellcc** [comment]
Hi,
Thanks for adding ellcc to godbolt.org. One minor nit: The pull down menu calls it elcc.
You can compile for  ppc64 with "-target ppc64-linux"  and ppc64le with "-target ppc64el-linux".

**Comment by ajdlinux** [comment]
I'd still like to get gcc for ppc64, will try and submit a PR shortly

**Comment by haneefmubarak** [comment]
@ajdlinux are you still looking at doing that PR or is it okay if I have a crack at it?

**Comment by munroesj** [comment]
The latest stable GCC  and GLIBC runtime is always available from the IBM Advance Toolchain for Linux on Power (AT for short). This all Open Source and free to download.

https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W51a7ffcf4dfd_4b40_9d82_446ebc23c550/page/IBM%20Advance%20Toolchain%20for%20PowerLinux%20Documentation

**Comment by mattgodbolt** [comment]
Thanks to @grooverdan we now have ppc64le 6.3.0 on the live site. I have little or no experience with powerpc and its various flavours, so am happy to take advice on how to name them on the site and which ones are required. Dan's change only seemed to cover the LE variant, so that's the one I've added.

**Comment by munroesj** [comment]
On Fri, 2017-05-19 at 08:58 -0700, Matt Godbolt wrote:
> Thanks to @grooverdan we now have ppc64le 6.3.0 on the live site. I
> have little or no experience with powerpc and its various flavours, so
> am happy to take advice on how to name them on the site and which ones
> are required. Dan's change only seemed to cover the LE variant, so
> that's the one I've added.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
I really would prefer that you use exactly the IBM-branch we use for AT
and the configuration options that we use the built AT.

This it from the team that enables / contributes Linux on Power in the
open source communities (include GCC). So we put a lot of care into
keeping the public tree updated and insuring that it is built properly.

**Comment by mattgodbolt** [comment]
I have no strong opinions: I can put both on (labeled as such). I don't have very much time to devote to adding new compilers, which is why if someone gives me a PR (as @grooverdan did) I can merge and update the site, but I can't invest too much time on novel work.

**Comment by grooverdan** [comment]
Ack. Will look at https://gcc.gnu.org/viewcvs/gcc/branches/ibm/?dir_pagestart=25 for the GCC 6 an 7 branches and get the naming right. Will also look at ppc64 (big endian) know that all the desired outcomes are described.

I might even get to looking at clang too and a rust cross-compiler.

**Comment by partouf** [comment]
For C and C++, a couple of Power PC compilers have been added by @grooverdan and others, so I think we can finally close this issue. Thanks everyone!
