### ISSUE TITLE
error: unable to rename temporary

### ISSUE THREAD

**Issue by datosh** [mattgodbolt/compiler-explorer#212]
Hey,

I just wrote this snippet [1]. And after playing with the implementation for a bit I got the following error in my clang-3.9 window: 

error: unable to rename temporary '/tmp/gcc-explorer-compiler1161122-70-pn3wry/output.s-8e27a20c' to output file '/tmp/gcc-explorer-compiler1161122-70-pn3wry/output.s': 'No such file or directory'
1 error generated.
Compiler exited with result code 1

I think there is some server side error? As soon as I make the smallest change to the program it compiles again, but when I undo this change and restore it to the original state I get the same error.
Compilation in the gcc window works like a charm. 

Can somebody verify the error using my link? 

[1] https://godbolt.org/g/XMjSSq

**Comment by mattgodbolt** [comment]
There's heavy caching on my side, so once it had the error it would cache it. I'll take a look, thanks . I just bounced the site and your link now looks, but I'll see if I can find anything in the logs.

**Comment by datosh** [comment]
Sure. I just bounced the site as well and everything works. 
Hit me up if you need more information/help from my side.

**Comment by mattgodbolt** [comment]
I cant see what happened in this case: if it happens again can you paste a bunch of the log and/or run with `make EXTRA_FLAGS='--debug'` and see if that turns up anything interesting?

Thanks!

**Comment by datosh** [comment]
Sure will do. But I do use the compiler explorer quite often and never had a problem before. Maybe someone else will encounter this error and find this post.

**Comment by mattgodbolt** [comment]
Thanks. I've had a similar thing happen once (#226) and I wonder if it's a race between the "temporary file cleanup" and the compiler.

**Comment by maqui7295** [comment]
I currently have a similar issue on windows while trying to use clang. Gcc and Msvc works well
