### ISSUE TITLE
On Mobile Safari (i.e. iPad), it's possible to close the output tab and lose the ability to open it again

### ISSUE THREAD

**Issue by learnopengles** [mattgodbolt/compiler-explorer#217]
Hi,

I noticed that on the iPad in Safari, it's possible to close the output tab, and because of the way that rust.godbolt.org is caching state, it's subsequently impossible to restore the tab, even after refreshing the page.

**Comment by mattgodbolt** [comment]
Thanks for the bug report. A new output window *ought* to open if you click the far right icon on the editor pane (the bar with the up arrow above it). There may be other issues though, touch support isn't all that great (see #176)

**Comment by learnopengles** [comment]
Hi Matt, on desktop that works but on the iPad that button doesn't do anything most of the time.

**Comment by mattgodbolt** [comment]
That's super weird. I don't know what might be going on: I may need a mobile expert (and/or to get deepstreamIO/golden-layout#166 or deepstreamIO/golden-layout#148 fixed too)

**Comment by mattgodbolt** [comment]
As a workaround: If there's a way to clear local storage for a single site on iPads, give that a go. I suspect not though

**Comment by mattgodbolt** [comment]
...or maybe try following a link like this: https://godbolt.org/g/5pZN98 which will hopefully reset it

**Comment by mattgodbolt** [comment]
Thanks; I'll see what I can change on my side. A UI reset seems reasonable.

**Comment by mattgodbolt** [comment]
There's now a UI reset in "Help".
