### ISSUE TITLE
History of editors

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#220]
As per @CppChedy on Twitter nice to have history of edits. Then clicking on CE links doesn't lose work in progress edits

**Comment by mattgodbolt** [comment]
This is another important-to-fix thing, and it's in-progress, but...it shouldn't hold up the monaco release.

**Comment by partouf** [comment]
What if we save a top 50 unique states in local storage, and offer a way to select from the list? I don't know how performant it is to hash and save state every change, but if we do it during the compilation it shouldn't pose much issues i think?

**Comment by mattgodbolt** [comment]
I think that would be great. I can't imagine the performance is too bad :) The trick will be how to present the popup list!

**Comment by partouf** [comment]
This is now live with https://github.com/mattgodbolt/compiler-explorer/pull/1735
