### ISSUE TITLE
Add support for selecting OS.

### ISSUE THREAD

**Issue by AraHaan** [mattgodbolt/compiler-explorer#222]
It would be nice if someone could select between linux and OSX for building. I know of some people who not only target linux but also for OSX with the same code and it would be nice what the assembly language is generated on an OSX compiler (being the OSX gcc or clang version). And yes the OSX supports gcc and clang.

**Comment by mattgodbolt** [comment]
Hi: thanks for your suggestion.  Can you give an example where OSX code generation differs from Linux? As best I can tell they use the same ABI and so produce identical results.

Having an OSX version is extremely problematic as, as far as I know, there's no virtualised support for OSX and it would require buying an Apple server somewhere outside of the AWS environment where Compilex Explorer runs.

**Comment by mattgodbolt** [comment]
I don't think I can do this: there's no way I can run an OSX service unfortunately.

If OSX support is useful for you, it's pretty straightforward to run a local Compiler Explorer on your own setup. I'd be happy to help you set it up if so.
