### ISSUE TITLE
Show an error message on invalid URLs

### ISSUE THREAD

**Issue by MatzeB** [mattgodbolt/compiler-explorer#223]
I just had an issue where an E-Mail client (or bugzilla) messed up a link to the compiler explorer which was supposed to contain sourcecode. It seems compiler-explorer just shows you whatever it displayed for you last time if it encounters and invalid link. This can be very confusing when the link looks mostly fine.

It would be nice if it could give you any indication that you used an invalid link.

Example: Go to https://godbolt.org/#z:INVALID
Expected behaviour: Some indication that the link is actually invalid

**Comment by mattgodbolt** [comment]
Great idea, thanks
