### ISSUE TITLE
How to run it locally

### ISSUE THREAD

**Issue by Vm900** [mattgodbolt/compiler-explorer#236]
Hi folks,
I ran make and everything ran well.Now how do i run it.
Newbie here,so please be gentle
Thanks

**Comment by mattgodbolt** [comment]
If you ran make then you should see some output which ends with something like "Running on http://localhost:10240"

Just visit http://localhost:10240 in your browser.

**Comment by mattgodbolt** [comment]
Closing - but please feel free to reply here if you have further questions or encounter any problems!

**Comment by Vm900** [comment]
Thanks matt i finally got it to work.Good day
