### ISSUE TITLE
CL needs unused function stripping

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#237]
Consider: https://godbolt.org/g/XNvVyg - lots of `EXTRN` and unused code is generated. 

@AndrewPardoe has some perl code that will help at: https://gist.github.com/AndrewPardoe/4f6770fee4853ccffb792e8f3e7951f1

**Comment by partouf** [comment]
Hey this is actually fixed the thing that @ubsan wrote for VC that evolved into the lib.f button. Just leaves some data, but all functions are eliminated. So I think we can close this old thing. ^^
