### ISSUE TITLE
XLC

### ISSUE THREAD

**Issue by chadbrewbaker** [mattgodbolt/compiler-explorer#240]
I'm interested in adding support for the XLC community Docker container.
https://github.com/IBM/xlc-community-edition-dockerfile/blob/master/LICENSE

Guessing IBM would look down on digging the XLC toolchain out of the container. That means standing up the container and shelling into it for compiles. Does this sound reasonable?

**Comment by chadbrewbaker** [comment]
Option 1): Modify the container so you can
~~~bash
docker exec -it <containerIdOrName> bash
~~~ 

Option 2): Stand up a simple server inside and serve requests over a port.

**Comment by mattgodbolt** [comment]
Hi ; thanks for this!

Ideally just having the executable is best. Compiler Ezplorer is already a mess of docker containers and maintaining it all is a huge burden. Running docker images from within other docker containers is pesky too (though I do have some nascent plans to do so for other reasons).

Recently I moved away from docker containers holding the compilers to having them all (read only) on an NFS mount. This makes life so much easier and makes site updates much quicker; 30+ GB of compilers being built into multiple containers is not fun.

Is there an alternative? If there's a Linux binary, just installing it would be a considerably easier. This works for almost all compilers - windows ones obviously being more troublesome.

All the scripts and docker config that lie behind CE are in https://github.com/mattgodbolt/compiler-explorer-image - in particular if you take a look at changes like https://github.com/mattgodbolt/compiler-explorer-image/commit/61c8de8019422ec48c2521b8b62311cb59421c2d which show how a PR brought in a new compiler.  I appreciate the process is not perfect but if it can work this way then it'd be much easier to integrate.

**Comment by mattgodbolt** [comment]
Worth noting though if all else fails 2) is an option: I already proxy a bunch of compiles through from the Ubuntu 16.04 instance to a 14.04 instance which runs some compilers I couldn't get working on 1604.

Also some background on how it became to be so: http://xania.org/201609/how-compiler-explorer-runs-on-amazon

**Comment by haneefmubarak** [comment]
I did a little digging - it appears that the dockerfile just fetches and installs the Community Edition of the XL Compiler Suite, which is nice, because we can actually just get a copy of that over apt and it's completely free:

 > XL C/C++ Community Edition and XL Fortran Community Edition are unlimited license, no-charge, fully functional products and do not include official IBM support.

That being said, the community edition only runs on little-endian 64-bit POWER Linux based systems (`ppc64le`; ie: Ubuntu POWER, RedHat POWER, or SUSE POWER). Unless anyone has access to either a POWER8 (or higher, seeing as that's a listed minimum system requirement) system/reasonably fast emulator, I unfortunately don't see any way that we could use the Community Edition.

**Comment by chadbrewbaker** [comment]
https://www.ibm.com/cloud-computing/bluemix/power-servers ...

**Comment by haneefmubarak** [comment]
Yeah... That might be a touch pricey to add a single compiler...

I did however stumble upon a possible solution: IBM actually has a free POWER8 simulator than runs on x86_64 Ubuntu and RedHat: 

> https://www14.software.ibm.com/webapp/set2/sas/f/pwrfs/pwrfsdownload.html

I'll look further into it, but I expect that even if this works out, it'll be on the slow side of things (and use up a lot of processing power in the cloud).

**Comment by trudeaun** [comment]
I see that gcc POWER compilers have been added to Compiler Explorer already. Do you know how the POWER hardware was obtained to run gcc? Can that hardware be reused to run XLC as well?

**Comment by trudeaun** [comment]
Thanks! Unfortunately, XL does not allow for cross-compilation, so you're right that you'll need access to some POWER hardware to add XL. 

IBM has a [list of some options for obtaining POWER hardware](https://developer.ibm.com/linuxonpower/cloud-resources/). I'm following up internally to see which program makes the most sense to try and request access to, but you might consider obtaining from the Power Development Cloud, Oregon State University, Unicamp MiniCloud, or Brno University of Technology listed there. I'll get back to you when I know more.

**Comment by mattgodbolt** [comment]
Thanks @trudeaun - I see the request on my behalf! I appreciate you moving this forward. Having not cross-compiler is a serious limitation. We've been working for years on hacking in just support for Windows and we're still trying to get it right: and that mostly runs the same code.

Compiler Explorer does support "shelling out" to another instance of Compiler Explorer running elsewhere. This is how we're looking to do proper windows support. However, it's really troublesome:

* It's yet another set of machines to update/manage/run/administrate/secure using a different system. The services I run are scalable and in AWS and so easy(ish) to take care of.
* It's another machine that needs to have SSL certificates created and looked after (though I can possibly use my wildcard cert,), and if others have access to it, then I need to be sure it matches the privacy policy and requirements I need to ensure user (and my own!) data is not leaked.

That said: I'm willing to try but you'll have to realise this is an awful lot of effort and administration for a very niche market. I've managed to avoid the Windows stuff for many years (with a terrible WINE stopgap solution), and you can imagine how many more requests I get for Microsoft Compiler support :)

**Comment by trudeaun** [comment]
@mattgodbolt Sorry to hear about the bad experience on the Windows side, and I completely understand that it would be a large effort to get XL added. We appreciate your consideration, and if you do decide to request POWER hardware in the future, you now have the email from IBM explaining how to get it. Good luck and let me know if I can help with anything. I'll keep you posted if XL ever offers support for cross-compilation too.

**Comment by mattgodbolt** [comment]
Thanks all. Unless someone has a burning desire to help out, I am going to close this issue. Running on third-party servers on an unfamiliar architecture and OS is not something we have bandwidth for. In the case of MS's Windows support, it is proving tricky to manage, too.

If the POWER folks want to give this a go, they're welcome to stand up an instance and (with our help) get it running, then we can consider connecting the sites like we do with the Windows stuff, but only if they'll take on the cost and continuing maintenance of the site.
