### ISSUE TITLE
Better support for LLVM IR

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#241]
Colourisation at least

**Comment by chadbrewbaker** [comment]
Linguist is the library usually use, https://github.com/github/linguist/blob/master/grammars.yml#L466

**Comment by mattgodbolt** [comment]
The Monaco syntax highlighting library is pretty straightforward (https://microsoft.github.io/monaco-editor/monarch.html)

**Comment by mattgodbolt** [comment]
Closed in favour of #288
