### ISSUE TITLE
clang 3.3 and earlier fail to run with an "unsupported option" error

### ISSUE THREAD

**Issue by alexbock** [mattgodbolt/compiler-explorer#242]
When using `x86-64 clang 3.3` or earlier, nothing will compile and the output window says:

```
clang: error: unsupported option '--gcc-toolchain=/opt/compiler-explorer/gcc-6.2.0'
Compiler exited with result code 1
```

It looks 40a20a1 was intended to fix something similar. I think the outstanding reference in `etc/config/c++.amazon1204.properties` line 26 is probably the problem.

**Comment by alexbock** [comment]
It looks 40a20a1335 was intended to fix this.

**Comment by mattgodbolt** [comment]
Yes...the I reintroduced it as part of a refactor. Thanks for reporting, I hadn't spied it myself (embarrassingly!) Even though I have some tests for this exact problem...
