### ISSUE TITLE
Rust compiler-explorer produce error with -g or no output with -O

### ISSUE THREAD

**Issue by ludwigpacifici** [mattgodbolt/compiler-explorer#248]
When I use the below valid code written in Rust, I see assembly generated - it's all good. I use the default GUI options of `compiler-explorer` and no compiler options. However, if I use the compiler option:

 * `-g`, the result is `<Compilation failed>`.
 * `-O`, the result is 7 empty lines.

In both cases, I expect to see assembly code.

```
fn main() {
    let mut sum: u32 = 0;
    let (from, to) = (0, 500);

    for i in from..to {
        sum += i;
    }

    println!("{}", sum) // 124750
}
```
https://godbolt.org/g/QgcCMQ

**Comment by mattgodbolt** [comment]
WIth `-g` the error is:
```
error: -g and -C debuginfo both provided
Compiler exited with result code 101
```

(CE already passes `-debuginfo` to get the line colouring)

CE compiles rust as a crate; so with optimizations on, any non-public symbols are dropped. Make your function `pub fn main` as a workaround for now: https://godbolt.org/g/OXJGA9

**Comment by ludwigpacifici** [comment]
> (CE already passes -debuginfo to get the line colouring)

Is it not miss leading for the user? Naively, I though the compiler options field is empty, so no option are provided: equivalent to run the command `rustc --emit=asm test.rs`. Do you think it will make sens to enable coloring only if `-g` is provided?

To continue about the defaulted `-g`, the produced asm code is very different between (in term of line number) between `-O` and `-O -g`. I am not expert enough in asm, but are the optimizations the same in both cases? In my example, it seems correct, since the `for` loop is computed a compile time: `movq	$124750, (%rsp)`.

**Comment by mattgodbolt** [comment]
I understand why it might be confusing! However several options are provided to the compiler:

* The `-g` is required to get the colourisation, so I auto-provide it (well, actually `-C debuglevel=1`). I subsequently learnt that for no good reason that I can see, asking rust to generate debug info causes code generation differences (see #79).
* `--emit=asm` is supplied unless the "binary mode" option is selected.
* `-o <filename>` is supplied to set the output to a temporary file.
* `--crate-type rlib` is provided. This is the best we could come up with to solve #139 but I confess I don't fully understand it.

Further thoughts welcomed, but my personal thoughts are CE should work with all its features "out of the box", and if those features need compiler options then it should provide them. I agree though that when this causes compilation differences, it becomes more of a problem. I've been hoping the rust folks might fix the underlying problem.

**Comment by ludwigpacifici** [comment]
Do you think showing this information on the web page (rust.godbolt.org) would give more transparency? Or show a small line with the actual run command. Example:

<img src="https://cloud.githubusercontent.com/assets/923945/22544871/83f43dc2-e92e-11e6-8baa-d90f05137971.png" width="480">

However, I have the feeling the UI is generic across supported compilers.

I would be happy to give a hand, on the Rust side. However, I very little knowledge in JavaScript (I guess this the main language in the project). Tell me if you think there are easy tasks :-)

**Comment by mattgodbolt** [comment]
That seems like a nice idea: thanks! Indeed, JS is pretty much the only language in this. The only rust is in the demangler

**Comment by ludwigpacifici** [comment]
I forked your repository. I'll try to add a bottom line with the actual command run. I let you know when I have some results.

**Comment by ludwigpacifici** [comment]
I played with the code. In the bottom line, I was able to display compiler options. 

I continued to think on how to display nicely the required options to give more transparency. Instead of using the bottom line, would it be better to put them as the picture below:

![tmp9](https://cloud.githubusercontent.com/assets/923945/22643589/18914332-ec57-11e6-8b3b-22a1912f5201.png)

To give a better user experience, this text could be replaced by "..." to hide options on a click. A tool tip can be displayed to explain these options are required. Normally, it should be generic for all compilers.

What do you think?

**Comment by mattgodbolt** [comment]
That sounds like an idea! My only concern is it taking up too much screen space. I'll have a think (and would accept patches too) - thanks!

**Comment by ludwigpacifici** [comment]
I agree. To save place on screen, these hard coded options required for compiler-explorer could be toggled between a "..." and the hidden options.

An ASCII drawing of the compiler and its options. Default view will hide the hidden options. Example with rust:

```
|------------------------------------------|
| rustc 1.15.1 | ... | compiler options... |
|------------------------------------------|
|                 <asm code>               |
|------------------------------------------|
```

If I clic on "...", the compiler bar would become for example a read only text showing hidden options:

```
|------------------------------------------------------------------------------------|
| rustc 1.15.1 | -g --emit=asm --crate-type rlib -o <filename> | compiler options... |
|------------------------------------------------------------------------------------|
|                                     <asm code>                                     |
|------------------------------------------------------------------------------------|
```

Tell me if my ASCII drawings are not clear enough.

**Comment by mattgodbolt** [comment]
That's very clear, good thought (and nice use of ASCII art!)

**Comment by mattgodbolt** [comment]
It's not _quite_ what you wanted but if you click on the compilation results indicator (between the compiler selection dropdown and the flags) you see all the options we pass. I hope this is good enough: If you feel strongly that this doesn't quite cover your idea then please reply and we'll consider alternatives. Thanks!
