### ISSUE TITLE
Add option to compare two C sources with the *same* compiler

### ISSUE THREAD

**Issue by tangentsoft** [mattgodbolt/compiler-explorer#249]
You currently have a feature that lets you take a single C source and compile it on two different compilers, with the output side-by-side.

I want the inverse of that feature: I want to take two different C sources, compile each with the *same* compiler, and see the results so that I can see how changing the C source affects the output without repeatedly rebuilding it and trying to remember across each rebuild what the assembly looked like on the prior build.

The motivating example is comparing how the normal C postincrement operator compares to atomic increment extensions like `__sync_add_and_fetch(&num, 1);`. For ARM, a one-line change of that line to `++num` turns into a many-line diff, difficult to remember.

**Comment by fenollp** [comment]
How about opening a second browser tab?

**Comment by tangentsoft** [comment]
Sure. This just seems like an obvious extension to existing functionality.

**Comment by mattgodbolt** [comment]
Hi! Great idea. This is already captured (moslty) in #171 

As a workaround I do something like this: https://godbolt.org/g/hyaAOl

**Comment by mark-99** [comment]
What would make this better than multiple browser tabs or toggling a #define would be to have a diff view. That is, 2 editor windows with almost the same code, compile both and show diff of the output.

**Comment by mattgodbolt** [comment]
Definitely yes! It's on the to-do list :)

**Comment by mattgodbolt** [comment]
I'm pretty happy with the current beta setup. Feel free to comment if you disagree here Closing for now.
