### ISSUE TITLE
add button for source upload

### ISSUE THREAD

**Issue by bluehood** [mattgodbolt/compiler-explorer#255]
Maybe I just overlooked something obvious, but I could not find a simple way to upload my own source file, even hosting the compiler explorer on my laptop.

What does work is putting my own file inside the `examples` directory using the same name as one of the examples. Then the `Load text from an example` button picks up my file :)

**Comment by mattgodbolt** [comment]
Good point! I use the clipboard myself and just paste in, but upload makes sense too. Thanks!

**Comment by bluehood** [comment]
Unfortunately my clipboard could not handle the 1000+ lines that I wanted to paste in today :sweat_smile: 

And since we are here, thank you so much for your work!

**Comment by mattgodbolt** [comment]
You're so welcome! 1000+ lines will work OK in a local CE instance, but quite possibly may fall foul of the compile time limit in the public instance (though I may increase that now I have more power available).
