### ISSUE TITLE
ctrl-f search friendly compiler output

### ISSUE THREAD

**Issue by bluehood** [mattgodbolt/compiler-explorer#256]
When the compiler output is longer than a few pages, a `ctrl-f` search is not able to parse it all on google chrome nor on firefox, meaning there is no way to jump to the interesting portions of the assembly code.

I would help out but I really wouldn't know where to start :)

**Comment by mattgodbolt** [comment]
This is a "feature" of CodeMirror, the editor I use. I'm moving towards using a different editor (Monaco), so this may become a moot point.

If you still fancy a look yourself, the `CodeMirror` object is initialised with some config (see https://codemirror.net/doc/manual.html#config ) - one of the config options might control this. I recall seeing something once but now for the life of me can't find it!

**Comment by bluehood** [comment]
got it:

> viewportMargin: integer
Specifies the amount of lines that are rendered above and below the part of the document that's currently scrolled into view. This affects the amount of updates needed when scrolling, and the amount of work that such an update does. You should usually leave it at its default, 10. Can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents.

where should I look for changing the configuration of the `CodeMirror` object? Could I do it from chrome's debugging console?

**Comment by mattgodbolt** [comment]
I don't think you can change things from the debug console, but editing: https://github.com/mattgodbolt/compiler-explorer/blob/master/static/compiler.js#L96 gives you some scope to do this :)

**Comment by mattgodbolt** [comment]
It could also be that I'm not using CodeMirror properly: perhaps it provides its own "find" dialog (I know Monaco does)...

You could also try checking out the "monaco" branch and see if that works better for you :)

**Comment by bluehood** [comment]
to add some context, my output is about 18k lines even with unused labels and assembly directives hidden (input is ~1k lines, c++ templates ftw).

- setting the `viewportMargin` option high enough (i.e. equal to `Infinity`) actually solves the `ctrl-f` search problem with `CodeMirror`: I can search the whole output, at the cost of an unbearably slow scrolling
- it seems `CodeMirror` would provide proper search and replace as an addon ([here](https://codemirror.net/doc/manual.html#addon_search))
- trying out the monaco branch now, ctrl-f works out of the box, smooth experience so far

**Comment by mattgodbolt** [comment]
I'm now decided on going the Monaco route: I think this is closed. Feel free to reopen if you feel the `master` branch doesn't appropriately fix this issue.
