### ISSUE TITLE
There's no link from title page of godbolt.org to go.godbolt.org, rust.godbolt.org, ...

### ISSUE THREAD

**Issue by atomsymbol** [mattgodbolt/compiler-explorer#259]
The first line of https://godbolt.org/ reads:

> Compiler Explorer ‐ C++

HTML links to D-, Go- and Rust-specific pages are missing.

**Comment by mattgodbolt** [comment]
Great idea. In the medium-long term I'll probably make it just one "compiler explorer" instead of N for N languages too.

**Comment by mattgodbolt** [comment]
Thanks to @RabsRincon this is now on the beta site
