### ISSUE TITLE
Command line tool variant

### ISSUE THREAD

**Issue by habemus-papadum** [mattgodbolt/compiler-explorer#263]
Hi -- thanks so much for your contributions!

Do you have any interest in the following functionality: creating a command line tool variant of compiler explorer that would take source + compiler options + compiler spec and produce a self contained (static) html that shows thew source + disassembly views sans any support for recompiling or making changes in the editor.  

I was thinking of integrating this into my build process (cmake) so that I could fold some results into the documentation of a library.

It looks as if some restructuring of the current code would be required -- nothing very complicated but still requiring making at least a handful of concrete decisions. I was going to just fork and refactor+hack, but if this idea seems appealing then perhaps we could try coordinating?  

cheers, nehal

**Comment by mattgodbolt** [comment]
I don't have a specific need for this myself, but the [API](https://github.com/mattgodbolt/compiler-explorer/#restful-api) might make it fairly easy to implement.

**Comment by habemus-papadum** [comment]
Thanks -- the api definitely seems like the path of least resistance.  When/if I implement my variant I'll follow up to see if it might be of use to you or others.  cheers
