### ISSUE TITLE
Tooltips to show hex values of decimal constants

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#27]
via Dennis Lubert: "I wouldn't be myself, if I could not find things to enhance even
more... ;) In one of my examples, I was using hex literals, but of
course the asm output was using decimals. While clang is so nice to show
it in hex, gcc isnt. Would it be hard to make a tooltip for the decimal
literals, showing their value in hex too?"

**Comment by mattgodbolt** [comment]
And (via Leon de Boer) the reverse, particular for ARM. That is, hex comments should show decimal values.

**Comment by haneefmubarak** [comment]
I think what might work well would be to show a tooltip for any stored numeric constant that showed `signed dec/unsigned dec/hex/bin` and also, for 32/64 bit values, showed the interpreted floating point value. That would basically work universally across most modern archs and should cover basically every common usecase.

All of that should be straightforward to implement in JS - I have some related code from something else a while back that I'd be happy to modify to convert from any string containing an integer (8/16/32/64/128/256 - workarounds were needed above 64 bit) to the aforementioned.
