### ISSUE TITLE
Add cool forks of clang

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#273]

**Comment by mattgodbolt** [comment]
On cppchat a fork of clang with reflection was mentioned.

**Comment by mattgodbolt** [comment]
via @rollbear: "Here's a suggestion for an experimental clang branch, should you want to support it.
https://github.com/matus-chochlik/clang/tree/reflexpr" - " Get in touch if you decide to build it. There's a slight bit of manual work required."

**Comment by mattgodbolt** [comment]
Also via Dmitry Arkhipov:
https://github.com/asutton/clang-reflect alternative reflection implementation by Sutton and Sutter.

**Comment by mattgodbolt** [comment]
Closing: we have some pretty cool branches, now, though @rollbear if you still would like reflexpr support let me know!

**Comment by rollbear** [comment]
I haven't found the time to toy with these things in a long while, but I think cppx is more than sufficient.
