### ISSUE TITLE
Update of ARM GCC to 6.x

### ISSUE THREAD

**Issue by offa** [mattgodbolt/compiler-explorer#278]
Would be cool, if the ARM GCC's – namely `arm-none-eabi` and `arm-linux-gnueabihf` – get an update to GCC 6.x (more C++17 features supported).

ARM has already released GCC 6 for `arm-none-eabi` and Linaro should ship it for `arm-linux-gnueabihf` too.

**Comment by Tilka** [comment]
Same for the ARM64 compiler :3

**Comment by mattgodbolt** [comment]
Site now has ARM 6.3 and ARM64 6.3. Will work on gcc 7.1 once I get crosstool trunk working in my docker environment.

**Comment by offa** [comment]
Good new, thanks!

**Comment by mattgodbolt** [comment]
Sorry it took so long! Bit swamped at the moment
