### ISSUE TITLE
Better naming for ARM GCC's

### ISSUE THREAD

**Issue by offa** [mattgodbolt/compiler-explorer#279]
At the moment there's a *"ARM gcc 5.4"* (`arm-linux-gnueabihf`) and *"ARM gcc 5.4.1"* (`arm-none-eabi`) in the list. Both target ARM but on different platforms (linux and bare metal).

It would be useful to have some more distinguished naming here. Maybe using the compiler triplet or "Embedded Linux" / "Embedded"?

**Comment by offa** [comment]
Hey @mattgodbolt, any news on this? 😄

**Comment by mattgodbolt** [comment]
Oh hi! Sorry, yes we should update these. I'll take any suggestion that's succinct -- UI pain means it has to fit nicely in the dropdown box :/

**Comment by offa** [comment]
Wow, that's a fast response!

Here are some suggestions:

| Current Name | Tripplet |  Alternative |
|------------|----------|---------------|
| ARM gcc X.Y.Z | arm-unknown-linux-gnueabi |  ARM gcc X.Y.Z (linux eabi) |
| ARM gcc 5.4.1 | arm-none-eabi | ARM gcc 5.4.1 (none eabi) |

Alternatives:

- Keep the `ARM gcc X.Y.Z` and add some hint to the *5.4.1*, eg. _"freestanding"_ or _"embedded"_
- Add the OS: *(linux)* and *(none)*

**Comment by mattgodbolt** [comment]
![image](https://user-images.githubusercontent.com/633973/32462378-c752172e-c2fe-11e7-9ef2-0e2749fa9051.png)
...we have a bug open to improve the dropdown too #257 . I'll see if just (linux) and (none) fit...

**Comment by mattgodbolt** [comment]
Will push to beta shortly and if you could check it out when it's there, all being well I'll push to prod! Thanks for the gentle reminder on this...

**Comment by offa** [comment]
Thanks!

**Comment by mattgodbolt** [comment]
Have a look at https://gcc.godbolt.org/beta/ and see what you think :)

**Comment by offa** [comment]
Looks good, Problem solved.

**Comment by offa** [comment]
Maybe it's even enough to add the notice only to the embedded one.

**Comment by mattgodbolt** [comment]
Sweet, I'll update prod now!
