### ISSUE TITLE
ASM output needs to be line-trimmed for diffs

### ISSUE THREAD

**Issue by lefticus** [mattgodbolt/compiler-explorer#282]
See this example from the beta site

https://godbolt.org/g/h9hVT1

GCC seems to pad the lines with spaces, while ICC does not, so the diff looks bigger than it should.

**Comment by mattgodbolt** [comment]
Right...somewhat of a duplicate of #269 - will update that with this info

**Comment by lefticus** [comment]
Oops, sorry :D
