### ISSUE TITLE
Option to disable symbol demangling

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#285]
Requested by a few people, including @dascandy

**Comment by mattgodbolt** [comment]
Also requested by @MalwareMinigun on twitter

**Comment by mattgodbolt** [comment]
Also now requested by @zygoloid ... we should really implement and soon...

**Comment by RabsRincon** [comment]
Hoping to push today after testing other than C++

**Comment by EricWF** [comment]
Hurray! Thanks @RabsRincon !

**Comment by mattgodbolt** [comment]
Site updating with demangling option
