### ISSUE TITLE
Better support for LLVM IR

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#288]
In the new UI, the "hack" for `-emit-llvm` to show IR shows up shortcomings...

https://godbolt.org/g/1cAQxA

Might be nice to either detect llvm output and colourise it better...or better yet...support llvm IR properly.

**Comment by mattgodbolt** [comment]
Taking this out of the milestone: I think we can live without it. It's an enhancement for later.

**Comment by samkellett** [comment]
FYI the above link is broken -- is that a bug?

**Comment by mattgodbolt** [comment]
whoops, I broke the cardinal rule of linking to the beta site and expecting it to be valid long term!

https://godbolt.org/g/MwHd7E is a non beta lonk

**Comment by mattgodbolt** [comment]
Somewhat duplicated by #241

**Comment by mattgodbolt** [comment]
Comment from 241: "The Monaco syntax highlighting library is pretty straightforward (https://microsoft.github.io/monaco-editor/monarch.html)", combining both issues here

**Comment by mattgodbolt** [comment]
We should consider making `-emit-llvm` a first-class operation (a button maybe?)

**Comment by samkellett** [comment]
would be nice to be able to write IR as well as compile into it

**Comment by mattgodbolt** [comment]
As a workaround IR can be written with `-x llvm-ir` (or similar, I forget the exact syntax...but yes!) Adding IR as a language is something we will have as part #277 (hopefully!)

**Comment by kula85** [comment]
And CFG view for LLVM IR?

**Comment by bugwelle** [comment]
@kula85 An LLVM IR view is added by #1022 and #992. For syntax highlighting see #1114

**Comment by bugwelle** [comment]
Can this be closed? :-)
The IR pane is live on godbolt.org
