### ISSUE TITLE
"Presentation mode" or at least allow fonts much bigger

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#290]
@joel_f (via twitter) suggested it to allow better use in presentations.

**Comment by mattgodbolt** [comment]
...and will probably need it myself sooner or later...

**Comment by JohanEngelen** [comment]
A presentation mode would have been nice for my presentation at DConf; I tried to hack the page template and css but failed.
Some ideas that come to mind:
-  Add web address to page header e.g. "d.godbolt.org", so people know where to go to try things themselves.
-  Increase vertical space for assembly output. Right now, a lot of vertical space is "wasted" with page header, buttons, compiler options, etc.   (possibly reduce the font size of the compiler name and flags?)

**Comment by mattgodbolt** [comment]
I'm hoping most of these things have been addressed: I've used CE on a number of presentations without _too_ much fuss. We can always improve though; if anyone has any concrete suggestions over the ones already implemented feel free to open new bugs!
