### ISSUE TITLE
Enabling Polly for clang + LLVM 3.8 - 3.9.1

### ISSUE THREAD

**Issue by singam-sanjay** [mattgodbolt/compiler-explorer#298]
Hello @mattgodbolt,

Could you please build LLVM 3.8 through 3.9 with Polly ? All that is need is a [copy of Polly's repository in llvm_src/tools](http://polly.llvm.org/get_started.html).

Polly is a polyhedral optimiser that can auto-parallelize programs. Enabling Polly in clang+LLVM would be very helpful for a  researcher working on Polly to understand it's effects on different kinds of programs.

Also, as a learning experience for me, please let me know how I could contribute these changes to your project.

Thank You,
Sanjay

**Comment by mattgodbolt** [comment]
Absolutely; thanks for the request. Will try and get to this today as it should be a very straightforward change to my build scripts.

**Comment by singam-sanjay** [comment]
Hello @mattgodbolt ,

Thanks for the initiative !

You'll find a release_xy branch on Polly which is stable with the corresponding release_xy branch on llvm.

**Comment by mattgodbolt** [comment]
Ok; I'm building with trunk at the moment - would you recommend I stick to the stable branch?
Once it's built, how will I tell the compiler has polly support? The polly website is unclear.

**Comment by singam-sanjay** [comment]
Please build it with the trunk version, and revert to a stable branch if it has build errors.

Polly is enabled at -O3. Try it out with `clang -O3 -mllvm -polly file.c
`. More examples [here](http://polly.llvm.org/docs/UsingPollyWithClang.html#optimizing-with-polly).

**Comment by mattgodbolt** [comment]
I had build errors, so now I build against the 'svn-tags/RELEASE_XXX' (where XXX is 391 for 3.9.1). We'll see how that goes. I plan on building master against llvm head for the daily builds.

**Comment by mattgodbolt** [comment]
So, I built it as described. Unfortunatley I still get this with `-O3 -mllvm -polly` :
```
clang (LLVM option parsing): Unknown command line argument '-polly'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-help'?
Compiler exited with result code 1```

The build script I use is https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build.sh

**Comment by mattgodbolt** [comment]
Ah... checking out that revision leaves me with some directories like:
 $ ls llvm/tools/polly
final/  rc1/  rc2/  rc3/
 ugh...

**Comment by mattgodbolt** [comment]
Am rebuilding now over my lunchbreak :) We'll get there...

**Comment by mattgodbolt** [comment]
Didn't help, unfortunately. I thought I'd updated but: https://godbolt.org/g/zxR5hn still shows the issue. Sorry this isn't as quick as I thought it would be.

**Comment by mattgodbolt** [comment]
Hi @singam-sanjay 

I'm not sure how, but the daily build of clang I built last night has picked up the polly install OK (I think)! Ca you test? https://godbolt.org/g/xICxTC for example

**Comment by singam-sanjay** [comment]
Hi @mattgodbolt,

It does work ! Thanks for you time and effort !!

Check out https://godbolt.org/g/Gu3677 for a matrix multiplication kernel being autoparallelized by Polly using OpenMP.

Sanjay Srivallabh
