### ISSUE TITLE
Tooltips to show help on assembly

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#30]
Several requests to have help about instructions from those (like me!) who are rusty in assembler.

**Comment by chriswhocodes** [comment]
https://github.com/zneak/x86doc looks good, it's used to generate http://www.felixcloutier.com/x86/ from the Intel manuals.

I use http://ref.x86asm.net/ in https://github.com/AdoptOpenJDK/jitwatch

Will let you know if I find any others (ARM would be next on my list).

**Comment by RabsRincon** [comment]
I'm 5 years late, but I'm on it!

**Comment by mattgodbolt** [comment]
Thanks @RabsRincon - I'm very excited!
