### ISSUE TITLE
Provide DMD compiler for d.godbolt.org

### ISSUE THREAD

**Issue by wilzbach** [mattgodbolt/compiler-explorer#306]
Hey @mattgodbolt,

Your compiler explorer is pretty awesome and I often use d.godbolt.org
Now as D has three main compilers I was wondering whether it's possible to expose DMD on your site as well?

AFAICT this shouldn't be difficult and @ibuclaw has already done a lot of great work in this regard:

https://github.com/mattgodbolt/compiler-explorer/compare/master...ibuclaw:dlang

@mattgodbolt what would be the best way to do so? Or in other words
- What would be required apart from addding a `lib/compilers/dmd.js`?
- Can I add `dmd` directly to `/etc/config/d.amazon.properties`?

Thanks in advance.

**Comment by ibuclaw** [comment]
DMD is an utter pain to get working as it only generates object code, not assembler.  Meaning that all the nice features have to be explicitly turned off/hidden.

I have a broken rebase against master from a couple months back, I'll push it as dlang-test if you're interested.

**Comment by WalterBright** [comment]
How to get assembler output from dmd:
````
dmd -c test
obj2asm test >test.asm
```

**Comment by mattgodbolt** [comment]
Thanks @WalterBright ! We use this approach in "binary mode" on the other compilers too. It loses some context (as obviously the compiler is free to annotate the assembly source it generates with useful comments, label names etc), but it should get us off the ground!

**Comment by RabsRincon** [comment]
I have started the proccess of adding dmd to CE. Sorry this took so long! It should be done in a couple of days :)

**Comment by RabsRincon** [comment]
Hi! So, after a bit of work, DMD is now oficially supported (Lone overdue, we know. Sorry!) It does not yet have line matching support, as I'm unable to get `dmd`/`obj2asm` to output relevant info (If you know how I could do this, please let me know!)
After it gets a bit of testing (Feel free to test on your machine, see if it works :D) we'll push this as soon as possible.
Thank you for your patience on this one :)

**Comment by JohanEngelen** [comment]
Great @RabsRincon !
