### ISSUE TITLE
ASM of Multiple Compilers

### ISSUE THREAD

**Issue by sirinath** [mattgodbolt/compiler-explorer#307]
Is it possible to add side by site comparisons of multiple compilers?

**Comment by mattgodbolt** [comment]
Yes: click or drag the high-handed button on an editor window.

**Comment by sirinath** [comment]
![image](https://cloud.githubusercontent.com/assets/637415/23576230/8483bbb0-00c5-11e7-88ce-2a503c644fec.png)

Cannot get a proper 2nd window.

**Comment by mattgodbolt** [comment]
It's the button that looks like a bar with an up arrow. Just to the right of the floppy disk and share icon above the text editor. 

Sorry it's not very clear!

**Comment by sirinath** [comment]
I want to compare them side by side. E.g. Clang vs GCC. What areas of code overlap if any and what differs.

**Comment by sirinath** [comment]
Got it
