### ISSUE TITLE
Sometimes short Link option generates full link.

### ISSUE THREAD

**Issue by AraHaan** [mattgodbolt/compiler-explorer#309]
For some reason some things like my code here always generates full link when I tell gcc.godbolt.org to generate short one for sharing on discord:

https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZTUAHAvVAOwGdK0AbVAV2J4OmAIIcAtiADkABmmk0Exnh6YA8mwDCCAIZtgmGfICUpDgOLIj0gPQAqAKSzRzgJwJMADw4FimXQlnVxd3AAkArGIAakcAJgA2aIBJZTUJTDYCXRZ2aIAzEmiCT2jPHz8AiWjkHl0ODgA6YPtbYPa4gGY8fLYsfOiw7AANAGUAFQAlbFEAWQB9ABFsADFkgDlsRY7O/rw2TEGRiem5pdWNrZ392v4sWM6tBsrAx07sa7Zb%2B7etVgl9HhGG8PqEXGxApgOIxdNZoqJiLowrp9LEAOwAIWC0RxNTqDWiACN6nhkPNyr5/IF0ViXLjoowhAA3HJGbH03G%2BdAgECU/bASlVIn1TDk7yC16dWmiDm4wmoVA8aLoHK6ea1AL%2BdCkaK6RiMTLoWReHUAdyEBEwFMwMMRlrI0X4Inm2UJHDe0tlOP2BGiAK8810xERAE8dchBP4soHg7owwVVKKOHgAF6YD3s2X8Th4YAHdA1PTEex%2BzASeaEvjIADWGbpuMY/ErpJAmY5DjbXvh6HQHF1haDsPtxVQxVKFJeEmaYJlXdx61QlpA0XGCGEuv4RABLGQuh4PBDuv1hr7qONnbnOKIRMwwH2bH50VQAxKh2QRaHmBi/kZUMylvQC9L32MpvAKEhqh6MdDj1A0%2BmNXViGAaJ1xEX1rz8fhMGnWdL3pUQeAsaDohEW1WRiU013fFDTxqVAJABXU%2Bn7aFYUOQlMAIU1MEyIC5wCajyhop9mFYCElUJTciUPfpdH4HhfVQziR2KYgsJwvCOVXdd8mzZBcjYJiCxKdcJypapUEJKhMH04TdD9J0CD4rs9CZQ5ChiITMHwIhiCaeFCNHV8B0RfSvwc3wbxQwyfXA4gpz41o%2BKZVA8ALUQex0QcwuICBYvfbL7RMGlnNxFVsnVNQg28h5FgKPcRDrXC5ygiBYMNY1iscTFStlVrzUIK1xRtQcipK%2BtNNlYlnTMoVfl%2BWI4jic8loeLQFq5Hl%2BGPKwRTWjaCG5XlOPyVQeAgMA5EurrHnmibJq7Tbjq4iA4hu9bHhIw6eSE%2BbPt8HJSXVeonMebNkzzGqOAQEhQewCACtCsa/q0Ra4h1eI4iah6cW6urMEIw5us9HH6Wm0VZupFG0ZWuJ9v%2B76QG2g1dpEenUaetDTv3C6rukd67ua0n6U5zjTVegWGaO37boZwGyV3XxfnB3N8xImHiDhhGPxykxsZxvHevRfHCfGoW8P6i0hp8Ea7S/Lqevu0nybFCpzPZr6juZr9FaJ2WOcZrmzt52RrvZo3NNFl63o9p6ZY%2BgP5eBpWwZzSGC2h2GQW1wr7Y9zGMaW/WHrx6ICbZ4mI69F3Keqamnu91m/YTz2eSDnnLtD/nw6d4WcSj8WY/rxn44OpPFdBrQVfT9Ws/eHOkft4vJsN3vZVX83cbRbY1%2BiDtd/pUZOL7KDgqdcLTX0Ag%2B2vdrmMx2mjOiAbLSYtHC6xg/cTyTA3OIQ9EafhiLoHsNUMLjnFJODSXokq7xSmlEinEmAGQ4BAeUiojxwXQPMY0Op0FKhftbUio0SA6liv6IMoZSBV2AlkBMahkxpjwQqJU59XQcB1NPNWiMSwZAkJWVANYHYk0vHfI0XhaqYMNDgrwy8uyEOtGRYcbw6oKOGkokgcivT%2BhjKGSRFDYwhi0bKbmSZUx%2BzqqYxh6YpRG3Pi6XQbpJFsMce6WxX8cR8IrFWas%2BiywCJrMY42fF96bw5MiGspYSgYDHDkP0uhqxQhEl%2BHImj/ZGw8ihfIEpqj6ALNkycup9L8D3AeOiyhEzQMvIsdQ0R1jqHGNEAAqqMbA0R1BNPGKMZIyx2krBXGEUQ4wqkclgWE2KhgCDqkjP%2BShcYIDCKNv4AgghDIRmDP%2BXRcYgkby7KEzSETfEZGicZPQvoASJL7EwFJvkUYZKKD0HJT8CnuyHCU/cAD6IqDUCMrsNS6kNOaa09pnTum9PUP08YgzhmJTaHA1KGdOLTI2VkOZIY8p0PWVGbIhjFkeJqDM6MaLJFYtmYYnZ28QlOHxYcqJMNTlxIuUk65do0kJ3uTER5hS8kFCeW80pnyKk/KNv8%2BpjSWltI6V0npkrIXQt%2BbiMZXZ8HREmQ4t0CyzaaWWasx0zp2EUp3mE/ZeFaXHPpbE85CTmUs1ScQO5%2BLMlctecxF5Qp%2BUfPKd87CIraliqBZK0FMq%2BkDKGQqnESqvQTKRVY8xmrK74p1cQQypj5jWMNVSo2ZrOIWpKIy61VzbW3PSY6h5brqQ8vLbk4pAqvWVN9QC8VwKpVgtlaGmFu9I1ZjTtwosJY1V8ICdWeNjswn0iTYZLxQ6M27xNZeAA4sfFcEC3ZCnKvZeoLE/D8nDdELtHI0CcF9JzbdBgvq5TxWO3EE7hQzUgeZRolIFkzuNdSq9OIj7X2XYcWuypVS7v3fSQ9kUT1CDPU%2B0Dj59iFEvZpGu96qiPr8BimDQTx2cV1fB1dgQkMXpfXst9mktBVT8k%2BKSv8vwhhMmekCwVf3roA3CsJ8CCwaiDCOkRc512VU1DVFRqksJoblCKV2OTGhsbw%2B499t6KYIZw0%2BzGmM9ZSa7Lsr0%2BQhCGlvUDWu8QkgsrtdTNBJIyS6cSIMOTEgdRPWdVUPT9DMCjEnLBvCkGz3rqEziFV9j2GSIiNhqcar2HPpU3hTJEAuE1VikqfjsgPTRBi59fzYm1WxrTCFjECX4hYjiBiFzD1WrJagWq0lqLDHxs6NsSr0RZD5eFq1Hzri6t9xxOuxaWJquXUcAAVi0AQLroW%2B6l3LkTUdLWORtey/xzG9JFODeFmpkulL8X0ki6xvtpZ%2BE%2BL85ZxoA7/E%2BIyzQ6KvpqL8YBjuZOk8fTZ0HT4nrGIeA9cWMpzjBzdsZXQFlReuV3yveO5N3L/GisPqff9lbuIQeIYk0diH3pMWEqmcS4Hu2SuI7RbD6T9IofyaRaVnFoYIBTdy/jrZIZwdY9xIV1HeP0fla6nEbr0RaBJBUbF5rOMGv6qa1q8bZVVSSIYz%2BOo1gIAMbUAYEomqAC0zOdT0DRj1rQbAldOSWhT8bw3TYJsp5eSb1Whc2hF5gMX/6JfACl8VaXCuFeKd64ZXESnPNzkWyvZb0nXddhx1OJ966Nd4Rvd7/D6nNPMWmjpyz9mDPFpbsZ5MpnI/me99ZxmVb7OmKc%2BZDnso3PIQ8/N5VLC9Wil8yjgLe2kXBf95ecLa2TsJckXFqUDeFre4r1MtLJvXtZaB7l7PLUBgQDb2jlFBP5k3Sq3VWrvO%2B5c5LzznXfP%2BfZHa/xrrvX%2BvSGd6p7eZdtdjaX3%2BlfU3qszcd0XAvBt3ek093hOvPDNtDp2%2BX/bW3BHDur5NfKCBJEXaBhPX4G7eeO7d/B7J7brF7bfSHD7TKHWe0bWT/TSQHDrOqNvMHKAnENvGHRAi2BHUfMnZ/FLWnUfDHHAy8NA4g7FDHYnDEUnNFMggfaIIfGnKZfHUgxaJnFnWqdnGferQfRrN0fvUmfXOqQ3RgY3U3bIRoc3S3aIWXG3D%2BJXFXDfJ3S/JbE2CuA/JfEQo/XQRoYXNiSQvQmQhAGXBQxXe3WbdXDAjkW/S8Ow2w6/U1XbX3VUBg9DFZZNCzALYPExUPAscPBPHw8zaPNlBaOPCPYIpIZPevQBXWXgr3GAr7OAr8BeIBdw69DDLwoPNQ4JXeDTPALTXPKPItNJD4d4JgwI0TScezGI4o8zTPfkIQ3ERos9E/VAlw5DDInEWwWwaIUYGGeSAsZIPETUMcVCGozofpBABiLNXbbA53G9Vo4AXwjkKo2uNBIvMRGRZhDBNRG2DRMgY7LschXQLwNFahOHFqOhTvXY1hNCVxS43XOce/DbEAoRBIr0NCZBMSVBbY3BZ%2BK2RREhB0AxKhBzaxThB4t0HUd46sboglfA5HarJvN7R3JwqaEzao8yDjPiBwgAP3WMs1xPxV6NGKDBvlKDayoEcmihqBFF3XpDJO0j7CZT7Ak0fBMlZP0HeTKR%2BPYD3EZKp3yAujAG4wk28maNlAWNyNmwxMcKNTlKq041qHqD7CqMoks14MZDwBZCXD4ielND5AMCeRdk1J8NyJVXFJI28h1DEQBP2OITtgdAELcTRPhytQDAuMROxTJx1FTXTVyNeKDF4TLG8VAPm0bGbGQFbFnUIzwk%2B1ojiOHHAR/V23aHxQXCXGXXXDki3HllrTEVPEMnPCuOvA4jvDYAfDPWfGImTPCh/H8BECyG8mOxAiEg8kghfFKHtIkSDGQiUnQiCjUh9SuIIiImCidPImfioh/1zPKUYh5XslYjhA4i4h4hVyuIEh/yEnXH5PEiJCkkJBkkwHyDkgUmEjQhUkwlHOeJZIKD0gMifi5NAgCyfCshskUlogkEcmO1cnciKC8h8hIH8nHKClKHrJiB/Mig4jpNik7MY2SgRW7GSNzlym/zQqlN0J42qgLH4zPMJmd1al7KwvpEtkGmBOdNIurhE3NKeWpgABkH5ZFVph4vYdpfZY5A4Tpg4GLO4w4HVnjHpuLo5JYA5pYwJh5x4QZlYe0oYNYtZIKxLogmKlpFDZSvQtdND3TJozTf1GLmKZs2KtoOK9pjLnpuZzo%2BK%2BYxLjiviRLB5lK45JL/YvppKU4p45KM4FLs4lKbCHClS99tK2zB9HTbZyJqLMTnQ6LClzLG5OLzL24rL%2BLu5BLD9W5npHKuKJKJEpLLsADU4IY1ZM5NZfKUjiBlLVL0ZFcNL15d8RtPiHo9KtS4rTKK5XKo5LKIBrKu5bKrjhKjo0IsrzLR45Z8qZLCrVZ5K554Y/LaqFSjYHCHC505xP0T5uzDhz4KIr4b5RwxEaYWK6YeVCE34C5Fd8Uf4/4AFyrdRQFjJwK0zy9YUkKEFvjRJ2BUEVV/iTQiQi8wrDiyE6EwS4wnj0r4LExITfqMEXEYTHQvKQpQy38PjF88JezJFvrnd/rRpwp%2BMsbWV7V5qdFkS6pgajF5qAzzFJFO9ndXTnFoS3SjYp1tt%2BM4TVimT4zyDYQjkc0Yk80rVLlkl8a0qwsy0%2BVXU%2BUa1PUlBvUhScRRVAUJUQVpVwU5Uw1nrd5o1WC6dCcsKb06DyVcjlqOa5xs0TlLV4kBbQiCb2VS1OUq1nkJaVla1pb618V5am1A1la20oU1bO0mMuwWNEEtaSDyt8pta4wsL9a9F%2BM2CDadKjas0ua6VeazkLabUbkwjbpbaskxb8lHbeTBUZaG1/VFaW1g0IV21ELd4VUgtXESTpMb1XS2bcQVqvck7zUU781LbSjrbBZNInV7bK187navlXbpN3aA0lbW0Q0faO0wlAMqc6FUsIa41dasiU1Ew01zFm6ejja27IkO6GV%2Bb06haS1pMB7c7eVuVJaykXbhU3a/UFbm0g0VbK71awlgzixVUkU4T67tV17NtwzAlDb5T2ajZF0v1VxHqnk2tN1lzT1gAq6wlgNj1GYjSEHz0/6A8AHmry90CQHFSvRW6vQ1rv1XyYH/136uwUGMr0GwNkIIM0HjSBy2AYNGq1jaLa5cMUNUAESb1cGxN8H47QGW696vRiNNQrlyMrrqMWHiJ6NKG/aXrWMSMsG9dVQcKtRJEbzncBGoEZSdKyZOHOjcoqrVDhHCG/DCiw8sSYrzISiM7e7PoIiyQ7G7Mk9LMU8jpTRbNXhzMM9nN2GRYmGMH89DG5Qi9aay8iCpkq9nda94botG94tEtUZh8Y0V70tu8nte88sgmo1B90ng6qD6duCUTIqOQ591UOAKmuxkD%2BNrLVcBtwn7D6r98WnJp6nqsqqrCsZ5qd9LG3dBnNJP7Ean9onisf6Dt39MdSZv9f9shxqPKgD4ZWbutHtnsETsckjvsgEECbCumOi8GuibCsDVGtnF7TtEcCCJmH0R8SmdbTmXDKCyVCcaCo6I6bDqcX8XmysdaODmdWdKseCUbZ9%2BDudBD8mHodCxCJDxdMgLdTCrc5cUWzH7dVdzG7Kt4NDRsOmkCBd%2BNYXDD4XJckW5DzC0XldemLm6rhm8IAr0S6XZQ0DkM/dFiAGciLG%2BICitMNSzN9Me6jM%2BXE9ojPHaG09/HExM8qgsLDTmHdDdHImIW%2BxbnENa6NUESEmiqos6FEsp8Um1pvCYn5hO8Mse8cs8nQWv9CmWDkUHnx8ymp9anhSmDXTnXZRDmVL18%2BtmmsXjYgrcW/X6RPWenz8%2Bm8XNKRHWmmWXj4aH84TCDJmplf6aXYif9ztFn/8Jq/gshbtpnAl1nwDID%2BnoDy9Ptdmcp9mS3WsCWgdqsWXJMI3MD5jzmvm8DfTiajWk27XXnx8nm8Hfmx90V3nrn6CvmbWfnine30UGdOCgXJ8at3WslXXlWl3g2CWDd/0DDRcSXEWZcUWFdKXlC%2BtMX%2BrGWA2oXOmN3RCt2jdiWzcEXZDrd5cdQj3qWbClTjsGXsW5jjnco2X5rA9I8CHuX/DtNXH%2BXBbDNXKXH5g3G/HRWAtAbTtyqsK29y3yq0jdZ2XPDDJOW8So2CgwO5WEGHHT7yi2lYP4OggPGkPaHmH7NlisLljV962THZm8IySBiBAeBhjySYgXyck3hpjZiaUW3NQOPLwljSOQPq7bGNivrjw%2BgdioaCEgT1EQTQbD9TjzjDEtOl9waGFzE7ji92F9O%2BdRnH8fFZWkF3rOA2olPsEHT1ODjNP4ldPwTbjTPHirP38ESPnDxYsd7wO4ONj%2B8CThWAs1G5wySJNKTDhqTaSQJfZZa94%2Bj7y2T%2BPOS1xuS2AC6RIDJBSjYehRTrTeN0AKmDHFrCPXdDZ5sCAQwDR%2BgQvf1dN6vGvvJTyQvqOZzgPpQN4dhDQehgh%2BZSAeAZBusFA2AZBaAFBUAZB1pcmSJLA4R4hOhZvSACBjB%2BYzBqwQAEg0RGglo3A3A0Q0Q3Bus0ROgAAOAAFjiGu7G5kFu6m%2B24YBkAUC4FkE2%2B27MDgFgCQDvq/HIG4FHrUGIBQDqAMBdDUjYGrFIG5ntC4DQTe6UAyCyE0APDe/wH8H0l1KhDe59AJl%2B4YDs64GkGl3UE6DkK5BUWQBoNoBe7MHG%2BkEm9IGm7kDm5kDW9oGfkIB/y8Gu4SGlwSFu7xH0GQggEwjh5MAUC2855MF25AE6DiEaDO9kFkCWlkHu4SFoEu/RhZ5e/Z7e/m%2BkE%2B5AG%2B/l9MGZ5kDiFe85/e7N5%2B4V7MD/mTHYBAFu6AA%3D%3D

please fix this.

**Comment by mattgodbolt** [comment]
Hi. This is a limitation in the Google Link Shortener I use. The link size is too long and it rejects the request. As such I have to fall back to the long-term URL.

I have a plan in the future to use my own storage for the code and settings, but this is a big commitment in terms of data safety and privacy etc.

**Comment by AraHaan** [comment]
ah, I see

**Comment by RabsRincon** [comment]
Would an alert acknowledging the fact that the url was too long to be converted be of any use?

**Comment by mattgodbolt** [comment]
@RabsRincon could well be yes! If you can get it to work without being too annoying if it pops up over and over :)

**Comment by RabsRincon** [comment]
While this does not fix it (Not until we handle our own short links) , there is now a notification that gets issued when this happens, letting the user know the probable cause is that the Url was too long to be shortened (How ironic...)
