### ISSUE TITLE
Monaco editor slowdowns

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#310]
@lefticus reports slowdown with the new editor and big files. I'm planning on updating to the latest Monaco; hopefully that'll fix it. But we should check before going live.

**Comment by lefticus** [comment]
There's still the possibility that it's just my dislike of the IDE like features it has :)

**Comment by mattgodbolt** [comment]
Any further thoughts on this @lefticus ? Would an option to disable the auto-highlight allay your IDE feature fears?

**Comment by mattgodbolt** [comment]
I'm going to close this for now - @lefticus feel free to reopen should you find something! :)
