### ISSUE TITLE
Make beta site more obviously beta!

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#317]
Would be ideal if the beta site announced its beta-ness. People have been confused before now...

**Comment by RabsRincon** [comment]
Would chaning .navbar-brand link text to "Compiler Explorer Beta!" or something like that work?

**Comment by mattgodbolt** [comment]
Yes probably. now we build using .pug I can make that happen pretty easily
:)

**Comment by mattgodbolt** [comment]
Pretty sure this can be closed :)
