### ISSUE TITLE
Error: undefined is not an object (evaluating 's.assembly[e].source')

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#324]
https://sentry.io/matt-godbolt/compiler-explorer/issues/233224743/

```
Error: undefined is not an object (evaluating 's.assembly[e].source')

http://gcc.beta.godbolt.org/v/680bd13bfce5ec22ab3dc9667785c4b49fb73ce3/main.js:12:15720
```

Seemingly comes from the new highlighting code. Unfortunately the auto-unminify seems to have failed here which makes the stack trace incorrect.

**Comment by mattgodbolt** [comment]
@RabsRincon possibly linked to your changes (I have a system tracking all the js exceptions thrown on the site).

**Comment by RabsRincon** [comment]
Ey! I'll check this out tomorrow/thursday if this is not too urgent, I'm a suddnely too busy!

**Comment by mattgodbolt** [comment]
No worries at all, not a problem. For what it's worth there's tons of funny
errors like this in the rest of the code. I haven't fixed them yet either
:) I added you to the tracking system (sentry.io) so you can dig around a
bit more if you ilke. No worries if not!

**Comment by RabsRincon** [comment]
I'll be checking this out later, but I think https://sentry.io/matt-godbolt/compiler-explorer/issues/233941784/ is also the same issue but with correct stack trace?

**Comment by mattgodbolt** [comment]
The stack trace is still for the minified code there. I was hoping we'd see
a full stack trace (as sentry is supposed to do...)
