### ISSUE TITLE
does not support meta-template 

### ISSUE THREAD

**Issue by vickoza** [mattgodbolt/compiler-explorer#326]
This  code should compile but show a complier error
#include <iostream>
template <size_t x> struct Fibonacci
{
  enum {
    value = Fibonacci<x - 1>::value + Fibonacci<x - 2>::value
  };
};

template <> struct Fibonacci<1>
{
  enum {
    value = 1
  };
};

template <> struct Fibonacci<0>
{
  enum {
    value = 0
  };
};

int main()
{
  std::cout << Fibonacci<10>::value << '\n';
}

**Comment by mattgodbolt** [comment]
Do you have a short link you can share? It compiles OK when I tried the code: https://godbolt.org/g/O7ihrn

**Comment by vickoza** [comment]
Never mind i just had  a ~ at the  end  and just did not recognize it.
Thanks
Sincerely,
Vishal Oza
