### ISSUE TITLE
Support Visual Studio 2017 C++ compiler

### ISSUE THREAD

**Issue by hughbe** [mattgodbolt/compiler-explorer#327]
I think the version number is 19.1

This would allow the use of c++ 17 features in godbolt!

**Comment by mattgodbolt** [comment]
I'm waiting on my contact at Microsoft getting me a nuget package I can install.

**Comment by hughbe** [comment]
Cheers - what about https://blogs.msdn.microsoft.com/vcblog/2016/02/16/try-out-the-latest-c-compiler-toolset-without-waiting-for-the-next-update-of-visual-studio/

**Comment by mattgodbolt** [comment]
Thanks! That's where I'm getting some of these from, but it doesn't yet have the latest 2017 compilers.FWIW I install them nicely on Linux with pretty [straightforward code](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh#L444).

**Comment by mattgodbolt** [comment]
Thanks to help from MS, the site now contains the RTW compilers.
