### ISSUE TITLE
Integrate llvm opt-viewer

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#332]
https://twitter.com/matpow2/status/841866977551519745

**Comment by mark-99** [comment]
Came here to suggest the same thing, looks very cool.

**Comment by jaredwy** [comment]
This has now landed in master. 

If you have a clang 3.9+ setup. Simply drop in -fsave-optimization-record  into your compiler arguments and click the new button in the compiler view.
