### ISSUE TITLE
Building boost.python C++ extension modules fail.

### ISSUE THREAD

**Issue by AraHaan** [mattgodbolt/compiler-explorer#344]
I weould love to test to see if my boost.python experimental extension would compile. However it fails to find pyconfig.h.

```
In file included from <source>:18:
In file included from /usr/include/boost/python.hpp:11:
In file included from /usr/include/boost/python/args.hpp:8:
In file included from /usr/include/boost/python/detail/prefix.hpp:13:
/usr/include/boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found
# include <pyconfig.h>
          ^~~~~~~~~~~~
Killed - processing time exceeded
Compiler exited with result code null
```

**Comment by AraHaan** [comment]
The module I am trying to compile here targets python 3.5+ as well. (because ``__builtin__`` was renamed to ``builtins``.

**Comment by mattgodbolt** [comment]
Hi. The version of boost on Compiler Explorer is pretty old; it's probably that.  See #154 - I currently don't have plans to update many libraries though I think it's worth doing boost someday.

**Comment by AraHaan** [comment]
yeah, it could be that. Are you able find an pyconfig.h file present somewhere in compiler explorer too?

**Comment by mattgodbolt** [comment]
I'm pretty sure I don't have python 3.5 on the CE machines.

**Comment by AraHaan** [comment]
alright then
