### ISSUE TITLE
Numeric tooltips appear in odd places

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#352]
To repro:

* Reset UI.
* Mouse over a line number
* Mouse over into the indent area to the left of the opcode
* Observe a tooltip for that line number pop up e.g. on line 4 (`4 = 0x4`)

**Comment by RabsRincon** [comment]
Fixed by 3d9c0a9

**Comment by mattgodbolt** [comment]
Thanks. If possible in future can you please make bug fixes in separate
commits instead of inside a larger commit: that makes it much easier to
cherry-pick just that bugfix into a release :)

Cheers, Matt :)
