### ISSUE TITLE
Clang/C2 support

### ISSUE THREAD

**Issue by lamarqua** [mattgodbolt/compiler-explorer#356]
Would it be possible to get Clang/C2 supported? This is a special version of C2 (Microsoft's backend) that uses clang's frontend. 

https://blogs.msdn.microsoft.com/vcblog/2016/06/03/clang-3-8-in-the-may-release-of-clang-with-microsoft-codegen/

**Comment by mattgodbolt** [comment]
If there's a simple-to-install-on-Linux way to do it (a ZIP file is fine) then I can probably do so. @apardoe might know?

I don't own a Windows machine, and so I'm limited to what I can do under WINE :)

**Comment by TBBle** [comment]
Looks like Clang/C2 is possibly no longer an interesting target? According to [Stephan T. Lavavej](https://twitter.com/stephantlavavej/status/871861920315211776?lang=en) referencing [Andrew Pardoe](https://blogs.msdn.microsoft.com/vcblog/2017/05/10/c17-features-in-vs-2017-3/) it's not being updated, and won't be supported by newer MS Visual Studio STL releases, in favour of [Clang/LLVM](http://llvm.org/builds/).

**Comment by AndrewPardoe** [comment]
Agreed. Please don't add Clang/C2 support.
