### ISSUE TITLE
New UI issues

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#359]
https://streamable.com/9m6ko

 From Ezra Chung on slack:

* Right-click menus are blocked/hidden(?) within their window. I was expecting the menu to be above the windows (over the border). 
* Right-clicking in one window, then immediately right-clicking in another window causes the right-click menu to disappear almost immediately after it appears
* Shift + scroll wheel does not horizontal-scroll windows whose text runs past the right border of a window, even when a horizontal scroll bar is visible and usable.

**Comment by octoploid** [comment]
On Linux I cannot paste anymore by middle clicking.

No copy or paste option when right clicking on editor.

**Comment by RabsRincon** [comment]
@octoploid From your Reddit comment: 

> There is also no copy or paste option when pressing the right mouse button.

After a bit of searching around, I think it's a Monaco Editor error https://github.com/Microsoft/monaco-editor/issues/391 . I will keep looking to see if I can work around it, but again, it does not sound great

**Comment by mattgodbolt** [comment]
@octoploid Thanks for reporting. As a stop gap ctrl-C and ctrl-V should still work - they may not be on the context menu but the functionality exists still.

**Comment by RabsRincon** [comment]
Some findings I've done, in case this enlightens you
- [ ] *Shift + Scroll:* **Monaco Editor related** Litle we can do. Maybe adding an action on the editors, but the mouse wheel is not exposed as shortcut.
- [ ] *No C&P:*  **Monaco Editor related** Again, little we can do. https://github.com/Microsoft/monaco-editor/issues/391 seems to be related. 
  - *Linux Primary Clipboard:* There is a constructor for the editor, `selectionClipboard:` that is meant to enable it, but seems to have no effect here.
- [ ] *Quickly right-clicking in different windows:* **Problem is in our end** Monaco Editor Playground does not have this problem.
- [ ] *Right-click menus are blocked/hidden:* **Problem is in our end** `z-index` for the Context Menu does not fix things. Maybe an option buried somewhere to put it always on top.

**Comment by Tilka** [comment]
- [ ] Auto-completion can be a bit annoying while trying to enter a newline, e.g. if you type
```c++
template<int>
struct A
```
and then hit enter, you will select the first auto-completion result (templ**a**te).

**Comment by mattgodbolt** [comment]
@Tilka wow that's super annoying...

**Comment by mattgodbolt** [comment]
@Tilka hopefully the site update addressed your annoying autocomplete?

**Comment by technosaurus** [comment]
At the moment it's impossible to use on Android.  As soon as you type 3 letters it starts repasting text so that "string" becomes something like ststrstristrinstring.   To top it off if you try to drag the screen to scroll, it moves the cursor, zooms way in and focuses to bring up the keyboard.  Then you can't pinch zoom-out because it starts the whole process again.

Perhaps going to button release event instead of button press event may help with a lot of this?  That's my best guess anyhow.

**Comment by mattgodbolt** [comment]
Hi! Thanks for the comments. We have a separate bug tracking mobile issues. Unfortunately we use another library (Microsoft's Monaco) for the editor and they have stated they will not support mobile.

We are considering a 'lite' version which uses a much more simple editor on mobile/tablets: we are a bit stuck otherwise, not wishing to either change editor wholesale or try and fix the issues ourselves.

**Comment by RabsRincon** [comment]
The new monaco version fixes most of the issues. We still need to make sure that the context menu pops above pane divisions, but for now, I'll (finally!) close this one.

Thanks everyone for reporting and your patience on getting this fixed :)
