### ISSUE TITLE
`array` is highlighted as a keyword

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#360]
...even though it isn't :)

**Comment by mattgodbolt** [comment]
e.g. https://godbolt.org/g/QolYXr

**Comment by RabsRincon** [comment]
Using 2nd method suggested https://github.com/Microsoft/monaco-editor/issues/252 , we override the highlighting for C++, removing the array token. This forces us to keep an eye on updates to the cpp.ts definitions (At least until we get any meaningful answer [in this StackOverflow question](https://stackoverflow.com/questions/43141005/removing-specific-keyword-from-a-built-in-language-highlighter)) but is inconsistent as hell. I won't push anything until a valid solution is found

**Comment by RabsRincon** [comment]
https://github.com/mattgodbolt/compiler-explorer/blob/master/static/ispc-mode.js to override a language definition could work!
