### ISSUE TITLE
Tooltips are clipped by their container

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#364]
Would be ideal if they floated above even the GoldenLayout external parts.

https://github.com/Microsoft/monaco-editor/issues/181 might have some clues.

**Comment by mattgodbolt** [comment]
Seems like: `fixedOverflowWidgets: true` in the outputEditor options fixes this, though it's not clear what else it might change.

**Comment by RabsRincon** [comment]
`fixedOverflowWidgets: true` applied to editor too to fix similar erros
