### ISSUE TITLE
Font sized and tooltips don't play well together

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#366]
@RabsRincon says: Monaco resizes the hover messages based on Editor font-size, so it seems like a "feature" from Microsoft

**Comment by RabsRincon** [comment]
Monaco releated. As I said on the issue edit, it does not seem to be "fixable" (I now think it's not an error, but a weird, hard coded, feature) without some css budu

**Comment by mattgodbolt** [comment]
I think this is probably working as intended. Unless @lefticus has any further thoughts, I'm going to close this.
