### ISSUE TITLE
gcc for PowerPC rejects VSX version of unpackl() and unpackh()

### ISSUE THREAD

**Issue by mtl1979** [mattgodbolt/compiler-explorer#367]
Code in https://godbolt.org/g/GlCV0i should compiler without errors.

**Comment by mattgodbolt** [comment]
Thanks: I don't know enough about PowerPC to fix this. I'm using the default Ubuntu GCC for PowerPC: `/usr/bin/powerpc-linux-gnu-g++-4.8` that one gets from `apt install g++-4.8-powerpc-linux-gnu` on Ubuntu 16.04.

Any thoughts welcome.

**Comment by mtl1979** [comment]
Ubuntu 16.04 also has g++-5-powerpc-linux-gnu, but I don't know if that has the same issue as my own machine only runs 14.04. AltiVec support in powerpc-linux-gnu-gcc-4.8 is pretty buggy and causes ICE on 14.04.

**Comment by mattgodbolt** [comment]
I have no ideas on this. Googling the error message yields a number of hits to people having the same problem and no obvious solution. Closing, but if you work out what's going on I'd be happy to look into it further.
