### ISSUE TITLE
safari: mouse over error does not render text

### ISSUE THREAD

**Issue by badeip** [mattgodbolt/compiler-explorer#371]
1. make typo
2. mouse over error
3. only a gray box with no text is shown.

I have no plugins that should be causing this, and it works perfectly with chrome.

**Comment by RabsRincon** [comment]
Ey! https://github.com/Microsoft/monaco-editor/issues/408 seems to be releated. A workaround is provided, so I'll check out if it doesn't break anything and try fix it

**Comment by badeip** [comment]
@RabsRincon thank your for the quick response.
The monaco-issue seems related, as I get the exact same symptoms as described in https://github.com/Microsoft/monaco-editor/issues/408

My safari version is `10.1.1 (12603.2.1)`
Running on MacOS `10.12.5 Beta`
