### ISSUE TITLE
unhandled EPIPE on macOS 10.12.3 when output truncation occurs

### ISSUE THREAD

**Issue by rryan** [mattgodbolt/compiler-explorer#376]
When output truncation occurs, the child process is killed. If this happens before writing to stdin is complete, an unhandled EPIPE exception occurs causing node to quit.

```
info: ::1 - - [09/Apr/2017:17:40:17 +0000] "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile HTTP/1.1" 200 - "http://localhost:10240/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
Program /usr/local/homebrew/bin/node ./app.js --language C++ exited with code 1
```

I can swallow the error with this patch:
```
diff --git a/lib/base-compiler.js b/lib/base-compiler.js
index 8aa3336..ed4bfe9 100644
--- a/lib/base-compiler.js
+++ b/lib/base-compiler.js
@@ -317,6 +317,10 @@ Compile.prototype.exec = function (command, args, options) {
             logger.debug("Error with " + command + " args", args, ":", e);
             reject(e);
         });
+        child.stdin.on('error', function (e) {
+            logger.error('Error writing to child stdin:', e);
+        });
+
         child.on('close', function (code) {
             if (timeout !== undefined) clearTimeout(timeout);
             var result = {
```

```
$ clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Compiler flags:
/usr/bin/clang++ -O3 -isystem /Users/user/Code/eigen

Source:
```c++
#include <Eigen/Core>

typedef float FPType;
typedef Eigen::Array<FPType, Eigen::Dynamic, 1> ArrayX;

int main() {
    ArrayX f(10), g(10);
    ArrayX h = f + g;
    return 0;
}
```

If I make the program slightly smaller by commenting `ArrayX h = f + g;`, it succeeds because truncation does not occur.

**Comment by rryan** [comment]
Oh, and if I increase maxOutput by a few orders of magnitude, this program no longer causes the problem.

**Comment by mattgodbolt** [comment]
Hi - I think this was fixed a while back - you seem to be using an older codebase. The execution functionality is now in `lib/exec.js` and each stream is set up with `setupOnError` which I think does the same as your proposed patch: that is, handle errors gracefully! Please let me know if you still see the troubles post-merge, or if you have any difficulties with getting the latest code.

**Comment by rryan** [comment]
Doh, sorry for the noise! I was using a checkout from February.

**Comment by mattgodbolt** [comment]
No worries at all! It took me a while to find a repro case for it: if
you'd've been a few weeks earlier you'd've saved me some debugging!
