### ISSUE TITLE
Option for (or resurrect) inline errors

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#378]
Maybe rethink them a little but some people (e.g. @mknejp) miss them. I'd like it configurable too; some others have enjoyed the inline comparison between multiple errors.

**Comment by RabsRincon** [comment]
Can I get a screenshot about what _inline errors_ were? I don't know what you're refering to by _inline errors_ 😥

**Comment by mattgodbolt** [comment]
If you check out an older release (e.g. `git checkout 7135ec2d77cbe76a88f1ab5dc753f0ae0ee38ac5`) you'll see them.

**Comment by mattgodbolt** [comment]
e.g. ![image](https://cloud.githubusercontent.com/assets/633973/25090719/7f2e4a20-234a-11e7-97ee-797cb0f237a4.png)

**Comment by RabsRincon** [comment]
Oh! You were refering to those! Let me see what I can do about it

**Comment by RabsRincon** [comment]
Trickier that it first seems. I tried implementing a css `...::after { content: '...'; }` version but it clutters the view too much.
I think the solution is custom handling of "ghost" lines on Monaco, like we used to do, and have those lines get a special decoration

**Comment by mattgodbolt** [comment]
I wonder if this can be closed now... @mknejp ...is this still an issue do you think?

**Comment by mknejp** [comment]
If it's too much effort then I can live without it. I already forgot about this issue 😅

**Comment by mattgodbolt** [comment]
Thanks Miro
