### ISSUE TITLE
nasm.godbolt.org

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#382]
Support for nasm, maybe? Requested over email.

**Comment by colejohnson66** [comment]
I'm not sure I see the purpose of this. If the Compiler Explorer is for seeing the assembly output of a higher level language, what would be the point of showing the assembly of a compiled assembly program?

**Comment by RabsRincon** [comment]
NASM supported at https://asm.godbolt.org/
