### ISSUE TITLE
clang 4 include files seem to be wrong

### ISSUE THREAD

**Issue by xaxxon** [mattgodbolt/compiler-explorer#383]
https://godbolt.org/g/6wWmtf

https://godbolt.org/g/OGEJk5

both of these work locally on clang 4.0 c++1z

I expect there are other issues, too, but these are the ones I tried that failed.

**Comment by mattgodbolt** [comment]
Hi! Thanks for your report. Try adding `-stdlib=libc++` -- by default Compiler Explorer uses GCC's standard library (and currently GCC 6.3.0's). I'm toying with building it by default to use libc++; but it's trickier to go back the other way.

**Comment by xaxxon** [comment]
I see.  Perhaps something more obvious like a checkbox on the side for this option to make it clear it's not using the stdlib it ships with.

It seems pretty reasonable to me to assume that clang would use libc++ unless otherwise specified.

**Comment by mattgodbolt** [comment]
I'm trying my best to not put too many tickboxes for different compilers in; the UI is complex enough. That said I agree it's not exactly obvious...I'll raise a separate issue to track it!

**Comment by mattgodbolt** [comment]
Filed #384

**Comment by nmr8acme** [comment]
Just want to chime in as a new user to say that the present behavior surprised me. (I was trying to see whether std implementations were different) Thanks for the explorer, it's super useful.
