### ISSUE TITLE
Libc++ for clang

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#384]
It's currently available with a command line argument. But it's not discoverable. There an argument that it should be the default. Or at least should have a tickbox.

I actually don't know why it's not the default: I build clang with libc++ support but it still needs the compiler argument to pick it up.  Needs thought.

**Comment by xaxxon** [comment]
if you grab the pre-built binary and untar it anywhere, it "just works" with no "installation process" other than untarring.

Not sure what they do, and I'm not suggesting you grab their prebuilts.. just trying to show that there is some way.

**Comment by mattgodbolt** [comment]
Thanks: I'll see what I might be doing wrong. I (mostly!) follow the instructions on their site and use this script: https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build.sh if there's anything you spot in there that might be the cause...

**Comment by EricWF** [comment]
> I actually don't know why it's not the default: I build clang with libc++ support but it still needs the compiler argument to pick it up. Needs thought.

Clang chooses the system STL by default to be ABI compatible with system C++ libraries. If you want to build a Clang version that uses libc++ by default on Linux you need to pass the CMake option `-DCLANG_DEFAULT_CXX_STDLIB=libc++`.

**Comment by EricWF** [comment]
@mattgodbolt Also feel free to add me directly to any issue involving libc++. Personal support is the least I can do as a daily Godbolt user.

**Comment by mattgodbolt** [comment]
@EricWF Thanks for the kind words and offer of support. I think we're good at the moment; if this is the linux default then I think we should stick with it. A button to choose the STL implementation might be useful down the line though.

**Comment by xaxxon** [comment]
Functionally libstdc++ quite limited, however.   People on mac or people
explicitly choosing clang who would also want libc++ with it seems like it
would be more likely.

Otherwise why not just use gcc?

**Comment by mattgodbolt** [comment]
Pardon my ignorance but what features are the GNU library missing? What am I missing out by not using clang's library? :)

I think the default on Linux of the GNU library makes sense just purely due to the ABI/interoperability issues with most prebuilt C++ libraries. Though it's great to have a choice!

**Comment by xaxxon** [comment]
The original point of the contact was features not available on godbolt
because I didn't realize it was using libstd.

**Comment by mattgodbolt** [comment]
I _think_ we are about as good as we're gonna get for this. I think the ABI point is good enough to mean  the standard library being libstdc++ by default is ok. And enough folks have gotten used to putting `-stdlib=libc++` etc or otherwise. I'm going to close: although it would be lovely to have tickboxes for all this, it's very compiler-specific, and there are plenty of other command-line options that could benefit.
