### ISSUE TITLE
Font is hard to read and is some letters are ubiquitous.

### ISSUE THREAD

**Issue by CvRXX** [mattgodbolt/compiler-explorer#386]
I made a slideshow where CE was used for live coding. This worked great and allowed for great interaction with the audience. However the font wasn't great for presenting. I would love to have another standard font or be able to change it in a menu.

**Comment by CvRXX** [comment]
I would like to propose to use [firamono](https://github.com/mozilla/Fira) as the default font and make [firacode](https://github.com/tonsky/FiraCode) an option.

**Comment by RabsRincon** [comment]
Ey @CvRXX . Can you provide me with an example of when the current font is hard to read? I've never had a problem with it and find it super easy to read.
Maybe your browser is using a different one?

**Comment by CvRXX** [comment]
Right now it is depended on which platform you are using and which fonts are installed. On some pc's that means that the l and 1 are the same. Don't know the exact os/browser combi though. But this patch will make sure that all browsers are using the same thing.

**Comment by RabsRincon** [comment]
Gotcha! So this unifies them all. Thanks!

**Comment by mattgodbolt** [comment]
Deploying to live site now :)
