### ISSUE TITLE
Dropdown for installed libraries

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#397]
"Would be cool if there was a drop down to select some often used libraries" from @CvRXX in #154 - I totally agree. Dropdown with tickboxes or something (or radio for versions of the same library?). I _think_ all compilers support `-I` to include so this could Just Work™?

**Comment by CvRXX** [comment]
Probably would work yes, would be cool to also be able to group them. For instance you might want a boost group and a kvasir one. So we don't bloat the list.

**Comment by RabsRincon** [comment]
This issue totally slipped by. The dropdown has been there for some days now.
:)
