### ISSUE TITLE
Compiler Integration Guide

### ISSUE THREAD

**Issue by jrast** [mattgodbolt/compiler-explorer#399]
Is there a guide on how to integrate a custom compiler in a instance installed localy?

I have a Renesas Compiler (based on llvm) which I wan't to integrate, however, modifing ./etc/config/copiler-explorer.default.properties or creating ./etc/config/compiler-explorer/compiler-explorer.local.properties does not have the slightest effect...

**Comment by mattgodbolt** [comment]
Try modifying c++.defaults.properties (on the move atm hence short reply)

**Comment by jrast** [comment]
Ok, at least the compiler version is recognised, and after creating a custom file in lib/compilers, the arguments for the compiler should be ok.

However, I get the following error message after a timeout on compilation:

> Application tried to create a window, but no driver could be loaded. Make sure that your X Server ...

I think this error message is actually from wine (I'ts a compiler for a MCU, available only for Windows). Any hints on this?

**Comment by mattgodbolt** [comment]
This is "normal" running under wine. The first time you fire up wine it tries to update your '~/.wine` directory and pops up a dialog.

It should still work. The live site works around this with this script: https://github.com/mattgodbolt/compiler-explorer-image/blob/master/docker/gcc-explorer/run.sh

Wine stuff is really fragile and experimental...so you're trail blazing here a little! :)

**Comment by jrast** [comment]
Hmm... i have copied the run.sh script and wine configured itself the frist time the script run.

I still get the same error in the frontend. In the console, a warning is logged: Timeout for /home/..../ after 10000ms...

**Comment by jrast** [comment]
But since i use the run.sh script, the version detection of the compiler at startup is a lot faster. So something must have changed.

**Comment by mattgodbolt** [comment]
Can you run the compiler yourself under wine without any windows popping up?

**Comment by mattgodbolt** [comment]
Also try adding --debug to the command line arguments to app.js

**Comment by jrast** [comment]
Normaly I execute the compiler directly from the command line and no windows are popping up. There is also no need to start it trough wine. For example, this works:

![ccrx-working](https://cloud.githubusercontent.com/assets/146369/25285877/1319088c-26bc-11e7-91a5-31f3b32894e9.png)

In the compiler explorer the call to the compiler looks ok, but fails:
![ccrx-notworking](https://cloud.githubusercontent.com/assets/146369/25285894/2aa03f52-26bc-11e7-921c-8b7f1ec2868f.png)

(Sorry for the images, somehow copy paste from my VM does not work at the moment...)

**Comment by jrast** [comment]
To integrate the compiler (so the version check and arguments are correct), I have created a custom compiler (as said above) with the following content:

```
function compileCcrx(info, env) {
    var compiler = new Compile(info, env);
    compiler.compiler.supportsIntel = false;
    compiler.optionsForFilter = function (filters, outputFilename) {
        var options = ['-output=src=' + this.filename(outputFilename)];
        //if (filters.intel && !filters.binary) options = options.concat('-x86-asm-syntax=intel');
        //if (!filters.binary) options = options.concat('-output-s');
        return options;
    };
    return compiler.initialise();
}
```

module.exports = compileCcrx;

**Comment by mattgodbolt** [comment]
Ah I see you're running it under `wine` implicitly...ok. On CE's website when I'm running `CL` compilers (under wine) there's a hook for it. Try copying into your custom compiler the stuff that `CL.js` does in terms of explicitly wrapping with a `wine` command and handling the filename mangling too (`Z:` stuff)... bit of a wild guess but worth a go? Maybe...

**Comment by jrast** [comment]
Ok, I tried to wrap the call with wine as in the CL script. Now no error is returned but the compiler still fails:

![ccrx-notworking](https://cloud.githubusercontent.com/assets/146369/25287340/478b86f8-26c1-11e7-9a02-01da24c8a26c.png)

What i tried:
 - Tried Wine from Ubuntu repo, wine and wine-devel from winehq.org
- Wrap ccrx.exe in a shell script
- Use a similar wrapper as in CL.js

Nothing seems to work... Giving up for today. Maybe I have time next week... But thanks a lot for your hints!

**Comment by mattgodbolt** [comment]
Hmm that's bewildering! Sorry it hasn't worked out: I know we've had issues before with node.js and wine noticing when processes exit, so I wonder if it's that. I've had to `strace` stuff before. :/

Keep me posted and we'll get there!

**Comment by jrast** [comment]
I tried to create a simple script to reproduce the problem, however, using this code, the compilation works:

```javascrit
var child_process = require('child_process');

var CC = "/home/jrast/Desktop/compiler-explorer/ccrx-example/CC-RX/bin/ccrx.exe"
cp = child_process.spawn('wine', [CC, '-nologo', '-isa=rxv2', '-output=src=./example.src', 'example.cpp']);

cp.stdout.on('data', (data) => { console.log(`stdout: ${data}`)})
cp.stderr.on('data', (data) => { console.log(`stderr: ${data}`)})

cp.on('error', function(err){ console.log(err) });
cp.on('close', (code) => { console.log(`child process exited with code ${code}`)})
```

**Comment by jrast** [comment]
Finaly! Got it working!! --> https://github.com/jrast/compiler-explorer/commit/62507f9a1093d381234de09e182948e4288d49c3

However, i need another hint: How is the mapping made between assembly and c++ code?

For example, for the code

```
const int a = 2;

static int square(int num) {
    int b = num * num;
    return b;
}

int doubleAndSquare(int num) {
    return a * square(num) * square(num);
}
``` 

This assembly is generated:

```
;RX Family C/C++ Compiler (V2.06.00 [07 Dec 2016])  21-Apr-2017 14:18:31

;*** CPU TYPE ***

;-ISA=RXV2

;*** COMMAND PARAMETER ***

;-output=src=output.s
;-isa=rxv2
;-optimize=2
;-size
;example.cpp

__$square(int):
                MUL R1, R1
                RTS
_doubleAndSquare(int):
                PUSHM R6-R7
                MOV.L R1, R6
                BSR __$square(int)
                MOV.L R1, R7
                MOV.L R6, R1
                BSR __$square(int)
                MUL R7, R1
                SHLL #01H, R1
                RTSD #08H, R6-R7
```
The nice linking with colors between assembly and c++ code is not available.

**Comment by mattgodbolt** [comment]
Hooray! Sorry I didn't see this earlier!

Line mappings are done by parsing the debug information. CE forces the '-g'
command line (or equivalent) to ensure the compiler outputs it. There's two
ways this is parsed (see asm.js):

- looking for .loc directives
- looking for stabs directives

The code is horrific and not my finest hour but hopefully skimming through
asm.js will give some clues.

**Comment by RabsRincon** [comment]
Closing for the lack of updates. @jrast if you have any other question, feel free to open a new issue 😄
