### ISSUE TITLE
Wrong results on hover for large 64 bit ints > 2^53 

### ISSUE THREAD

**Issue by jaredwy** [mattgodbolt/compiler-explorer#402]
From slack
https://godbolt.org/g/mIgmU4

```
dcoder [11:16 AM] 
https://godbolt.org/g/mIgmU4

[11:16] 
if you hover over the constant on the right side, it is wrong

[11:17] 
says `9223372036854775807 = 0x80000...000` instead of `= 0x7ff..ff`
```

**Comment by RabsRincon** [comment]
Wasn't it because they are too big for js?

**Comment by jaredwy** [comment]
Yup.  JS uses a double precision float to store *all* numbers. So once you hit the upper limit of the exponent you start to get strange things happening. I have a fix, just waiting for a upstream change to a package to land and i can commit it.

**Comment by mattgodbolt** [comment]
Fixed (tested locally). Nice one @jaredwy - will release to the live site shortly :)
