### ISSUE TITLE
Issue with D mangle

### ISSUE THREAD

**Issue by jeb2239** [mattgodbolt/compiler-explorer#404]
When I run make on my local machine I get this error from the D sources. I have dmd and gdc installed with the following versions:

DMD64 D Compiler v2.071.2
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
and 
gdc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

The Error:

```
make -C d
make[1]: Entering directory '/home/barriosj/compiler-explorer/d'
dmd -O -release demangle.d -ofdemangle
demangle.d(36): Error: function expected before (), not module demangle of type void
demangle.d(48): Error: function expected before (), not module demangle of type void
Makefile:5: recipe for target 'demangle' failed
make[1]: *** [demangle] Error 1
make[1]: Leaving directory '/home/barriosj/compiler-explorer/d'
Makefile:27: recipe for target 'optional-d-support' failed
make: *** [optional-d-support] Error 2
```

**Comment by mattgodbolt** [comment]
Looks like I need to update the D version I'm compiling with. I don't know much about D. Currently I build the d demangler with gdc5.2.0. If you can get it building with the newer versions I'll upgrade the D compilers on the site and use a newer demangler too.

**Comment by jeb2239** [comment]
Nope the issue was gdc vs dmd.

Dmd seems to use a command line tool called ddemangle but gdc works with your method. I am not good with the Dlang either but the current build only works with gdc, which is fine for me.

**Comment by mattgodbolt** [comment]
Ok thanks! I'll fix up the Makefile to use gcc only (for now!)

**Comment by JohanEngelen** [comment]
Fixed by this: https://github.com/mattgodbolt/compiler-explorer/pull/412
