### ISSUE TITLE
Specifying a compiler-id

### ISSUE THREAD

**Issue by wimalopaan** [mattgodbolt/compiler-explorer#411]
How to specify a compiler-id?

I made a c++.local.properties with my own compilers. However, to use the Rest-API I need a compiler id for each discovered compiler. How to specify that?

**Comment by mattgodbolt** [comment]
The compiler id comes from the properties. If you've just listed the compilers by executable, it will be their executable name. If you've listed them by ID, then the ID is the thing you should use.

By ID I mean:
```
compilers=foo:bar
compiler.foo.exe=/path/to/foo
compiler.foo.name=Foo compiler
compiler.bar.exe=/path/to/bar
compiler.bar.name=Bar compiler
```

in this case the ID will be `foo` or `bar`. If you've just listed executables:

```
compilers=/path/to/foo:/path/to/bar
```

then the ID is `/path/to/foo` etc. You can list the compilers by getting `/api/compilers`, e.g.

```bash
$ curl http://localhost:10240/api/compilers
Compiler Name | Description
/usr/bin/g++  | /usr/bin/g+
```

In this example, the ID is `/usr/bin/g++`.

Note that to use a name with slashes in it you'll need to HTML escape them, so the endpoint for my compiler above is `/api/compilers/%2Fusr%2Fbin%2Fg++/compile`. Usually it's easer to use the human-friendly names like the first example above.

Let me know if you have any other questions.

**Comment by wimalopaan** [comment]
Ok, thank you -> solved!
