### ISSUE TITLE
Colourisation oddities

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#417]
https://godbolt.org/g/fwqVVz

GCC isn't emitted any `.loc` for the first (inlined) function, which isn't our fault. However would be good to understand why lines 11/12 and 15/16 are coloured in the asm but not in the code.

**Comment by RabsRincon** [comment]
Again, the compiler responses as to what are the sources of those asm are weird numbers, way outside the number line count of the code

**Comment by mattgodbolt** [comment]
This was fixed by 476fde3
