### ISSUE TITLE
Last line of file is apparently given a phantom colour

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#418]
Consider https://godbolt.org/g/utqOtc - the last line of the file is given a colour even though nothing appears to map there. If there's no newline at the end of the file (https://godbolt.org/g/4TWIAD) then the colour overrides the actual colour given to the ret instruction.

**Comment by RabsRincon** [comment]
Monaco seems to clamp the decoration lines

**Comment by RabsRincon** [comment]
Mitigated by 9fde03a. We have to fix it still, but at least we're not showing misleading source

**Comment by mattgodbolt** [comment]
The examples appear to be OK now: the last line is highlighted as the `ret` instruction in the asm in both cases.
