### ISSUE TITLE
Missing boost libraries

### ISSUE THREAD

**Issue by mujido** [mattgodbolt/compiler-explorer#420]
I am relatively sure I remember boost libraries working before, but when I tried today they are not being found by the compiler. I've tried numerous different compilers and all fail. I also tried different parts of the boost library and wasn't able to find any that worked.

**Comment by RabsRincon** [comment]
Ey @mujido! [Nowadays Boost 1.64 is under a command line](https://github.com/mattgodbolt/compiler-explorer/issues/154#issuecomment-295576667). But ey! We plan on adding selectable include paths on the neart future, which would ease the discovery of what you can use on CE
