### ISSUE TITLE
Checking out custom libraries

### ISSUE THREAD

**Issue by cjdb** [mattgodbolt/compiler-explorer#421]
# Motivation
All too often, I copy my code to Compiler Explorer, only to realise I'm not compiling with Standard headers. I often end up with dummy code like this:

```
namespace ranges {
   using std::move;
} // namespace ranges
```

This works for simple things, but full libraries are quite difficult to import. Consider Asio, Boost, Ranges TS, etc.

# Proposal
It'd be great if we could checkout our own libraries via a textbox. Here's what I envision:

```
git https://github.com/Microsoft/GSL # master branch checked out by default
git https://github.com/cjdb/cmcstl2 numerics # numeric branch checked out
```

It'd then be possible to compile with GSL and Ranges TS without needing to make a feature request for library X, every time something novel comes around.

## How it'd work (if it is local)

```
for each url:
   git clone $url
   git checkout $branch
<compile line> -I <dir1> -I <dir2> ...
for each url
   sudo rm -rf <end of url>
```

## Concerns

Obviously, this is a terrible idea for anyone that's remote. The input needs to be sanitised, and we'd need to make sure that it isn't abused (e.g. if someone decided to checkout GCC or LLVM, the amount of space required would be enormous).

I also don't (yet) have a solid grasp for how Compiler Explorer actually works on a technical level, so the above functionality is all speculative.

# Extensions

1. For now, I think Git would be a good starting point to see if and how it works, but I'd like to see support for Subversion and Mercurial at some point.
2. Caching would be a good idea for the most popular repositories and branches: something that's frequently used (e.g. Boost, GSL, etc.) might benefit from being stored permanently to reduce system load with respect to downloads and removal. This is purely speculation at this point.

# Contacts
 @mattjegan is a developer with a keen interest in security. Perhaps you might like to follow this?

**Comment by mattgodbolt** [comment]
This is great stuff. CE runs on AWS instances, and disk space shouldn't be (too) much of a problem. Bit of a brain dump:

- Caching will be key. A `git clone` takes many seconds, and people expect interactivity (most compiles are ~200ms). Though refreshing the cache will be tough: git endpoints change all the time, so TTL needs to be short enough to make sure people see the latest...OR it just snapshots. I like the fact CE links are (essentially) immutable: this kind of breaks that as the same link will fetch different code if new commits have been added. Perhaps that OK and/or we separately should use tagged pulls.
- `git clone --depth 1` will be our friend here; though I think it interacts badly with non-default branches.
- Caching etc needs to be either 'just" local, or needs to fit into AWS somehow: CE runs on multiple throwaway AWS nodes so probably we should just use a big local disk as a cache/temporary unpack spot. This does mean there's potential for version skew between instances (if one has `git clone`d either side of a commit on two different CE nodes behind the scenes). This might suggest a global cache would be better (though trickier).
- `sudo rm -rf` ain't gonna happen :) just `rm -rf` is needed. And really I think the files should just stick in the cache until disposed of by natural LRU cacheness
- I'm not aware of many security issues around this. Obviously one would sanitize before shelling out to `git` to do the heavy lifting, but I think that's about it?
- I like the library textbox (though I'd also like it to be a check box for other libraries). Other useful "transports" would be `untar <url>.tar.gz` or similar to allow for released tarballs to be installed.

Other bugs that are relevant and might be solved: #420 #405 #397

**Comment by cjdb** [comment]
Awesome, thanks for your feedback :)
Correct me if I'm wrong, but this seems mostly like an ops issue (I have zero experience with ops, but there's a first for everything).

> A git clone takes many seconds, and people expect interactivity (most compiles are ~200ms).

That's also assuming we're cloning something small and with a reasonable download rate. I've had clones that take over an hour (not on GitHub or BitBucket). I'm thinking this implies a global cache to be necessary.

> I like the fact CE links are (essentially) immutable: this kind of breaks that as the same link will fetch different code if new commits have been added.
> Caching etc needs to be either 'just" local, or needs to fit into AWS somehow: CE runs on multiple throwaway AWS nodes so probably we should just use a big local disk as a cache/temporary unpack spot.

This isn't something that I considered. I agree that it is an issue. I guess the best thing that we can do is log the current commit for the URL, and checkout that particular commit. Two problems here:

1. We're now spending a lot of time with git :(
2. What happens when you want to checkout commit 1234 and I want checkout 12345? (Yep, saying that's 10k commits later).

> This does mean there's potential for version skew between instances (if one has git cloned either side of a commit on two different CE nodes behind the scenes). This might suggest a global cache would be better (though trickier).

Carrying on from above, the best solution I can see here is that if a commit _isn't_ specified:
 * cloning in a global cache happens if it doesn't exist, or 
 * pull/rebase if it does

Perhaps this could be a solution (it's pretty out there though):

```
# For very first use of Compiler Explorer (link1)
mkdir -p /repos/github.com/mattgodbolt
cd /repos/github.com/mattgodbolt
if [ -d 
git clone "https://github.com/mattgodbolt/compiler-explorer.git /repos/github.com/mattgodbolt/compiler-explorer
git clone /repos/github.com/mattgodbolt/compiler-explorer # this one is local
cd compiler-explorer
compiler_explorer_commit=`git rev-parse HEAD`
cd ..
g++ ...

# For next use of Compiler Explorer (link2)

cd /repos/github.com/mattgodbolt/compiler-explorer
git pull [--rebase?]
cd
git clone /repos/github.com/mattgodbolt/compiler-explorer
cd compiler-explorer
git checkout beta
compiler_explorer_commit=`git rev-parse HEAD`
cd ..
g++ ...
```

It does completely disregard your `git clone --depth 1` suggestion though.

> sudo rm -rf ain't gonna happen :) just rm -rf is needed.

Blast, you saw through my plan to get control :)
In all seriousness though, I can't remember why I thought `sudo` was a good idea.

> I like the library textbox (though I'd also like it to be a check box for other libraries).

Big things that are frequently used like Boost and range-v3? Note I'm not well-versed enough in the other languages CE supports to weigh in on them :)

> Other useful "transports" would be untar <url>.tar.gz or similar to allow for released tarballs to be installed.

I like it! I think this'll be far, far simpler than using Git too.

**Comment by mattgodbolt** [comment]
Thanks for your comments, and sorry for not replying here sooner. Lots to think about: were you thinking of taking this on, or just offering ideas and suggestions? I'm working on execution support at the moment, but this is also high on the list of "wants".

**Comment by simonvpe** [comment]
How about we can `#include` a github url and preprocess the source code to download that exact header and its dependencies?

I.e. I want to test something with my library @ https://github.com/simonvpe/cmap so I write the following code:
```c++
#include "https://github.com/simonvpe/cmap/blob/5f52e9ee0b2fc1cec152dd3df0ff194e357f1819/include/cmap.hpp"

int main() {
  using cmap::make_map;
  using cmap::map;
  constexpr lookup = make_map(map(1,17), map(65,12));
  return lookup[65];
}
```

CE proceeds to download the header file and any recursive includes except system headers.

Now the obvious drawback of this is that it doesn't easily extend to downloading dependencies for that library.

**Comment by mattgodbolt** [comment]
Hi @simonvpe that's already possible... sort of ( https://godbolt.org/g/dDKkA5 ) . CE supports #include-ing github permalink URLs. But the issue is following the include that the GH link brings in: I don't want to implement a full preprocessor which is what would be needed in order to resolve those.

**Comment by mattgodbolt** [comment]
(the reason it has to be a permalink is that GH doesn't allow other websites to load GH links without some GH API calls. The permalinks have no such restriction)

**Comment by mattgodbolt** [comment]
@cjdb and I chatted a lot on the cpplang slack and I'd like to try and capture what we discussed here. Hopefully he can correct me here if I misremember, sadly we don't have a record.

* Having some kind of "environment" script as above, with a kind of "build" step. 
  * That is; edit the git checkout rules and hit "save" to `POST` to an api endpoint to create the environment. Behind the scenes CE would do a one-time sync and checkout/whatever and assign the resulting image(/tarball?) a unique environment ID, storing its text too.
  * That EID would be stashed in the UI's save state. 
  * It would be used to POST to the compile api endpoint.
  * To "refresh" the endpoint, a new POST would be made to get a new EID.
  * Editing the script would require a GET to get the text of a given EID.
* Pros:
  * Simple, sensible caching strategy on the remote end. Solves issues with multiple instance: a local cache on the execution machine can store the unpacked environments, and some distributed key/value store can be the permanent store (or s3?).
  * `git` versions are fixed at the point of creation, meaning a permalink URL remains permanent and doesn't change under one's feet if the underlying GH repo changes. (This is arguably a drawback too for some use cases, but on balance I prefer it).
  * URLs don't get stupendously large with extra information (already a limiting factor with current strategy, though there's #272 to track this).
* Cons:
  * The environments have to live forever and might be a potential disc hog. Perhaps we can introduce "registered users" and limit unregistered creation? I don't like it, but it's an option.

We also discussed the potential for synergies with #429 - the environment building solution could use the "safe execution environment" to actually run a `bash` script to set up! That way no magic special stuff is needed or parsed: the script itself could be `git clone foo@bar.com:baz.git` and other stuff.

@cjdb what did I miss?

**Comment by cjdb** [comment]
>It would be used to POST to the compile api endpoint.

Is this referring to your idea about downloading the environment?

* We also discussed this:
```
UID -> {tarball} // cached for a bit
UID -> {mapping} // permanent
```

Other than that, looks like you've covered everything.

**Comment by pcordes** [comment]
> `git clone --depth 1`  I think it interacts badly with non-default branches.

You can use `git clone --depth 1 --no-single-branch` to get a repo with the head of every branch.  With depth greater than 1, I think you also get that many parent revs for each branch, whether or not they overlap.  `--single-branch` is implied by `--depth`, but this disables it again.

It's also possible to undo the effect of cloning with `--single-branch`, without re-cloning the repo:
http://stackoverflow.com/questions/17714159/how-do-i-undo-a-single-branch-clone.

To increase the depth after the fact, `git-fetch --depth 100` or `git fetch --unshallow`. 
 See https://stackoverflow.com/a/21217267/224132

Related: if you forgot to clone with `--recurse-submodules`, you can use `git submodule update --init --recursive` on an existing repo.

**Comment by pcordes** [comment]
I didn't read the whole thread, but it seems to me **you'd want a global cache of "bare" repos (no working tree) to avoid ever re-fetching external repos**.

**You'd *also* want local caches (per VM instance) of a checkout of whatever revision the user specified**.  Git supports a couple mechanisms for having multiple working trees sharing the same objects.  Hardlinking probably doesn't work for us, if we want the git objects global but the working trees local.  But git has another mode: `git clone --shared`, to set `.git/objects/info/alternates` to share the objects with the source repository.  https://stackoverflow.com/questions/7187088/git-how-to-create-local-repo-with-symbolic-links-to-the-git-main-repo

Do all fetching into the global bare repos, then `git reset --hard` the local checkout.

Actually, do a new `clone --shared` of the bare repo into a directory names for the repo+revision, so different sessions don't fight each other resetting the same repo back and forth.  Manage these checkouts with an LRU algorithm.  Or just delete the oldest ones without checking if they've been used, since they can be cheaply recreated.

Or instead of actually cloning, use `cp -al` on an existing `clone --shared` working tree to make a hardlink farm, then `git reset --hard` in that.  If most files haven't changed, this will be a lot faster and use a lot less space.  (I haven't tested this is safe.  I'm hoping git doesn't rewrite files in-place in the working tree or in `.git` during `reset --hard`.)

----

If a revision is needed that's not in the global cache, then wait for a fetch on it to complete before making a local repo.  (Actually, the `cp -al` of an existing revision can happen in parallel, but just wait for it to complete before trying the `reset --hard`.)

----

Corner case to handle: upstream repo edits history with `rebase` or `filter-branch`.  I guess fetch and checking out by commithash takes care of that; it's only `pull` when you care about updating local tracking branches that you need to force anything.

**Comment by sivaraam** [comment]
@mattgodbolt I addded information about the ability to `#include` a GH permalink on the wiki page. If my guess is correct you can `#include` any URL to a header file. I wasn't sure of that thought and just wanted to be sure. If that's the case the [Wiki page](https://github.com/mattgodbolt/compiler-explorer/wiki/Installed-libraries) should be updated.

**Comment by gnzlbg** [comment]
I am trying to check the assembly for some range-v3 functions using compiler-explorer online, is this possible? 

I tried: `#include <https://raw.githubusercontent.com/ericniebler/range-v3/master/include/range/v3/all.hpp>` but that header includes a bunch of other files and those fail.

**Comment by RabsRincon** [comment]
Sorry to hear that. 
GitHub header inclusion is not recursive yet as it's not an easy task to both add the functionality and don't shoot ourselves in the feet by doing so.

**Comment by gnzlbg** [comment]
@mattgodbolt must be getting tired to hear this, but could we add range-v3 master to compiler explorer? Moving from C++ Iterators to C++ Ranges is a great usability improvement, but most folks I know worry about the quality of the generated code. It would be great to have range-v3 here to both help these folks make informed decisions and also report compiler bugs.

**Comment by Yahia2** [comment]
namespace ranges {
   using std::move;
} // namespace ranges

**Comment by Yahia2** [comment]
git https://github.com/Microsoft/GSL # master branch checked out by default
git https://github.com/cjdb/cmcstl2 numerics # numeric branch checked out

**Comment by PikalaxALT** [comment]
It would appear that there are two different libraries by the name "GSL", one marketed by Microsoft (the one described in this thread) and one distributed by GNU (the GNU Scientific Library).  Is there a way to have both libraries installed without namespace collision?

**Comment by RabsRincon** [comment]
Sure thing! Can you link the gnu one?

**Comment by mattgodbolt** [comment]
I'm going to close this one for now: we have enough on our plate. @cjdb if you fancy resurrecting this some time, then feel free to do so. Trying to rationalise the number of outstanding issues, and we have plenty enough libraries set up now I think...
