### ISSUE TITLE
asm sometimes isn't an array

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#424]
In some cases the 'asm' is undefined or not an array. Usually this is if there's an error in CE itself and just an error document ("Internal compiler error") is sent back. A bit tricky to reproduce, but on my laptop I have seen it while developing.
I think a simple check for result.asm being set might do it? Not sure... the error I see locally is "no length on undefined", not this.

https://sentry.io/matt-godbolt/compiler-explorer/issues/268480152/

```
TypeError: e.asm.splice is not a function
  at result (compiler.js:402)
  at this (compiler.js:320)
  at list (ext/jquery/dist/jquery.js:3317)
  at fire (ext/jquery/dist/jquery.js:3447)
  at deferred (ext/jquery/dist/jquery.js:9272)
...
(45 additional frame(s) were not displayed)
```

**Comment by RabsRincon** [comment]
Oops! I'll fix it real quick. I did not realize that `.asm` was not always an array/defined (I supposed it would be an empty one 100%) I'll only skip the trimming, just because it has worked until now pretty well
