### ISSUE TITLE
Support execution of compiled binaries

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#429]
I really want to be able to support execution, and have been working on it. I hit a flaw, and ended up writing this essay to cover options. I put it here for reference, review and comment.

Execution
---------

## Goals

* Be able to safely execute user-supplied programs.
* (optionally) Execute the compilers in a more safe manner.

## Threat model

1. Curious internet folk seeing if they can hack the site/read files they shouldn't
   (e.g. `/etc/passwd` and the like).
2. Malicious users attempting to DoS Compiler Explorer; either taking it down or attempting
   to delete shared resources (e.g. `/opt/compiler-explorer` compilers).
3. Malicious users seeking to gain control of the site to mine bitcoin/send spam/etc.
4. As above but to attempt to steal other users' data.
5. As above but to attempt to access AWS to spin up further instances/access other services.

## Considerations

The current setup runs each AWS instance with limited privileges. Each AWS instance runs multiple
docker containers (one for each sub-site). The compilers are run inside these docker images, and each is run with an `LD_PRELOAD` wrapper that attempts to minimise the number of files the compilers can access. Additionally some command-line flags are banned (e.g. `-fplugin` type functionality).

The docker containers isolate both the node.js server and the compilers it runs from the host AWS
environment: most of the security comes from this. Over the years the `LD_PRELOAD` has become less effective: most compilers now need to look at most files in `/etc` and `/proc` etc, and so a lot
of files one might otherwise want to restrict need to be whitelisted. Additionally, some compilers
are statically linked and so cannot for `LD_PRELOAD`ed in this way.

A full breach via the compiler would expose just the one docker instance, and modifications would
be ephemeral. If the site was taken down, AWS healthchecking would kill the instance and spawn a
new one (with a fresh clean docker image), so no lasting damage would be done.

However, there's a weakness even here: the `/opt` drive is a read-write mounted EFS drive (Amazon's
network file system). Changes made here would be lasting, and would be seen by the other running
nodes immediately.

The `/opt` drive is mostly a convenience: it stores all the compilers so that each AWS node doesn't
need >20GB of compilers in its image. This allows new AWS nodes to boot quickly when load requires,
and means building a new Compiler Explorer image is also pretty quick.

All data in `/opt` can be recovered from the S3 source.

Execution of Windows compilers is achieved via `wine`. This can have a long start-up time, and requires a daemon process (`wineserver`). In order to minimise startup time, in the gcc.godbolt.org docker image the `wineserver` is run as a long-lived background process during boot. Calls to `wine` then execute quickly by attaching to this `wineserver` instance.

## Options

All these options rely on a restricted docker container to run the user executable in. The image
has very little in it; just enough to run the user program. It runs as an unprivileged user and with
(if possible) user namespaces to prevent root in that container being root on the host. It has no
setuid programs installed, and will be run without network bridges, and with restricted cgroups.

### Docker-in-docker

Compiler Explorer continues to run in docker, and uses a docker-in-docker approach. This is/was the current plan until issues were found.

By mounting `/var/run/docker.sock` from the host into the CE docker image, that docker image (with
some userid/groupid gymnastics) can launch other docker images. Thus it can in principal launch
the execution docker images.

The following issues have been found:

* It is not possible for the execution image (EI) to mount directories from the compiler image (CI).
  The non-docker implementation of the CI compiles to a random directory in `/tmp`, and then runs the EI with that temporary directory mounted as `/home/ce-user`. This doesn't work under docker-in-docker. Solutions could include mounting a well-known host directory as the `/tmp` in the CI, and then having knowledge of how to specify the real host path to this directory as the mount target in the EI. Care must be taken to only mount the one `/tmp` directory with the user's code in it in the EI, not the whole `/tmp`, else information leakage between executions is possible.
* Even when running as a restricted user, the CI must be able to talk to the docker socket. As the docker daemon runs as root on the host, this effectively gives the CI effective host root access, weakening its security considerably. The increased attack vector means targeting the compilation part to gain root on the AWS instance would be feasible.

#### Pros:

* Pretty much written

#### Cons:

* Has the above flaws and issues

### Drop the CI docker

Compiler Explorer would run on the AWS host directly. It would then use the same EI isolation techniques to run the compiler as it does to run user binaries. That way the fact it's running directly on the AWS host is "hidden". In the EI the `/opt/compiler-explorer` would probably have to be mounted (read-only), to gain access to libraries etc there (gcc's libs for example). If the compiler is run in the EI it'll need a "non-free" mount too to cover the licenses etc.

#### Pros:

* Solves compilation security holes in a similar way to execution does.

#### Cons:

* Running CE on bare AWS host opens door to more security issues there. (mitigated by compilers being run in safe way).

### Remote execution

CE/compilation as before, but executable is transmitted to a separate app to be run. That app would run on AWS directly, but would then use an EI as described above.

#### Pros:

* Most isolation from rest of activities of all techniques
* Could run on separate AWS nodes with even fewer permissions
* Could be scaled independently of the rest of the Compiler Explorer infrastructure

#### Cons:

* A new server type to administrate
* Handling serialisation of the executable and its dependencies could be tricky
* Not sure how it fits into the "compilation environment" ideas mooted with Christopher Di Bella. Though
  it might form the foundation of the "make an environment" process too.

## Other notes

* Split `/opt/compiler-explorer` into sensitive and non-sensitive areas so the licenses etc can be
  specifically unmapped.
* `wine` startup time is common to all issues: we either have to accept it or have some kind of persistent `wineserver` that can potentially leak information. Maybe `wineserver` can run in its own container and somehow be shared with all `wine` processes? Looks like wine talks via a UDS in `/tmp/.wine-$UID`. It might also be the case that the pause is long only due to the particular wine setup used: a container with a "pre-warmed" wine setup might be fast enough.

**Comment by badeip** [comment]
It would be nice if this could be added as an option for a locally running instance until the security concerns are solved.
That could possibly facilitate addressing some of the above mentioned concerns by other developers.

**Comment by mattgodbolt** [comment]
Hi @badeip - the `supportsExecute` option in the properties file turns it on. At the moment it relies on the presence of a docker `exec` image. If you don't want to hassle with that, there's a bit of code you can manually hack: in `lib/base-compiler.js` in the function `execBinary` replace the `exec.sandbox(...` call with `exec.execute(...`

**Comment by badeip** [comment]
Hi @mattgodbolt!
I tried your latter suggestion, but I don't get any program stdout, just `Compiler exited with result code 0`

**Comment by mattgodbolt** [comment]
@badeip you'll still need to have the `supportsExecute=true` property. Create a file called `etc/config/compiler-explorer.local.properties` and put `supportsExecute=true` in it too.

**Comment by badeip** [comment]
`lib/base-compiler.js:  var compileToAsmPromise = tempFileAndDirPromise.then(function (info)`

`info` contains the following:

    { 
        inputFilename: '/var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler117523-7975-jvhsfp.tqckk5ipb9/example.cpp',
        dirPath: '/var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler117523-7233-3e90vl.sb24sd1jor' 
    }

This results in `execBinary` trying to spawn `/var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler117523-7233-3e90vl.sb24sd1jor/output.s` which does not correspond to an existing path.

btw: this is on macOS

**Comment by badeip** [comment]
I only got `<No output>` in the disassembly view unless 110010 ("compile to binary and disassemble the output") was enabled,  so a GNU compatible `objdump` had to be installed and used (`brew install binutils`)
The following enables local execution for macOS:

    From 211e666af0f80593ea9139a693ac6741f4548b46 Mon Sep 17 00:00:00 2001
    From: Petter Wahlman <petter@wahlman.no>
    Date: Sun, 25 Jun 2017 17:57:24 +0200
    Subject: [PATCH] local exec on macOS

    ---
     etc/config/c++.defaults.properties            | 2 +-
     etc/config/compiler-explorer.local.properties | 1 +
     lib/base-compiler.js                          | 2 +-
     3 files changed, 3 insertions(+), 2 deletions(-)
     create mode 100644 etc/config/compiler-explorer.local.properties

    diff --git a/etc/config/c++.defaults.properties b/etc/config/c++.defaults.properties
    index 50fd7ea..ae1ad2e 100644
    --- a/etc/config/c++.defaults.properties
    +++ b/etc/config/c++.defaults.properties
    @@ -4,7 +4,7 @@ defaultCompiler=/usr/bin/g++
     compileFilename=example.cpp
     postProcess=
     demangler=c++filt
    -objdumper=objdump
    +objdumper=gobjdump
     #androidNdk=/opt/google/android-ndk-r9c
     options=
     supportsBinary=true
    diff --git a/etc/config/compiler-explorer.local.properties b/etc/config/compiler-explorer.local.properties
    new file mode 100644
    index 0000000..ca121ad
    --- /dev/null
    +++ b/etc/config/compiler-explorer.local.properties
    @@ -0,0 +1 @@
    +supportsExecute=true
    diff --git a/lib/base-compiler.js b/lib/base-compiler.js
    index 0249a5f..1690ad4 100644
    --- a/lib/base-compiler.js
    +++ b/lib/base-compiler.js
    @@ -115,7 +115,7 @@ Compile.prototype.objdump = function (outputFilename, result, maxSize, intelAsm)
     };

     Compile.prototype.execBinary = function (executable, result, maxSize) {
    -    return exec.sandbox(executable, [], {
    +    return exec.execute(executable, [], {
             maxOutput: maxSize,
             timeoutMs: 2000
         })  // TODO make config
    --
    2.10.2

**Comment by rene-aguirre** [comment]
@badeip did you get any "error: Error Error: spawn EACCES" failures?

How did you fix it?

**Comment by badeip** [comment]
@rene-aguirre yes, the `EACCESS` failure should be solved with a combination of installing GNU `binutils` and applying the patch above.

**Comment by mattgodbolt** [comment]
Thanks for that! I am so Linux-centric I had no idea it was possible to have a working compiler et al without `binutils` :)

**Comment by rene-aguirre** [comment]
@badeip Can't break the EACCESS error. I'm using latest master, it looks compiler explorer is trying to execute a .s assembly file.

I'm using homebrew's binutils and your patch.

Is there anything possible that might be missing in your changes or instructions? Would be possible you'd share a fork with your full changes to take a look?

**Comment by badeip** [comment]
@rene-aguirre also, make sure that you have highlighted `1101010` and `a.out` on the webpage.

**Comment by rene-aguirre** [comment]
Thanks @badeip, actually the error is shown when `a.out` is highlighted and no `11010` (exec by no binary).

I had tried this too, but there is only a binary listing when both binary and execution filters are selected. The log shows no failures though.

I even tried the patches (`suportsExecute` and changing `.sandbox` to `.execute`) in a docker container (to isolate any OS X issue), and got the same results, I can't see the expected "printf" output from my snippets.

Am I missing something here?, I thought the execution implies capturing any stdout from my snippet.

**Comment by colejohnson66** [comment]
Just an idea, but would it be possible to write wrappers around, say, `libc++` that the executed program would run instead? Then a custom `fopen` wrapper could be written that checks if the requested file is allowed, and if not, returns an error, but if it is, call the original `fopen`?

**Comment by mattgodbolt** [comment]
@colejohnson66 It absolutely is, and that's what we do for the compilers (see the `LD_PRELOAD` code in the `c-preload` directory). But that doesn't work all that well for security as it stands:

- It breaks for statically linked executables (already bites us for some compilers)
- Only works for apps that use `fopen` or other OS functions. It's incredibly trivial to work around if you can compile your own code, using `SYSCALL` inline assembly to talk directly to the OS in a non-trappable way.

My plans to support execution rely on virtualisation techniques (e.g. the mostly lightweight stuff that Docker does), instead of user-mode trickery.

**Comment by mattgodbolt** [comment]
I've just committed a change which enables execution by default with no sandboxing. This will allow anyone running a local server to execute their code with the minimum of fuss.

**Comment by mattgodbolt** [comment]
New notes on sandboxing, post-CppCon:

* Charlie Cloud could be an option. https://github.com/hpc/charliecloud - lacks network isolation
* https://firejail.wordpress.com/ might be an option. setuid root, but seems pretty stable
* docker's security opt might help

**Comment by hermanzdosilovic** [comment]
Hi @mattgodbolt,

Saw your talk on CppCon and just wanted to let you know what might be an option for code execution on Compiler Explorer.

I have made an [api](https://api.judge0.com) that allows you to run untrusted source code in isolated environment. Whole project is available on [GitHub](https://github.com/judge0/api). I have also made simple code editor that uses this api in the background ([link](https://ide.judge0.com)).

Currently, this API doesn't support as much GCCs as Compiler Explorer but architecture is such that adding new compiler is really easy. I also, currently, do not support compiling with custom flags.

Except GCC I have in total 43 compilers for various languages.

Take a look and let me know what you think about this idea. I will help you on my end to make this happen if you think you should go in that direction. :smiley: 

BR,
Herman

**Comment by mattgodbolt** [comment]
Thanks @hermanzdosilovic ! I'm starting to look into this more and more. I'm currently evaluating [firejail](https://firejail.wordpress.com/) but I'll be sure to check out your site and isolation technique too.

It looks like if I were to use your API I'd need your site to compile the code. That's not ideal as I of course support special builds of compiler etc as you know. Trying to match up the compiler a user selected in my UI with your compiles might be tricky, and seems a little unnecessary as I'll have already compiled their code with the right compiler :)

I took a very quick look through your code and it seems that `isolate_job.rb` is the spot where the isolation happens, and that relies on an `isolate` command. I can't find where this executable comes from, can you help me understand where this comes from? Looks like a handy utility if I wish to run my executables locally.

**Comment by hermanzdosilovic** [comment]
@mattgodbolt I am using [isolate](https://github.com/ioi/isolate). That's the command you spotted. My API is basically smart wrapper around this tool.

Yes, I understand that I would also need to compile already compiled code :smile:. If you want I could make a feature that enables you to run any binary in my isolated environment. You could compile user code (for x86_64) on your end and send me binary for me to run it. This is just an idea. I am not really sure if that would be safe on my end :smile: but it seems doable. I could make this feature in no time flat.

**Comment by mattgodbolt** [comment]
Thanks for the link. I think probably given I'm already running things locally on my instances, and have already compiled them, and have the libraries etc locally, it would be easiest to run them locally using either `firejail` or `isolate` (like you do). Thanks for the links and the kind offer of a remote service though!

**Comment by mattgodbolt** [comment]
I'm starting to work on this feature again. Will update here and the new "Execution support" project as I discover things and make any decisions.

**Comment by ilAYAli** [comment]
I decided to go down this rabbit hole again, and figured out that the main problem was incompatibility between gobjdump and clang generated executables.

```
hello.cpp: int main() { puts("hello"); }
```
`clang++ hello.cpp  && gobjdump -d ./a.out`
```
gobjdump: a.out: unknown load command 0x32
gobjdump: a.out: unknown load command 0x32
gobjdump: a.out: unknown load command 0x32
gobjdump: a.out: file format not recognized
```

After some digging I found out that 0x32 is related to this define:
```
/usr/include/mach-o/loader.h 
#define LC_BUILD_VERSION 0x32 /* build for platform min OS version */
```

I also found out that it is possible to specify the min build version with `clang++` and e.g `-mmacosx-version-min=10.1`, where 10.1 is the oldest supported version on my local build of clang 8.0.


In short:
To make execution and disassembly work on macOS with recent versions of clang:

1. add `-mmacosx-version-min=10.1 -stdlib=libc++` to your compiler flags
2. set `objdumper=gobjdump` in `etc/config/c++.defaults.properties`

**Comment by ilAYAli** [comment]
@mattgodbolt I also had to make a workaround for an error related to `Cannot read property 'on' of undefined"`, associated with streams, so I made a pull request for that.

**Comment by germandiagogomez** [comment]
I am not sure what hou are running but what I did before was:

- Docker + Ubuntu.
- Use apparmor and confine.
- limit execution time

I did not read the other comments maybe I am being too naive 😅

**Comment by mattgodbolt** [comment]
Thanks! Docker + Ubuntu are great; we're already running the processes under Docker. One tricky point is running Docker-inside-docker which is generally frowned upon and is a source of security vulnerabilities.

apparmor is great; but needs kernel support (I think!) We'd need to rebuild our images to support this feature (the default Amazon ones don't have it enabled, unless I'm missing something!)

`confine` sounds like a good thing to look upl. I'm looking at `firejail` currently for this. ("currently" is a bit of a lie, I have looked at it but haven't had time for a long while).

Limiting execution is definitely needed too =)

Thanks so much for taking the time to make suggestions!

**Comment by janwilmans** [comment]
What about running the program in an emulation inside the browser of the user? something along the lines of https://bellard.org/jslinux/

**Comment by janwilmans** [comment]
You could also think about running compiler explorer completely in Jslinux on the client side, and maybe enable to use it offline as well?

**Comment by mattgodbolt** [comment]
Good idea: but JSLinux might be too slow: booting up a whole operating system, then sending down many megabytes of dependent binaries (post compilation, I need to send both the binary and any library it uses e.g. libgcc, libstdc++.so.7 etc).

Running CE in JsLinux might be possible. Currently our base docker image which contains all the dependencies needed to fire up the site is pretty large (we have to have a full node installation, plus all the node libraries we use). And then the compilers we have available are just slightly more than 250GB which might be a limiting factor.

**Comment by janwilmans** [comment]
I agree, 250 GB might be rather large to fit inside a browser.

However, running the compiled code at the client in JsLinux, targeting _just that exact_ target, might be a good start. You would be able to have one target for running, and other targets for inspection.

Ideally, you would not boot it after every compilation, but just update the single binary.
Supporting the execution only on this target prevents you from having to send all the dependencies after compilation, we would just send them once, and keep them around.

**Comment by SoniEx2** [comment]
this may be a bit of a stretch, but... https://en.wikipedia.org/wiki/Bochs ?

**Comment by mattgodbolt** [comment]
An update with my state-of-mind now. Mostly just my own notes, in a bit of a hope to break the stalemate I currently have.

I'm convinced we need to use the same system for running compilers as running user programs. I hate the `LD_PRELOAD` stuff, and don't want to support two different mechanisms for isolation.

### Isolation approaches
* Docker-in-docker: this is a no-go for me. I don't want to propagate docker any more than I need to (if at all)
* `firejail` still seems to be the best approach: it can be locked down pretty well. It can't be run within `docker` itself though, which means either we un-docker the main image, or else custom execution instances run natively.
* Various emulation technologies (bochs, qemu) are appealing and are worth investigating but I worry about start-up times.

### Work distribution approaches
There are multiple ways to spread the (presumably greater) execution work around:
* *Run inline* (locally). If we undocker the main instance, we can run isolating technologies directly in the current web nodes. Pros: simple (other than de-dockering). Cons: we get no instance-level protection, relying totally on the isolation technique to prevent network access etc. Cons: can't smart load-balance
* *SQS* - prototype of this exists (thanks @partouf ). We post data to S3, then post a request to SQS (a queue). An EI picks up the work, executes it, and posts results back. Pros: Allows for awesome isolation and load balancing over multiple workers. Cons: uncertain latencies in both SQS send->SQS rx, and reading and writing to S3.
* *REDIS* - using REDIS as a queue. Pretty much as above, but requests can live inline, and latencies should be better. Pros: as above. Cons: requires another moving part and another instance to be the master (and/or cost of running managed instances).
* *MQ* - similar to above but using managed MQ.
* *REST requests to a separate pool*. Execution requests are POSTed via a load balancer to EIs. Pros: simple, cons: careful config of the LB to prevent external traffic, no smart queueing can be done, one node might be swamped with lots of CPU-intensive jobs while another runs idle.

All queue-based strategies have benefit of us distributing load more evenly across instances (as instances only "pull" a request when idle). The LB approach is dumber, posting all requests to an instance (which maintains its own queue in memory), and if it falls behind those requests in the queue will just be slower.

Queue-based approaches have the drawback of filling up...if we got swamped completely there's a chance we could have thousands of items in the queue to chew through before we "caught up".

Queue-based autoscaling is desireable: the number of items in the queue, or the staleness of items can be used as a metric to autoscale on.

### Other
WINE is a big problem. Any of the isolation techniques mostly rely on a short-lived, hermetic environment. WINE breaks that. Perhaps we'll need to accept that, and either drop WINE, accept slower WINE builds, or a non-hermetic environment for WINE builds.

**Comment by mattgodbolt** [comment]
In order to make forward progress, I'm going to push on with a `firejail`-based isolation execution service. This seems the best bet to me, and I have prototyped it a number of times. Whatever mechanism is used to send requests will need this as a fundamental lower layer anyway.

**Comment by SoniEx2** [comment]
if it's not too big of a deal, one idea would be to preload some environments and keep them live, and as execution is requested, spawn more of them to handle the load.

so e.g. you have 5 live idle environments:

    [ ][ ][ ][ ][ ]

someone comes along and requests a task, so you spawn another environment. it has some start-up time so you just put them in an idle environment:

    [!][ ][ ][ ][ ][.]

(where `[!]` is busy and `[.]` is idle)

you can build a linux kernel down to 7MB or less. in something like bochs you could get each of those live environments to use very little RAM (uh, 64MB?). you don't need to run the compiler in them if you don't want to, which also helps the RAM usage. might have issues with the WINE environments, tho.

**Comment by mattgodbolt** [comment]
@SoniEx2 Great ideas! Will definitely consider that as a potential solution to the WINE issue.

**Comment by mattgodbolt** [comment]
Status update: We've moved to mostly using firejail, though I've also been pointed at `minijail` and `nsjail` with the comment "They've received a lot more attention and review". One to strongly consider!

**Comment by mattgodbolt** [comment]
`gvisor` also being suggested

**Comment by shepmaster** [comment]
> * `fork`() bombs are pretty effective at taking the site down.

The [Rust playground uses Docker's `--pids-limit` option](https://github.com/integer32llc/rust-playground/blob/5c3ee96373426204dc034e9b36c784ed94cb1623/ui/src/sandbox.rs#L384) to mitigate these. Perhaps your tools have a similar configuration?

**Comment by apmorton** [comment]
Summary of conversions on slack:
- `rlimit-nproc $n` in `sandbox.profile` is indeed per jail, and will effectively mitigate fork bombs
- `nice 19` in `sandbox.profile` is probably not a bad idea. it should limit impact of cpu intensive user code on the rest of compiler explorer
- `--timeout=hh:mm:ss` on cmdline set to a longer timeout than compiler explorers internal execution timeout as a failsafe - firejail itself kills itself more reliably than we can. when firejail times out a jail, it exits silently with code 1. we should retain the existing timeout handling for well behaved user code, since it makes it clear your program was terminated due to execution time limits.
- `env GLIBC_TUNABLES=glibc.malloc.check=1` in `sandbox.profile` may be useful, since it provides at least some basic error output when you do silly things with malloc/free on a compiler using glibc
  - should look into other runtime libraries equivalent debug features as well
- apmorton/firejail@b040316ff1ec828203c92e7d2171038d4146e7a6 has been tagged as `0.9.58.2-ce-patch.2`, and should provide "Segmentation fault (core dumped)" like messages when user code crashes
- firejail patches are being upstreamed
  - `--private-cwd` https://github.com/netblue30/firejail/pull/2712
  - ~~`--deterministic-exit-code` https://github.com/netblue30/firejail/pull/2715~~ merged
  - `--terminate-orphans` pending
  - segfault output pending

**Comment by mattgodbolt** [comment]
More execution issues:
* https://godbolt.org/beta/z/KqWgt6 - clang with -stdlib=libc++ has an `LD_LIBRARY_PATH` issue (or rpath, or whatever)

**Comment by mattgodbolt** [comment]
We're getting closed folks :)

**Comment by mattgodbolt** [comment]
Latest filebans in `/run` checked in. Hopefully that's "it". Well let it bake today and then hope to deploy tomorrow...

**Comment by janwilmans** [comment]
Very nice, next week, when I'm back from vacation I'll test too

**Comment by mattgodbolt** [comment]
Ok! This is about to go live :) Thanks everyone for their invaluable help getting this done!
