### ISSUE TITLE
Missing <string> when using -m32 with x86-x64 clang

### ISSUE THREAD

**Issue by pps83** [mattgodbolt/compiler-explorer#431]
If you use `-m32` switch then [clang cannot find `<string>` header](https://godbolt.org/g/Av1RzE).
[Works with gcc](https://godbolt.org/g/p5aK34), but [fails with clang](https://godbolt.org/g/Av1RzE).

**Comment by mattgodbolt** [comment]
Try adding ` -stdlib=libc++` - this will use clang's built-in libc++ standard library instead of GCC's. I'm not sure why this is required, but hopefully you don't need to compare GCC's string implementation.

**Comment by pps83** [comment]
Thanks, works!

**Comment by pcordes** [comment]
Yup, that works for `#include <atomic>` with clang -m32 as well.

**Comment by mattgodbolt** [comment]
> Does that mean that with -m64, clang is also using gcc's headers instead of its own? Could this affect code-gen vs. what you'd get from a normal install of clang on a desktop?

Yes; it does.

However, a "normal install" of clang, as best I can tell, uses the GCC toolchain's libstdc, at least on Linux. Apple's builds I believe bundle libc++, but it's a separate project and repository for clang and so requires extra building.

**Comment by mattgodbolt** [comment]
Fixed since clang 5
