### ISSUE TITLE
opt-viewer displays post-processed source instead of original source

### ISSUE THREAD

**Issue by willkill07** [mattgodbolt/compiler-explorer#432]
Steps to reproduce:

1). click link https://godbolt.org/g/Ot7Vdm
2). click the opt-viewer button
3). ???
4). Profit (and the fact that preprocessor artifacts are seen)

```cpp
# 1 "https://gist.githubusercontent.com/anonymous/9ce324ebc4a490ecf689d784a2c22390/raw/ec488fdf550e8d481a37dd1fd8603c3fc9587319/make_aligned.hpp"
#include <memory>
// <<<< SKIPPING DOWN TO LINE 26 >>>>
# 1 "<stdin>"

#include <iostream>
#include <algorithm>
// <<<< REST OF FILE >>>>
```

**Comment by jaredwy** [comment]
Just a FYI. The red mark at the bottom with a bunch of unrelated cruft I have a fix for already. The reading of the wrong source should hopefully be an easy fix. If no one has time, I will this weekend.
