### ISSUE TITLE
number tooltips (hex) ignore leading minus sign

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#434]
e.g. `mov     eax, -17` comes up as `0x11`, not `0xffffffef`.

https://godbolt.org/g/87guwr

**Comment by RabsRincon** [comment]
Ey! I investigated this a bit and it turns out it's a Monaco (The text editor we use from Microsoft) problem. I'll leave this open as a reminder until I have more time to go and open an issue in their repo. But don't expect a quick fix. Their last commit was on the third of March :disappointed:

**Comment by mattgodbolt** [comment]
Thanks @RabsRincon I agree: even if I update the tokeniser to treat '-17' as a single token, `getWordAtPosition` still only yields the `17` part. Will see if there's a hacky workaround.

**Comment by mattgodbolt** [comment]
c.f. Microsoft/monaco-editor/issues#397
