### ISSUE TITLE
number tooltips are hard to copy/paste from (they disappear as you try to get the mouse over them)

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#435]
It's possible to get the mouse over the popup number tooltips to copy/paste the hex representation of a number.  But it's not easy: you have to move the mouse fast and accurately to go from hovering over the number to hovering over the tooltip itself, so you can double-click the number and CTRL-C.

Is it possible to make them less finicky?  Sometimes you want to copy the hex representation instead of the original decimal (or I guess vice versa for binary `objdump` mode), especially for negative numbers if you're pasting into an arbitrary-precision calculator that doesn't do 32-bit 2's complement.

I'm using chromium on Linux, in case that matters.

**Comment by RabsRincon** [comment]
@pcordes I just pushed a commit that might adress this. I can let you know once this hits the live site so you can tell me if it helps? :smile:

**Comment by pcordes** [comment]
@RabsRincon:  Sure, I can test.  Let me know when.  (And where, if it's only on the alpha site, if that's still a thing.)

**Comment by mattgodbolt** [comment]
The beta site is currently away on holiday...but I have pushed the latest code to the live site.

**Comment by RabsRincon** [comment]
Ey! Sorry to bug you with this, but have you been able to test it?

**Comment by pcordes** [comment]
@RabsRincon: Sorry for the delay.  Just re-tested and it's very easy to mouse from the number to the tooltip now.

I just noticed that the binary-mode machine-code hexdump isn't selectable, and neither are the tooltips (useful for instructions longer than 5 bytes).  I don't think I've ever wanted to copy/paste hex machine code from godbolt, but maybe someone has.  I assume those tooltips are totally separate from the number tooltips, but if it's easy to do something about it without making the page run slower in people's browsers, that might be cool.
