### ISSUE TITLE
Cannot Copy and Paste

### ISSUE THREAD

**Issue by MaeCon** [mattgodbolt/compiler-explorer#437]
I like to copy and paste my code but godbolt only allows for uploading code from files. I cannot even upload a text file with my code in it.

**Comment by mattgodbolt** [comment]
Hi: there's an issue with the menus (#359) which we are awaiting an upstream fix for. In the short term you can use the keyboard shortcuts control-C and control-V to copy and paste code.

Can you elaborate on the "I cannot even upload a text file"? Have you tried the "Load from filesystem"? Click the floppy disc icon and then choose "File system".

**Comment by mattgodbolt** [comment]
Hi @MaeCon - did this solve your issue or are you still having trouble?

**Comment by tni** [comment]
Using paste, gratuitous white space and extra braces are added.

Copy doesn't copy everything, it only copies a small part and adds an ellipsis.

So it's basically unusable.

**Comment by mattgodbolt** [comment]
Hi @tni - I've not seen this (and I use copy and paste an awful lot!) Can you put together a step-by-step reproduction for me, and also let me know which browser you're using. It certainly sounds unusable!

**Comment by tni** [comment]
I'm using the current Firefox. It's actually caused by DOM clipboard events being disabled (abused by some web sites). If I enable them things work.

It was working pretty well with clipboard events disabled a few months ago.

**Comment by mattgodbolt** [comment]
Hi @tni - thanks for letting me know it was a DOM clipboard issue on your side. I obviously can't do much about that in general.

A few months ago we were using a different editor -- we have a bug filed to have a "simple UI" #443 - but I don't have any plans to roll back to the earlier editor. I'm still hoping (with fingers crossed!) that this was the right decision to make, as a number of features now rely on Monaco.

**Comment by mattgodbolt** [comment]
Latest Monaco (f88a92ea248d51d5ba79ac2f3cbfd975f61eddf1) should fix this I hope.
