### ISSUE TITLE
`-flto` does not work with LDC

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#438]
The cmdline option `-flto=thin` (or `-flto=full`) does not work with LDC.
https://godbolt.org/g/YokGlg

LDC searches for the required LLVMgold.so plugin in the path and in LDC's own path.
LLVMgold.so has to match or be newer than the LLVM version used to build LDC, so that can become a problem. When LLVM is built with the correct option to build LLVMgold.so, LDC will copy it to its own installation and rename it to include "ldc" in the name and it will take priority over a potential LLVMgold.so in the system path.

The current image downloads the release package of LDC, and these unfortunately don't include LLVMgold.so (because of potential system incompatibilities...).

Don't know what would be a good solution here, other than building LLVM+LDC from scratch...

**Comment by mattgodbolt** [comment]
Building ldc is quite possible: if it's not too much more difficult than clang/llvm. There's already support for building clang from source in the https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build.sh file: maybe that's close to what's needed already?

**Comment by JohanEngelen** [comment]
Building LDC is easy. I'll have a closer look at the clang build script and try to come up with one for LDC. I see the clang script already contains stuff to build the LTO plugin :-)

**Comment by mattgodbolt** [comment]
Will do! I'll take a look tonight: thanks!

**Comment by mattgodbolt** [comment]
I had a quick look but for some reason the script exits with code 8 during install in my build:

```
-- Installing: /root/staging/bin/llvm-diff
-- Installing: /root/staging/bin/llvm-link
-- Installing: /root/staging/bin/llvm-rtdyld
-- Installing: /root/staging/bin/llvm-strings
-- Installing: /root/staging/lib/cmake/llvm/LLVMExports.cmake
-- Installing: /root/staging/lib/cmake/llvm/LLVMExports-release.cmake
-- Installing: /root/staging/lib/cmake/llvm/LLVMConfig.cmake
-- Installing: /root/staging/lib/cmake/llvm/LLVMConfigVersion.cmake
-- Installing: /root/staging/lib/cmake/llvm/LLVM-Config.cmake
-- Up-to-date: /root/staging/lib/cmake/llvm/.
-- Installing: /root/staging/lib/cmake/llvm/./LLVMInstallSymlink.cmake
-- Installing: /root/staging/lib/cmake/llvm/./FindSphinx.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CheckCompilerVersion.cmake
-- Installing: /root/staging/lib/cmake/llvm/./GenerateVersionFromCVS.cmake
-- Installing: /root/staging/lib/cmake/llvm/./GetSVN.cmake
-- Installing: /root/staging/lib/cmake/llvm/./LLVMProcessSources.cmake
-- Installing: /root/staging/lib/cmake/llvm/./HandleLLVMOptions.cmake
-- Installing: /root/staging/lib/cmake/llvm/./HandleLLVMStdlib.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CheckAtomic.cmake
-- Installing: /root/staging/lib/cmake/llvm/./AddOCaml.cmake
-- Installing: /root/staging/lib/cmake/llvm/./VersionFromVCS.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CheckLinkerFlag.cmake
-- Installing: /root/staging/lib/cmake/llvm/./AddLLVM.cmake
-- Installing: /root/staging/lib/cmake/llvm/./FindOCaml.cmake
-- Installing: /root/staging/lib/cmake/llvm/./LLVMExternalProjectUtils.cmake
-- Installing: /root/staging/lib/cmake/llvm/./AddSphinxTarget.cmake
-- Installing: /root/staging/lib/cmake/llvm/./TableGen.cmake
-- Installing: /root/staging/lib/cmake/llvm/./DetermineGCCCompatible.cmake
-- Installing: /root/staging/lib/cmake/llvm/./ChooseMSVCCRT.cmake
-- Installing: /root/staging/lib/cmake/llvm/./CrossCompile.cmake
-- Installing: /root/staging/lib/cmake/llvm/./AddLLVMDefinitions.cmake
root@27e8331415b7:~# echo $?
8
```

There's no obvious other error in the scroll buffer. I'll have to keep digging on my side.

**Comment by mattgodbolt** [comment]
(the llvm build was successful, this appears to be in the `make install` step)

**Comment by JohanEngelen** [comment]
Hmm, strange.  8?

**Comment by mattgodbolt** [comment]
Yes! I was perplexed too!

**Comment by JohanEngelen** [comment]
How can I help move this forward? :S

**Comment by mattgodbolt** [comment]
I'm sorry I have been busy; I meant to get back to you. The way I'm repro-ing it at the moment is through:

```
$ docker run -t mattgodbolt/clang-builder
```

then in the docker container:
```
# bash ./build-ldc.sh 1.2.0 s3://compiler-explorer/opt/
```
and watch it fail stop. You should be left with the root prompt in the docker container still running happily with the "broken" installation. I'm not quite sure what to do! Good luck, I'll try and take a look too!

**Comment by JohanEngelen** [comment]
(btw, i remember reading something about error code 8 caused by cannot write to disk or smth.. but can't find it)

**Comment by mattgodbolt** [comment]
Interesting: in errno 8 is `Exec format error` which is similarly perplexing. I have plenty of disc space...

**Comment by JohanEngelen** [comment]
Argh, a typo...
https://github.com/mattgodbolt/compiler-explorer-image/pull/27

**Comment by JohanEngelen** [comment]
Btw, the current script is not smart when it is called multiple times for different LDC versions. (repeatedly downloads gcc-6.3.0, builds LLVM, and downloads bootstrapping D compiler...)

**Comment by JohanEngelen** [comment]
(having a script like this would also enable building LDC master..... =) =) =))

**Comment by mattgodbolt** [comment]
Merged and retrying. With regards to being smart, I prefer it this way: it's easier to get reproducible builds. I'm not against an external http cache or something, but it's nice for the script to stand by itself.

Re: master builds, yes, this is exactly how I have GCC and clang master builds :)

**Comment by JohanEngelen** [comment]
It'd be good if the LLVM version could be specified as script argument. E.g.:
`./build-ldc.sh 1.1.0 3.9.0 s3://compiler-explorer/opt/`  to build LDC 1.1.0 with LLVM 3.9.0.

How to proceed from here? Change this script somehow https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh ?

**Comment by mattgodbolt** [comment]
The retry failed; I was busy so didn't have a chance to investigate but I suspect a typo.

Re: other versions of LLVM; will happily support that if there's a need for it.

The `install_compilers.sh` will need a change to load the built compiler once it's actually working. I'll take another look as to why it failed shortly.

**Comment by JohanEngelen** [comment]
I am a total docker beginner, but if I run `docker pull mattgodbolt/clang-builder` and then `docker run -it mattgodbolt/clang-builder` again, the typo `$` is still there in build-ldc.sh.

**Comment by mattgodbolt** [comment]
I haven't pushed the fix yet; sorry. Have pushed it now and fixed some
other bits and am re-running :)

**Comment by mattgodbolt** [comment]
All fixes pushed and it gets a lot further:

```
-- Found host D compiler /root/ldc110/bin/ldmd2, with default flags ''
-- Found LLVM: /root/staging (found suitable version "4.0.0", minimum required is "3.5")
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibConfig (missing: LIBCONFIG_INCLUDE_DIR LIBCONFIG_LIBRARY)
```

Any ideas?

**Comment by JohanEngelen** [comment]
Ah yes... :(  libconfig is needed for LDC < 1.3.  The ubuntu package is called `libconfig++8-dev`.

**Comment by mattgodbolt** [comment]
Cool: I'll add it to the docker image and retry later. Sorry this is taking
so long!

**Comment by mattgodbolt** [comment]
Ok....I have a built version at last :) yay!

I'm now having troubles with the runtime requirement for `libconfig.so.9` : 

```
/opt/compiler-explorer/ldc2-1.2.0/bin/ldc2
/opt/compiler-explorer/ldc2-1.2.0/bin/ldc2: error while loading shared libraries: libconfig.so.9: cannot open shared object file: No such file or directory
```

I can reimage all the CE instances to also include libconfig but before I do this (it's a bit of a pain), why might the regular ldc1.2.0 work just fine, but this home-built version not?

```
/opt/compiler-explorer/ldc1.2.0/ldc2-1.2.0-linux-x86_64/bin/ldc2 | head -4                               
OVERVIEW: LDC - the LLVM D compiler
USAGE: ldc2 [options] files --run Runs the resulting program, passing the remaining arguments to it      
```

**Comment by JohanEngelen** [comment]
Yay!

> why might the regular ldc1.2.0 work just fine

We copy libconfig.so.* to the LDC bin directory when creating the binary packages. So the buildscript here should do the same. We use this fancy piece:
```sh
    libfile=$(ldd $PKG_DIR/bin/ldc2 | grep libconfig | cut -d ' ' -f 3)
    if [ -n "$libfile" ]; then
        cp -aL $libfile $PKG_DIR/bin
    fi
```

**Comment by JohanEngelen** [comment]
Wait, maybe we can simplify things a lot. From LDC 1.3, libconfig is not needed any more.
Why not simply this: only provide CE-specific builds with LTO for LDC 1.3 onwards, and keep the current older versions simply as downloads from github packages.

**Comment by mattgodbolt** [comment]
I'm happy to give that a go :) I am out on vacation for the next week; hopefully time to get this when I get back

**Comment by JohanEngelen** [comment]
Hi @mattgodbolt , I've lost sight of this, what's the status of this? Anything you want from me?

**Comment by mattgodbolt** [comment]
Likewise! I'll have to dig in a bit more!

**Comment by mattgodbolt** [comment]
Johan: I'm so sorry I haven't looked at this. It's still on my todo list
but other things have been getting in the way recently....so sorry!

**Comment by JohanEngelen** [comment]
It's not high priority :)

**Comment by mattgodbolt** [comment]
Hi @JohanEngelen - just an apology that I haven't looked in to this still. I know it's low priority...but...no progress at all is pretty bad! Sorry :(

**Comment by JohanEngelen** [comment]
@mattgodbolt `-flto` working on CE with LDC since version 1.4.0 already :)  (we now ship the required plugin)
