### ISSUE TITLE
C++ compile error when using std::apply with clang 4.0.0.

### ISSUE THREAD

**Issue by ghjang** [mattgodbolt/compiler-explorer#440]
clang 4.0.0 has C++17 std::apply implementation. I confirmed that it works OK on my local LLVM 4.0.0 installation.

Following are test codes to reproduce the compile error. It fails with clang 4.0.0 and clang (trunk). But it succeeded with gcc 7.1 and gcc (snapshot).

Of course, I set `-std=c++1z` compiler option.

```cpp
#include <tuple>

constexpr int add(int a, int b)
{
    return a + b;
}

static_assert(std::apply(&add, std::make_tuple(10, 20)) == 30);
```

<img width="979" alt="screen shot 2017-05-26 at 3 22 22 pm" src="https://cloud.githubusercontent.com/assets/13075164/26483314/56663fca-4227-11e7-817b-d3d0f7e4020a.png">

**Comment by mattgodbolt** [comment]
Add the parameter -stdlib=libc++ to use clang's library instead of the
default GCC library.

**Comment by mattgodbolt** [comment]
I'm currently pointing clang at GCC 6.3's standard library. I should change that. Also the general confusion of which stl is being used needs to be addressed.

**Comment by jtsylve** [comment]
Note: Adding `-stdlib=libc++` to the compiler flags allows this to compile correctly.  I've resolved these sorts of issues locally by just adding that flag to the clang options in the properties file.  See: https://github.com/jtsylve/compiler-explorer-docker/commit/409fa89444bef337f1344afb535d12a783053bad

**Comment by mattgodbolt** [comment]
Just as a point: I haven't made libc++ the default as a Linux clang by default will use GCC's STL. If I were to change the behaviour then any links people have to existing clang compiles using the STL would have their compilation change unexpectedly.

**Comment by mattgodbolt** [comment]
^^-- but maybe I should change the behaviour for newer clangs going forward...

**Comment by jtsylve** [comment]
> but maybe I should change the behaviour for newer clangs going forward...

Or at least have them point to libstdc++ from gcc 7.0.0+, since that has much more support for C++17

**Comment by mattgodbolt** [comment]
Oh wow! I thought I'd already updated them to do so! Will do that at least!!! Thanks :)
