### ISSUE TITLE
compiler-explorer's MSVC lack include file "windows.h"

### ISSUE THREAD

**Issue by rongjiecomputer** [mattgodbolt/compiler-explorer#441]
Just one line, `#include <windows.h>`, can cause MSVC to throw this error:

```
example.cpp
<source>(1): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
Internal Compiler Error in Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
Compiler exited with result code 2
```

Other windows specific header files like `#include <process.h>` are fine though, weird.

**Comment by mattgodbolt** [comment]
CE runs on a Linux node with an wine-based installation of the free compilers. There's a limited amount of win32 headers available, but the windows subsystem is not (currently) available as far as I can tell.

**Comment by rongjiecomputer** [comment]
So I should file a bug to wine instead? (Not familiar with wine).

**Comment by mattgodbolt** [comment]
This is a MS installer issue; sorry. I'm not sure where `windows.h` comes from, or indeed if I can include it (license restrictions etc)

**Comment by rongjiecomputer** [comment]
Both `process.h` and `windows.h` are part of Windows 7/8/10 SDK.

Windows 10 SDK can be found [here](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk). Just install only the header files if you need to save space. CE does not do linking so libraries or other executables are not needed.

**Comment by mattgodbolt** [comment]
Thanks for the link. I'll see if it will install on `wine` - if it does we might have a solution.

**Comment by AraHaan** [comment]
If not I can compress the headers on it that I have.

**Comment by mattgodbolt** [comment]
@AraHaan thanks for the offer, but I need to be careful about licenses, so copying things from other folks' machines is a little dangerous :)

**Comment by AraHaan** [comment]
Well Windows.h includes the folowing files anyway:

```c
#include <sdkddkver.h>
#include <excpt.h>
#include <stdarg.h>
#include <windef.h>
#include <winbase.h>
#include <wingdi.h>
#include <winuser.h>
#include <winnls.h>
#include <wincon.h>
#include <winver.h>
#include <winreg.h>
#include <winnetwk.h>
#include <cderr.h>
#include <dde.h>
#include <ddeml.h>
#include <dlgs.h>
#include <lzexpand.h>
#include <mmsystem.h>
#include <nb30.h>
#include <rpc.h>
#include <shellapi.h>
#include <winperf.h>
#include <winsock.h>
#include <wincrypt.h>
#include <winefs.h>
#include <winscard.h>
#include <winspool.h>
#include <ole.h>
#include <ole2.h>
#include <commdlg.h>
#include <stralign.h>
#include <winwlm.h>
#include <ole2.h>
#include <winsvc.h>
#include <mcx.h>
#include <imm.h>
```
depending on macros and stuff that control which of these are included when they are defined (or not).

**Comment by RabsRincon** [comment]
This is not an issue anymore with the addition of the Microsoft-hosted Windows compilers

**Comment by AraHaan** [comment]
Nice, also what about if one wanted to tell the compiler to simulate having specific headers installed based upon a folder structure of a git repository? Should compiler explorer also ask for github or git repository urls to temporarily clone or download from the repository for the compilation? I recently was thinking of it.
