### ISSUE TITLE
`npm install` step in Makefile fails with newer `npm`s

### ISSUE THREAD

**Issue by Wentzell** [mattgodbolt/compiler-explorer#451]
I am using compiler explorer on mac OS Sierra.

I currently get the following error when trying to setup the explorer on my system (release branch)

```
# Workaround for lack of versioned monaco-editor in bower
rm -rf static/ext/monaco-editor
cp -r node_modules/monaco-editor static/ext/
cp: cannot stat 'node_modules/monaco-editor': No such file or directory
```

Any clue what this might be linked to?

Here is the full output of the setup
[output.txt](https://github.com/mattgodbolt/compiler-explorer/files/1052879/output.txt)

**Comment by mattgodbolt** [comment]
That's really odd. I just did a completely clean checkout and then I see in my `npm` output :

```
jshint@2.9.4 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@3.0.4 (brace-expansion@1.1.7)
├── cli@1.0.1 (glob@7.1.2)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.14, domutils@1.5.1)
└── lodash@3.7.0

monaco-editor@0.8.3 node_modules/monaco-editor

pug@2.0.0-rc.2 node_modules/pug
├── pug-runtime@2.0.3
├── pug-strip-comments@1.0.2 (pug-error@1.3.2)
```

So monaco is being pulled down ok.

If you run `npm install` by itself, do you see anything?

**Comment by Wentzell** [comment]
If I run 
```
npm install monaco-editor
```
i get
```
added 1 package in 1.176s
```
and the node_modules/monaco-editor folder exists afterwards.

**Comment by mattgodbolt** [comment]
That's very odd! Can you experiment a bit: in theory the `package.fig` includes monaco and so a flat out `npm install` should pick it up (which is what the makefile does)! Thanks!

**Comment by jsheard** [comment]
I had the same problem on Ubuntu 17.04 with Node 8.0 and NPM 5.0. The makefiles `$(NPM) install --only=production` line installs the monaco package, but then the subsequent `$(NPM) install --only=dev` line immediately removes it along with many other packages.

``` shell
josh@vm:~/Projects/compiler-explorer$ make
[snip]
/home/josh/.apps/node/bin/npm install --only=production
added 178 packages in 7.321s
/home/josh/.apps/node/bin/npm install --only=dev
added 47 packages, removed 160 packages and updated 4 packages in 6.685s
```

I'm not sure what the makefile is trying to achieve here, I just worked around it by replacing both lines with a straightforward `$(NPM) install`.

**Comment by mattgodbolt** [comment]
Ahhh I see!

Sounds like npm has changed its behaviour. The issue with doing both is that in "production environments" (that is environment variable `NODE_ENV=production` as suggested by the node folks), the `npm install` doesn't include dev dependencies (quite reasonably!). However, the setup I have needs some dev tools to complete the build...so I worked around it as a hack by forcing both dev and non-dev deps to install.

Clearly that isn't working any more: I'll have to look into a better solution. I've since moved to a better deployment strategy for release builds, but staging and beta builds still rely on this.

Thanks @jsheard for chiming in, that's one mystery solved.

**Comment by mattgodbolt** [comment]
@Wentzell would you mind testing to see if this has fixed your original issue? Thanks!

**Comment by Wentzell** [comment]
@mattgodbolt This indeed fixed the problem! Thanks

**Comment by mattgodbolt** [comment]
Great stuff: thanks for confirming
