### ISSUE TITLE
Label Filter Problems with gcc-7.1 on mac

### ISSUE THREAD

**Issue by Wentzell** [mattgodbolt/compiler-explorer#460]
For the small program
```c++
int main()
{}
```
the current release branch with all filters turned on gives the following verbose output with gcc-7.1 on mac (confirmed on different macOS versions)
```
_main:
        xorl    %eax, %eax
        ret
EH_frame1:
        .long L$set$4
        .long   0
        .byte   0x1
        .ascii "zR\0"
        .byte   0x1
        .byte   0x78
        .byte   0x10
        .byte   0x1
        .byte   0x10
        .byte   0xc
        .byte   0x7
        .byte   0x8
        .byte   0x90
        .byte   0x1
        .long L$set$5
        .long   LASFDE3-EH_frame1
        .quad   LFB0-.
        .quad L$set$6
        .byte   0
```

**Comment by mattgodbolt** [comment]
I think this is a duplicate of #320 ? The asm parser is basically unable to work out how to handle the output from OS X compilers.

**Comment by Wentzell** [comment]
That could well be! 

I just opened two because I thought it might be tied to the compiler (one for clang and one for gcc)

**Comment by mattgodbolt** [comment]
Righto! I don't understand quite what's going on myself here! I may need to borrow a mac to do some testing...

**Comment by Wentzell** [comment]
Travis has an osx image to test things on.
https://docs.travis-ci.com/user/osx-ci-environment/
But debugging there without console access would be painful.

**Comment by Wentzell** [comment]
If you have any test to run I could also do that on mine and pass you the output.

**Comment by mattgodbolt** [comment]
I _think_ this is now fixed as part of a whole bunch of changes made to the way we parse things. We added some Mac tests too. @Wentzell could you possibly confirm and close if this is fixed for you. Thanks!

**Comment by Wentzell** [comment]
Hey @mattgodbolt,

Indeed this is fixed now on master!

For the code

```c++
int main() {}
```

g++ 7.3 now gives

```
_main:
        xorl    %eax, %eax
        ret
```

while with clang 5.0.1 I get

```
_main:                                  ## @main
        pushq   %rbp
        movq    %rsp, %rbp
        xorl    %eax, %eax
        popq    %rbp
        retq
```

on Mac OS High Sierra.

**Comment by mattgodbolt** [comment]
Hooray! Thanks for checking :grin:
