### ISSUE TITLE
"Conformance" view: how many compilers build XX code (and or warnings/error view)

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#461]
Example idea: https://godbolt.org/g/zhH2YG -- how about a view where you pick N compilers and see the results of all together (green for compiles OK, amber for warnings, etc maybe?) Suggested by @adishavit

**Comment by RabsRincon** [comment]
First implementation is there. I have to yet fix some issues. PR will come shortly after it so someone can check that I have not fucked up something
