### ISSUE TITLE
Won't Run on Ubuntu on  Windows

### ISSUE THREAD

**Issue by Vm900** [mattgodbolt/compiler-explorer#463]
Hi folks,

I've been trying it out on ubuntu on windows and i keep getting this error:
![compilerexplorererror](https://user-images.githubusercontent.com/9399631/27080041-16a7e2da-5032-11e7-97e8-84a20b8635e8.PNG)

What could be the problem?
Thanks

**Comment by mattgodbolt** [comment]
Hi. I don't have any experience with this but I know @AndrewPardoe has a working version in https://github.com/AndrewPardoe/compiler-explorer which I plan to get merged once I get some spare time!

**Comment by Vm900** [comment]
Ok 
Thanks

**Comment by AndrewPardoe** [comment]
@Vm900, it looks like you're trying to get Node set up through the makefile. You might be better off to [install node.js and npm first](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), then try running make.

**Comment by Vm900** [comment]
@AndrewPardoe  Ok,i got it.Now it works.Thanks
