### ISSUE TITLE
Finer-grained compiler names ordering

### ISSUE THREAD

**Issue by hcpl** [mattgodbolt/compiler-explorer#466]
Compiler Explorer sorts compiler names by simple lexicographical string comparison.
As I see, all compiler strings are of form "binary_name + version", so they can be split up and be sorted firstly by binary_name, then by version.

Compiler list for Rust as shown at https://rust.godbolt.org:
```
rustc 1.0.0
rustc 1.1.0
rustc 1.10.0
rustc 1.11.0
rustc 1.12.0
rustc 1.13.0
rustc 1.14.0
rustc 1.15.0
rustc 1.16.0
rustc 1.17.0
rustc 1.18.0
rustc 1.2.0
rustc 1.3.0
rustc 1.4.0
rustc 1.5.0
rustc 1.6.0
rustc 1.7.0
rustc 1.8.0
rustc 1.9.0
rustc beta
rustc nightly
```

Expected output:
```
rustc 1.0.0
rustc 1.1.0
rustc 1.2.0
rustc 1.3.0
rustc 1.4.0
rustc 1.5.0
rustc 1.6.0
rustc 1.7.0
rustc 1.8.0
rustc 1.9.0
rustc 1.10.0
rustc 1.11.0
rustc 1.12.0
rustc 1.13.0
rustc 1.14.0
rustc 1.15.0
rustc 1.16.0
rustc 1.17.0
rustc 1.18.0
rustc beta
rustc nightly
```

UPD: seems like [this](https://github.com/mattgodbolt/compiler-explorer/blob/20c1332905cf13136239439a4fb4a177e35b3a6b/app.js#L147-L156) is the function responsible for comparing strings. Please correct me if am wrong.

UPD2: https://gcc.godbolt.org/ holds (most?) compiler names of form "architecture + binary_name + version", so the comparison function is going to be either language-specific or generic. It still can be made generic though, for Rust with `arch = undefined` comparator parameter for example.

UPD3: fortunately, currently there are only 2 representations shown above:
- "binary_name + version" (D, ispc, Rust)
- "architecture + binary_name + version" (C++, Go, Haskell)

**Comment by RabsRincon** [comment]
What do you think. Should architecture be grouped or not? I mean, what would seem more obvious for you?
```-AA Compiler v1
-AA Compiler v2
-BB Compiler v1
-BB Compiler v2```

**Comment by RabsRincon** [comment]
Should architecture be grouped by version? I mean, what would seem more obvious for you?
```
-AA Compiler v1
-AA Compiler v2
-BB Compiler v1
-BB Compiler v2
```
or..
```
-AA Compiler v1
-BB Compiler v1
-AA Compiler v2
-BB Compiler v2
``` 
With AA and BB being diferent architectures

**Comment by hcpl** [comment]
Personally, I need the first one more because I often compare different versions for 1 architecture. But there also can be use cases with a single version for different archs. So... both (behaviour switchable in settings)?

**Comment by RabsRincon** [comment]
I'll try to adress this on the next few days. I will let you know what comes out of it once it's done
And thanks for your suggestions too! Really appreciated :)

**Comment by hcpl** [comment]
That formatting looks good to me and is definitely better than the previous one that involves architecture-first sorting.

The most generic and user-friendly solution I can think of now is to let user to decide what order and appearance is the most appealing for him:
- Order is chosen by 2-3 comboboxes (preferably in a row container) with `Name`, `Version` and `Architecture` options. Comboboxes are in "rightwise-exclusive"<sup>1</sup> widget group. The leftmost ones are applied first in sorting compiler entries.
- General appearance is controlled by string templates, like `{arch} {name} {version}` or `{name} {version} ({arch})`.

Those two settings are independent and placed in "Settings" menu.

In case if this idea proves to be difficult or impractical to implement fully, it can still be used in backend only for future-proof scaling needs. And if this is not suitable too (works much slower than before, though I doubt this can ever happen) then simple changes should do.

<sup>1</sup> It can be explained using the following algorithm. Let's say, we have `n` comboboxes. So:
- Loop:
    1. For any `k` number of set comboboxes, `0 <= k <= n`, the user is only allowed to set at most `k+1` leftmost ones.
    2. If user saves and exits settings, use default values for remaining comboboxes but retain their state and break the loop.
    3. After setting any combobox at position `i`, `i <= k+1`, set `k = i`.

**Comment by RabsRincon** [comment]
Waiting for #476 to be merged before doing anything. Sorry for the wait!

**Comment by mattgodbolt** [comment]
Sorry; I'm working through my backlog still. Hope to get to Jared's change
soon and then we can go forward here too.

**Comment by mattgodbolt** [comment]
Jared's change is in (though I had some questions on it); hope that unblocks you :)

**Comment by DrPizza** [comment]
The way I think about this is to think about the kinds of comparisons I tend to want to make. I'm usually interested either cross-compiler, or latest compiler versus older version of the same.

I also generally don't care about very old compilers.

To that end; yes, 'trunk' should sort as "higher" than any stable release; I think it would also make sense to sort in reverse order, so trunk is the first of each compiler family, then the latest stable, and so on.

As for architecture; I think it would usually make sense to group by arch before grouping by compiler. Personally I virtually never want to see ARM or x86 results, so having them mingled with the x64 compilers that I care about would be a huge step backwards.

**Comment by RabsRincon** [comment]
Hi! Just dropping in here to let you know that, even if it's not as in-depth as we would like, semver ordering for most compilers will be implemented in the next release, which should happen "soon"
We're still looking into improving the experience, but right now, this is a good first step :)
