### ISSUE TITLE
Doesn't work in Chrome on Android.

### ISSUE THREAD

**Issue by Zingam** [mattgodbolt/compiler-explorer#469]
I tried typing some code and the input is totally messed up.

**Comment by RabsRincon** [comment]
Hello! We're pretty aware of how bad the experience is on phones is (#176 #443)
We plan on improving it at some point, but some things have higher priority than this, so give us some time!

I'll close this issue so we can organize everything about this in one of the mentioned issues above. If you have any ideas besides what's mentioned in them, please feel free to share it with us!

**Comment by Zingam** [comment]
@RabsRincon Well, actually I was reading a book on a tablet and I wanted to try some code from the book. I don't really care about phones. :)
