### ISSUE TITLE
Paths with the at (@) sign

### ISSUE THREAD

**Issue by wks** [mattgodbolt/compiler-explorer#470]
I am using Mac and Homebrew. Homebrew installs different versions of the same package into directories that contain the `@` character.  For example, I have several versions of LLVM and clang:

- `/usr/local/opt/llvm@3.7/bin/clang++`
- `/usr/local/opt/llvm@3.8/bin/clang++`
- `/usr/local/opt/llvm@3.9/bin/clang++`
- `/usr/local/opt/llvm@4/bin/clang++`

It looks like when a path contains the `@` symbol, compiler-explorer treats the path as a remote address.

# How to reproduce:

My `etc/config/c++.local.properties` contains:
```
compilers=/usr/bin/g++-4.4:/usr/bin/g++-4.5:/usr/bin/g++-4.6:/usr/bin/g++-4.7:/usr/bin/clang++:/usr/bin/g++:/usr/local/bin/g++-7:/usr/local/opt/llvm@4/bin/clang++
```

When running `./app.js`, it prints:

```
info: Fetching compilers from remote source /usr/local/opt/llvm:4
warn: Failed /usr/local/opt/llvm:4 : Error: getaddrinfo ENOTFOUND /usr/local/opt/llvm /usr/local/opt/llvm:4, retrying
warn: Failed /usr/local/opt/llvm:4 : Error: getaddrinfo ENOTFOUND /usr/local/opt/llvm /usr/local/opt/llvm:4, retrying
warn: Failed /usr/local/opt/llvm:4 : Error: getaddrinfo ENOTFOUND /usr/local/opt/llvm /usr/local/opt/llvm:4, retrying
warn: Failed /usr/local/opt/llvm:4 : Error: getaddrinfo ENOTFOUND /usr/local/opt/llvm /usr/local/opt/llvm:4, retrying
error: Too many retries for /usr/local/opt/llvm:4 : Error: getaddrinfo ENOTFOUND /usr/local/opt/llvm /usr/local/opt/llvm:4
warn: Unable to contact /usr/local/opt/llvm:4; skipping
```

But ideally, it should recognise my compiler `/usr/local/opt/llvm@4/bin/clang++`

**Comment by RabsRincon** [comment]
Hello! Sorry for taking this long to get back to you with this issue.
You're right in that we should give the choice as to wheter or not identify `@` as a remote adress. 

For this reason, I'll add an extra argument (disabled by default) to stop this behaviour. By invoking make like
```
make EXTRA_ARGS='--noRemoteFetch'
```
paths with `@` won't be treated as a remote adress to get compilers from.

In case you also need remote adresses, I recomed changing your `.properties` layout to something like
```
compilers=&gcc:&clang

group.gcc.compilers=g44:g46

compiler.g44.exe=/usr/bin/g++-4.4
compiler.g44.name=x86-64 gcc 4.4
compiler.g46.exe=/usr/bin/g++-4.6
compiler.g46.name=x86-64 gcc 4.6

group.clang.compilers=clang4

compiler.clang4.exe=/usr/local/opt/llvm@4/bin/clang++
compiler.clang4.name=x86-64 clang 4
```
which happily ignores `@` on the paths

I won't be closing this issue, in case @mattgodbolt has something else to say (when he gets the chance to!)

**Comment by mattgodbolt** [comment]
Hi!

Probably the best solution is to not name full paths in the compiler list, as @RabsRincon recommends. This gives much finer grained control. That said, I'm not against the `--noRemoteFetch` argument either, so I think both are fine solutions. Closing.
