### ISSUE TITLE
"Execute the binary" does not work for LDC

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#471]
https://godbolt.org/g/hSM9rK

LDC does not output the binary by default to `a.out`, but to `<filename>`. So that'd be `example` in CE's case (it's compiling `example.d`, iirc).

I am not sure but I think LDC cannot output the binary _and_ the LLVM IR from one compiler invocation.

**Comment by JohanEngelen** [comment]
Note: LDC has the `-run` compile switch, that compiles to a temporary binary and then executes the result.

E.g.:
`ldc -run example.d`
`ldc -O3 -g -... -whatever-user-compile-switches-here   -run example.d`

**Comment by RabsRincon** [comment]
I don't think this is right! Execution is not a ready for the live server yet! Let me double check this and I'll get back to you once I know something more about it.
(Sorry for taking so long!)

**Comment by RabsRincon** [comment]
As I expected, this feature is not intended to be live _yet_.
But the information you gave us about LDC could be really helpful once we get into finally implementing it.
Thank you :smiley:

**Comment by JohanEngelen** [comment]
(actually, I thought it would be a security hazard but currently passing `-run` doesn't work :)

**Comment by mattgodbolt** [comment]
Oh cripes, it _is_ a security issue!

https://godbolt.org/g/Jswkpx

:) oops!

We're working on execution support as the next big feature...
