### ISSUE TITLE
URL-based headers not working with CL

### ISSUE THREAD

**Issue by johnmcfarlane** [mattgodbolt/compiler-explorer#472]
[example](https://godbolt.org/g/oXowPQ)
This happens with 32 and 64-bit. Compiler output:

```
example.cpp
<source>(1): error C2019: expected preprocessor directive, found '1'
<source>(5): error C2019: expected preprocessor directive, found '1'
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
Compiler exited with result code 2
```

**Comment by mattgodbolt** [comment]
Ah yes: I insert `# <linenum>` directives in the pre-processed file to say where they come from [here](https://github.com/mattgodbolt/compiler-explorer/blob/master/static/compiler-service.js#L118) and of course that doesn't work on CL!

**Comment by mattgodbolt** [comment]
Probably changing it to the standard `#line <linenum> <filename>` might fix it?
