### ISSUE TITLE
"&" not working

### ISSUE THREAD

**Issue by vineetmhapsekar** [mattgodbolt/compiler-explorer#475]
As Keyboard input "&" is not working. Since in C++ it is required for passing parameter as reference to function.

**Comment by RabsRincon** [comment]
Sorry, I might not be understanding this correctly. 
Do you mean you can't type `&` in the code editor?

**Comment by mattgodbolt** [comment]
@vineetmhapsekar can you clarify please? If you can't get the `&` character in the editor, can you let us know:

* your operating system
* your browser and version
* can you open the javascript console and see if there are any errors there?

Thanks!

**Comment by RabsRincon** [comment]
Closing this as there has been no followup from @vineetmhapsekar. If this pops up again, feel free to reopen
