### ISSUE TITLE
Conformance view no longer working

### ISSUE THREAD

**Issue by jtsylve** [mattgodbolt/compiler-explorer#483]
Conformance views seem to be ignoring compiler flags and thus are no longer working properly.

Ex: https://godbolt.org/g/8d1kdg

**Comment by RabsRincon** [comment]
Ooops.
Thanks for reporting it. Something weird seems to be happening indeed. I'll (try to) fix it when I get home.
Give me 2-3 days :)

**Comment by RabsRincon** [comment]
Ok, fixed now!
I'll explain what happened a litle bit so we hopefuly can avoid problems like this in the future:

@jaredwy changed how we send compilation requests to the server in commit 7de967f but conformance view was not changed accordingly. This is mainly my error as I should have catched it before it hit master, so I'm sorry about that.
But! On the bright side of things, hopefuly this does not happen again with the inclusion of the new Owners feature that GitHub has recently launched and better communication as we move forward. So yay for that! :smile: 

@mattgodbolt can you do a release with this fix when you have some spare time? I would prefer for this error to get fixed the sooner, the better

**Comment by mattgodbolt** [comment]
Deploying this fix now. Thanks Rubén.
