### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by Tilka** [mattgodbolt/compiler-explorer#485]
Compilations seems to have gotten slower compared to, say, a few months ago. It often takes longer than 10 seconds, exceeds compilation time for trivial programs, or times out altogether. Sometimes old results trickle in while I already finished typing a new program, which can be quite confusing.

Might be related to #462.

Thanks for doing all this!

**Comment by mattgodbolt** [comment]
Agreed. I've noticed it too. We have seen more and more compilation time
outs which means 7.5seconds of 1/4 of the compilation power tied up for
that long. I'm not yet sure if the timeouts are "real" or they're a new and
fun way for node process control to fail.

As a huge hack I've bumped up the number of parallel compiles to 4 (from
2), and allowed the number of back end nodes to go up to 6 (from 4). Most
of the time we will be running on the minimum of two; only if CPU spikes do
new nodes come up. So far I've not noticed these 7.5s timeouts being CPU
bound. My money's on some nasty NFS caching problem now I think about it...

Thanks for raising this. We also have grand plans to improve fairness in
the queueing too, but that's a bit more off.

**Comment by mattgodbolt** [comment]
Initial investigations: maybe the periodic rescan of the compilers has reached some kind of limit: we execute all the compilers at once (with `--help` and `--target-help` amongst other thing). This is fine during startup, but with ~60 compilers `fork()`ed at once we get a sudden load average of ~30+.

Each of the larger bursts of timeouts I see in the log happen within 30s of the refresh. So I suspect it's that.

Solutions to this:
* not scanning so often
* only `fork()`ing a single compiler at a time (or just N at a time)
* memoizing the compiler by timestamp or something like that

We only rescan so I can cheekily update the "daily" built compilers by just swapping a symlink and then have all the instances notice fairly quickly on.

**Comment by mattgodbolt** [comment]
To be clear: not _all_ timeouts have this pattern. I'm now graphing timeouts over time and it's clear they've started creeping up in the last month or so. It seems unlikely they're all related to people trying out zany TMP trickery in CE, so there's still more to dig here.

**Comment by mattgodbolt** [comment]
More evidence for the timeouts...the "rust" scan of compilers seems to crush the machine. Just logged into a node and it was super laggy at even typing. In `ps` I see:

```
root     10499  0.1  0.0      0     0 ?        S    14:15   0:01 [kworker/u30:8]
root     13324  0.4  0.0      0     0 ?        S    14:23   0:00 [kworker/u30:0]
ubuntu   13500  0.1  0.1 149496  6600 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.17.0/bin/rustc --version
ubuntu   13501  0.1  0.2 149088 11620 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.16.0/bin/rustc --version
root     13502  0.1  0.0      0     0 ?        S    14:24   0:00 [kworker/u30:3]
ubuntu   13504  0.1  0.0 142284  2684 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.14.0/bin/rustc --version
ubuntu   13506  0.1  0.2 146456 11496 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.12.0/bin/rustc --version
ubuntu   13507  0.1  0.3 165024 12680 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.11.0/bin/rustc --version
root     13508  0.0  0.0      0     0 ?        S    14:24   0:00 [kworker/u30:4]
root     13509  0.3  0.0      0     0 ?        S    14:24   0:00 [kworker/u30:5]
ubuntu   13510  0.1  0.4 163920 19084 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.10.0/bin/rustc --version
ubuntu   13511  0.1  0.3 174148 16060 ?        Rs   14:24   0:00 /opt/compiler-explorer/rust-1.9.0/bin/rustc --version
ubuntu   13513  0.1  0.2 152824  8844 ?        Rs   14:24   0:00 /opt/compiler-explorer/rust-1.8.0/bin/rustc --version
ubuntu   13515  0.1  0.3 144032 14392 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.6.0/bin/rustc --version
ubuntu   13516  0.1  0.3 135212 12144 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.5.0/bin/rustc --version
ubuntu   13517  0.1  0.2 137672 10452 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.4.0/bin/rustc --version
ubuntu   13518  0.1  0.1 131732  7920 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.3.0/bin/rustc --version
ubuntu   13519  0.1  0.3 127708 12348 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.2.0/bin/rustc --version
ubuntu   13520  0.1  0.2 211084 10236 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-1.1.0/bin/rustc --version
ubuntu   13521  0.1  0.5 126968 20736 ?        Rs   14:24   0:00 /opt/compiler-explorer/rust-1.0.0/bin/rustc --version
ubuntu   13523  0.1  0.2 157196 10504 ?        Ds   14:24   0:00 /opt/compiler-explorer/rust-beta/bin/rustc --version
root     13524  0.8  0.0      0     0 ?        S    14:24   0:01 [kworker/u30:6]
root     13633  0.0  0.0  95368  3064 ?        Ss   14:24   0:00 sshd: ubuntu [priv]
ubuntu   13708  0.0  0.0  45364  2280 ?        Ss   14:25   0:00 /lib/systemd/systemd --user
root     13709  0.0  0.0      0     0 ?        S    14:25   0:00 [kworker/0:0]
```
and these persisted for many seconds. Eventually once they had completed the machine become responsive again.

**Comment by mattgodbolt** [comment]
Just updating site with the `stat`-and-only-rerun-compiler-if-changed patch.

**Comment by mattgodbolt** [comment]
so far so good; we've run over half an hour without a single timeout. whilst under moderate load too. @Tilka give the tyres a kick and see what you think too. Thanks again for reporting; it was the kick up the arse to get something actually done!

**Comment by mattgodbolt** [comment]
![screenshot from 2017-07-26 21-26-31](https://user-images.githubusercontent.com/633973/28651737-278bc204-7249-11e7-8160-92dcfd4c431d.png)

I think that's enough to declare victory (for today anyway) -- closing this bug and hoping it won't come back for a bit! Thanks all!
