### ISSUE TITLE
New feature request: ispc

### ISSUE THREAD

**Issue by ronniec95** [mattgodbolt/compiler-explorer#486]
Would love to have the ispc compiler assembler output added to this. It's not C++ but it would be a great addition to the toolbox

**Comment by RabsRincon** [comment]
You're in for a treat.
We've been supporting ispc for a month at https://ispc.godbolt.org/

:)

**Comment by RabsRincon** [comment]
I'm closing this one. Let us know if you have any suggestions regarding ispc!
