### ISSUE TITLE
Release commit 766b330ee46d763c4a06e2ec17490a178cd20949 can't find any compilers

### ISSUE THREAD

**Issue by ggnkua** [mattgodbolt/compiler-explorer#487]
Hi guys,

I have my own server running based on CE that specialises in 68000 based gcc flavours. (You can try it live at http://brownbot.hopto.org). In general I use the `release` branch and update my repo from time to time. When I tried updating it today and restarted the process using `make`, after the familiar startup messages I was met with lines like:

`warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrown-elf-gcc'
`

one line for each of the compilers I have installed on the system. When the UI came up it would not show any compiler available. I tried resetting the tree back and forth and saw that up and including commit 831f5217ffae28f957191435f719b809a5ec0d9a (which if I'm not mistaken is one commit before the latest) it works fine.

Any ideas?

Just to cover some questions: a) I did do a git reset --hard and then applied my changes (which is just etc/config/c++.defaults/properites and a few c++ example sources), b) I also tried nuking the repo, re-cloning it without any difference, c) the host machine is a raspberry pi 2 running raspbian.

Here are the 2 console logs with some paths edited out: first is the nonworking log and the second is the working.

Haskell language support disabled
D language support disabled
Rust language support disabled
make -C c-preload
make[1]: Entering directory '/----/gcc-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/----/gcc-explorer/c-preload'
/usr/local/bin/node ./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec /usr/local/bin/node -- ./app.js --language C++

Running node-supervisor with
  program './app.js --language C++'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '/usr/local/bin/node'

Starting child process with '/usr/local/bin/node ./app.js --language C++'
Watching directory '/----/gcc-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/----/gcc-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/----/gcc-explorer/etc/config' for changes.
Press rs for restarting the process.
info: properties hierarchy: defaults, dev, C++, dev.linux, linux, chinny, local
info: Reading properties from ./etc/config with hierarchy defaults,dev,c++,dev.linux,linux,chinny,local
info: Multiarch: arm-linux-gnueabihf
info: Cleaning temp dirs every 600 secs
info: Found compiler id=m68k-ataribrown-elf-gcc, exe=m68k-ataribrown-elf-gcc, name=m68k-ataribrown-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrown-elf-g++, exe=m68k-ataribrown-elf-g++, name=m68k-ataribrown-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-atari-mint-gcc, exe=m68k-atari-mint-gcc, name=m68k-atari-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-atari-mint-g++, exe=m68k-atari-mint-g++, name=m68k-atari-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataripeylow-mint-gcc, exe=m68k-ataripeylow-mint-gcc, name=m68k-ataripeylow-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataripeylow-mint-g++, exe=m68k-ataripeylow-mint-g++, name=m68k-ataripeylow-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrowner-elf-gcc, exe=m68k-ataribrowner-elf-gcc, name=m68k-ataribrowner-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrowner-elf-g++, exe=m68k-ataribrowner-elf-g++, name=m68k-ataribrowner-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrownish-elf-gcc, exe=m68k-ataribrownish-elf-gcc, name=m68k-ataribrownish-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrownish-elf-g++, exe=m68k-ataribrownish-elf-g++, name=m68k-ataribrownish-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Loading compiler from ./compilers/default
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrown-elf-gcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrown-elf-g++'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-atari-mint-gcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-atari-mint-g++'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataripeylow-mint-gcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataripeylow-mint-g++'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrowner-elf-gcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrowner-elf-g++'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrownish-elf-gcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat 'm68k-ataribrownish-elf-g++'
info: Compilers:
error: #### No compilers found: no compilation will be done!
info: =======================================
info: Listening on http://----/
info:   serving static files from 'static'
info:   git release 766b330ee46d763c4a06e2ec17490a178cd20949
info: =======================================

Haskell language support disabled
D language support disabled
Rust language support disabled
make -C c-preload
make[1]: Entering directory '/----/gcc-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/----/gcc-explorer/c-preload'
/usr/local/bin/node ./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec /usr/local/bin/node -- ./app.js --language C++

Running node-supervisor with
  program './app.js --language C++'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '/usr/local/bin/node'

Starting child process with '/usr/local/bin/node ./app.js --language C++'
Watching directory '/----/gcc-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/----/gcc-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/----/gcc-explorer/etc/config' for changes.
Press rs for restarting the process.
info: properties hierarchy: defaults, dev, C++, dev.linux, linux, chinny, local
info: Reading properties from ./etc/config with hierarchy defaults,dev,c++,dev.linux,linux,chinny,local
info: Multiarch: arm-linux-gnueabihf
info: Cleaning temp dirs every 600 secs
info: Found compiler id=m68k-ataribrown-elf-gcc, exe=m68k-ataribrown-elf-gcc, name=m68k-ataribrown-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrown-elf-g++, exe=m68k-ataribrown-elf-g++, name=m68k-ataribrown-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-atari-mint-gcc, exe=m68k-atari-mint-gcc, name=m68k-atari-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-atari-mint-g++, exe=m68k-atari-mint-g++, name=m68k-atari-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataripeylow-mint-gcc, exe=m68k-ataripeylow-mint-gcc, name=m68k-ataripeylow-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataripeylow-mint-g++, exe=m68k-ataripeylow-mint-g++, name=m68k-ataripeylow-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrowner-elf-gcc, exe=m68k-ataribrowner-elf-gcc, name=m68k-ataribrowner-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrowner-elf-g++, exe=m68k-ataribrowner-elf-g++, name=m68k-ataribrowner-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrownish-elf-gcc, exe=m68k-ataribrownish-elf-gcc, name=m68k-ataribrownish-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Found compiler id=m68k-ataribrownish-elf-g++, exe=m68k-ataribrownish-elf-g++, name=m68k-ataribrownish-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[]
info: Loading compiler from ./compilers/default
info: Gathering version information on m68k-ataribrown-elf-gcc
info: Gathering version information on m68k-ataribrown-elf-g++
info: Gathering version information on m68k-atari-mint-gcc
info: Gathering version information on m68k-atari-mint-g++
info: Gathering version information on m68k-ataripeylow-mint-gcc
info: Gathering version information on m68k-ataripeylow-mint-g++
info: Gathering version information on m68k-ataribrowner-elf-gcc
info: Gathering version information on m68k-ataribrowner-elf-g++
info: Gathering version information on m68k-ataribrownish-elf-gcc
info: Gathering version information on m68k-ataribrownish-elf-g++
info: m68k-ataribrownish-elf-g++ is version 'm68k-ataribrownish-elf-g++ (GCC) 5.4.0'
info: m68k-ataribrownish-elf-gcc is version 'm68k-ataribrownish-elf-gcc (GCC) 5.4.0'
info: m68k-ataribrowner-elf-g++ is version 'm68k-ataribrowner-elf-g++ (GCC) 7.1.0'
info: m68k-ataribrowner-elf-gcc is version 'm68k-ataribrowner-elf-gcc (GCC) 7.1.0'
info: m68k-ataripeylow-mint-g++ is version 'm68k-ataripeylow-mint-g++ (GCC) 4.6.4 (MiNT 20130415)'
info: m68k-ataripeylow-mint-gcc is version 'm68k-ataripeylow-mint-gcc (GCC) 4.6.4 (MiNT 20130415)'
info: m68k-atari-mint-g++ is version 'm68k-atari-mint-g++ (GCC) 4.6.4 (MiNT 20130415)'
info: m68k-atari-mint-gcc is version 'm68k-atari-mint-gcc (GCC) 4.6.4 (MiNT 20130415)'
info: m68k-ataribrown-elf-g++ is version 'm68k-ataribrown-elf-g++ (GCC) 6.2.0'
info: m68k-ataribrown-elf-gcc is version 'm68k-ataribrown-elf-gcc (GCC) 6.2.0'
info: Compilers: id=m68k-atari-mint-g++, exe=m68k-atari-mint-g++, name=m68k-atari-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-atari-mint-g++ (GCC) 4.6.4 (MiNT 20130415), id=m68k-atari-mint-gcc, exe=m68k-atari-mint-gcc, name=m68k-atari-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-atari-mint-gcc (GCC) 4.6.4 (MiNT 20130415), id=m68k-ataribrown-elf-g++, exe=m68k-ataribrown-elf-g++, name=m68k-ataribrown-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrown-elf-g++ (GCC) 6.2.0, id=m68k-ataribrown-elf-gcc, exe=m68k-ataribrown-elf-gcc, name=m68k-ataribrown-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrown-elf-gcc (GCC) 6.2.0, id=m68k-ataribrowner-elf-g++, exe=m68k-ataribrowner-elf-g++, name=m68k-ataribrowner-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrowner-elf-g++ (GCC) 7.1.0, id=m68k-ataribrowner-elf-gcc, exe=m68k-ataribrowner-elf-gcc, name=m68k-ataribrowner-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrowner-elf-gcc (GCC) 7.1.0, id=m68k-ataribrownish-elf-g++, exe=m68k-ataribrownish-elf-g++, name=m68k-ataribrownish-elf-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrownish-elf-g++ (GCC) 5.4.0, id=m68k-ataribrownish-elf-gcc, exe=m68k-ataribrownish-elf-gcc, name=m68k-ataribrownish-elf-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataribrownish-elf-gcc (GCC) 5.4.0, id=m68k-ataripeylow-mint-g++, exe=m68k-ataripeylow-mint-g++, name=m68k-ataripeylow-mint-g++, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataripeylow-mint-g++ (GCC) 4.6.4 (MiNT 20130415), id=m68k-ataripeylow-mint-gcc, exe=m68k-ataripeylow-mint-gcc, name=m68k-ataripeylow-mint-gcc, alias=undefined, options=, versionFlag=undefined, versionRe=undefined, compilerType=, demangler=m68k-ataribrown-elf-c++filt, objdumper=m68k-ataribrown-elf-objdump, intelAsm=, needsMulti=true, supportsBinary=true, supportsExecute=false, postProcess=[], supportsIntel=false, version=m68k-ataripeylow-mint-gcc (GCC) 4.6.4 (MiNT 20130415)
info: =======================================
info: Listening on http://----/
info:   serving static files from 'static'
info:   git release 831f5217ffae28f957191435f719b809a5ec0d9a
info: =======================================

**Comment by mattgodbolt** [comment]
I think I see what's going on. I now try and get the modification time of the compiler so I can tell if it gets updated (which only happens on CE's main website). This uses `stat` to find the files.

However, the `stat` call doesn't search `PATH`, unlike the exec calls....so, the stat fails for a non-fully-qualified path.

I'll fix this, but as a workaround try editing your properties to specify a full path to the compilers.

**Comment by ggnkua** [comment]
Hi,

I tried your suggestion and hardcoded the paths of the compilers in `etc/config/c++.defaults/properites`. Now it started up fine and seems to have got info out of the compilers. However, when I try to compile something I get `<Remote compilation failed: Not Found>` in the compiler window and `Compiler exited with result code -1` in the compiler output window.

**Comment by mattgodbolt** [comment]
Very odd, I just checked in a "real" fix too (tested locally).

Can you try your current version with `make EXTRA_ARGS="--debug"` and see if there's anything useful in the debug information? I'd like to work out what's going on here.

**Comment by ggnkua** [comment]
Sorry, I meant to edit the post above but I deleted it :/

Will try make clean then make and let you know.

**Comment by mattgodbolt** [comment]
Thanks: there's nothing really to `make clean` -- although the target exists it really only forces a refresh of dependencies (which haven't changed). By all means do it but note that if a `make clean` ever fixes anything I will treat that as a high-priority bug. I never do it myself :)

**Comment by ggnkua** [comment]
Hi again,

I ran it with `--debug` but I can't see any weird messages. But after starting I was monitoring the log and noticed that when trying to compile something I got messages like

`info: 127.0.0.1 - - [30/Jul/2017:15:08:27 +0000] "POST /api/compiler/usr/bin/m68k-ataribrown-elf-g++/compile HTTP/1.0" 404 66 "http://brownbot.hopto.org/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38"`

that 404 seems alarming there - perhaps that's the problem?

**Comment by mattgodbolt** [comment]
Ah, yes. I see the issue. So; there are two ways to define compilers: by executable (the old way) or by name (the new way). The old way doesn't support having paths in, as the API address will be wrong (containing the path of the compiler and not escaped).

The solution is either to move to the new style, or to apply the fix (in the change applied above) and then go back to unqualified names.

To go to the new style, make your `compilers` list refer to abstract IDs, and then for ID do:

```
compiler.ID.name=Some nice name here
compiler.ID.exe=/path/to/exe
```

See, for example, the `c++.amazon.properties` file which has a lot of examples. Sorry it's not at all clear; the configuration remains the wartiest part of CE.

Let me know how you get on!

**Comment by ggnkua** [comment]
First of all, thanks a lot for all the prompt replies - appreciated!

I used the new format and all seems to be fine now, so thanks for that too :)

Before I forget: make `clean && make` did not make any difference - hope I didn't make you paranoid there - I just thought of trying it out of reflex!

**Comment by mattgodbolt** [comment]
Fantastic! Glad it's working :) phew!

Also thanks for the headup on `make clean` etc - good to know!
