### ISSUE TITLE
Confusion regarding the "int" keyword.

### ISSUE THREAD

**Issue by thiagopeixoto** [mattgodbolt/compiler-explorer#489]
Hi,

There's a confusion regarding the int keyword and the int instruction. It can be confusing if we consider one who is a beginner in Assembly Language. :)

![screenshot](https://user-images.githubusercontent.com/2343178/28756491-e5843f76-7545-11e7-8e84-593068cf468b.png)

**Comment by mattgodbolt** [comment]
We already tag opcodes in the view. We should probably only popup on the opcode, not any arbitrary bit of text. Thanks for reporting this.

**Comment by RabsRincon** [comment]
I forgot to fix this by commit message, but anyway, it's now fixed as we now trust Monaco to tell us what's a keyword and what's not before trying to show the tooltip (https://github.com/mattgodbolt/compiler-explorer/commit/6ac3161fe6ca5cf69894d1f9a2041b686f282180)
