### ISSUE TITLE
Document what libraries (like Boost) are installed, and how to use them

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#490]
Boost is available if you add `-I/opt/compiler-explorer/libs/boost_1_64_0` to the compiler options.  But not by default.  (At least `#include <boost/dynamic_bitset.hpp>` isn't.

`clang -stdlib=libc++` is not really documented anywhere (outside of a couple mentions in comments on other issues), but it's a big deal.  (e.g. `std::count(v.begin(), v.end(), true)` for `std::vector<bool>` uses AVX2 vpshufb / vpsadbw to popcount, vs. scalar looping over single bits.  https://godbolt.org/g/MYd4BJ).

Are there other libraries lying around?  Like Eigen?  Or Agner Fog's VCL?

Seems like a page on the Wiki (https://github.com/mattgodbolt/compiler-explorer/wiki) would be a good place to document what's installed on your own site, even though it wouldn't apply to other installs of this codebase.  

[`#include` of github permalink URLs](https://github.com/mattgodbolt/compiler-explorer/issues/421#issuecomment-302693609)  is also undocumented, AFAIK.  If there is a documentation page somewhere, the compiler-explorer page itself should have a link.  I'm not seeing one in the menus.

**Comment by mattgodbolt** [comment]
Agreed. We always hoped these would be a stop-gap before a proper UI was developed but that hasn't (yet) happened so we should absolutely document what we have!

**Comment by sivaraam** [comment]
Any ways in which I could help with this?

**Comment by mattgodbolt** [comment]
@sivaraam Maybe adding a popup like the "Thanks to" in the "Other..." menu with the list of installed compilers. Or coming up with some other helpful way of surfacing the information!

Or I should take a look at fixing the actual problem :S - either as a stopgap with a tickbox, or as part of a full environment system. The former is quicker and easier I think.

**Comment by mattgodbolt** [comment]
@sivaraam I've made a wiki page at least. Feel free to edit/change and we'll link to it from the menu system once we're happy.

**Comment by mattgodbolt** [comment]
Link placed on menu system too. This is still really a stopgap!

**Comment by sivaraam** [comment]
> Link placed on menu system too. This is still really a stopgap!

So, you stopgapped it yourself, for now! In which case, I would like to ask something about this,

>  We always hoped these would be a stop-gap before a proper UI was developed but that hasn't (yet) hap

*Proper UI* that sounds interesting. Any ways in which I could help with that, at the least?

**Comment by mattgodbolt** [comment]
Re: _Proper UI_, yes! Some kind of repository of known include paths, and then a way of turning a list of check-boxed paths into a command-line for the compiler woudl be needed. It would need to work in both C++ and the other languages supported by CE (or at least not break them), and would also need to work with all the compilers (I think they all support `-I` so we might be OK).

**Comment by mattgodbolt** [comment]
Note that this is somewhat antagonistic with #421, where we'd ideally like a much more general solution to this problem.

**Comment by RabsRincon** [comment]
I've got an early version for a dropdown which I hope to finish in some days. 
But what @mattgodbolt says is true. We need to abstract the "I want this compilation to also include X libs" based on which compiler is doing the job, and here how litle I usually know about things like this makes it so much harder (and slower) for me to do anything, so don't expect a finished version in the nearest future.

**Comment by sivaraam** [comment]
> I've got working an early version for a lib selector which I hope to finish in some days.
So, this one is taken too! Ok that leaves me free for now OR @RabsRincon could I help you with this in any way?

**Comment by RabsRincon** [comment]
Oh, I didn't know you planned on doing this, sorry!
I have a mostly finished implementation now, BUT, if you feel up to the challenge, you could help with #505  (Only the naming links part, the unfurling is another issue)
If you need any help, feel free to ask (We have a channel on the Cpplang Slack if you want to discuss anything :) )

**Comment by sivaraam** [comment]
> Oh, I didn't know you planned on doing this, sorry!

No issues. I was just s asking if I could dive into this.

> BUT, if you feel up to the challenge, you could help with #505 (Only the naming links part, the unfurling is another issue)

I'll see to it when I'm free again. If you wish to finish that up quickly please feel free to do so because I'm not sure I would get anything solid as quickly as you can.
