### ISSUE TITLE
Permalink broke the compiler-error window

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#492]
I generated [this permalink](https://gcc.godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(j:1,source:'%23define+SIZE+1024*1024%0Aunsigned+long+sum8(unsigned+char+*__restrict__+a)+%7B%0A++++unsigned+long+sum+%3D+0%3B%0A++++for+(int+i%3D0+%3B+i%3CSIZE+%3B+i%2B%2B)+%7B%0A++++++++sum+%2B%3D+a%5Bi%5D%3B++//+compilers+suck,+and+don!'t+know+how+to+use+vpsadbw+for+this%0A++++%7D%0A++++return+sum%3B%0A%7D%0A%0A%23include+%3Cvector%3E%0A%23include+%3Ccstdint%3E%0A%23include+%3Cnumeric%3E++//+accumulate%0A%23include+%3Calgorithm%3E%0A%23include+%3Cbitset%3E%0A%0A//+very+good+with+clang+-stdlib%3Dlibc%2B%2B%0A//+otherwise+total+garbage+with+clang+and+gcc%0Auint64_t+popcnt_boolvec(const+std::vector%3Cbool%3E+%26v)+%7B%0A++++//uint64_t+sum+%3D+std::accumulate(v.begin(),+v.end(),+0ULL)%3B++//+terrible%0A++++uint64_t+sum+%3D+std::count(v.begin(),+v.end(),+true)%3B++//+terrible%0A++++return+sum%3B%0A%7D%0A%0Auint64_t+count_bitset(const+std::bitset%3CSIZE%3E+%26v)+%7B%0A++++return+v.count()%3B%0A%7D%0A%0A%23include+%3Cboost/dynamic_bitset.hpp%3E%0A//+scalar+byte+LUT%0Auint64_t+sumdynamic_bitset(const+boost::dynamic_bitset%3C%3E+%26v)+%7B%0A++++uint64_t+sum+%3D+0%3B%0A++++return+v.count()%3B%0A%7D%0A%0A//+good%0Avoid+db_and(boost::dynamic_bitset%3C%3E+%26a,+const+boost::dynamic_bitset%3C%3E+%26b)+%7B%0A++++a+%26%3D+b%3B%0A%7D%0A%0Along+db_ff(const+boost::dynamic_bitset%3C%3E+%26b)+%7B%0A++++//+pretty+good:+checks+64+bits+at+a+time,+but+doesn!'t+vectorize%0A++++return+b.find_first()%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),header:(),k:35.52330203177444,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang400,filters:(b:'0',commentOnly:'0',directives:'0',intel:'0'),options:'-stdlib%3Dlibc%2B%2B+-std%3Dgnu%2B%2B11+-Wall+-O3+-march%3Dnative+-I/opt/compiler-explorer/libs/boost_1_64_0+-fno-unroll-loops',source:1),l:'5',n:'0',o:'x86-64+clang+4.0.0+(Editor+%231,+Compiler+%233)',t:'0')),k:30.217942285737152,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g71,filters:(___0:(),b:'0',commentOnly:'0',directives:'0',intel:'0',jquery:'3.2.1',length:1,prevObject:(___0:(sizzle1501393868964:(undefined:(legend:!(34038,0,'1')))),length:1,prevObject:(___0:(jQuery321025565795414854021:(display:''),sizzle1501393868964:(undefined:(legend:!(34038,0,'1')))),length:1))),options:'-std%3Dgnu%2B%2B11+-Wall+-O3+-march%3Dnative+-fverbose-asm+-I/opt/compiler-explorer/libs/boost_1_64_0',source:1),l:'5',n:'0',o:'x86-64+gcc+7.1+(Editor+%231,+Compiler+%231)',t:'0')),k:34.258755682488406,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:76.79112008072654,n:'0',o:'',t:'0'),(g:!((h:output,i:(compiler:3,editor:1),l:'5',n:'0',o:'%233+with+x86-64+clang+4.0.0',t:'0')),header:(),l:'4',m:23.20887991927346,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4) earlier today (for [this SO answer](https://stackoverflow.com/questions/45376006/binary-matrix-multiplication-as-int-by-int-or-float-by-float-a-waste-of-resource/45392171#45392171)), and I'm sure the bottom window was for error messages for one of the compiler windows.

On re-opening the link, it's now just a blank grey window with no title.  (Everything else is correct: contents of the source window, compilers selected, their options, and window layout is exactly as I remember it.)  I don't think the error window was messed up when I generated the perm-link, but I may have just not noticed.  (There are no errors or warnings, I just forgot to close the error window before permalinking).

Any idea how this happened?  I can't repro it: creating a perma-link for a layout with an error window seems to work now.  But following that perma-link from earlier today always produces an orphan window.

**Comment by RabsRincon** [comment]
You might be onto something. Let me double check few things and I'll let you know

**Comment by RabsRincon** [comment]
This has turned out to be a known issue (#482) that does not seem to be as easy to fix I had hoped. 
Even though we know now it's a duplicated issue, I'm not closing this one as you gave us a reproducible link. Let's see if it leads to the discovery of the bug that's causing the output not to close with its compiler
