### ISSUE TITLE
clang3.8 and older broken (with some standard headers including <iostream>)

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#493]
All clang versions are now using the new libstdc++ from gcc7.1.  But clang3.8.1 and older don't support `__float128`

```
In file included from <source>:2:
In file included from /opt/compiler-explorer/gcc-7.1.0/lib/gcc/x86_64-linux-gnu/7.1.0/../../../../include/c++/7.1.0/cstdlib:77:
/opt/compiler-explorer/gcc-7.1.0/lib/gcc/x86_64-linux-gnu/7.1.0/../../../../include/c++/7.1.0/bits/std_abs.h:102:3: error: support for type '__float128' is not yet implemented
```

The most obvious casualty is that `#include <iostream>` can't compile, because it ultimately includes `<cstdlib>` 

**Using `-stdlib=libc++` fixes it.**

[example here](https://gcc.godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(j:1,source:'+%23include+%3Ciostream%3E%0A//%23include+%3Ccstdlib%3E%0A//+doesn!'t+compile+with+clang3.7.1+without+-stdlib%3Dlibc%2B%2B%0A//+because+gcc7.1!'s+libstdc%2B%2B+is+too+new+for+older+clang'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:48.21142552055527,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang371,filters:(___0:(),b:'0',commentOnly:'0',directives:'0',intel:'0',jquery:'3.2.1',length:1,prevObject:(___0:(sizzle1501838729350:(undefined:(legend:!(61,0,'1')))),length:1,prevObject:(___0:(jQuery32100049214251650744331:(display:''),sizzle1501838729350:(undefined:(legend:!(61,0,'1')))),length:1))),options:'-stdlib%3Dlibc%2B%2B+-std%3Dgnu%2B%2B11+-O3+-fverbose-asm',source:1),l:'5',n:'0',o:'x86-64+clang+3.7.1+(Editor+%231,+Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:48.21142552055527,l:'3',n:'0',o:'',t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang381,filters:(___0:(),b:'0',commentOnly:'0',directives:'0',intel:'0',jquery:'3.2.1',length:1,prevObject:(___0:(sizzle1501838729350:(undefined:(legend:!(10,0,'1')))),length:1,prevObject:(___0:(jQuery32100049214251650744331:(display:''),sizzle1501838729350:(undefined:(legend:!(10,0,'1')))),length:1))),options:'-std%3Dgnu%2B%2B11+-O3+-fverbose-asm',source:1),l:'5',n:'0',o:'x86-64+clang+3.8.1+(Editor+%231,+Compiler+%232)',t:'0')),k:50.36705819540843,l:'4',m:31.038251366120218,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:2,editor:1),l:'5',n:'0',o:'%232+with+x86-64+clang+3.8.1',t:'0')),header:(),l:'4',m:68.96174863387978,n:'0',o:'',s:0,t:'0')),k:51.78857447944475,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by RabsRincon** [comment]
Clang should now work again
