### ISSUE TITLE
Investigate BOM stripping in URLs

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#494]
Via Fiora on twitter: https://pastebin.com/c0aJhuVQ seems goo.gl strips BOMs and causes issues... We should really use our own shortener...but see if there's a work around, maybe?

**Comment by colejohnson66** [comment]
The Pastebin is unavailable

**Comment by mattgodbolt** [comment]
Oh, good point. I hadn't realised it would time out.... :(  I guess we'll hang on for another report. Closing for now.
