### ISSUE TITLE
Can't get ARM output in the Rust compiler

### ISSUE THREAD

**Issue by kscz** [mattgodbolt/compiler-explorer#496]
I was hoping that adding `--target=arm-unknown-linux-gnueabihf` to the rust compiler flags would get me arm output, but I get:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `arm-unknown-linux-gnueabihf` target may not be installed
error: aborting due to previous error
Compiler exited with result code 101
```
Same issue for `thumbv7em-none-eabi`, and all the `arm` prefixes targets in this list (output truncated for readability):
```
`--> rustup target list                                                
aarch64-apple-ios
aarch64-linux-android
aarch64-unknown-fuchsia
aarch64-unknown-linux-gnu
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armv7-apple-ios
armv7-linux-androideabi
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabihf
armv7s-apple-ios
```

Is there any way to have the standard libraries installed for at least `armv7-unknown-linux-gnueabihf` and `arm-unknown-linux-gnueabihf`?  I haven't read through the setup code for the images which run godbolt, but if you're just using docker or something similar, it should be as easy as adding these lines to the setup scripts (assuming you're using rustup):
```
rustup target add arm-unknown-linux-gnueabihf
rustup target add armv7-unknown-linux-gnueabihf
```

Anyway, I'll take a look and see how painful it is to add it myself and generate the PR, but I figured I would create the issue to track the problem regardless!

**Comment by kscz** [comment]
Ah! looking through, it appears this should be a PR against `compiler-explorer-image` as well as this repo.

I think all I need is for [this line](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh#L83) to have an option to download:
* https://static.rust-lang.org/dist/rust-1.19.0-arm-unknown-linux-gnueabihf.tar.gz
* https://static.rust-lang.org/dist/rust-1.19.0-armv7-unknown-linux-gnueabihf.tar.gz

I can probably handle this tonight if no one else has time

**Comment by mattgodbolt** [comment]
Thanks @kscz - I'll add the arm compilers in.

**Comment by mattgodbolt** [comment]
@kscz It wasn't quite as straightforward: older rusts don't have those downloads, and I'm not sure we can install them all in the same directory (as duplicating those lines would do). I'll investigate more, but if you know more or can implement/test it yourself, please do!

**Comment by kscz** [comment]
@mattgodbolt glarg! As is perhaps obvious my "I'll handle this tonight" comment was hilariously optimistic.  The short set of comments is:
* You'll only be able to get back until Rust 1.8 for armv7 because that was when it was [added as a supported platform](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#misc-10) (and things like [1.13 contains misgeneration](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html#other-notable-changes))
* I *think* all we need to do is change the `NAME` variable to be `VERSION-architecture-triple-here` instead of just the version number, so that `1.19.0-x86_64-unknown-linux-gnu` is separate from `1.19.0-armv7-unknown-linux-gnueabihf` etc such that they don't cause a version conflict... (i.e. just pop the architecture triple off [here](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh#L62) and add it on [these lines](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_compilers.sh#L123-L138))
  * unfortunately I haven't mucked through enough of the rest of the code to know what would need to change to accommodate a new path for each menu item in the main interface!

I'll definitely take a look once my life has calmed down slightly... maybe this weekend?  Mostly a question of the time to setup the necessary infrastructure so that I can actually test my PR before I send it your way!
