### ISSUE TITLE
not able to get LLVM IR for rust and D

### ISSUE THREAD

**Issue by andjo403** [mattgodbolt/compiler-explorer#497]
wanted to compare the LLVM IR for c++, rust and D but was only able to get the IR for c++.
- for Rust when I add the argument " --emit=llvm-ir" I get the assembler  and a warning: "due to multiple output types requested, the explicitly specified output file name will be adapted for each output type"
- for ldc when I add the argument "-output-ll" I only get the assembler 

I guess that the IR is not shown due to other file name is generated for the IR files.
is it maybe possible to add a "show LLVM IR output" button like the "show ast output"?

**Comment by mattgodbolt** [comment]
Good idea; I've been wanting to add syntax colouring for LLVM IR too. Should support all of these things.

**Comment by jaredwy** [comment]
I have pushed a fix for this for rust :)

**Comment by mattgodbolt** [comment]
That fix is merged, and will deploy this weekend.

**Comment by JohanEngelen** [comment]
@jaredwy To help you: for LDC, specifying `-output-s -output-ll` will generate both an `.s` file with assembly, and `.ll` with LLVM IR. If you don't specify an output file (`-of <filename>`), LDC will use the input filename minus the `.d`: example.d --> example.s (for `-output-s`) or example.ll (for `-output-ll`). You can override that with e.g. `ldc2 example.d -output-ll -of example.s`, which will write LLVM IR to example.s.

**Comment by jaredwy** [comment]
Great Ill take a look over this later. Shouldn't be too hard to wire up.

**Comment by JohanEngelen** [comment]
much obliged, it is very useful functionality

**Comment by CryZe** [comment]
Btw, does anyone know how to get clang to show the LLVM IR before it went through the optimization passes. With rustc, I can just pass -C no-prepopulate-passes but I couldn‘t figure out how to get clang to do the same.

**Comment by JohanEngelen** [comment]
In the meanwhile, for LDC you can use these flags to see LLVM IR: `-output-s=false -output-ll` and then I like to add `-gline-tables-only` to get rid of all the `llvm.dbg.declare` clutter.

**Comment by JohanEngelen** [comment]
@mattgodbolt How shall I go about implementing LLVM IR support? Shall I make a new view (similar to e.g. the AST view), or a toggle inside the assembly view (similar to binary view)?
The LLVM IR view would need some specific filter buttons, such as filtering comdat specification (lots of cluttering), removing debug declarations (terrible cluttering), ... So perhaps better to do this in a separate view at first?

**Comment by mattgodbolt** [comment]
@JohanEngelen I think a new view is probably best; as you say. I'm not quite sure how the UI will work, but in my experience the best thing to do is to start somewhere and see how it comes out!

**Comment by mattgodbolt** [comment]
Thanks @JohanEngelen . Ideally we'd roll it into the asm view; but sketching it as a separate view is a good start. We can take a look. You're absolutely right about the public API -- any "view" is effectively part of the public API. So, finding a way to make it part of the regular asm view is probably best. Thanks!
