### ISSUE TITLE
AST view requires a recompile to work

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#499]
Repro steps:

* Visit https://godbolt.org/g/ZoiJQp
* Drag the AST tree down, notice no output in the window.
* Make a trivial edit in the editor (e.g. hit newline)
* Observe the AST pops up

Expected: the AST view is populated on creation

**Comment by mattgodbolt** [comment]
From scratch repro:
* Reset UI
* Pick clang
* Drag down the AST view
* Observe AST view has `<No output>`
* Make a trivial edit; see the AST springs to life

**Comment by TartanLlama** [comment]
I'll hopefully be able to get to this in the next few weeks, but an currently sans computer at home due to a series of unrelated incidents.

**Comment by mattgodbolt** [comment]
Thanks @TartanLlama -- might be able to take a look in regards to finding similar issues in the opt view (cf #500)

**Comment by jaredwy** [comment]
Had thought I hs fixed this. Seems to be something else not sending the
compile. I will look this afternoon.

**Comment by mattgodbolt** [comment]
Any thoughts @jaredwy ?

**Comment by RabsRincon** [comment]
So, turns out there was an easier way to fix this. Just move the compilation logic to the event handlers on the compiler, just as we do on the editor.

The same goes for #500
