### ISSUE TITLE
Optimization view requires manual addition of -fsave-optimization-record

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#500]
To repro:

* Visit https://godbolt.org/g/viu1Mj
* Observe opt view is populated with source but no annotations.
* add `-fsave-optimization-record`
* Observe opt view now has annotations, but no source
* Make a trivial edit to the source.
* Observe opt vie is now correctly populated

Expected: opt view is populated correctly from initial creation

**Comment by mattgodbolt** [comment]
I just retried this and got a case where the "annotations but no source" didn't happen. Not sure what triggers that.

**Comment by jaredwy** [comment]
I will look into this this afternoon.

**Comment by jaredwy** [comment]
Ok. I couldn't reproduce this at first. 
I think I figured out how you got into that state. I had to hazard a guess by reading code. 

I have put a PR up. Unfortunately since that URL has stashed a bad state, i don't think it will ever work.

But it should prevent it going forward.

**Comment by mattgodbolt** [comment]
Thanks! This is much improved! The AST button is broken (it's missing a `_.bind(..., this);` but that's easy to fix.

However I can still break it:
* Go to main page, reset UI
* Pick clang
* Drag down an opt view
* Observe everything works now, yay
* Modify the options to `-O2`
* opt view now empty - unexpected (it has the annotations but no source in it)
* Make a trivial change, opt view now populates.

This also works if you click the opt view instead of clicking it.

**Comment by mattgodbolt** [comment]
Merged: this is fixed. There's some potential to unify the fix with #499 and maybe to fix by ensuring the initial view/drag creation forces a recompile/redraw too? Discussed with @jaredwy on slack.
