### ISSUE TITLE
Environment from calling process not forwarded

### ISSUE THREAD

**Issue by h-2** [mattgodbolt/compiler-explorer#502]
It seems like only the variables PATH and HOME are passed to the compile process environment. This can be problematic in certain cases, e.g. I have a custom CCACHE_PATH that needs to be forwarded. Are there reasons for not passing the entire env?

Thanks!

**Comment by mattgodbolt** [comment]
There's no reason other than I needed to specify some other environment variables, and it appears if one supplies the `env` parameter to `child_process.exec()` then the existing environment is not preserved.

The code to return the environment passed to compilers is in `lib/compilations-env.js`, so it should be fairly easy to update to grab the existing environment and modify that, should you need it, or to pass through a set of whitelisted environment variables.
