### ISSUE TITLE
armcc 5 support for compiler-explorer

### ISSUE THREAD

**Issue by ggnkua** [mattgodbolt/compiler-explorer#510]
Hi,

A few months ago as an experiment I tried adding support for arm's armcc. Long story short armcc doesn't have gcc compatible arguments by default but there is a switch that enables that. So I was able to add a compiler to `c++.defaults.properties` that points to a very simple script:

```
#!/bin/sh
export ARMLMD_LICENSE_FILE=port@server_ip
armcc --translate-gcc "$@"
```

This made compiler-explorer detect armcc as a viable compiler and after that it was usable (of course things like highlighting matching code with matching assembly didn't work but that's not a big concern).

I know that this is not useful in general as (AFAIK) armcc isn't freely available but I thought I'd just share the info :).

**Comment by mattgodbolt** [comment]
Thanks for this!

**Comment by shyun3** [comment]
According to the [ARM documentation][arm-doc], it should be `--translate_gcc` with the underscore. There's also a `--translate_g++` option.

[arm-doc]: https://developer.arm.com/products/software-development-tools/compilers/arm-compiler-5/docs/dui0472/latest/compiler-command-line-options/-translate_gcc

**Comment by mattgodbolt** [comment]
Thanks for this. I'm not sure how `armcc` fits into the general ecosystme of ARM compilers (@willlovett ?) but we now have the HPC compilers available. Closing this to keep the issue tracker relevant, but thanks again for the info.
