### ISSUE TITLE
Error: Nothing to unbind for editorChange

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#512]
https://sentry.io/matt-godbolt/compiler-explorer/issues/343125608/

```
Error: Nothing to unbind for editorChange
  at this (ext/golden-layout/dist/goldenlayout.js:292)
  at iteratee (hub.js:162)
  at _ (ext/underscore/underscore.js:153)
  at self (hub.js:161)
  at this (compiler.js:186)
...
(12 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
Seems something that came in with the newer GoldenLayout. I bet it's my fault somehow, either on the GL side or the `hub.js` side.

**Comment by RabsRincon** [comment]
Added some workarounds to at least allow for pane closure until we find the root cause in 39b8bbeb85d2ad5cdf9c53a34f3b2740f1de2d56
