### ISSUE TITLE
Multiline raw string literals not formatted correctly

### ISSUE THREAD

**Issue by SuperWig** [mattgodbolt/compiler-explorer#513]
Only the first line of raw string literal is formatted as a string.
```
R"(This is a multiline
raw string literal)"
```
So "raw string literal" would show up as normal code.

**Comment by mattgodbolt** [comment]
This is an issue in the upstream Monaco C++ mode, but we've worked around its issues before. Thanks for the report.

**Comment by RabsRincon** [comment]
Relevant monsco-languages file https://github.com/Microsoft/monaco-languages/blob/master/src/cpp.ts

**Comment by RabsRincon** [comment]
Filled https://github.com/Microsoft/monaco-editor/issues/703 to let them know

**Comment by mattgodbolt** [comment]
I'm going to remove this from the bug fix iteration we're on: we're dependent on the downstream fix for this, without a lot of work.

**Comment by RabsRincon** [comment]
The Monaco team has added support for raw strings in the upcoming update. We just have to wait now! 👍

**Comment by RabsRincon** [comment]
Monaco 0.11 has now been released and will hit the live site some time this week. :D
