### ISSUE TITLE
C++ name demangling loses $ from immediate operands (AT&T syntax)

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#515]
This happens only `static` symbols but not global variables with static storage, because apparently globals aren't name-mangled in C++.

test case: https://godbolt.org/g/ESvgs7

We get `movl    foo, %eax` from the compiler-emitted
 `movl    $_ZL3foo, %eax`.

Intel-syntax mode is fine, showing `mov     eax, OFFSET FLAT:foo`

Normally it's not confusing, but if you're doing something weird and you're trying to check that the compiler's giving you an immediate instead of a load, it's a problem: https://godbolt.org/g/9VgRfB
(https://stackoverflow.com/questions/34467092/inline-64bit-assembly-in-32bit-gcc-c-program#comment64418850_34467109)

**Comment by mattgodbolt** [comment]
Thanks for the report! Will have a think; no obvious solution springs to mind but we are already doing more than just `c++filt` in some cases.

**Comment by mattgodbolt** [comment]
This is interesting. Seems `c++filt` strips the leading dollar if it recognizes a symbol as being mangled, but not otherwise:

```
~ $ echo '$_ZL3foo' | c++filt
foo
~ $ echo '_ZL3foo' | c++filt
foo
~ $ echo '$foo2' | c++filt
$foo2
```

**Comment by mattgodbolt** [comment]
The GNU folks replied:

https://twitter.com/gnutools/status/956183399898796032

>Maybe the comment in the code: /* _ and $ are sometimes found at the start of function names in assembler sources in order to distinguish them from other names (eg register names).  So skip them here.  */

**Comment by mattgodbolt** [comment]
Will be fixed in an upcoming site update.

**Comment by mattgodbolt** [comment]
Fix is now live. Thanks @partouf
