### ISSUE TITLE
Feature request: line wrapping of error messages

### ISSUE THREAD

**Issue by thecppzoo** [mattgodbolt/compiler-explorer#519]
C++ errors many times include things related to templates that lead to large error messages, it is not practical to see just 30% of the text in the screen while the space is mostly empty vertically

**Comment by RabsRincon** [comment]
This one is being trickier than anticipated, and I really hoped to finish this one in 5 mins... . CSS is not colaborating with me, so give me some more time until I get lucky and achieve the overflowing result that I'm looking for.
Sorry for the wait! :smile:

**Comment by RabsRincon** [comment]
This took a while! I have had to change a bit of how we handled the output UI, but it's now done! 
I'm so sorry it took so long in the first place.

This should hit the live site soon (this week)

Closed by 75b0735f6d285f81a5dbc4dfc61a93c917f699b6

**Comment by thecppzoo** [comment]
Hello, @RabsRincon thanks for the feature, I am using it all the time, apologies for taking so long to thank you, kept forgetting
