### ISSUE TITLE
Clang on godbolt returns a different result

### ISSUE THREAD

**Issue by dcci** [mattgodbolt/compiler-explorer#527]
The following example yields two different results when compiled locally and on compiler explorer.

**Comment by dcci** [comment]
https://godbolt.org/g/NsMVRG

**Comment by dcci** [comment]
The triple for clang is the same, x86_64-unknown-linux (clang version is 5.0, although I'm sure it reproduces also with 4.0 etc..)
In particular, the online version seems to completely remove the call to `foo()` and the second printf . This is fine, as the program exhibits UB (missing return for the entry block of `foo()`.

The version compiled locally seems a little more gentle:
```
0000000000400520 <main>:
  400520:       50                      push   %rax
  400521:       8b 35 09 0b 20 00       mov    0x200b09(%rip),%esi        # 601030 <__TMC_END__>
  400527:       bf f0 05 40 00          mov    $0x4005f0,%edi
  40052c:       31 c0                   xor    %eax,%eax
  40052e:       e8 ad fe ff ff          callq  4003e0 <printf@plt>
  400533:       c7 05 f3 0a 20 00 01    movl   $0x1,0x200af3(%rip)        # 601030 <__TMC_END__>
  40053a:       00 00 00
  40053d:       bf f0 05 40 00          mov    $0x4005f0,%edi
  400542:       be 01 00 00 00          mov    $0x1,%esi
  400547:       31 c0                   xor    %eax,%eax
  400549:       e8 92 fe ff ff          callq  4003e0 <printf@plt>
  40054e:       31 c0                   xor    %eax,%eax
  400550:       59                      pop    %rcx
  400551:       c3                      retq
  400552:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
  400559:       00 00 00
```

**Comment by dcci** [comment]
And the intermediate:
```
; Function Attrs: norecurse nounwind uwtable
define i32 @foo() local_unnamed_addr #0 {
entry:
  store i32 1, i32* @blah, align 4, !tbaa !2
  ret i32 undef
}

; Function Attrs: nounwind uwtable
define i32 @main() local_unnamed_addr #1 {
entry:
  %0 = load i32, i32* @blah, align 4, !tbaa !2
  %call = tail call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i32 %0)
  %call1 = tail call i32 @foo()
  %1 = load i32, i32* @blah, align 4, !tbaa !2
  %call2 = tail call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i32 %1)
  ret i32 0
}
```

To clarify, both versions are valid, but these days as godbolt is used as the de-facto way of sharing the output of the compiler (at least, I use it a lot in LLVM bugzilla and code reviews ;), it would be interesting to understand why the output differs. Presumably there's some flag mismatch, I didn't check myself.

**Comment by mattgodbolt** [comment]
By default CE's clang uses GCCs STL. To make it use libc++ try adding
-stdlib=libc++ and see if that fixes the issue.

**Comment by dcci** [comment]
Thanks for the attempts :)
No, it's same (adding `-std=libc++` to CE cmdline). That's unfortunate, but not entirely unexpected.
In particular, I don't see how a different standard library can be the cause of the issue (unless operating in WHOPR/LTO, which this one is not).
In particular, it seems that the optimizer in one case is replacing instructions (entire blocks :) with unreachable, while in the other case it just zaps the return value (replacing with undef) but still leaves around the store of `1` to the global.

I'll investigate further, once I get a minute, but IMHO the problem is either:
1) in the IR emitted by the frontend (in this case clang)
2) In one of the xforms.

**Comment by dcci** [comment]
Oh, it seems to be the former.
On godbolt, the frontend already emits a couple `llvm.trap` + `unreachable`, i.e. the code produced at `-O0` is:

```
; Function Attrs: noinline nounwind optnone uwtable
define i32 @foo()() #0 {
  %1 = alloca i32, align 4
  store i32 1, i32* @blah, align 4
  call void @llvm.trap()
  unreachable
  ; No predecessors!
  %3 = load i32, i32* %1, align 4
  ret i32 %3
}
```

While the code I see emitted locally is:
```
define i32 @foo() #0 {
entry:
  %retval = alloca i32, align 4
  store i32 1, i32* @blah, align 4
  %0 = load i32, i32* %retval, align 4
  ret i32 %0
}
```

Now I wonder why this difference :)

**Comment by mattgodbolt** [comment]
Very perplexing. I build clang from, and pass it GCC 7.2's toolchain. The build scripts are in mattgodbolt/compiler-explorer-image - let me know if you want to dig more down that route.

**Comment by zygoloid** [comment]
@dcci Is it possible that you're compiling the testcase as C locally? Your example code has defined behavior in C, but not in C++.

**Comment by mattgodbolt** [comment]
@zygoloid I think has the answer here. Adding `-x c` has the semantics you describe: https://godbolt.org/g/E8KEE2 - @dcci let me know if you can corroborate this, and we can put this bug to bed (yay!)

**Comment by dcci** [comment]
Confirmed, thanks. This can be closed now.
