### ISSUE TITLE
"Reset UI layout" menu entry also resets code and compiler options!

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#528]
Suggest relabelling "Reset (code and UI layout)", because it would suck a lot for someone to click that and lose something they were working on.

It doesn't reset your saved editor settings, so "Reset (everything)" wouldn't be appropriate.

  (I just clicked it because I wondered what it did while I was looking for the "library dropdown" that https://github.com/mattgodbolt/compiler-explorer/wiki/Installed-libraries mentions, but I don't see it anywhere.)

**Comment by RabsRincon** [comment]
Sorry to hear that, but you're right, that should be renamed! Thanks for the heads up

Hint: The dropdown is only available at the beta site (https://godbolt.org/beta/).
😄

**Comment by pcordes** [comment]
> Sorry to hear that

I didn't lose anything myself, I was in a tab that I'd already posted a permalink to; I just saw the potential for danger.

**Comment by RabsRincon** [comment]
You're right. I should have stated it more clearly. I've edited the wiki to reflect that the dropdown is a beta thing for now.
Thanks for your help!
