### ISSUE TITLE
allow demangling to be disabled

### ISSUE THREAD

**Issue by zygoloid** [mattgodbolt/compiler-explorer#532]
I use compiler explorer to investigate how a range of compilers handle certain code patterns, and one of the things I care about is how they mangle names. Applying a demangler to the assembly output therefore makes the stock Compiler Explorer installation useless to me for this purpose (especially because demangling is lossy).

**Comment by mattgodbolt** [comment]
Thanks! This is a duplicate of #285 but definitely underlines how important this should be. We'll prioritise accordingly.

**Comment by mattgodbolt** [comment]
In case you missed it; we fixed #285 and the update's been pushed to the live site. Thanks again for reporting it!
