### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by wa120** [mattgodbolt/compiler-explorer#538]
hi, may I include header file "arm_neon.h" and dump vector assembly likes vadd instruction or v0,v1...v15 registers ?

**Comment by mattgodbolt** [comment]
Absolutely. If you pick the ARM compilers you can see these instructions and include that header, provided you tell the compiler to target the right processor: https://godbolt.org/g/JWw8XM for example. Let me know if you have any other isseus

**Comment by wa120** [comment]
Thanks!
