### ISSUE TITLE
Support MSVC name unmangling

### ISSUE THREAD

**Issue by nunoplopes** [mattgodbolt/compiler-explorer#541]
It would be nice to support MSVC name unmangling. It's easy to do: just call the undname tool. It works well with wine.

```
$ wine undname '?h@@YAXJ@Z' 2> /dev/null
Microsoft (R) C++ Name Undecorator
Copyright (C) Microsoft Corporation. All rights reserved.

Undecoration of :- "?h@@YAXJ@Z"
is :- "void __cdecl h(long)"
```

**Comment by mattgodbolt** [comment]
CC @andrewpardoe - is there an unmangler for msvc?

**Comment by AndrewPardoe** [comment]
Yes, the undname tool: https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names#Undecorated

**Comment by mattgodbolt** [comment]
Perfect. I should learn to use a search engine! (Bing maybe? :))

**Comment by AndrewPardoe** [comment]
That is what I used, as a matter of fact!  But it helps to know what you're looking for _a priori_.

**Comment by Trass3r** [comment]
To be closed?
It does not demangle lambdas correctly, but I guess that is a problem with undname.
Or maybe a newer version of the tool is required.

**Comment by partouf** [comment]
there are some exceptions because of the Wine environment, otherwise undname is used, so yes, this can be closed.
