### ISSUE TITLE
ICC16 and ICC17 missing

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#542]
They're still in the dropdown on beta, but the license is expired.  I assume that's why they're gone from the dropdown on the main site.

https://godbolt.org/g/ykbQAm

(I assume this is a known issue, but reporting it in case others miss it and come looking.)

**Comment by mattgodbolt** [comment]
Oh wow! I hadn't noticed. Thanks so much...

**Comment by mattgodbolt** [comment]
I'm at CppCon and was talking with Erich from Intel who gave me the licenses in the first place...I'll track hi down and work out what's going on!

Can't believe we hadn't noticed this...

**Comment by mattgodbolt** [comment]
The license expired two days ago...working on a new one!

**Comment by mattgodbolt** [comment]
icc17 is now back! Yay :)

**Comment by mattgodbolt** [comment]
And we're back on both! Thanks for the report!

**Comment by mattgodbolt** [comment]
Seems to be a few caching problems still, reopening until I'm happier

**Comment by mattgodbolt** [comment]
Ok, I had forgotten to restart the beta service to clear its cache. Done now.
