### ISSUE TITLE
Update MSVC

### ISSUE THREAD

**Issue by stevefan1999-personal** [mattgodbolt/compiler-explorer#543]
RTW version is way too old...

Also how the hell I cannot `#include <windows.h>`? It is not MinGW so I thought I can still play around WinAPI.

**Comment by mattgodbolt** [comment]
We are working on a better solution (CC @andrewpardoe ) - currently we're running the compilers under WINE which means they don't have `<windows.h>` or similar. In future we hope to run them on a Windows node which will give us all the versions and a real compilation environment,

**Comment by danilaml** [comment]
Would be nice if it was updated to at least 15.3 version (I think it should be available on NuGet if that's what you are using). There were quite a few nice C++17 support/conformance updates in it.

**Comment by Trass3r** [comment]
There is now a "MSVC Pre 2018" option. Not sure why it is called like that though. It should rather be named after the VS update, 15.7 etc.

**Comment by ubsan** [comment]
@Trass3r working on it!

**Comment by partouf** [comment]
The latest compilers have now been updated to CE, and also support Windows SDK includes like windows.h

The WINE compilers will not support this.
