### ISSUE TITLE
Add Eigen Matrix Library to library list. 

### ISSUE THREAD

**Issue by Nomadluap** [mattgodbolt/compiler-explorer#552]
It would be interesting to see how code is generated for the  [Eigen matrix library](http://eigen.tuxfamily.org/index.php?title=Main_Page) under different optimization levels. 

Could this library be added to the library list?

**Comment by mattgodbolt** [comment]
Should be pretty straightforward. Note for implementors, can we use a versioned directory for this one: extract it to `/opt/compiler-explorer/libs/eigen/v3.4.3` (or similar). Should be pretty easy, will take a look tonight unless someone else gets to it.

**Comment by RabsRincon** [comment]
Which versions should be added? Latest and which more?

**Comment by mattgodbolt** [comment]
As a start I'd probably just put the latest version, unless @Nomadluap needs a specific version?

**Comment by Nomadluap** [comment]
Anything version 3+ would work for me.

**Comment by mattgodbolt** [comment]
Will be in next site update

**Comment by themightyoarfish** [comment]
It does not seem to be available for me: https://godbolt.org/z/MYb5YPzfv

**Comment by mattgodbolt** [comment]
@themightyoarfish pick it from the library dropdown:

![Screenshot 2023-09-26 at 7 02 46 AM](https://github.com/compiler-explorer/compiler-explorer/assets/633973/00f8435a-71a4-43a6-ba82-f69694511378)

The library is the book icon four from the left.

Search for or browse for Eigen:

![Screenshot 2023-09-26 at 7 03 25 AM](https://github.com/compiler-explorer/compiler-explorer/assets/633973/0f05ef27-c236-4e23-b969-55ebd74d52a4)

Pick a version:
![Screenshot 2023-09-26 at 7 03 25 AM](https://github.com/compiler-explorer/compiler-explorer/assets/633973/2629a8b9-b10b-4d68-ac4b-b4a5329a237c)

Close the window and Eigen will be there for you: https://godbolt.org/z/sYE98hEs5
