### ISSUE TITLE
highlighting disabled when 11010 (compile to binary) is turned on.

### ISSUE THREAD

**Issue by badeip** [mattgodbolt/compiler-explorer#553]
OS: macOS High Sierra
Compiler Explorer commit hash: 83ff138

simple `return 42` disassembly:

**compile to binary not enabled, correct colouring:**

<img width="267" alt="screen shot 2017-10-05 at 22 37 16" src="https://user-images.githubusercontent.com/1106732/31251341-ec7c5112-aa1d-11e7-9633-3c275e90a2af.png">

**compile to binary enabled, no colouring:**

<img width="259" alt="screen shot 2017-10-05 at 22 37 28" src="https://user-images.githubusercontent.com/1106732/31251336-e788d7d4-aa1d-11e7-9e36-ade537b640d6.png">

**Comment by mattgodbolt** [comment]
Thanks for the report: will investigate.

**Comment by RabsRincon** [comment]
Note that this is not exclusive to MacOs. Happens on the live site too

**Comment by badeip** [comment]
I can confirm that the fix works for MacOS (also).
Good work.
