### ISSUE TITLE
Get GCC's backend debug dumps (RTL)

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#561]
When developing in GCC, I very often compare RTL dumps for different passes in the backend. Having them available in compiler-explorer will help my day-to-day work. I've already started a prototype, and if you think it could be interesting, I could polish it when ready and push a PR....?

**Comment by mattgodbolt** [comment]
Would love to have a PR for such a thing. Let us know if you need any help with it!

**Comment by dkm** [comment]
Thanks ! I'm still new to all this javascript idioms and frameworks, so it may take some time before my ugly prototype is good for merge.
Currently, I'm using a some `*Sync()` methods that should probably be forced async instead (fs accesses).

Regarding files, it looks like all files are automatically cleaned by the temp module, which forces me to read and store in memory all the dumps. When the user selects a given pass in the drop-down menu, it simply gets what is stored in memory.... But in some cases, dumps can be really big, so having the files would probably be better than loading all of them.

Can you confirm that files are getting cleaned when the compiler has been executed and all callbacks are finished ? (and that when the user starts playing with the UI, the files are already gone).

**Comment by honggyukim** [comment]
Hi, thanks for suggesting this feature. I would also be great if compiler explorer can provide the output of `-fdump-tree-gimple` or `-fdump-tree-optimized` in my humble opinion.

The output of that option provides high level understanding of how complicated C++ programs are destructured while it still preserves the source format that is more readable than assembly output.

**Comment by dkm** [comment]
I guess this is straightforward, as long as you don't expect to link dumps to source code. Simply getting the text file displayed in a window is easy (and what I am planning to do).

**Comment by mattgodbolt** [comment]
Hi @dkm 

To answer your questions: yes, files are automatically cleaned by the temp module as soon as the compilation process has completed and results have been read out.

It's worth realising that in general Compiler Explorer (the main website at least) runs on a cluster of computers, and user requests will likely not go back to the same machine they first compiled on. So even if we left temporary files around for a while, and hoping the user can load a new one as they change "dump" settings in the UI won't work.

I'm thinking you'll have to recompile ech time, and pick the one dump the user has asked for. As time ticks on we can improve the caching etc, and even move to a distributed cache for the main site.

So yes, by the time the user is in the UI the files are gone, and likely as not their requests won't hit the same node when they recompile/change UI settings.

I'm happy to discuss more: feel free to join us on the cpplang slack: https://cpplang.now.sh/ for more interactive discussion.

Thanks! Matt :)

**Comment by mattgodbolt** [comment]
@honggyukim This is also a great idea, thanks!

**Comment by dkm** [comment]
@mattgodbolt ok, thanks for the reply. I will keep that in mind :). I'll join the slack next time I'm hacking this, thanks !

**Comment by honggyukim** [comment]
> @honggyukim This is also a great idea, thanks!

@mattgodbolt Thanks for considering it!

**Comment by mattgodbolt** [comment]
So, prototype is on the beta site: https://godbolt.org/g/92nDRj yay!

Some things I spotted:

* The icons now spill onto a new line (on my setup at least). We need a more scalable solution for these things.
* I found myself wanting to open two views (with different passes) and then diff them. If we relax the constraint of only having one open (unlike the Clang AST etc) then it should be pretty easy to teach the differ to diff RTL too.
* Syntax colouring would be nice; it's pretty straightforward to do - I designed all the novel modes in https://microsoft.github.io/monaco-editor/monarch.html :)
* Obviously I have to come up with a solution to the ordering problem. Now I have the code locally I'll take a look.

Looking good! Thanks so much for the contribution @dkm !

**Comment by dkm** [comment]
* not sure I understand. If you are talking about the 'Pass filter' and 'Pass dump to display' being on 2 separate lines, that's expected. I was trying to make things easier to read/understand...
* diffing would be really great. That would be really really helpful !
* syntax coloring was in my mind. I wanted to open a PR for that, but was waiting a bit, I've already used a bit of your time :). Problem is that not all passes uses the same lang. The backend uses RTL, but the earlier passes use gimple. I was thinking of a way to keep track of this and use the correct language highlight setup.

**Comment by RabsRincon** [comment]
Point 1 refers to the compiler icons. I'm on the middle of generalizing buttons that open another panel so this should not worry you (I should finish it sooner than later)

For point 3, note that if you know which pass you're in, you can tell monaco editor which language is it, and if you add a definition for said language, it will handle the colouring nicely

**Comment by mattgodbolt** [comment]
Please never worry about the time...your patience is appreciated but we want CE to continue to improve :)

Thanks, yes @RabsRincon is right for point one I meant the compiler icons. He's on the case! (Yay Rabs)

For point 2. cool - do you think it would be OK to enable multiple views? I think it would be OK anyway...I can take a look at this if you aren't quite sure.

Point 3: I'd be happy to start off without and add it later, and I can help if needed too.

**Comment by dkm** [comment]
After re-reading, I realized I did not understand correctly your point 2. In fact, diff 2 passes will mostly shows garbage as each passes prints loads of debug info that are specific. Sometimes it even has RTL duplicated so a single function will have its RTL several times in the same file.
I'm less sure about the gimple dumps as I never use them, so maybe diffing them would be meaningful... I'm convinced that the code won't work with multiple views as there are some values stored in compiler.js : it should be easy to store values for each views...

point3: I'll have a look. I already have some ideas that I need to test :) 

Thanks for your time !

**Comment by mattgodbolt** [comment]
re: 2 Ahhh I see. I was thinking it might output something useful, but playing around a bit and I see what you mean!

Great stuff!

(PS I just made a mailing list if you don't want to or can't join the `#ce_implementors` group on slack. All the details are in the new README.md!)

**Comment by dkm** [comment]
I've joined the slack channel :) See you there !
