### ISSUE TITLE
Remove LD_PRELOAD stuff

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#564]
It doesn't work anyway, a better isolation process is required (in progress)

**Comment by jason-s** [comment]
Is there a workaround? I have a Windows PC with node.js and npm installed, just trying to run this on an embedded cross-compiler.

**Comment by mattgodbolt** [comment]
Hi @jason-s  - a workaround for what? Which part is failing - the LD_PRELOAD stuff is only used if you have a compiler-wrapper configured (which is off by default).

**Comment by RabsRincon** [comment]
Is this still an issue with firejail/nsjail now in place?

**Comment by apmorton** [comment]
LD_PRELOAD is indeed removed since the introduction of firejail/nsjail

**Comment by mattgodbolt** [comment]
Yay! Thanks for clearing up....so nice to see the issue count change in a decreasing way...
