### ISSUE TITLE
D: "demangle" button does not work

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#565]
The new "demangle" toggle button is nice!
But it does not yet work for the D language.

**Comment by mattgodbolt** [comment]
Good point. Thanks for continuing to help us keep CE working well for D language users!

**Comment by RabsRincon** [comment]
Ey Johan! Sorry for taking this long to get to this... 

I've been trying to fix this, but I can't compile D on my local version of CE (Getting `<Error during post processing: 127>` and `stderr: 'bash: d/demangle: No such file or directory\n',` if I look deeper) so I'm trying to look for a workaround.
If in the meanwhile you do find why it does not work on the live site, please please let us know, I'd love to fix this and make the D experience better on CE

**Comment by JohanEngelen** [comment]
Do you get compile errors for `d/demangle.d`?

(btw in the past, demangling did work for D)

**Comment by mattgodbolt** [comment]
Oh good point. On the live site the D compiler is built with some travis magic (from the .travis.yml)

```
before_script:
    - export PATH=$PATH:$PWD/out/compilers/ghc/bin
    - export PATH=$PATH:$PWD/out/compilers/gdc/x86_64-pc-linux-gnu/bin
    - export PATH=$PATH:$PWD/out/compilers/rust/bin
```

It's possible that isn't working, which would explain the lack of demangling? Rabs; if you need to build the D thing locally try something like:

```
$ make GDC=/opt/compiler-explorer/gdc5.2.0/x86_64-pc-linux-gnu/bin/gdc
```

**Comment by JohanEngelen** [comment]
btw, since release 1.3.0, the LDC binary package includes `ddemangle`. So there should be a `/opt/compiler-explorer/ldc1.3.0/ldc2-1.3.0-linux-x86_64/bin/ddemangle` on the server.

**Comment by RabsRincon** [comment]
Sorry. Matt was right, the `d/demangle.d` was not compiled yet. No wonder I couldn't use it!

The included demangler is bnackwards compatible, right?

**Comment by JohanEngelen** [comment]
backwards compatible, yes.

Recent dlang changed the mangling, but there is no LDC version with that mangling scheme yet. I don't know whether the new ddemangler can handle both the new and old mangling schemes.

**Comment by RabsRincon** [comment]
Now that I'm able to compile D locally, I'm trying really hard to get this working, so here's what I've got so far: I have traced the demangled output to the compiler, so it seems that the compiler itself (IF I'm not mistaken) is already demangling the output by itself.
Every compilation is done with `-g -of FILENAME`, but those do not seem to be the cause of it. If you have any idea, please let me know, I want finally to get this fixed! (And sorry it's taking so long :( )

**Comment by JohanEngelen** [comment]
The compiler itself does not demangle the textual asm output (`-output-s`). Because of `-g`, it does contain demangled names in the debuginfo.  Are you sure the compiler output is not immediately routed through `demangle.d`?

**Comment by RabsRincon** [comment]
Ok, so I'm just blind. I think the demangler should work now. If it does, I'll push this as soon as I can. (If you can't run it locally, I can push beta so you can test)

**Comment by JohanEngelen** [comment]
Don't know what happened, but it works on the live site just now.
(the problem wasn't that demangling didn't work, it was that it was not possible to turn it off! ;-))

**Comment by RabsRincon** [comment]
@mattgodbolt just pushed a bunch of fixes to the live site, this being one of those. 
Thanks for not letting us forget about D :)
