### ISSUE TITLE
link shortener not working when cfg window is open

### ISSUE THREAD

**Issue by cppchedy** [mattgodbolt/compiler-explorer#570]
I get a message that the link cannot be shortened.
https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHI0A7BgzAA8ADsQDUeHgTENmAWwAqqCJOmCAlGICkAdgBCWgAwBBMRKkz52gMwARMYa3WDJswDMSYlRbw37j5wkbAGEne0EnPW0AJgNYvHUjUzNLORiDOwlIpLNiTAJWHlTsk11bJNUxOQBDSW9pauJgZFIxXn42hEaxACpG4AA3LQBWA2HbTV0XZLyC4iLZRWV%2B5ETnJLLOdVIAGy5hzlIeLkND1C5Q2K1YmRY2TBjrWkOCE63tgGsQa2sAOh%2BAYCgQA2XZcAAsh2OnFOpHOnEODBAhlIrxhW1IcFgSDQcmEeB2mDIFAguPxhOIIGAOmipDcBIExCREAARm9SCzJI0AJ5cZ6kXFyTBSADyPB2vPRpCwNR4wEJ7PweWQBDwA0wSKlQkwyGYAj5h1UmD2UoIxDwcje2x2eBZSMg21QwlVqD4XAAtCLrGJ3fx0GFkNc4npaAAvH01NgIMJdBgAd2NOzEiLu7Do1v2UPZ8MEAA5ge7geCxM1kGIdL9ol5cIRPNcnq1gqg8QSiY9aOoXlbtghMNUsJSIJ9vn8gWOAaCTZCjtmuIjkairZiYIgUG5gORKMh1wAlDXMHavCCcGqSLiUTDoYAa%2BAQRrEVBxpFEAWoHYkKl5YV0h%2BWk%2B1aFSBoThaEMABObc3DcYZ3XBHQ3B0WDhjccF3TAlk3DAtDDHQYZaDAwxoloYEWX5IguF%2BAAZHQuG2O9iAfJ8QBfNB30pPJ0B/ZsuFPQCaDcFkCOQdBokwd1aEwFDYOsQw3HdXMWVzVDhn7MDwWscFwUE6IdFReFeJAAABawMXoxjn1QV82M/TBvzcX8eIAoyTKArhgR0aoJOiaJrHdUjL1g9BgRgxTDBg8FMEMTBwWQcEwNoYTYXIzgqNzWjMXvR8LKsj8OK4v8DOMw5gOGdAoOidTcz84Zc1oWDiJg6odHQKrwVzQjohZNqguBNwXn0pzDOBUzMqYli3w/YA8m5fLHLPIbirczBhmseLMEQwxqieWDZMMNDhls8ThlK4ZDBI0qRP6ijKOGdKzKy5jLNYyavx4WaUpurhXM4DygtzUTqnEnRgT29SdDE2q3ALSTPPcy8yo8q6PtukaGIe8brLy%2BzuORr7gJ0awRM0iDC2BaJWqCsTFIJ90dAg2gJPQ6KgqRqjbsM2hc1R8zHpyykptst7sb/NmjM5xbODA6ptPQWg5JpHRkHqzBfOqYEwMQyK3EMQwWVOyTkGQVnKNoaI7tG7LnvYy93tFjmue%2B6wfJZeG5MwaJcKQ8E9rAgSC3QcE3GiaoouiXqouN9mne59Gnom/npttz7jOiCXrBZapEuQPbomQLbYOQMCCwU8EYLC9gdHB5AM%2Br43rHNtGxrj6yBbshyPvrxaWUMSudFoY60OQcHYJ0TT3WqTB/vdaIwOGDXjtwvWwL067QIbnmMdym3heuzvXMw9AdD16D3Swao5LiqT/rJ2CIIzlDNoS8EV475yuboi3eatmy25xqj6%2BMg7fGLJhJdXVn5aIK0kIJT8rmOe7oF5gWsMgYEoFkAKWNmvGOTc%2BYgCxu3f%2Bb9FqYFoOgaw1QpZiW3LLWCvUsL/TamhHQ4FtalWQGHUEyVCGGXBKnD%2BjdLbxx/kLAhlEAG8Ilh5PC0tkAhRZCyXy4I5ZyWqDPPazDlqEWBP9WKSV4RUSwfwjezct6cR3q/HhqdvpKVzFgESgNwSoMUcgdO490EwVzNBWqRFbGOKNi/bhjjsGCJbq9JO4jhrfQ9kggiwICzRAEtEWh6lx4snQCyWmqj0HRXcnFMi%2BiTaGHXrHXB%2BC/5iKMkEqJMlfaCV8tXWgiEtIkPHkRMSwJs5NVoC7RpmE65GVOsEr%2BQjW4iPKQAwZrlD6kLAn2Oq8EdDhU2ugeScEMlgR8rwww4J0CxWzgEwpxScHfzKSLCphlJklWqMMcE58pJ00NtJDOsDMAFgwgTYOpCUIe36RcyERiSnf1GeEgZ05gJhTDnFYSpN0mwXaqhaobVAZ9lucCSetAtJoswUUoZm9rZmNERMsF%2Bw1KdUWXJRp1gCxtWhfIqGfknhgXasCdA/YfK/JqrikxCdBYgouUAk4REXYTySW4J4GT1LbRDu7Pykk3CyKdlLXM/iuGHK5aU7ehKBkCpAcwiqM9x6Z1BqyqqTVOrunYERSlOlM6YAOQAsm6qgVhPMdwx1rlz6kI9pJd0ry3AOPkb5WeAlfWeLcOkvsCkwoHMMRlARwzMaavGUZd14KCZQQ1gWPOJFAotX2kPQ1TLqgUKUtYYGvy4lOpGYnV11E8YgFZaPRZPqJ5INghVOquYi5YSCmpdCnkPI%2BRjTigFxyhEsh2MwO1ta0oS2GBnVatAJ47Vku27yflTZJM0mFJlcVS4E36e8I4GAbywG/vWMCEFILfQMocHY0tjRzWODkMQAgOiXjwK0D9L6qAMDEFRHQiIujCA4CyVAGhMTnp8pew2UEb2DRcvel2JpCrWBfYSaoYgdSCFaCMPQxB8BBloCMcorg2h4iw/gVouYf2En/ZRB2DBgOgfA3RKDq0r1weAoVSJSHH3/nmsCF9chUADEozhrDyAIhkYGCJgY6AACOmHuRyDkPQMQABNAAslpgA6iKHc9gAAKCgdz0eCI4UY5phAkZfYITwfYJOOZfQMYQ9nxCCFUyiMQnm5Ded844GTcnFPKdU7STTOn9OGbECZszVFgjEas3gGz4wX1MfEJeCTLkmPVBAyAMDEHSRCIvZxtw31RZ3ofSaUWL7%2BzoCw9UCTxGZPCDq/VlTfnWgde8x15ryRXNtbEL1rrqn1MdeiC%2B5AFHHNfvQNJ5IVAWT0YOIwZj%2BXWOQeK9B0r5Xk7i12FV667NOYubc54Xz6mLutAu8J0T4mv1SdO0SOQ0Q8Cm1zENsLI3OufbU60H4tWeD1cy60eSp3Bvde%2Bz1sLT3iAvbe%2BTX74XIe/fUwDlr1QbTAB4OIcb33kdeeo%2BD9AJPfvQ5%2B%2BN2H8P3uo6h99tHaGMdY5x7T1nKPwTE9Jyj7no2XPBYaxJgLk3ptSdm/NswVAHgGKsTlvLBW2NbY47BsrwE7bRwO8ho7zkJsydDESFgwgQPECA7lljhX2MwevariplXNev3Q32STEm8MEYiLERLpHkh1YF2L4XwhKOfqd7R%2BjoETdy420V6yJXle7YAdYB2fHqvnPj7V0nM2g9kYw073DVm5tBgm6lsjU3/cfoe%2BLsQVAkwGNhLLs3Cuo/bZj9b8RVjE%2B70qTrr3afGtl4d5h7DOf8N59iGhwvyRi8B972RyvIea9rfl5thvSurft54bxw7FjHGp%2BBz3jPyQs8D%2B0Lnt3egOdj7MBP0ve%2BJdV8KWHuvi%2BPzR5XxYyZbfX%2BBa7zvpzj3M%2BO8Py7sPnoMMLZkXtNlRtfhXrfqHqtqbutuborpblxqvjcrbvxtwjctvj7pAQfqLkfkPifkJufuRiXhAdhsHtXvfvAfXk/o3i/hgQnhvgwVgenuQX/v3ngYASfjoKAePuAYHmwQttAXPnAQvpHrQcvsgRYu6u/m6p3mYN7iDmIDRmRoobvoIRfvwb7tPsIVQWIRbjts3imuvnbm6kJqod3k5nnmRrMHoRHgYU3tdDRGgUnjRHZg5uoY1nYQgUvkgSrqvDihrugYci%2BrYbAeHj4RIX4btqbF9LISbGbC5nrg%2BMwIbkSKEfkN4TQZSM/lIalHEUwQxiAO4Rlp4eXu5vduJj%2BhRv/FkeoPUa%2BC2BSAAHLVBChcB5gFhFgliGzliViHAfpEDmjoB0CuT0BMCsBpjcCuj8BCCiDmDSCLBKD1A%2BaTD6AvqVCLB%2BAOAlDJAeDiArG%2BBhA7GBBHHWChCZARCBBBhBgJAvpmBbE3GZB4C7G5D5CFDFDrClA6Ce6VC8QrErCtDtDSDIBdDiB9BNBDCjAkZrHTBvFzALDyDLErBrDTCbAZicArbQiwg5j5iFjFilh9FVgADixAuWCAYgAAangJgAmAcTWEMe2I2M2OSG2PWB2F2OiA0V8D8P8OOGOGCJwNONiWcHOIwAuGiKcA0SaFYiKXCGKZKUeuqEyHgK6CAOCEAA%3D%3D%3D

**Comment by mattgodbolt** [comment]
The link is more than Google's link shortener limit. That's a big old URL :)

**Comment by mattgodbolt** [comment]
Oh!
This is super trouble: it looks like the URL is encoding the graph itself!

```
"{"settings":{"hasHeaders":true,"constrainDragToContainer":false,"reorderEnabled":true,"selectionEnabled":false,"popoutWholeStack":false,"blockedPopoutsThrowError":true,"closePopoutsOnUnload":true,"showPopoutIcon":false,"showMaximiseIcon":true,"showCloseIcon":true,"responsiveMode":"onload","tabOverlapAllowance":0,"reorderOnTabMenuClick":true,"tabControlOffset":10},"dimensions":{"borderWidth":5,"borderGrabWidth":15,"minItemHeight":10,"minItemWidth":10,"headerHeight":20,"dragProxyWidth":300,"dragProxyHeight":200},"labels":{"close":"close","maximise":"maximise","minimise":"minimise","popout":"open in new window","popin":"pop in","tabDropdown":"additional tabs"},"content":[{"type":"row","isClosable":true,"title":"","reorderEnabled":true,"content":[{"width":33.333333333333336,"type":"stack","isClosable":true,"title":"","activeItemIndex":0,"reorderEnabled":true,"content":[{"componentName":"codeEditor","componentState":{"id":1,"source":"constexpr int sumTo(int x) {\n  int sum = 0;\n  for (int i = 0; i <= x; ++i)\n    sum += i;\n  return sum;\n}\nint main(int argc, const char *argv[]) {\n  return sumTo(argc);\n}"},"type":"component","isClosable":true,"title":"C++ source #1","reorderEnabled":true}]},{"header":{},"width":33.333333333333336,"type":"stack","isClosable":true,"title":"","activeItemIndex":0,"reorderEnabled":true,"content":[{"componentName":"compiler","componentState":{"compiler":"g72","source":1,"options":"-O3 -std=c++1z -march=haswell ","filters":{"binary":false,"execute":false,"labels":true,"directives":true,"commentOnly":true,"trim":true,"intel":true,"demangle":true},"libs":[]},"type":"component","isClosable":true,"title":"x86-64 gcc 7.2 (Editor #1, Compiler #1)","reorderEnabled":true}]},{"width":33.33333333333333,"type":"stack","isClosable":true,"title":"","activeItemIndex":0,"reorderEnabled":true,"content":[{"componentName":"cfg","componentState":{"cfgResult":{"main:":{"edges":[{"arrows":"to","color":"green","from":"main:","id":"109cfff5-47f7-45f4-9bf9-90d5190216b1","to":".L7:"},{"arrows":"to","color":"red","from":"main:","id":"fb90cd2e-1ef4-430f-8b84-5ad94344b927","to":"main:@3"},{"arrows":"to","color":"green","from":"main:@3","id":"67a1e223-b1ed-4d65-b805-4e0e4c491cd0","to":".L8:"},{"arrows":"to","color":"red","from":"main:@3","id":"5dff2438-b581-4165-a7d8-48022b48d66f","to":"main:@6"},{"arrows":"to","color":"grey","from":"main:@6","id":"6e5391e7-0a31-40f0-95ee-155d506b5dd2","to":".L5:"},{"arrows":"to","color":"green","from":".L5:","id":"7ad682ea-1760-437e-81f6-efa167eddf7a","to":".L5:"},{"arrows":"to","color":"red","from":".L5:","id":"73d2449c-6628-4d6e-b873-79c11e9be4d6","to":".L5:@18"},{"arrows":"to","color":"green","from":".L5:@18","id":"9ab92d1f-727c-41e3-a697-e0f00b50efcc","to":".L12:"},{"arrows":"to","color":"red","from":".L5:@18","id":"323beddf-e2d5-4540-9fb6-d4f2a0e26f0e","to":".L5:@32"},{"arrows":"to","color":"grey","from":".L5:@32","id":"3bacd0c0-2ca3-4c96-8b45-05ce77ecbacb","to":".L3:"},{"arrows":"to","color":"green","from":".L3:","id":"b0777155-9c7e-4744-ae82-2959755d5b59","to":".L10:"},{"arrows":"to","color":"red","from":".L3:","id":"f9d7b5f5-deaf-49f4-8262-49cbaf40a1c4","to":".L3:@38"},{"arrows":"to","color":"green","from":".L3:@38","id":"7bcdb469-b253-451c-b859-55d93c610c8b","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@38","id":"e1d3a9ae-cfd1-46f9-8248-9709f05dc266","to":".L3:@42"},{"arrows":"to","color":"green","from":".L3:@42","id":"7a51abc5-bbb3-41ff-a290-70e502682c40","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@42","id":"848ded2a-4613-4c3b-ac85-8f581218d46c","to":".L3:@46"},{"arrows":"to","color":"green","from":".L3:@46","id":"2d939066-2fb2-4643-abdb-7a2c8e467491","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@46","id":"2309fb93-cb17-4be1-a21e-6c0a71be17f9","to":".L3:@50"},{"arrows":"to","color":"green","from":".L3:@50","id":"d71d9ea1-7f75-40ad-847b-9234204dc4c0","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@50","id":"5a54aff4-79cc-43ba-b8e6-bf732a1df42d","to":".L3:@54"},{"arrows":"to","color":"green","from":".L3:@54","id":"052649cd-66db-4804-a48a-ea4a6e814b6e","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@54","id":"5942b75f-1736-48cd-bbf6-b319806dad23","to":".L3:@58"},{"arrows":"to","color":"green","from":".L3:@58","id":"021beae2-f31b-4331-a0e2-beffc5329a8c","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@58","id":"bc702429-aac0-4da8-a72b-ce2117327ace","to":".L3:@62"},{"arrows":"to","color":"green","from":".L3:@62","id":"af1d2def-e6fa-4bb3-95fb-e8ffdbea8b05","to":".L10:"},{"arrows":"to","color":"red","from":".L3:@62","id":"073ff976-ca6b-4dd8-95c7-aa98aa984376","to":".L3:@66"},{"arrows":"to","color":"grey","from":".L7:","id":"da7475ef-ae93-4241-8969-d6949ba17a23","to":".L10:"},{"arrows":"to","color":"blue","from":".L8:","id":"5ba391ae-400f-4222-b122-440598494573","to":".L3:"}],"nodes":[{"color":"#99ccff","id":"main:","label":"main:\n  test edi, edi\n  js .L7","shape":"box"},{"color":"#99ccff","id":"main:@3","label":"main:@3\n  lea ecx, [rdi+1]\n  cmp edi, 8\n  jle .L8","shape":"box"},{"color":"#99ccff","id":"main:@6","label":"main:@6\n  mov edx, ecx\n  vmovdqa ymm1, YMMWORD PTR .LC0[rip]\n  xor eax, eax\n  vpxor xmm0, xmm0, xmm0\n  vmovdqa ymm2, YMMWORD PTR .LC1[rip]\n  shr edx, 3","shape":"box"},{"color":"#99ccff","id":".L5:","label":".L5:\n  add eax, 1\n  vpaddd ymm0, ymm0, ymm1\n  vpaddd ymm1, ymm1, ymm2\n  cmp eax, edx\n  jb .L5","shape":"box"},{"color":"#99ccff","id":".L5:@18","label":".L5:@18\n  vpxor xmm1, xmm1, xmm1\n  mov edx, ecx\n  vperm2i128 ymm2, ymm0, ymm1, 33\n  and edx, -8\n  vpaddd ymm0, ymm0, ymm2\n  vperm2i128 ymm2, ymm0, ymm1, 33\n  vpalignr ymm2, ymm2, ymm0, 8\n  vpaddd ymm0, ymm0, ymm2\n  vperm2i128 ymm1, ymm0, ymm1, 33\n  vpalignr ymm1, ymm1, ymm0, 4\n  vpaddd ymm0, ymm0, ymm1\n  vmovd eax, xmm0\n  cmp ecx, edx\n  je .L12","shape":"box"},{"color":"#99ccff","id":".L5:@32","label":".L5:@32\n  vzeroupper","shape":"box"},{"color":"#99ccff","id":".L3:","label":".L3:\n  lea ecx, [rdx+1]\n  add eax, edx\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@38","label":".L3:@38\n  add eax, ecx\n  lea ecx, [rdx+2]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@42","label":".L3:@42\n  add eax, ecx\n  lea ecx, [rdx+3]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@46","label":".L3:@46\n  add eax, ecx\n  lea ecx, [rdx+4]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@50","label":".L3:@50\n  add eax, ecx\n  lea ecx, [rdx+5]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@54","label":".L3:@54\n  add eax, ecx\n  lea ecx, [rdx+6]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@58","label":".L3:@58\n  add eax, ecx\n  lea ecx, [rdx+7]\n  cmp edi, ecx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@62","label":".L3:@62\n  add edx, 8\n  add eax, ecx\n  cmp edi, edx\n  jl .L10","shape":"box"},{"color":"#99ccff","id":".L3:@66","label":".L3:@66\n  add eax, edx\n  ret","shape":"box"},{"color":"#99ccff","id":".L7:","label":".L7:\n  xor eax, eax","shape":"box"},{"color":"#99ccff","id":".L10:","label":".L10:\n  ret","shape":"box"},{"color":"#99ccff","id":".L12:","label":".L12:\n  vzeroupper\n  ret","shape":"box"},{"color":"#99ccff","id":".L8:","label":".L8:\n  xor eax, eax\n  xor edx, edx\n  jmp .L3","shape":"box"}]}},"compilerName":"x86-64 gcc 7.2","editorid":1,"id":1,"source":"constexpr int sumTo(int x) {\n  int sum = 0;\n  for (int i = 0; i <= x; ++i)\n    sum += i;\n  return sum;\n}\nint main(int argc, const char *argv[]) {\n  return sumTo(argc);\n}"},"type":"component","isClosable":true,"title":"x86-64 gcc 7.2 Graph Viewer (Editor #1, Compiler #1)","reorderEnabled":true}]}]}],"isClosable":true,"reorderEnabled":true,"title":"","openPopouts":[],"maximisedItemId":null}"
```

This is _not_ what we want! The URL shouldn't contain the results, it should only contain the information needed to reconstitute the results!
