### ISSUE TITLE
ICEs in CL don't ever reply

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#571]
https://godbolt.org/g/RpeZpw for example never returns an error

**Comment by RabsRincon** [comment]
Note that the UI has a bogus output windows (which case has been fixed). If you open another output window, you do get some error output, but you're right in that we should show something in the compiler output

**Comment by mattgodbolt** [comment]
Right! "Fixed" URL - https://godbolt.org/g/gZqGER
