### ISSUE TITLE
Add google benchmark library (C++)

### ISSUE THREAD

**Issue by dominichamon** [mattgodbolt/compiler-explorer#578]
Hello

I maintain the [google benchmark library](https://github.com/google/benchmark). I think it would be useful to have this library available in the compiler explorer.

Please let me know if and how I can help.

**Comment by mattgodbolt** [comment]
Hi! Would love to, we will add it to our list of libraries. It will also
make for useful integration with quick-bench.com

**Comment by dominichamon** [comment]
quick-bench was going to be my next question. wonderful, thanks :)

**Comment by mattgodbolt** [comment]
Sweet. I've chatted to @fredtingaud a bunch about this, and we have some ideas. But nothing concrete yet.

Also: thanks for Google Benchmark! :)

**Comment by mattgodbolt** [comment]
Will be pushed in next site update (hopefully tonight or tomorrow morning). Have opened #581 to track quick-bench stuff

**Comment by dominichamon** [comment]
That was fast! Thank you :)

**Comment by mattgodbolt** [comment]
We're trying to make this kind of thing easier as the floodgates of
thirdparty libraries have opened...

**Comment by marcpawl** [comment]
How do I use the shared libraries that are listed in https://godbolt.org/admin/libraries.html.
What are the include and library paths?

**Comment by partouf** [comment]
@marcpawl there's no need to add paths manually, you can use the Libraries dropdown

![image](https://user-images.githubusercontent.com/442630/66497690-227f5700-eabd-11e9-92a9-b15561a60725.png)

**Comment by fabianbuettner** [comment]
While trying to use googlebenchmark, I get the following linker error:

> ASM generation compiler returned: 0
> 
> /tmp/ccit9Xft.o: In function `benchmark::State::end()':
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:715: undefined reference to `benchmark::State::StartKeepRunning()'
> 
> /tmp/ccit9Xft.o: In function `benchmark::State::StateIterator::operator!=(benchmark::State::StateIterator const&) const':
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:702: undefined reference to `benchmark::State::FinishKeepRunning()'
> 
> /tmp/ccit9Xft.o: In function `benchmark::State::end()':
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:715: undefined reference to `benchmark::State::StartKeepRunning()'
> 
> /tmp/ccit9Xft.o: In function `main':
> 
> /home/ubuntu/<source>:74: undefined reference to `benchmark::Initialize(int*, char**)'
> 
> /home/ubuntu/<source>:74: undefined reference to `benchmark::ReportUnrecognizedArguments(int, char**)'
> 
> /home/ubuntu/<source>:74: undefined reference to `benchmark::RunSpecifiedBenchmarks()'
> 
> /tmp/ccit9Xft.o: In function `__static_initialization_and_destruction_0':
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:289: undefined reference to `benchmark::internal::InitializeStreams()'
> 
> /tmp/ccit9Xft.o: In function `benchmark::internal::FunctionBenchmark::FunctionBenchmark(char const*, void (*)(benchmark::State&))':
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:938: undefined reference to `benchmark::internal::Benchmark::Benchmark(char const*)'
> 
> /opt/compiler-explorer/libs/google-benchmark/v1.4.0/include/benchmark/benchmark.h:938: undefined reference to `vtable for benchmark::internal::FunctionBenchmark'
> 
> /tmp/ccit9Xft.o: In function `__static_initialization_and_destruction_0':
> 
> /home/ubuntu/<source>:72: undefined reference to `benchmark::internal::RegisterBenchmarkInternal(benchmark::internal::Benchmark*)'
> 
> collect2: error: ld returned 1 exit status
> 
> Execution build compiler returned: 1

**Comment by mattgodbolt** [comment]
Hi @fabianbuettner -- We currently don't support linking or executing with any third party libraries: see #1662 for details. You can compile them to assembly and look at the output but you can't use the link (`11010`) or execute (`a.out`) features on Compiler Explorer.  If you need this, I'd suggest looking at http://quick-bench.com/

**Comment by fabianbuettner** [comment]
Hi @mattgodbolt,
thanks for the quick response. Sorry, totally missed that info.
