### ISSUE TITLE
quick-bench.com integration

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#581]
As discussed with @FredTingaud and now we have Google Benchmark available we should have bidirectional links to quick-bench.com :)

**Comment by partouf** [comment]
Maybe it's time to implement this like we did with cppinsights

**Comment by FredTingaud** [comment]
I'll have time to work on it and that is definitely something I want to see.

**Comment by partouf** [comment]
This was already implemented on the quickbench side of things by Fred.
Will see if I can figure out this React thing to allow links from our side of things.

**Comment by mattgodbolt** [comment]
Great stuff, thanks Partouf. I have a CE evening coming up to take a look (and might even have time tonight...)
