### ISSUE TITLE
https://gcc.godbolt.org/ no more works with IE11

### ISSUE THREAD

**Issue by ardi69** [mattgodbolt/compiler-explorer#583]
I use enthusiastically gcc.godbolt.org. But for about 2 weeks it no longer works with IE11. But I am dependent on IE11

**Comment by RabsRincon** [comment]
Hello. I'm so sorry to hear that!

Can you tell us more about what does not exactly work, or if you see something reported in the console that shouldn't be there?

We try very hard not to break stuff we have supported in the past, so I'll try to fix this asap once I know the details

:)

**Comment by ardi69** [comment]
SCRIPT1003: ':' erwartet
Datei: main.js, Zeile: 36339, Spalte: 36

 ```
  Compiler.prototype.currentState = function () {
        var libs = [];
        _.each(this.availableLibs, function (library, name) {
            _.each(library.versions, function (version, ver) {
                if (library.versions[ver].used) {
                    libs.push({name **>>>here<<<** , ver});
                }
            });
        });

```

**Comment by RabsRincon** [comment]
Oops! That's my fault. I expected it to be conformant with every browser. I guess I was wrong.
This should be up in the next release, so hopefuly you can start to use CE again :)

**Comment by mattgodbolt** [comment]
Site has been updated; please reopen if you continue to have problems.

**Comment by ardi69** [comment]
perfect thanx
