### ISSUE TITLE
"Graph output" button grayed out

### ISSUE THREAD

**Issue by ggnkua** [mattgodbolt/compiler-explorer#591]
Hi,

I just updated my repository of compiler-explorer in order to try out the new "graph output" button (the server is live at http://brownbot.hopto.org/ and it specialises in 68k compilers)  and I can't seem to enable the feature with my own set of compilers. Here's a few things about the machine and what I tried so far:

1. It's a raspberry pi 2 running linux raspbian wheezy
1. The only thing I changed from a clean repository is etc/config/c++.defaults which I'm attaching for reference. - [c++.defaults.zip](https://github.com/mattgodbolt/compiler-explorer/files/1383558/c.defaults.zip)
1. I tried running ```npm update``` in case packages were out of date
1. I reverted the repo fully and then enabled the gcc arm compilers. Then the button worked as expected.
1. Just as a test I added both native arm gcc and my cross compilers (some are gcc). Then I can press the "graph output" button on the arm compiler, but switching to the 68k gccs, the window refreshes with "no output"

After this I ran out of ideas to try. The server is running as described in the last step if you are inclined to check.

Any pointers on what to do would be appreciated. Worst case I can live without that particular feature but when possible I do like the shiny new stuff like this :)

Thanks for your time,
George

**Comment by mattgodbolt** [comment]
@cppchedy -- I think your parser only works on x86 assembly so far, is that right?

**Comment by ggnkua** [comment]
It seems to work for arm too fwiw!

**Comment by cppchedy** [comment]
@ggnkua it should only work for x86 as said by @mattgodbolt . but if you want you add other arch, you need to add  predicates to detect jmp instruction in lib/cfg.js. I think I will write a tutorial on how to add new compilers/lang/arch.

**Comment by mattgodbolt** [comment]
@ggnkua - did you get anywhere with this? I think it should appear in the UI but probably get confused over the opcodes. I'm not sure how it decides whether to display the option to graph or not (@cppchedy do you remember?)

**Comment by ggnkua** [comment]
No, there's not enough time to dive into this :). And since I see you're in a spring cleaning spree, lemme save you the trouble and close this one myself!

**Comment by cppchedy** [comment]
@mattgodbolt sorry I don't remember exactly but I think it was a simple check for gcc and clang (for x86).
