### ISSUE TITLE
Error: Cannot add item: item with id  push rbp already exists

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#592]
https://sentry.io/matt-godbolt/compiler-explorer/issues/369895043/

```
Error: Cannot add item: item with id  push rbp already exists
  at _addItem (ext/vis/dist/vis.min.js:27:1)
  at add (ext/vis/dist/vis.min.js:27:1)
  at setData (ext/vis/dist/vis.min.js:38:1)
  at setData (ext/vis/dist/vis.min.js:37:1)
  at showCfgResults (cfg-view.js:165:1)
...
(17 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
Looks like a CFG issue, creating two nodes with the same name, perhaps? was on https://swift.godbolt.org/ but I don't have the code.

**Comment by cppchedy** [comment]
I don't have access.

**Comment by mattgodbolt** [comment]
I don't know. I'll add you to the sentry site and you can take a look: thanks!

**Comment by mattgodbolt** [comment]
As @cppchedy noticed, this is not swift.godbolt.org - the referer was swift.godbolt.org but this page was gcc.godbolt.org

**Comment by cppchedy** [comment]
this should be closed.
