### ISSUE TITLE
"Error: load timeout" while trying to load a Compiler Explorer link

### ISSUE THREAD

**Issue by theres-waldo** [mattgodbolt/compiler-explorer#594]
Every time I try to load [this link](https://godbolt.org/g/cPM9Cx), I get a blank page with only the black header at the top. The developer tools console shows:

> Error: Load timeout for modules: main http://requirejs.org/docs/errors.html#timeout

My browser is Firefox 52 ESR.

**Comment by cppchedy** [comment]
that's odd, I am enable to reproduce this, the page load normally.

**Comment by mattgodbolt** [comment]
Can you try opening the page with the network debug page open? It's usually
off of the JavaScript debug console somewhere. I forget how to do it in
Firefox, but hopefully it's easy to find. Once open hopefully there's an
obvious problem...worth a look anyway

**Comment by theres-waldo** [comment]
It's working now. Perhaps it was a temporary network issue with one of the servers contacted during page load.
