### ISSUE TITLE
suggestion: use LZ-string on full URL for 

### ISSUE THREAD

**Issue by JobLeonard** [mattgodbolt/compiler-explorer#597]
So I just watched Matt's CppCon 2017 talk about this website (which was very interesting, thanks for the great presentation Matt!), and in the Q&A [someone mentions the URLs](https://www.youtube.com/watch?v=bSkpMdDe4g4&feature=youtu.be&t=3904). You also mention the maximum length of characters.

So I have a slightly crazy idea that just might work (in fact, I use it myself in one of my apps): apply LZ-string to the stringified state before exporting it to the URL.

> `compressToEncodedURIComponent` produces ASCII strings representing the original string encoded in Base64 with a few tweaks to make these URI safe. Hence, you can send them to the server without thinking about URL encoding them. This saves bandwidth and CPU. These strings can be decompressed with `decompressFromEncodedURIComponent`. See the bullet point above for considerations about size.

http://pieroxy.net/blog/pages/lz-string/index.html
https://github.com/pieroxy/lz-string

Obviously, this would need some kind of backwards-compatible set-up to distinguish it from the existing long URLs, to keep both working, but other than that the idea is really simple: LZ-string can take any valid JS-string, and turn it into a compressed string of 64 URI-safe characters. So you could take the entire state of the website, stringify it, run it through the URI-safe compressor of LZ-string and get a shorter string for your URL.

Very short code snippets might end up a bit longer, but for longer ones it makes a difference. I just tried throwing the part of a full URL that comes after `https://godbolt.org/#g:` through LZ-string *as is* as a stupid test:

```
!((g:!((g:!((h:codeEditor,i:(j:1,source:'%23include+%3Ciostream%3E%0A+%0Aint+main()%0A%7B%0A++++++++unsigned+int+a+%3D+1,+b+%3D+1%3B%0A++++++++unsigned+int+target+%3D+48%3B%0A++++++++for(unsigned+int+n+%3D+3%3B+n+%3C%3D+target%3B+%2B%2Bn)%0A++++++++%7B%0A++++++++++++++++unsigned+int+fib+%3D+a+%2B+b%3B%0A++++++++++++++++std::cout+%3C%3C+%22F(%22%3C%3C+n+%3C%3C+%22)+%3D+%22+%3C%3C+fib+%3C%3C+std::endl%3B%0A++++++++++++++++a+%3D+b%3B%0A++++++++++++++++b+%3D+fib%3B%0A++++++++%7D%0A+%0A++++++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',trim:'0'),libs:!(),options:'',source:1),l:'5',n:'0',o:'x86-64+gcc+(trunk)+(Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

IQChHMC5Q6wC0gYwPYBMCmBRNBLALigE4A0ukIAVpAIwkDOKArkUhpAOQCkATAMy4AdkgA2TTAGoufAMK4U9fEQwBDALbSsXAAwBBKXqH4JalUJABKHbq4B2AELWJzl86aD6ucIIxoJRiRUpPgARCToJACNgsJppRz1XV3dPb19-QWN8FSJwDGNpMIAWAA54pyTnADNiEBSvHz8AwRiJPniJFukZQols3PyO3kcee0ErRMqpBwqpqfq0psyJKtxo3qDhqPLJucrFNEhkZgLZbqkeHgAxEF4ebvOus9kLngtWu+Cel9X155kJAcjhhBGgRDt9HtKptQts+AlIVDXH8wr8IXM7CEnLMksp8CwWtoIZiOBYSCJOABWDgkQScbQ0lCcHqjLaMFhsC58Gg0-D00lkgDWkEp2nJnCKNLpHAZJCZHBp9EgYr5MtJJFgMEQqDUAAdcCIMKRyCAdfrDURIOB6IIVLr6PAUPgSKsRPgjUqQJF+SRIkIcgBPTg8kg6tQg-AAeUEIiDapImFMgnAhp9eGUSHwuAAbhglfGMAAPDBIJju4M0owYCnxpS4NT8skiNZK0BklC6rMoDycRXMVjsGhNqlSn3ywslABsAFpJ0UJOAkEgJCAlO5Be8QDgCMQuREZCg9QajXuLLzG0KRWKa5KSA2aNoxdLZfLFcqSKqGRZhxweKP46+H4XiQuZEJ43aQEUQA
```

That's just the Rosetta code for [Fibonacci's sequence](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,source:'%23include+%3Ciostream%3E%0A+%0Aint+main()%0A%7B%0A++++++++unsigned+int+a+%3D+1,+b+%3D+1%3B%0A++++++++unsigned+int+target+%3D+48%3B%0A++++++++for(unsigned+int+n+%3D+3%3B+n+%3C%3D+target%3B+%2B%2Bn)%0A++++++++%7B%0A++++++++++++++++unsigned+int+fib+%3D+a+%2B+b%3B%0A++++++++++++++++std::cout+%3C%3C+%22F(%22%3C%3C+n+%3C%3C+%22)+%3D+%22+%3C%3C+fib+%3C%3C+std::endl%3B%0A++++++++++++++++a+%3D+b%3B%0A++++++++++++++++b+%3D+fib%3B%0A++++++++%7D%0A+%0A++++++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',trim:'0'),libs:!(),options:'',source:1),l:'5',n:'0',o:'x86-64+gcc+(trunk)+(Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4), by the way. It's hard to see, but that's a compression from 910 characters to 713. If you apply it earlier in the state you might even get better results. It would also mean that you could squeeze slightly longer codes through the google URL shortener.

**Comment by RabsRincon** [comment]
Hello! Thanks for your suggestion!

Just to be clear, isn't it exactly what we already do? https://github.com/mattgodbolt/compiler-explorer/blob/master/static/url.js#L111 We just have a threshold so not so long urls stay "beautiful"

**Comment by JobLeonard** [comment]
Apologies, I should have been a bit more thorough in my checking... I just searched for lz-string in the issues and it came up empty, and I guess the snippet I used was too short. to trigger the compressor.

**Comment by anavalo** [comment]
> https://godbolt.org/#g

Link is dead :(

**Comment by mattgodbolt** [comment]
> I guess this one is the correct one: https://github.com/compiler-explorer/compiler-explorer/blob/main/static/url.ts

Yes that is the right link. thanks!
