### ISSUE TITLE
Kvasir::mpl goes too far in the include path

### ISSUE THREAD

**Issue by Quincunx271** [mattgodbolt/compiler-explorer#598]
Kvasir::mpl seems to be intended to be used similarly to this:

```c++
#include <kvasir/mpl/mpl.hpp>
```

The include path used for the library dropdown goes one folder too far, so you'd have to write

```c++
#include <mpl/mpl.hpp>
```

The include path should be changed from `/opt/compiler-explorer/libs/kvasir/mpl/trunk/src/kvasir` to `/opt/compiler-explorer/libs/kvasir/mpl/trunk/src`

**Comment by RabsRincon** [comment]
Hello! 

Thanks for reporting this, but we have a problem now. The urls are meant to work forever, and changing the path from one to another would break every single code that happens to include kvasir "the wrong way".

I think the only possible solution is to add both paths, which would resolve, as far as I can tell, both issues
Thanks again for reporting this
:)
