### ISSUE TITLE
Increase timeout for compiler process invocation

### ISSUE THREAD

**Issue by pmed** [mattgodbolt/compiler-explorer#601]
Hi @mattgodbolt 

Thank you so much for the great project!

I tried to compile a code snippet  with Boost.Spirit: https://godbolt.org/g/W6Sxs5 but got an error: 

"Killed - processing time exceeded
Compiler exited with result code null"

g++ (GCC-Explorer-Build) 8.0.0 20171024 (experimental)- 7919ms

When I comment out the Boost.Spirit header #include, it works.

**Comment by mattgodbolt** [comment]
The limit is currently ten seconds, and I don't know if I can absorb much more than that without leaving the site open to denial of service attacks.

Boost spirit is well known for being extremely slow to compile. I ran the equivalent compilation of your example on one of the CE nodes:

```
ubuntu@ip-172-30-1-29:~$ time /opt/compiler-explorer/gcc-7.2.0/bin/g++ -I /usr/include/x86_64-linux-gnu -I /opt/compiler-explorer/libs/boost_1_64_0 -g -c /tmp/test.cc
/tmp/test.cc: In function ‘int testBoostSpirit(int)’:
/tmp/test.cc:13:64: error: no matching function for call to ‘generate(std::back_insert_iterator<std::__cxx11::basic_string<char> >, const type, int&)’
         generate(std::back_inserter(buf), "number: "<<(int_), i);
[error cut]

real	0m23.565s
user	0m3.860s
sys	0m0.396s
```

It took 23 seconds. I have limited resources and Compiler Explorer is really best suited to interactive exploration of code, not full compilation. I'm happy to consider options though. What do you think?

**Comment by pmed** [comment]
Ok, thank you for the clarification. I thought the timeout is about several seconds, so 10 second seems enough for the interactive web site.

Maybe a precompiled header like `all_boost.hpp` would help? It then can be used with some option in a command-line.

**Comment by mattgodbolt** [comment]
If you can provide an example using precompiled headers that would be useful. I have not used them before.

**Comment by mattgodbolt** [comment]
A bit of googling reveals we'd need one PCH per library per compiler, per compiler options...it's an option I suppose but I'd need to be convinced it would be useful. And we'd have to somehow teach the compiler how to find the "right" PCH file.

**Comment by mattgodbolt** [comment]
I made a PCH for your example:
```
-rw-rw-r-- 1 ubuntu ubuntu 361M Oct 30 15:29 test.hpp.gch
```

And now the compile takes:
```
$ time /opt/compiler-explorer/gcc-7.2.0/bin/g++ -H -I /usr/include/x86_64-linux-gnu -I /opt/compiler-explorer/libs/boost_1_64_0 -g -c /tmp/test.cc
! /tmp/test.hpp.gch
 /tmp/test.cc
/tmp/test.cc: In function ‘int testBoostSpirit(int)’:
/tmp/test.cc:11:64: error: no matching function for call to ‘generate(std::back_insert_iterator<std::__cxx11::basic_string<char> >, const type, int&)’
         generate(std::back_inserter(buf), "number: "<<(int_), i);
                                                                ^
In file included from /opt/compiler-explorer/gcc-7.2.0/include/c++/7.2.0/algorithm:62:0,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/fusion/sequence/intrinsic/swap.hpp:12,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/fusion/sequence/intrinsic.hpp:23,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/fusion/include/intrinsic.hpp:11,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/proto/fusion.hpp:22,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/proto/core.hpp:21,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/proto/proto.hpp:12,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/phoenix/core/debug.hpp:17,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/phoenix/core.hpp:13,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/spirit/include/phoenix_core.hpp:11,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/spirit/home/support/terminal.hpp:17,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/spirit/home/support/common_terminals.hpp:15,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/spirit/home/karma/numeric/int.hpp:18,
                 from /opt/compiler-explorer/libs/boost_1_64_0/boost/spirit/include/karma_int.hpp:16,
                 from /tmp/test.hpp:4:
/opt/compiler-explorer/gcc-7.2.0/include/c++/7.2.0/bits/stl_algo.h:4428:5: note: candidate: template<class _FIter, class _Generator> void std::generate(_FIter, _FIter, _Generator)
     generate(_ForwardIterator __first, _ForwardIterator __last,
     ^~~~~~~~
/opt/compiler-explorer/gcc-7.2.0/include/c++/7.2.0/bits/stl_algo.h:4428:5: note:   template argument deduction/substitution failed:
/tmp/test.cc:11:64: note:   deduced conflicting types for parameter ‘_FIter’ (‘std::back_insert_iterator<std::__cxx11::basic_string<char> >’ and ‘boost::proto::exprns_::expr<boost::proto::tagns_::tag::shift_left, boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<const char (&)[9]>, 0>, const boost::spirit::terminal<boost::spirit::tag::int_>&>, 2>’)
         generate(std::back_inserter(buf), "number: "<<(int_), i);
                                                                ^

real	0m0.389s
user	0m0.244s
sys	0m0.040s
```

Which is pretty amazing...though the space-time tradeoff is interesting.

**Comment by pmed** [comment]
Cool, thanks for sharing!

Yes, precompiled headers are the space-time tradeoff. I used the PCHs only with Visual C++ some time ago.

**Comment by ggnkua** [comment]
Hi,

I'm trying to increase the limit on my own instance of CE but end up chasing my tail around and around inside the source. Could anyone please point me at the file/setting I need to tinker?

Thanks in advance!

**Comment by mattgodbolt** [comment]
@ggnkua to override the timeout, create a file called `etc/config/compiler-explorer.local.properties`. In this file put the line:

```
compileTimeoutMs=100000
```

This file will override the setting that's defaulted from `etc/config/compiler-explorer.defaults.properties` to 10s. Hope this helps.

**Comment by ggnkua** [comment]
@mattgodbolt indeed it was! Although some compilations take so long that they produce a 504 error - but I guess that can't be helped :)

Thanks for the prompt reply :D

**Comment by ggnkua** [comment]
@mattgodbolt as a matter of fact I do use nginx, Do you think that I could increase some limit in nginx's config then? I'll take a look

**Comment by mattgodbolt** [comment]
https://stackoverflow.com/questions/10806928/increasing-504-timeout-error :)

**Comment by ggnkua** [comment]
Yup, I found a similar hint around the same time you posted the reply - just finished testing it and it looks to have done the trick!

Thanks again then - and I'm glad my day job doesn't have anything to do with server admin or I'd have been in deep trouble :D

**Comment by mattgodbolt** [comment]
Just to waken this thread and bring it (somewhat) back on topic - I've been experimenting with other filesystems. I am trying [ObjectiveFS](https://objectivefs.com/) at the moment. Their support is great, but I don't think it's going to be fast enough even for this kind of example (the original link) to compile in the 7.5s timeout I currently have.

**Comment by mattgodbolt** [comment]
(actually I should have waited before posting... a couple of reloads and the file did compile...mainly due to caching finally bringing in enough of boost/spirit etc to make it fast). That said; having it time out the first few times while all the caches are warmed isn't a great option.

Anyone know any clever and quick ways to get 80GB of compilers copied onto amazon S3 instance local disks quickly at startup? :)

**Comment by phuclv90** [comment]
Hey I have an idea, why don't just give users that disabled automatic compilation a little bit longer timeout? Maybe also reduce the timeout for the others, with the shorter the recompile period, the shorter the timeout. If the users got a timeout they'll get a hint to disable automatic compilation or remove boost

I'm not sure whether the default 0.25s cycle puts too much load on the server or not, but that looks like a good balance and fairness to everyone
