### ISSUE TITLE
Add a 68k compiler

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#602]
Requested by Thomas Troeger over email.

CC #82

**Comment by flamewing** [comment]
GCC supports 68k; you can even install 68k cross-compilers in Ubuntu.

**Comment by haneefmubarak** [comment]
Duplicate of #271

**Comment by mattgodbolt** [comment]
Clsoed as duplicate (like @haneefmubarak says!)
