### ISSUE TITLE
Missing update of Visual Studio compiler.

### ISSUE THREAD

**Issue by Sorennnn** [mattgodbolt/compiler-explorer#604]
Nice tool you have build here. Really handy in a jiffy.

I am missing an update to the latest Visual Studio 2017 compiler though.

Regards.

**Comment by mattgodbolt** [comment]
Hi, we're working with Microsoft (CC @AndrewPardoe) on improving the Visual Studio compiler support. For now, we are a bit stuck running the compilers under `wine` on Linux. Unless there's a simple way to grab new VC packages (like https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_nonfree_compilers.sh#L66 for 14.0.24629), we'll have to hang on for help from MS.

**Comment by danilaml** [comment]
@mattgodbolt any update on this? There have been two major updates since VS2017 release that contained great work on conformance, features and performance.

http://landinghub.visualstudio.com/visual-cpp-build-tools

Also, it looks like [this](https://visualcpp.myget.org/gallery/dailymsvc) can be considered "trunk".

**Comment by mattgodbolt** [comment]
Hi @danilaml . We're aware of the awesome improvements in VS. We're working with @AndrewPardoe of Microsoft to get them onto the site. Sorry it's taking so long!

**Comment by AndrewPardoe** [comment]
This is entirely Microsoft's fault! But we promise that we'll get this updated soon.

**Comment by danilaml** [comment]
This seems to be taking longer than expected.Is it possible to just add a newer NuGet to the old setup in the meantime? Or is this the PR with an improved support for MSVC you've been waiting on https://github.com/mattgodbolt/compiler-explorer/pull/736 ?

**Comment by mattgodbolt** [comment]
If there's a new NuGet compiler that "just works" I can move to it. I don't really have the experience or knowledge to know how to get NuGet URLs; if you know different then something like this change: https://github.com/mattgodbolt/compiler-explorer-image/commit/9fdafa71461ece1f699c7892e2ae615890df0c94 brought the compilers in the first time. Any hints as to which endpoints I can hit to get working compilers appreciated!

**Comment by AndrewPardoe** [comment]
Sorry for the lack of action on Microsoft's part. I've tried to set the wheels in motion but there's gum in the works. 

The NuGet feed we're using now is here: https://visualcpp.myget.org/F/dailymsvc/api/v2/Packages

We do intend to start maintaining these ourselves. I just don't know what promises to make on timeframes.

**Comment by danilaml** [comment]
@mattgodbolt https://visualcpp.myget.org/F/dailymsvc/api/v2/package/VisualCppTools.Community.Daily.VS2017Layout

Should give you the latest NuGet package (MSVC trunk? Doesn't seem to contain any stable versions though) not sure if it'll work exactly like the current one but it probably should. Also not sure if it can be installed side-by-side.

**Comment by partouf** [comment]
CE has now support for the latest compilers, and are updated by MS.
