### ISSUE TITLE
Allow disable caching

### ISSUE THREAD

**Issue by lichray** [mattgodbolt/compiler-explorer#605]
When doing compiler development, we need to keep changing the compiler and verify the outcome, and every time we have to tweak the input a little bit.  `cacheMb=0` doesn't change the symptom.

**Comment by RabsRincon** [comment]
Hello! It's so great to read the different ways in which Compiler Explorer is used, and it's true that that makes it harder to please every use case, sorry about that!

So we have two solutions here. I'll ask around and come back to you as soon as I can

:)

**Comment by RabsRincon** [comment]
Ok, so I'll add a new `EXTRA_ARG` parameter, `-noCacheResults` which (when called like `make EXTRA_ARGS="--noCacheResults"`) will avoid caching the compilation results. Note that you'll still have to explicitly call for a compilation on the editor (Right click -> Compile OR Ctrl + Enter)

I won't push jusy yet as I want to give it one more thought in case I'm missing something, and meanwhile, I'll also wait for your feedback

**Comment by lichray** [comment]
I didn't know Ctrl-Enter is an explicit call for compilation...

For me, it would be enough if CE can detect the timestamp for each compiler and invalidate the associated cache if a timestamp changes.  But this approach may not be "generic" enough for others.

Another thought is to turn the "_- cached_" text at the bottom a clickable element, clicking it will invalidate cache.

**Comment by mattgodbolt** [comment]
Both solutions sound great. I'd prefer not doing the compiler timestamp; mainly as the compiler is comprised of more than just the single binary you run, one can change library headers only for example and then the timestamp of the binary will remain the same. A "force recompile" option through clicking the `(cached)` and/or a `--noCacheResults` work for me

**Comment by lichray** [comment]
I now prefer just making the "cached" text clickable -- like some element to indicate a state, by clicking the element it disappears and takes away such a state.  If possible, it should only clear cache which is associated with the current compiler.

`noCacheResults` will disable all caches, which may not be desirable, since even we modified the compiler, when trying it out, we may still want to benefit from caching to speed up editing.  Using Ctrl-Z and Ctrl-Y to switch between two edits are still reasonable to be cached.

**Comment by RabsRincon** [comment]
Hello! Sorry for taking this long. (Lots of things to do!)

The final solution is a button to the right of each compiler's bottom bar, which clears its cache and asks for a recompilation. This is the best I have been able to come up with, but please, if you have any other suggestion, feel free to share it with us

Note that this might not be the final word on this issue, as I still need to check with Matt if we want to put this feature under a launch parameter (Either opt-in or opt-out), or if this should be available everywhere.
If any more changes are made, I'll be sure to notify you here

:)

**Comment by lichray** [comment]
Works as expected, very nice.  Thanks!

**Comment by RabsRincon** [comment]
Oh wow I'm a dummy. This actually flushes every compiler's cache, which is something you did not want. (I wrongly thought that each compiler had its own cache, but as it turns out ,every compiler shaers the same cache, so it's hard to just flush only one out of the box. I'll look for a solution to this, see if something can be done.
Thanks for your pacience :)

**Comment by lichray** [comment]
Per-compiler caching would be ideal, but to me the behavior you just implemented already solved my problem -- after all caching is an optimization, losing some won't be too surprising :)

**Comment by lichray** [comment]
Reopen this please -- the cache seems to be cleared only form the client side.

I see the requesting being sent to the server after pressing the small refresh button, but then the text says:

> clang version 6.0.0 (trunk 320111) - 7ms

That's not possible, it at least takes 230ms to compile.  And of course, the result is from the old compiler.

**Comment by mattgodbolt** [comment]
Will do. Caching has been under discussion on the CE chat channel so this is pertinent! Thanks.

**Comment by RabsRincon** [comment]
Hi! Sorry this got little attention for so long. So, the good news: I've added an EXTRA_ARG that disables all caching, server & client side. But as you might have guessed, this is not going to be used in the live site (For obvious reasons!) so you need to launch a local instance of CE to get all the benefits from it. Simply running `make EXTRA_ARGS="--noCache"` should do the trick.

Thanks again for your patience! :)
