### ISSUE TITLE
Not showing optimized code.

### ISSUE THREAD

**Issue by hanickadot** [mattgodbolt/compiler-explorer#606]
https://godbolt.org/g/Xjdtft

**Comment by mattgodbolt** [comment]
The compiler isn't generating any code...so we're not showing anything!

When you make the functions `static` they're only visible at file scope. If the compiler sees they're not used by any visible non-`static` function it won't even bother compiling them. Taking the `static` off fixes the issue: https://godbolt.org/g/brw8U3

**Comment by hanickadot** [comment]
My bad, thank you.

**Comment by mattgodbolt** [comment]
Oh not at all! This stuff is tricky, and I wish we had a better way of explaining what might be going on! Thanks for taking the time to raise the issue, and glad it was a relatively easy one :)
