### ISSUE TITLE
split(":") use doesn't allow drive paths on windows

### ISSUE THREAD

**Issue by Pachelbel1414** [mattgodbolt/compiler-explorer#607]
split(":") use doesn't allow drive paths on windows
compilers=d:/compilers/gcc.exe  gets treated as two compilers, "d" and "/compilers/gcc.exe"

**Comment by mattgodbolt** [comment]
Thanks, indeed. We'll look to change it to something else! Windows is still very much a second-class citizen I'm afraid.

**Comment by Pachelbel1414** [comment]
I got past this (changed locally to split("|"), and a couple other Windows
issues to have it run locally with a MicroChip PIC compiler.

This is going to be a fantastic tool for doing some micro optimizations on
the embedded platforms I work daily with.

-Shane

**Comment by mattgodbolt** [comment]
Great to hear @Pachelbel1414 . We on the dev team are discussing changing to using completely different configuration as a result of this; so watch this space! :)

**Comment by mattgodbolt** [comment]
It's also the case you can define compilers by ID and then refer to their paths one per line.  See https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md for more details

**Comment by RabsRincon** [comment]
An optional json format is coming along nicely, albeit more verbose, will let every platform play nicely with eachother. Should be finished this week or so. Thanks for your patience!

**Comment by RabsRincon** [comment]
Would an aceptable solution be to use the platform specific path delimiter as the separator (https://nodejs.org/api/path.html#path_path_delimiter)? We might run into troubles with the wine stuff, but that's solvable. Any thoughts?

**Comment by mattgodbolt** [comment]
When do we actually need the oath separator any more? If one uses compiler IDs, the paths referenced by ID are not split. It's better in general to not mention all the compilers by path in the list, but obviously it's nice to support that on all platforms if we support it at all...

**Comment by mattgodbolt** [comment]
When do we actually need the oath separator any more? If one uses compiler IDs, the paths referenced by ID are not split. It's better in general to not mention all the compilers by path in the list, but obviously it's nice to support that on all platforms if we support it at all...

**Comment by mattgodbolt** [comment]
When do we actually need the oath separator any more? If one uses compiler IDs, the paths referenced by ID are not split. It's better in general to not mention all the compilers by path in the list, but obviously it's nice to support that on all platforms if we support it at all...

**Comment by mattgodbolt** [comment]
When do we actually need the oath separator any more? If one uses compiler
IDs, the paths referenced by ID are not split. It's better in general to
not mention all the compilers by path in the list, but obviously it's nice
to support that on all platforms if we support it at all...

**Comment by mattgodbolt** [comment]
I'm going to close this: Anywhere we have paths lists we have an alternative for specifying. For example in a list of compilers one shouldn't list the paths directly, but instead list the IDs of compilers, and then for each compiler separately list its path. Examples of this can be found in the `etc/config/c++.amazon.properties`
