### ISSUE TITLE
Support C, not just C++

### ISSUE THREAD

**Issue by dhouck** [mattgodbolt/compiler-explorer#608]
Currently, specifying a C standard flag like `-std=c11` doesn’t work on either GCC or Clang. C++ and C are different languages. C++ is *mostly* a superset, but there are features C supports and there are edge cases where they both accept some code but behave differently. It would be nice to be able to use C code in Compiler Explorer even in these circumstances.

**Comment by mattgodbolt** [comment]
A workaround for now is to pass the argument `-x c`

**Comment by mattgodbolt** [comment]
We'll make this more of an official thing when we combine languages (#277)

**Comment by dhouck** [comment]
Ah, I wasn’t aware of that workaround. Thanks!

**Comment by RabsRincon** [comment]
C has been supported now for a while https://godbolt.org/g/7dgnGC. Sorry we did not notify it here, my bad!
