### ISSUE TITLE
Compiler Explorer as a Normal Windows Executable?

### ISSUE THREAD

**Issue by RaTcHeT302** [mattgodbolt/compiler-explorer#610]
Will there ever be an .exe version which can be run directly on Windows?

**Comment by mattgodbolt** [comment]
Probably not. Compiler Explorer is a website, most actively developed on Linux. There are ways to make it run as something that looks like an app (while still being a Javascript app mainly), but that's not planned. I wouldn't be against someone making such an app, but it's not something that's on the roadmap.
