### ISSUE TITLE
Include Eigen library (c++)?

### ISSUE THREAD

**Issue by ibtaylor** [mattgodbolt/compiler-explorer#614]
Should be trivial since it is header only.

http://eigen.tuxfamily.org

This seems like a very good case for godbolt considering all the template magic and different results depending on compiler flags with Eigen. It would benefit my work a lot, as well as give a way to communicate better with its core developers.

Please let me know what I can do to help this through. I'd love to help.

**Comment by mattgodbolt** [comment]
Eigen is already available on the library drop down, both trunk and v3.3.4.

![image](https://user-images.githubusercontent.com/633973/32521318-a80befe0-c3d8-11e7-9e8b-3039917a18e2.png)

**Comment by ibtaylor** [comment]
Whoops, guess I missed that.

Looks like the wiki is out of sync. https://github.com/mattgodbolt/compiler-explorer/wiki/Installed-libraries

**Comment by RabsRincon** [comment]
It indeed is, thanks for the heads up!
