### ISSUE TITLE
Allow loading of already-compiled binaries for local compiler-explorer

### ISSUE THREAD

**Issue by RealLitb** [mattgodbolt/compiler-explorer#615]
It would be useful if one could load an already-compiled binary. For my case, I have a binary that consists of many source files and copying the files into the webinterface is very time consuming. If I could just upload the source files I am interested in, and provide the pre-compiled executable and have the nice source<->asm coloring, that would be really cool.

**Comment by mattgodbolt** [comment]
Hi! What do you mean by an already-compiled binary? Compiler Explorer works on source, not binaries.

You can upload a single source file with the little disc icon on the editor.

Compiler Explorer is not a reverse engineering tool - it can't map arbitrary compiled binaries back to source. It's limited by the debug information output by either the compiler (in its normal mode), or else using the debug information recorded in the binary (when doing binary mode).

**Comment by RealLitb** [comment]
I thought because it already can associate assembly-lines back to source lines (using debug informations?), it should be able to know also the file name that the assembly-line comes from (filename:sourceline). So I imagine it could "simply" omit the compilation-process and let me pass the result-executable. With its assembly-lines <-> sourcefile:sourceline association features which it gets from the debug information, it should be able to color the source lines aswell, of any files I upload. 

So if the executable consists of 100 source files, but I'm only interested into looking-up the assembly for a single source file "foo.cpp", I can pass it the generated executable, and paste only "foo.cpp". And it would color the part of the disassembly that belongs to "foo.cpp"'s source files. 

It wouldn't have to decompile back to source.

**Comment by mattgodbolt** [comment]
I see. Ok, for 99% of Compiler Explorer's output I parse the text output of the compiler. There's no binary, no disassembly, and I use the handy `.line` directives in the assembly output.

For "binary mode" (the terrible `11010` icon), I do actually compile and link, and then run `objdump` on the executable. This would probably work work your setup, however it's not something I'm planning on adding myself; handling large binary uploads, and `objdump`ing them adds complexity. We'll keep this bug open though as a feature request!

If you'd like to spike something out yourself, the code is in the https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/asm.js#L235 binary parser here, and the binary flag triggers the run of `objdump` here: https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/base-compiler.js#L453

**Comment by mattgodbolt** [comment]
I'm going to close this, as I don't think it's part of the remit of Compiler Explorer, and is better served by other decompilers/disassemblers (`gdb` for example!). If however you have other ideas on improving this, or pull requests, I'll happily consider them!
