### ISSUE TITLE
"Add new compiler" button is really hard to find

### ISSUE THREAD

**Issue by zackw** [mattgodbolt/compiler-explorer#617]
I usually use the Compiler Explorer to compare what two different compilers do for the same source code.  When I do this, I invariably spend multiple minutes not being able to find the buttons that add additional compilers for a particular input:

![screenshot from 2017-11-09 14-56-17](https://user-images.githubusercontent.com/325899/32629415-20680f0c-c567-11e7-9c0b-2dc79da4f199.png)

It doesn't occur to me to even look at that bar for those buttons until I've tried literally every other piece of UI on the page, because that bar, in my head, should only contain buttons that manipulate the source code itself (the save, load, and change font size buttons are appropriately on that bar).  It doesn't help that the icons have no meaning to me and I have no idea what the "conformance viewer" does.

It seems to me that these controls belong on the very topmost bar, which would also have the advantage that they could be words instead of cryptic icons.  I understand from discussion on twitter that they need to be tied to a specific source, but other things on the top bar, like the choice of language, also seem to be source-specific to me, so maybe I don't fully understand the constraints here?  Another possibility would be to put them inside the tab strip, kind of like how web browsers have a "new tab" button inside their tab strip.

**Comment by mattgodbolt** [comment]
I filed this as #616, will close that in favour of this

**Comment by mattgodbolt** [comment]
From 616, my original comments:
>Several folks are confused by the terrible icons in general, and specifically the ones on the editor. See, for example the thread at https://twitter.com/elwoz/status/928713541326123008 Suggestion was to replace the "new compiler" and the "conformance view" buttons with words, and to hoist them up into the main menu bar. That won't work exactly as-is, as I need to know which editor to bind the compiler or conformance view to. Currently the code has a strict binding between compiler and editor. We could make it more flexible (like the diff view), at the risk of making it a bit more confusing. However, for the simple and very very common case of only one editor being open, it will work perfectly.

**Comment by regehr** [comment]
Yay!!

Also I don't know what "conformance view" means :)

**Comment by RabsRincon** [comment]
@regehr Conformance view is just a panel wherr you can select multiple compilers to compile your code with, and it lets you know if they emit any warning/error and which

@zackw the main difference between the top bar menu and the per editor icons is the fact that the top bar ones affect *every* source and the per editor one is isolated to that which it's called from. (I hope that makes any sense)

Note that what we can do is, at the expense of 1 more click, we can add a "More"/"Other" dropdown button and put the confusing icons there as text. 
Would this compromise (or a variation) be ok?

**Comment by zackw** [comment]
> the main difference between the top bar menu and the per editor icons is the fact that the top bar ones affect every source and the per editor one is isolated to that which it's called from.

Yes, but that seems like an artificial distinction. It would be perfectly reasonable to want to see whether there are codegen differences when the same code is compiled as C and as C++, for instance.

> at the expense of 1 more click, we can add a "More"/"Other"/"Add view" dropdown button and put the confusing icons there as text. Would this compromise (or a variation) be ok?

If this dropdown were placed where the confusing buttons are now, that would not help, because the problem is the _location_ of the buttons as much or more than their icons not being terribly meaningful.  My brain expects the toolbar immediately above the code pane to contain only buttons that manipulate the code itself - save, load, alter font size, search, replace, copy, paste, that sort of thing. So, again, it doesn't even occur to me to look at it until I've wasted a bunch of time trying _every other possible location_.

**Comment by RabsRincon** [comment]
The distinction is indeed technical, as our current setup does not allow more than one language at once (Every language runs on its own node) but we are working on unifying it so you can compile more than 1 language in the same page.


You mention that the position should be changed, but I how would it work being outside the panel? Note that we need to know from which editor you want the new compiler/conformance view to get its source from.
If you know of any good way for it, please let me know, and I'll be super happy to test it :)

**Comment by zackw** [comment]
I don't understand why the button's association with a particular editor window should mean that it has to be inside that editor window.  For instance, a more logical location, that would remain _somewhat_ associated with the editor window, would be at the right-hand limit of the tab strip for the editor window and its compilers.

(This might be a case of what my UI-designer friends would call the "using the internal data structure as the UI" antipattern.  Models and views are two different objects for a reason.)

**Comment by mattgodbolt** [comment]
@zackw I don't quite get where you mean when you say "right-hand limit of the tab strip and its compilers". There's plenty of ways to separate the compiler and editor where there's no tab strip in common between the editor and its compilers.

I appreciate the feedback, and if you can mock something up it might help me understand what you're saying. Anything to improve my dire UX skills!

**Comment by RabsRincon** [comment]
So, sorry that this took so long. More impending issues kept coming, but that's not relevant anymore. I have added some improvements ot the UI which might help what we disclosed here. Note that, as @mattgodbolt mentioned, the placement of the buttons is not something trivial, that's why I opted for building on top of what we had instead of rebuilding from scratch.
Please do let me know what you think about the new look (now available in the site), and again, thanks for your patience :)

**Comment by mattgodbolt** [comment]
I think this is covered by @RabsRincon 's change to make everything a lot more explicitly named. Please re-open if you think work can still be done to improve. Thanks!
