### ISSUE TITLE
ASM parsing looks broken for our proprietary asm

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#620]
We are using CE for internal devs, and it really works nice !
Since 83ff13813bc4458da37929daf6d4bd39e127d8d4, it seems that the link between asm and source code is broken for our backend. We are using a private gcc port, and up to this commit, everything looks correct.

Since this commit, most asm is not bound to C source code. There is still some matching that is correct (eg. function call, return), but mostly, it's not working. If using some regular x86_64-gcc, everything is working as expected, so that must be something in our assembly that breaks the matching code...

I'll try to see if I can fix this. If you need some asm example, I can provide it.

**Comment by dkm** [comment]
Ok, I understand :)
Here's an example of our asm : 

```
printf:
  addw $r12 = $r12, -100
  copyd $r9 = $r0
  make $r0 = 0
  ;;
  sd 20[$r12] = $r10
  addw $r10 = $r12, 36
  ;;
  get $r8 = $ra
  ;;
  sd 0[$r10] = $r1
  copyd $r1 = $r0
  ;;
  sd 16[$r10] = $r3
  copyd $r3 = $r10
  ;;
  sd 8[$r10] = $r2
  copyd $r2 = $r9
  ;;
  sw 16[$r12] = $r8
  ;;
  sd 24[$r10] = $r4
  ;;
  sd 32[$r10] = $r5
  ;;
  sd 40[$r10] = $r6
  ;;
  sd 48[$r10] = $r7
  ;;
  sw -8[$r10] = $r10
  call _vfprintf_r
  ;;
  addw $r12 = $r10, -36
  ;;
  lwz $r1 = 16[$r12]
  ;;
  ld $r10 = 20[$r12]
  addw $r12 = $r12, 100
  ;;
  set $ra = $r1
  ;; /* Can't issue next in the same bundle */
  ret
  ;;
```

Mnemonic should never be in upcase... Are the constants always upcase ? That would not be very robust, but that may be enough ?

**Comment by mattgodbolt** [comment]
I"ll have a think; thanks! Relying on case seems a bit unsafe...how about assignment never has a space, e.g. `foo = bar` is clearly an assignment, but `this is not = an assignment` isn't as there's multiple whitespace-delimeted things on the left. Are all your opcodes of the form `OP REG = THING` ?

**Comment by dkm** [comment]
Yes, that should be correct in our case !

**Comment by dkm** [comment]
What about simply using the `assignmentDef` re that is already defined ? It can be used to check that LHS has exactly one element. I can't test if that's working for mac clang.
`        if (line.match(assignmentDef)) return false;`

**Comment by mattgodbolt** [comment]
@dkm if you make that change, test it with 

```
npm test
```

which will run the (canned, pre-recorded) mac clang test amongst others (it's how I tested, I don't own a mac!)

**Comment by dkm** [comment]
Ok, didn't know that sorry. I have some fail, but I'm not sure they are real fail, maybe more a test problem:

```
  Cfg test cases                                                                                                                                                                                                    
    gcc tests                                                                                                                                                                                                       
      1) .../compiler-explorer/gccexplorer/test/cases/cfg-clang.if-else.json                                                                                                                           
      2) .../compiler-explorer/gccexplorer/test/cases/cfg-clang.loop.json                                                                                                                              
      3) .../compiler-explorer/gccexplorer/test/cases/cfg-clang.single-block.json

...

      {                                                                                                                                                                                                            
      -  "_GLOBAL__sub_I_example.cpp: # @_GLOBAL__sub_I_example.cpp": {                                                                                                                                             
      +  "_GLOBAL__sub_I_example.cpp:": {                                                                                                                                                                           
           "edges": [

```
It's always failing because of these changes after `#`, and it also fails on `master` for the 3 same tests. I guess that's because you generated the golden with a different gcc version ? (4.8.5 here)

**Comment by mattgodbolt** [comment]
The tests are all canned, no compilers run at all. It's just a test of processing text. If you `git stash` and `npm test` without your change, does it work? It really ought to, and if not that's a problem with the tests. To me it seems like that change has changed (not necessarily broken..!) the output. I can take a look if it's only as a result of your change.

**Comment by mattgodbolt** [comment]
Oh, when you say on `master` do you mean a clean checkout of master? Hmm... what OS are you running the tests on? They should all be passing (and there's a continuous build agent here: https://travis-ci.org/mattgodbolt/compiler-explorer which is currently green).

**Comment by dkm** [comment]
Yes, when I said on `master`, it meant a `git reset --hard upstream/master && git clean -xxfd`.
I'm running a Centos 7 and have installed nodejs 8.6.0 locally...

**Comment by mattgodbolt** [comment]
That's super odd! can you attach the full failure here and I'll try and work out... thank you!

**Comment by dkm** [comment]
Using ` 3a6acdb (HEAD, upstream/master) Add option to reset LruCache for each compiler`
[log.txt](https://github.com/mattgodbolt/compiler-explorer/files/1467708/log.txt)

**Comment by mattgodbolt** [comment]
Thanks! That's super weird, it seems the difference is somehow the comments have been stripped...

I checked out the same version locally and it passes for me. I'll keep digging. Thank you!

**Comment by mattgodbolt** [comment]
Ok, this is bizarre. @cppchedy - looks like something in the `cfg tests` is failing but only on @dkm 's machine.

@dkm - if it's only the CFG test cases that are failing, then your patch is good! If you can (try!) and put your example code into the test cases that would ensure we don't break it again. If you look at tests/filter-test.js you'll see all the horrible `bless` things I use to "bless" the output. I typically add a test case, bless it, then manually check to see the output looks how I'd expect. Then I comment out the bless and check it in.  If you can't fathom the weird naming conventions, don't fret. I can do this too!

**Comment by dkm** [comment]
Sure, I'll provide a PR with test today ! Thanks for your time !

**Comment by dkm** [comment]
I'm implementing the fix, and it looks like something was wrong in the previous setup. The git clean may have left something as a clean worktree does not produce error in cfg tests... Sorry for the noise...
