### ISSUE TITLE
Support llc

### ISSUE THREAD

**Issue by samth** [mattgodbolt/compiler-explorer#625]
It would be very nice (and ought to be easy to add) to support `llc` to compile LLVM IR directly.

**Comment by samth** [comment]
cc @rjnw

**Comment by mattgodbolt** [comment]
This is sort-of possible already: pass `-x ir` : https://godbolt.org/g/ATQwdE 
But we'd love to support this properly as part of multi-language support #277

**Comment by Som1Lse** [comment]
I am sort of working on this. I have already implemented `llc` support, and I am working on getting `opt` as well.

There are a few things I am not sure of yet, which are:
 - I don't know if Monaco has a mode for LLVM IR, so for now I am just using the ASM mode, which works well enough.
 - `opt` outputs binary bitcode files by default, or human readable bitcode files when passed `-S`, but it cannot output assembly (even though `--help` claims it can). I am currently thinking of fixing this by writing a shell script that pipes the output to `llc`, but if anyone has a better approach I would love it hear it. Maybe passing it through clang as in the above example? I believe the arguments to clang are different from `opt` though.
 - Also, neither tools can output a runnable binary (only object files), and I happen to like the feature to run the compiled program. Again, I am considering just wrapping it in a shell script, but it is not exactly an elegant solution.

**Comment by mattgodbolt** [comment]
Fantastic! Thanks for the update. Monaco doesn't have a mode for LLVM IR as such, but it's pretty easy to add.

**Comment by RabsRincon** [comment]
This was closed by #843 a week ago. LLVM IR is now a supported language on CE 👍
