### ISSUE TITLE
wrong interpretation of global variables in cfg structure

### ISSUE THREAD

**Issue by cppchedy** [mattgodbolt/compiler-explorer#630]
the cfg parser doesn't make a difference between global variable and function name. waiting for [#629](https://github.com/mattgodbolt/compiler-explorer/issues/629) to be fixed to deal with it ones and for all.

**Comment by mattgodbolt** [comment]
@cppchedy #629 was closed a while ago, and this is still assigned to you. If you have a moment can you see if this bug is still an issue, and if so can you write a little more explanation please? I'm not sure how I'd go about fixing this myself :)

**Comment by mattgodbolt** [comment]
Going to close this as no response. @cppchedy feel free to reopen if you think there's something to do still.
