### ISSUE TITLE
FPC -g line highlighting

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#637]
I've been experimenting with various -g options to try and mimic the line highlighting the C++ code gets.

It does seem to work great if you have only 1 method, but not when you have multiple.
For example: https://godbolt.org/g/KUXPv4

I don't know where to start on how to fix this. Can anyone point me in the right direction?

**Comment by mattgodbolt** [comment]
On other languages we always supply the `-g` option so we can highlight lines regardless of the user's chosen options.

GCC and the like have a clear indicator for each instruction which line it maps back to.  Looking at the raw output of the compiler (in non-binary mode) I can't see how it is working. https://godbolt.org/g/GA9axw vs https://godbolt.org/g/tcnuwH - check the `.loc` and `.file` directives GCC inserts.

I'm similarly confused by the binary mode (the link you sent) -- something in the disassembly output must really be confusing CE's parser.

**Comment by partouf** [comment]
I think I may have found a solution by building an actual executable (previously only 1 unit was compiled 'as if' it was an executable) - but, because most things are statically linked in FPC, all the boring system calls are included at the top of the objdump, and then the assembly is cut off with "[truncated; too many lines]"

From manually running the objdump I think I can see the correct line numbers, so this should be the solution. But now I have to figure out how to filter out the FPC System functions before it arrives at asm.js

**Comment by partouf** [comment]
Current progress -> [Imgur](https://i.imgur.com/F14sbKo.png)

I stripped all the irrelevant stuff in the assembly output, and now the line highlighting is spot on

But out of nowhere all these NOP commands are pasted into the output (I mean the code is that far apart, but it's kind of useless to show), and I'm not sure where that's coming from.

**Comment by mattgodbolt** [comment]
That's looking great @partouf !

From the screenshot you're in binary mode (is there any reason why you often pick this mode?). So, the output is from the disassembled binary. For performance reasons many functions, labels and loop targets are aligned on 8- or 16-byte boundaries. The assembler inserts padding between these using `NOP`s.

One of the reasons to use binary mode over non-binary mode is to see these padding instructions (so you see the actual layout as the CPU sees it).

In your screenshot it seems the fpc compiler is using a sequence of `NOP` instructions to align the `thello.test2` function on a 16-byte boundary. Other compilers might use different padding instructions - for example GCC - https://godbolt.org/g/Rwv2xC - uses multi-byte `NOP`s like ` nop WORD PTR cs:[rax+rax*1+0x0]` (which is a ten-byte-long `NOP`).

So, the `NOP`s are expected, and a desired feature of binary mode, in this case.

**Comment by partouf** [comment]
Aah ok, thanks, I hadn't realized that.

I use binary mode a lot because that should look about the same across all the compilers.

I'll leave it like this and concentrate on getting the regular assembly view to look right.

**Comment by mattgodbolt** [comment]
Fantastic. Thanks for your help with this!
