### ISSUE TITLE
Show GCC tree/RTL dump not working

### ISSUE THREAD

**Issue by pree-jackie** [mattgodbolt/compiler-explorer#642]
The drop-down list in Show GCC tree/RTL dump feature is not working ( Pass dump to display  drop-down list not appearing when clicked). I don't know whether it is drop-down list but it's icon seems like a drop-down list. If I'm wrong please tell me how to use that feature. 
System details:
ubuntu 16.04 xenial and mozilla firefox browser 
Thanks

**Comment by RabsRincon** [comment]
Hello, sorry to hear you're having problems!
Could you please post an image of what you're describing so we can get a clearer picture of your issue? Thanks :)

cc @dkm who implemented it in first place

**Comment by pree-jackie** [comment]
![k](https://user-images.githubusercontent.com/18092207/33210152-0a4247f4-d13f-11e7-939d-d51a6f3e9472.png)

**Comment by pree-jackie** [comment]
see the  right most tab, It's a drop down list.

**Comment by dkm** [comment]
Won't work with clang, only GCC. Sorry, I've already opened a ticket for this : #638 
The UI should be explicit about that.

**Comment by dkm** [comment]
@RabsRincon this is a duplicate of now-closed #638. Maybe you could merge them ?

**Comment by RabsRincon** [comment]
You're right. Good catch!
