### ISSUE TITLE
`WINE`-style filename is exposed to code via `opts.inputFilename`

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#643]
https://sentry.io/compiler-explorer/compiler-explorer/issues/409375530/

```
Error: ENOENT: no such file or directory, scandir 'Z:/tmp/compiler-explorer-compiler1171024-55-1uxi964.7zsm'
  File "/compiler-explorer/lib/base-compiler.js", line 488, in Object.Compile.processGccDumpOutput
    var allFiles = fs.readdirSync(rootDir);

Error: ENOENT: no such file or directory, scandir 'Z:/tmp/compiler-explorer-compiler1171024-55-1uxi964.7zsm'
```

**Comment by mattgodbolt** [comment]
Currently only on the beta site. Having the gcc dump window open and then changing to a MS compiler causes the issue.

Reproducing link: https://godbolt.org/g/FuTy8n 

Looks straightforward to fix by only attempting to process dumps for gcc. @dkm ?

**Comment by dkm** [comment]
Yes. See #638 . I wanted to produce a fix, but last few days have been really busy...

**Comment by dkm** [comment]
Is there something wrong with this code ? It should list files in the output directories and detect gcc dumps. How is it possible that the directory does not exist ?

**Comment by mattgodbolt** [comment]
Hi @dkm - sorry I didn't spot the other issue. No worries.

In reply to your second comment; no nothing wrong. The error comes from the `Z:/tmp/...` nature of the file: the `wine` backend for the MS compilers has to map back and forth between linux filenames (of the form `/tmp/blah`) to Windows filenames (`Z:/tmp/blah`) in order to get things to work. It seems that the `Z:/` filename is making it to your code somehow...this is something we should fix on our side!

**Comment by RabsRincon** [comment]
Is this still an issue? I don't seem to be able to reproduce it

**Comment by mattgodbolt** [comment]
I couldn't repro either. Closing.
