### ISSUE TITLE
`ection` present in ICC code

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#646]
Seen on beta, perhaps as part of an earlier fix: https://godbolt.org/g/yfAuZf

Output is:

```
square(int):
  push rbp #2.21
  mov rbp, rsp #2.21
  sub rsp, 16 #2.21
  mov DWORD PTR [-16+rbp], edi #2.21
  mov eax, DWORD PTR [-16+rbp] #3.18
  imul eax, DWORD PTR [-16+rbp] #3.18
  leave #3.18
  ret #3.18
ection .text
```

Possibly related to @cppchedy 's fix for the single-character labels.

**Comment by mattgodbolt** [comment]
Oh, that's super odd. I just reloaded the page and it didn't happen again. I had previously had a windows compiler selected (with the non-functioning GCC dump view open). But I can't repro now. One to keep an eye on.

**Comment by cppchedy** [comment]
I don't see how but it's very probable because that's the only thing that changed in asm.js in this commit.
(but hope it's not me)

**Comment by RabsRincon** [comment]
Note that the link does not have a `ection .text` anymore. Is this fixed already?

**Comment by mattgodbolt** [comment]
It does indeed look fixed! Marking as closed unless someone can reproduce!
