### ISSUE TITLE
MIPS labels aren't tracked correctly (`$LC0` and the like)

### ISSUE THREAD

**Issue by lzutao** [mattgodbolt/compiler-explorer#660]
![NO_SYMBOL](https://user-images.githubusercontent.com/15225902/33322213-196abe2a-d47b-11e7-9b67-66bfc24895ee.png)

**Comment by mattgodbolt** [comment]
Hi! Thanks for this. I can probably reproduce but in future if you could post a short link to an example that makes it much easier for us to see what's going on!

**Comment by mattgodbolt** [comment]
https://godbolt.org/g/bxQG5E seems to reproduce the issue. I believe you're referring to the fact there's no `"hello world\n"` constant in the MIPS assembly, right?

**Comment by mattgodbolt** [comment]
Anyone thinking of taking this one on, it's probably fairly straightforward. in `lib/asm.js` we look for label usages using a bunch of regular expressions. My guess is that the MIPS-style labels aren't being recognised.  Some simple (ish) code looks for opcodes that use labels, and then marks the label as being "used". This is how CE prunes dead code and unused labels.

**Comment by lunastorm** [comment]
I do this in lib/asm.js to workaround this issue:

 function AsmParser(compilerProps) {
-    var labelFind = /[.a-zA-Z_][a-zA-Z0-9$_.]*/g;
+    var labelFind = /[.a-zA-Z$_][a-zA-Z0-9$_.]*/g;

not sure if it has any side effect on other ISAs or not :)

**Comment by mattgodbolt** [comment]
@lunastorm thanks for the the update. I think the other ISAs like to use `$`. MIPS, for example. There are tests which check this: with your change a whole bunch of tests fail...but I am investigating and I think they fail because they now work (and the expectations were wrong!). Will investigate more...thanks!

**Comment by mattgodbolt** [comment]
Ah, sadly no. The tests fail for good reasons: On ARM `$` is used to indicate a constant, and so `movl    $.L.str, %edi` refers to a label called `.L.str` not `$.L.str`. We'll need a way to distinguish these.
