### ISSUE TITLE
Add cppcoro library

### ISSUE THREAD

**Issue by samkellett** [mattgodbolt/compiler-explorer#661]
Add this library for playing around with coroutines in trunk compilers: https://github.com/lewissbaker/cppcoro

**Comment by mattgodbolt** [comment]
We can add to the list, but you can also submit a PR for this if you have time: details on how are at https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALibrary.md

**Comment by samkellett** [comment]
good shout i've done that now: https://github.com/mattgodbolt/compiler-explorer/pull/663

will close this issue and use the PR instead
