### ISSUE TITLE
Getting include paths to work in self-hosted version

### ISSUE THREAD

**Issue by jcelerier** [mattgodbolt/compiler-explorer#674]
Hi,
I'm trying to self-host CE, but I can't manage to make it recognize my custom include directories.

eg given 
* a file /tmp/tutu/foo.hpp
* the following request: 

```JSON
{
  "options": { 
     "userOptions": "  -I/tmp/tutu "  
  }, 
  "source": "#include <foo.hpp>" 
}
```
*  `curl -H "Content-Type: application/json"  -X POST http://127.0.0.1:10240/api/compiler/%2Fusr%2Fbin%2Fg%2B%2B/compile -d '$MY_API_REQUEST'`

I get a dreaded `<source>:1:10: fatal error: foo.hpp: No such file or directory`

I tried looking in the README but couldn't find any mention of include restriction... is this a supported use-case ?

**Comment by jcelerier** [comment]
found it: the argument name should be userArguments, not userOptions as said in the readme

**Comment by mattgodbolt** [comment]
Thanks for the bug: we'll update the readme!
