### ISSUE TITLE
errors not highlighted in monaco

### ISSUE THREAD

**Issue by cppchedy** [mattgodbolt/compiler-explorer#680]
For some reasons, compilation errors aren't highlighted with in [here](https://godbolt.org/g/q1eTUn).
by highlighted, I mean there is no colors on  bar portions (no red or even an underlined text).

**Comment by partouf** [comment]
Seems that if you replace the first 2 includes with just #include vector the highlighting does work.

So it's something about these includes
```
#include <https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp>
#include <https://raw.githubusercontent.com/ben-strasser/fast-cpp-csv-parser/master/csv.h>

```

**Comment by partouf** [comment]
So the url includes seem to change the compiler output into this:
```
<stdin>:120:25: error: variable or field 'transform_data' declared void
<stdin>:120:25: error: 'It' was not declared in this scope
<stdin>:120:35: error: 'It' was not declared in this scope
<stdin>:120:44: error: 'Op' was not declared in this scope
<stdin>:128:1: error: expected '{' before '}' token
<stdin>:128:1: error: expected '}' at end of input
Compiler returned: 1
```

But with just include vector it's this:
```
119 : <source>:119:25: error: variable or field 'transform_data' declared void
     void transform_data(It first, It last, Op op){
                         ^~
119 : <source>:119:25: error: 'It' was not declared in this scope
119 : <source>:119:35: error: 'It' was not declared in this scope
     void transform_data(It first, It last, Op op){
                                   ^~
119 : <source>:119:44: error: 'Op' was not declared in this scope
     void transform_data(It first, It last, Op op){
                                            ^~
127 : <source>:127:1: error: expected '{' before '}' token
 }
 ^
127 : <source>:127:1: error: expected '}' at end of input
Compiler returned: 1
```

And if you apply the current regex to it it doesn't match:
`^\s*<source>[:(]([0-9]+)(:([0-9]+):)?[):]*\s*(.*)`

So either we could change the regex to this:
`^\s*<source>|<stdin>[:(]([0-9]+)(:([0-9]+):)?[):]*\s*(.*)`

Or the output needs to be bugfixed to be the same in both cases.

**Comment by mattgodbolt** [comment]
Nice spot @partouf - I will fix the transforms accordingly. (I just added tests for them! shock!)
