### ISSUE TITLE
Update the ARM gcc to 7

### ISSUE THREAD

**Issue by korken89** [mattgodbolt/compiler-explorer#689]
Hi!

The arm-none-eabi-gcc 7.2.1 was just release on https://launchpad.net/gcc-arm-embedded
Would it be possible to add the updated compiler to try C++17 features on embedded?
Current version is 6.3.0.

Thanks!

**Comment by RabsRincon** [comment]
Hi Thanks for letting us know that a new verison is available. Strangely, I can only see download links to v6. Is this what I want? If not, could you provide a link to the download page? I can't seem to find one for the version you mention

😄

**Comment by korken89** [comment]
Sure, no problem! Here is the direct link:
https://launchpad.net/gcc-arm-embedded/7.0/7-2017-q4-major

**Comment by korken89** [comment]
Sorry, the download files were not there, here is the PPA with the files: :)
https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa

**Comment by mattgodbolt** [comment]
Hi @korken89 - thanks! We need to build the compiler from source (we don't install using package managers etc). We'll have to wait for it to arrive in crosstool-ng (https://crosstool-ng.github.io/), or else come up with another way to install it. We can't use packages as we install to a shared network drive in a known location (`/opt/compiler-explorer/gcc-arm-eabi-....`)

**Comment by korken89** [comment]
Hi @mattgodbolt , you can't just use the pre-compiled one in the zip here? https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
Sorry, I do not know all the requirements and constraints for it to work on your servers. :)

**Comment by mattgodbolt** [comment]
Hi @korken89 - that might just do it! Thanks so much!

**Comment by korken89** [comment]
Hi @mattgodbolt , awesome :D 
I hope it works!
