### ISSUE TITLE
Opt view doesn't work with binary mode: cannot open file 'example.opt.yaml': Permission denied

### ISSUE THREAD

**Issue by mads256c** [mattgodbolt/compiler-explorer#690]
When you try to compile to binary and disassemble it this error occurs: fatal error: cannot open file 'example.opt.yaml': Permission denied.
I'm using x86-64 clang 5.0.0
with following arguments: -std=c++17 -O3

**Comment by mattgodbolt** [comment]
Hi, is this with a local install or on the main site? If the latter can you
provide a short link please!

Thanks!

**Comment by mads256c** [comment]
It is on the main site: https://godbolt.org/g/ibCCrv

**Comment by mattgodbolt** [comment]
Hi! Looks like it's a bug in the `opt` viewer. If you close the `opt` view (it's hiding in a tab next to the compiler itself) all works: https://godbolt.org/g/LbtMt7 

We'll look into the opt issue separately. (CC @jaredwy )

**Comment by mattgodbolt** [comment]
@jaredwy  https://godbolt.org/g/pFyfzz replicates this nicely

**Comment by mattgodbolt** [comment]
(assigning to you Jared but let me know if you're busy or can't look at it and I'll take a gander)

**Comment by jaredwy** [comment]
Thanks! I’m free end of the week to start back up on CE fun.

**Comment by mattgodbolt** [comment]
Thanks @jaredwy
