### ISSUE TITLE
Bad usage of rlwimi with PowerPC gcc 4.8.5 compilation

### ISSUE THREAD

**Issue by PhilLinggmx** [mattgodbolt/compiler-explorer#691]
PowerPC gcc 4.8.5 generate a machine code badly using rlwimi.

It used a 3rd register while rlwimi can only use 2:
ex: rlwimi %r9,%r3,%r10,16,23 instead of rlwimi %r9,%r3,8,16,23
Most funny is that in my example, %r10 is an immediate value, 8.

Following code can reproduice the problem :
N32_mf_Update_with_masked_left_rotated(l_Result,l_Temp,8,16,23);

with:

/*-- Update with masked left rotated --*/
#define N32_mf_Update_with_masked_left_rotated(\
  i_Initial,\
  i,\
  i_Bit_count,\
  i_Begin_bit_offset,\
  i_End_bit_offset)\
  i_Initial = N32_f_With_masked_left_rotated(i_Initial,i,i_Bit_count,i_Begin_bit_offset,i_End_bit_offset)\

/*---------------- With masked left rotated ----------------*/
N32_t N32_f_With_masked_left_rotated(
  N32_t const i_Initial,
  N32_t const i,
  N32_t const i_Bit_count,
  N32_t const i_Begin_bit_offset,
  N32_t const i_End_bit_offset){

  /*==== Data ====*/
  N32_t l_Mask;
  
  /*==== Processing ====*/
  l_Mask = N32_f_Mask(i_Begin_bit_offset,i_End_bit_offset);
  return
      (i_Initial & ~l_Mask)
    | (N32_f_Left_rotated(i,i_Bit_count) & l_Mask);
}

**Comment by mattgodbolt** [comment]
Hi!

Compiler Explorer just shows the output of compilers; it isn't a compiler itself. If you think this is an issue with the specific compiler build used on Compiler Explorer, let me know - else this sounds like a bug in GCC and should be reported at https://gcc.gnu.org/bugzilla/

Let me know if you have any further comments: I'll close this bug tomorrow if I don't hear back.
