### ISSUE TITLE
globals deleted by "remove comments" when viewing LLVM IR via -emit-llvm

### ISSUE THREAD

**Issue by zygoloid** [mattgodbolt/compiler-explorer#700]
I often use compiler explorer with a `-emit-llvm` flag to view the LLVM IR produced by Clang / LLVM's middle-end optimizers. This generally works pretty well (and even syntax-highlights fairly nicely), but the "remove comments" option strips out lines starting with an `@`, which deletes all the global variables!

Some better support for viewing LLVM IR output would be great (per #288), but if that's a long way off, something as simple as detecting `-emit-llvm` in the command line and not treating lines starting with `@` as comments would be marvelous.

**Comment by jaredwy** [comment]
I have support half way done for LLVM IR with proper syntax handling in monaco. I will have some time over the holidays to focus on all my "half way done" work in progress for CE.   

I will keep this bug open to remind my self to check that comments stay in.

**Comment by JohanEngelen** [comment]
@jaredwy I've independently started working on LLVM IR support too, but rather join your effort. Do you have a public branch up that we can collaborate in?

**Comment by mattgodbolt** [comment]
https://godbolt.org/z/dp_iOv demonstrates this -- the `@global` vanishes. However, the "LLVM IR" view is now around: https://godbolt.org/z/2WMSas

Would be nice for the `-emit-llvm` to not filter `@global` though: we have some magic to notice LLVM it seems. So will leave this open.

**Comment by nickdesaulniers** [comment]
bump. comments in llvm are lines starting with `;`, `@` is to denote global symbols.

**Comment by RabsRincon** [comment]
Hi - I've now improved how we detect when the compiler is asked to emit the IR and we properly filter it now. The fix should hit the live site shortly :)

**Comment by partouf** [comment]
This change is now live. Thanks for the reminder @nickdesaulniers 
 and thanks @RabsRincon for fixing it!
