### ISSUE TITLE
Reports of "racy" behaviour with new compiler site

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#707]
https://twitter.com/mattgodbolt/status/946518175004397574

Having no luck getting things to work until several refreshes and whatnot.

Transcript of sorts:

>it doesn't seem to work at all for me? Neither Rust nor C++ work D:
actually, no language works. clang segfaults and the others complain about wrong command line options
after refreshing a couple of times, the bugs slowly faded away. There were no compiler options left, and yet they were passed to the compilers. It looks like there's some racy behavior with the text boxes

**Comment by RabsRincon** [comment]
Please if someone else experiences this, let us know. We've not been able to reproduce this

**Comment by CryZe** [comment]
I tried to reproduce it and there's a lot of small weird behaviors.

 - Open godbolt beta through private browsing (so there's no cookies)
 - Put `-O3` in compiler options
 - Switch to Rust, notice how it doesn't compile and the `-O3` is gone. It uses the `-O3`, which is not a valid compiler option for Rust, but it is not shown.
 - Switch to C++ and back to Rust, and now it's here.

There's a couple of other weird behaviors, but those could be related.

**Comment by RabsRincon** [comment]
@CryZe Fixed, thanks for the detailed report :)

**Comment by mattgodbolt** [comment]
Awesome work everyone! Thank you so much

**Comment by mattgodbolt** [comment]
Fix pushed to beta and seems to be working!
