### ISSUE TITLE
Two different methods demangle to the same name

### ISSUE THREAD

**Issue by kosak** [mattgodbolt/compiler-explorer#713]
Hi Matt,

In https://godbolt.org/g/1Nvfdz , the compiler (correctly) generates two destructors for `Normal::~Normal`, one which calls `operator delete` for you and one that doesn't.

The problem is that the demangler gives them both the same name, which always bugs me just a little bit when I'm tracing through code. Is it possible to demangle these to different names? Do you have any control over demangler output? 😃

**Comment by partouf** [comment]
The odd thing to me is why the 2nd destructor (_ZN6NormalD2Ev) isn't filtered out by the unused labels filter.

But CE uses whatever c++filt gives back from the asm, but it's not contextual or anywhere smart, it just tries its best to translate anything mangly to a human readable version.

I think the question would be, what would you call it, if somehow both destructors were actually used in the code?

**Comment by kosak** [comment]
It's in use because it's in the vtable... more accurately `_ZN6NormalD1Ev` is in the vtable and it's defined as an alias for `_ZN6NormalD2Ev`.

According to https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling , ...D0 is a "deleting destructor", ...D1 is a "complete object destructor", and ...D2 is a "base object destructor". (note 1)
There is a completely analogous situation with respect to constructors.

As for what would I call it? Doesn't matter much to me. Might be nice to see
```
call Foo::~Foo() [deleting destructor]
```
or
```
call Foo::~Foo() [complete object destructor]
```

Seems to me this would be a trivial patch to c++filt. On the other hand, it's also easy to see that the c++filt maintainers might not want such a patch, and on the third hand it's also easy to see that Matt might not want to run a custom build of c++filt.

On the Nth hand however, the whole point of Compiler Explorer is to peer into what the compiler is *really* doing, and it seems just a tiny bit sad that (owing to demangling), this particular issue or which constructor/destructor is called sort of gets glossed over, unless you are careful to look at the mangled names.

note 1: The difference between D1 and D2, as explained in 1.1 Definitions, is that the complete object destructor also deletes virtual base classes. Since I don't have any of those, the compiler decided to alias them).

**Comment by mattgodbolt** [comment]
Will be fixed in an upcoming site release.

**Comment by mattgodbolt** [comment]
Fix is now live. Thanks @partouf

**Comment by kosak** [comment]
This is amazing. Thank you folks so much!!!
