### ISSUE TITLE
GCC dump view does not update its name when compiler is changed

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#720]
View gets its name when created and does not update when compiler is changed.
Will provide a trivial PR in the coming days :)

**Comment by RabsRincon** [comment]
Ey @dkm thanks for noticing this. When taking a look into this, I've found that we're storing the compiler name in the url state, which is probably not needed. So, hoping that it does not bother you, I'll fix this and push to the live server right now.

:)

**Comment by RabsRincon** [comment]
Note, tho, that the GCC pass is not working when execution is enabled, or at least, not for me locally. Can you take a look into that?

**Comment by dkm** [comment]
Ok, I'll have a look :) Thanks for fixing it. I tried to have a look at it, but updating my local setup with latest master did not worked as expected. Maybe I'll open some new tickets :D
