### ISSUE TITLE
Paste is missing from right click menu

### ISSUE THREAD

**Issue by badeip** [mattgodbolt/compiler-explorer#721]
Cut and Copy exists, so Paste should also be an option.

**Comment by RabsRincon** [comment]
Hi! I wish we could do something for this, but the Monaco team has explained why there is no paste button there already: https://github.com/Microsoft/monaco-editor/issues/391#issuecomment-312237052

**Comment by RabsRincon** [comment]
Hi! I wish we could do something for this, but the Monaco team has explained why there is no paste button there already: https://github.com/Microsoft/monaco-editor/issues/391#issuecomment-312237052

**Comment by badeip** [comment]
Ok.
AFAICS, that makes it impossible to paste when using the site with e.g an iPad.
