### ISSUE TITLE
Requests for libraries are not being sent

### ISSUE THREAD

**Issue by cjdb** [mattgodbolt/compiler-explorer#724]
I'm currently unable to import C++ libraries. Upon refreshing, the checkboxes for the libraries I've asked for are now unchecked.

Sample: https://godbolt.org/g/E11zxk (both GSL trunk and cmcstl2 should be checked)

**Comment by mattgodbolt** [comment]
Oh cripes! Good spot. Thanks!

**Comment by RabsRincon** [comment]
Sorry about this, it slipped past my reviews... I'll udpate the shite as soon as Travis is done building the commit

**Comment by RabsRincon** [comment]
This should now be fixed. Note that you'll have to create a new url (We forgot to store the selected libs in the URL!) for it to work. Sorry about this!

**Comment by mattgodbolt** [comment]
I can't get it to work, e.g. https://godbolt.org/g/UfS2AS doesn't show any new libraries added to the search path

**Comment by mattgodbolt** [comment]
Will do another update shortly! Thanks for your patience @cjdb  :)

**Comment by mattgodbolt** [comment]
Ok! Site updated, and my tests suggest it's working!

**Comment by cjdb** [comment]
Thanks for getting to this so fast! 😄
