### ISSUE TITLE
Slow access to headers: Boost asio times out

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#730]
Recently, when compiling snippets that involve including a boost header, the compiler times out. I am aware of the 10s compilation time limit, but it would surprise me if including, say, boost/asio.hpp would take this much time.

Could it be that the disk /opt/compiler-explorer/libs/boost_1_65_0 is being mapped to storage that is somehow slow/laggy/broken?

Example:

https://godbolt.org/g/Pmhwvi

```
#include <boost/asio.hpp>
int main()
{
}
```
command line options:

`[gcc7.2] -std=c++17 -O3 -pedantic -Wall -Wextra -march=native -I/opt/compiler-explorer/libs/boost_1_65_0`

output:

```
Killed - processing time exceeded

Compiler returned: -1
```

**Comment by partouf** [comment]
Locally on my Mac Clang8.1.0 it takes 3 seconds to include and build with the boost asio compared to 63 millseconds with just a main(), so I'm guessing depending on the files included through that, if the storage is even a fraction slower it can definitely build up to be slower than 10s

**Comment by mattgodbolt** [comment]
I ran on the beta node (which is similar to the live nodes but has a local disc for `/opt`):

```
real	0m1.479s
user	0m1.120s
sys	0m0.352s
```

So this is odd. But, we are definitely seeing very slow NFS/CacheFiles issues at the moment which we're trying to diagnose. Could easily be related.

**Comment by mattgodbolt** [comment]
Confirmed: running on a prod node over NFS take around 9 seconds:

```
real	0m8.859s
user	0m1.624s
sys	0m0.220s
```

We're definitely seeing some really odd network problems here.

**Comment by mattgodbolt** [comment]
I've now bounced the nodes to disable fs caching (Suspected to be the cause of issues). Still no joy I'm afraid.

**Comment by mattgodbolt** [comment]
Some other thoughts. To just preprocess the files takes ~7 seconds:

```
$ time g++ -E -o monk -std=c++17 -O3 -pedantic -Wall -Wextra -march=native -I/opt/compiler-explorer/libs/boost_1_65_0 moo.cc

real	0m7.147s
user	0m0.208s
sys	0m0.044s
```

It generates a 4.6M, 169307-line file:

```
ubuntu@ip-172-30-0-71:/tmp$ ls -lh monk
-rw-rw-r-- 1 ubuntu ubuntu 4.6M Jan  3 18:16 monk
ubuntu@ip-172-30-0-71:/tmp$ wc -l monk
169307 monk
```

**Comment by mattgodbolt** [comment]
See also mattgodbolt/compiler-explorer-image#53
