### ISSUE TITLE
AST button is available when compiling with gcc

### ISSUE THREAD

**Issue by ruipacheco** [mattgodbolt/compiler-explorer#733]
I'm using godbolt with gcc 4.8.5 to test some simple CRTP code. I noticed that on the right side pane there's a disabled button labelled "Show optimization (Clang only)" and next to it there's another button labelled "Show AST output (Clang only)", except this one is not disabled. Is this correct?

**Comment by mattgodbolt** [comment]
We've been a bit indecisive about which things are available when. We'll look to unify the UI.

**Comment by RabsRincon** [comment]
Hi! Sorrry this took so long to get addressed. We had to wait for an internal change to land before we were able to change the needed parts for the AST button to be disable-able. The fix will land in the site some time this week, should everything go as planned.

Thanks again for your patience :)
