### ISSUE TITLE
Visual cursor doesn't match the actual text cursor

### ISSUE THREAD

**Issue by CryZe** [mattgodbolt/compiler-explorer#737]
Here's a video of the behavior:

[Video](https://i.imgur.com/iJPObUz.gifv)
  
This is on Chrome 63.0.3239.84 on Windows 10. I can check other browsers. This didn't happen before the language unification.

**Comment by RabsRincon** [comment]
Hello. This behaviour has been reported before, but nothing in the unification changes suggest that we are the culprits. I'll keep looking around in case I find how we are triggering this issue, but I think this is ultimately a Monaco problem

**Comment by CryZe** [comment]
Yeah, I suspect it's a Monaco bug too.

**Comment by mattgodbolt** [comment]
Idle thought: we also fiddled the font in c202f1dc70095f542825ac8bf9ca2a30275fe0be which might confuse things? No idea...clutching at straws.

**Comment by partouf** [comment]
Can imagine that if the browser chooses Monospace, but Monaco picks Fira Mono that's not available and reverts to some non-monospaced font to determine the width of the text to place the cursor. Again, still a Monaco bug then, but might be able to fix by removing Fira Mono.
