### ISSUE TITLE
https://godbolt.org/ will not load, "TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by mhorowitz** [mattgodbolt/compiler-explorer#741]
I get a setting-related JS error "TypeError: Cannot read property 'id' of undefined" which looks like it was introduced by https://github.com/mattgodbolt/compiler-explorer/commit/4c3762d7ad0d30f0701fae58568f875072a61a64

![image](https://user-images.githubusercontent.com/290225/34547947-933f383a-f0b3-11e7-8b82-bf0335c5bbf5.png)

I see a similar error in Chrome (shown), Safari, and Firefox, all on OSX.

cc @RabsRincon

**Comment by aryan-gupta** [comment]
Same issue here. Nothing loads. All I see is the top navbar and a white screen.

**Comment by d0mm** [comment]
Same here. Firefox 57.0.3: TypeError: w[this.settings.defaultLanguage] is undefined

**Comment by RabsRincon** [comment]
I am so so so sorry about this. A fix is coming. Again, so sorry about this

**Comment by RabsRincon** [comment]
Please bear with me while the update is in progress. Our control node seems to be haing some problems and it's taking longer than expected to update the page. Sorry again about any problems that this may cause

**Comment by RabsRincon** [comment]
Ok. Site should be updated. Please let me know if you experience something similar again
