### ISSUE TITLE
Please enable openmp for clang.

### ISSUE THREAD

**Issue by LebedevRI** [mattgodbolt/compiler-explorer#751]
Needs libomp5
https://godbolt.org/g/XM3H8A

Works for gcc.

**Comment by mattgodbolt** [comment]
Hi. As a workaround, disable the "compile to binary" which will prevent linking: https://godbolt.org/g/edfGrc

Compiler Explorer doesn't yet have a rich set of third party libraries to link against. I image as part of the execution support we'll have to fix this anyway.

**Comment by LebedevRI** [comment]
Oh, right, thank you :)

**Comment by RoyiAvital** [comment]
@mattgodbolt , How exactly did you "Disable Compile to Binary"?
I don't see such option.

**Comment by LebedevRI** [comment]
![image](https://user-images.githubusercontent.com/88600/45262233-be9ee080-b41b-11e8-8b93-a3dbad4999b7.png)

**Comment by RoyiAvital** [comment]
It still fails at that mode if the user add `#include <omp.h>` with `CLang`.

By the way, I'm having issues with Intel Compiler as well in https://godbolt.org/z/j1F7Ac.

**Comment by mattgodbolt** [comment]
Hi @RoyiAvital - do you have any ideas on this? I admit I have no idea at all what might be going on. There's nothing obvious in the compilers that I can see. I googled the error and found https://software.intel.com/en-us/forums/intel-c-compiler/topic/760979 - defining -D__PURE_INTEL_C99_HEADERS__ then makes it look like math.h isn't being included at all. Very odd!

**Comment by mattgodbolt** [comment]
Hi @RoyiAvital - I am going to close this issue as not reproducible. If you still have issues please let me know!
