### ISSUE TITLE
De-ggc-fy favicon

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#752]
I think it's about time to change the favicon, as we currenlty support a lot more compilers than just GCC. This is more of a suggestion than a TO-DO. First of all, it would be great to know what @mattgodbolt thinks :)

**Comment by mattgodbolt** [comment]
Absolutely! I've been meaning to try and get a logo sorted. We've had a few contributed along the way, nothing that's ever grabbed me and made me go "wow". I've been thinking of actually paying a designer to do one (!)

**Comment by mattgodbolt** [comment]
I've asked a designer to take a look!

**Comment by mattgodbolt** [comment]
And we're done. Fixed in 1050da5d559bc2b16bca0e51d09cd6239a6d3d71 amongst other commits.
