### ISSUE TITLE
routing for languages or/and examples

### ISSUE THREAD

**Issue by DaemonSnake** [mattgodbolt/compiler-explorer#759]
I believe it would be useful to allow routing to a specific language or example.
For instance instead of using *cppx.godbolt.org* we could use *godbold.org/lang/meta_class*.

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to suggest an improvement. 
Could you give me some insights into how language routings could be useful?  :)

**Comment by DaemonSnake** [comment]
Personally I use compiler explorer to test/share my implementations of some C++ proposals for G++.
Because of that I create a new 'language' for CE per proposal so that each language has its own default example. The issue arise when I want to share a new implementation through a link.
The default share solution would be pretty long and with the short-URL solution we end up with something meaningless.
On the godbolt front, it make it easier to share godbolt for non-C++ languages as I've notices that the language box if often missed by new users. For recurring users routing allows the user to idealize autocomplete, bookmark, etc... for one the different languages.
It's not a huge feature but at least personally I would have some uses for it.
Thanks in advance.

**Comment by RabsRincon** [comment]
This has been allowed for some time now. Sorry we did not notice the issue sitting here for so long! :)
