### ISSUE TITLE
Short URL doesn't decode properly

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#766]
Consider https://godbolt.org/g/mboZWU (via #169 ) - it used to work (as best I recall) but now loads up the default view. You can see in the expanded URL that there's some text, but the editor window has the default program.

**Comment by mattgodbolt** [comment]
Expands to: https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,source:''),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50.610257954431404,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg630,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',trim:'1'),libs:!(),options:'-include+/etc/passwd+-E',source:1),l:'5',n:'0',o:'ARM+gcc+6.3.0+(Editor+%231,+Compiler+%231)',t:'0')),k:49.38974204556861,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by mattgodbolt** [comment]
Ok - looking at the code it's the case that there's no source as such (looks like it's the text "C++ source"). Still odd that it doesn't appear in an editor.

**Comment by RabsRincon** [comment]
This was an oversight on my end. Fixing as soon as I finish my lunch. Oops

**Comment by mattgodbolt** [comment]
Oh don't worry this is not high priority
