### ISSUE TITLE
Consider adding OCaml support

### ISSUE THREAD

**Issue by philtomson** [mattgodbolt/compiler-explorer#775]
OCaml is said to be in the C++ ballpark performance-wise and used about as much as Haskell in industry.  Facebook and JanesSteet are a couple of the larger users.

**Comment by Freyr666** [comment]
+1. and it should'n be hard.

**Comment by RabsRincon** [comment]
A week ago @ubsan showed some intereset on implementing it over at the Slack channel, so this might be closer to getting implemented than expected! :)

**Comment by ubsan** [comment]
I need time to do it, I've been pretty busy 😄 

I think I should have time tonight.

**Comment by philtomson** [comment]
I notice this says it's "waiting"  - so is this a finished feature that just isn't merged in yet?

**Comment by mattgodbolt** [comment]
Not as far as I know, I'm afraid. I think the waiting here is on @ubsan (maybe!?)

**Comment by ubsan** [comment]
I ended up not working on this, unfortunately.

**Comment by RabsRincon** [comment]
Closed by #1445 a while ago, ooops!
