### ISSUE TITLE
Fix `Jcc` assembler instructions documentation link.

### ISSUE THREAD

**Issue by Ethiraric** [mattgodbolt/compiler-explorer#784]
This is the follow-up of PR #783.

The generated documentation for the `Jcc` family of instructions redirects to the wrong page.

https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/scripts/docenizer.py Should be the script to modify.

**Comment by RabsRincon** [comment]
Hi @Ethiraric thanks for the follow-up to the PR, we really appreciate it. Are you planning giving it a try?

**Comment by Ethiraric** [comment]
No worries! Many thanks to you for the amazing tool!

I will definitely have a look at it by the end of the week. I don't know whether you consider it as urgent, but if it is, anyone can do it before me.

**Comment by RabsRincon** [comment]
Sure! Feel free to contact us should you find any problem implementing this. Note that if you want to test the changes, you will need the documentation set @ http://www.felixcloutier.com/x86/x86.zip

**Comment by Ethiraric** [comment]
Thank you very much for the info and support! :+1:

**Comment by Ethiraric** [comment]
It seems like the problem affected more instructions that I expected. I have identified the problem and have worked on a fix.

However, the linting is completely different, which makes it impossible to know whether I've actually broken something.
`git` shows me that I've deleted the entire file and re-written it back.

Do you have an automatic linter for Javascript, or should I try to change the format of the dumping?
