### ISSUE TITLE
Rustc: Would it be possible to support WASM?

### ISSUE THREAD

**Issue by adiba** [mattgodbolt/compiler-explorer#786]
Compiling with rustc and `--target wasm32-unknown-unknown` fails because this target is not installed.
Support for WASM and WebAssembly Text Format in the output pane would be great.

**Comment by CryZe** [comment]
It may actually make sense to add other targets like arm, powerpc and co. as well, considering some other languages have those.

**Comment by CryZe** [comment]
It already works if you try hard enough. Here's a little rust fibonacci implementation compiled to WebAssembly on Godbolt: https://godbolt.org/g/Bj1gG2

**Comment by adiba** [comment]
@CryZe interesting!
why does it fail with `opt-level=0` though?

**Comment by CryZe** [comment]
If you mean the missing panic item error. That's because opt-level=0 has panic paths that would get optimized away otherwise and I didn't copy the panic handling code from libcore / libstd. But I think wasm-unknown-unknown generally has problems with opt-level=0 atm
