### ISSUE TITLE
Dragging elements creates a gap 

### ISSUE THREAD

**Issue by RabsRincon** [mattgodbolt/compiler-explorer#788]
When dragging an element to the right of the screen (Either a new one or just moving an-already created one) a gap appears on the right side screen.

**Comment by RabsRincon** [comment]
A GIF is worth a thousand words: 
![peek 05-02-2018 10-25](https://user-images.githubusercontent.com/5364255/35797114-f9b5f288-0a5e-11e8-81a1-3612e931829e.gif)

**Comment by mattgodbolt** [comment]
Seems the scroll bars that pop up and then vanish are the culprit (if I see it right). Weird! I wonder when this issue came in. We can try `git bisect`ing to find it
