### ISSUE TITLE
Adding "-g" to Rust explorer causes code generation differences

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#79]
Specifically the -g I use to get the colourise information adds frame setup to all functions (!)

**Comment by CryZe** [comment]
This is now resolved on the nightly compiler.

![https://i.imgur.com/OhFhEXk.png](https://i.imgur.com/OhFhEXk.png)

https://godbolt.org/g/dCPJyK

**Comment by mattgodbolt** [comment]
Was fixed in Rust 1.27, so...calling this done. Thank @CryZe
