### ISSUE TITLE
Browser hangs with certain code

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#794]
https://godbolt.org/g/f8gMpD - enabling some of the filters kills the browser. Investigating now

**Comment by mattgodbolt** [comment]
It's the unused label filter that does it. It's stuck in the LRU cache code.

I think this is fixed by @jaredwy 's changes to get the newer, working LRU cache in.

**Comment by mattgodbolt** [comment]
```javascript
function trim (self) {
  while (self._lru < self._mru && self._length > self._max)
    del(self, self._lruList[self._lru])
}
```
is the culprit. The `del` code exits early and we spin forever.

**Comment by RabsRincon** [comment]
Duplicate of #568
