### ISSUE TITLE
Checkbox selection of compiler options

### ISSUE THREAD

**Issue by lhayhurst** [mattgodbolt/compiler-explorer#8]
In addition to allowing the user to type in the compiler flags into the "Compiler Options:" text area (for example "-O2 -std=c++0x -march=native"), present a checklist of option and option descriptions (perhaps ripped from the [manpage](http://linux.die.net/man/1/gcc).    User can go through and check off the ones she'd like to try, generating the command line on-the-fly.

**Comment by mattgodbolt** [comment]
Also requested recently both at CppCon and via email.

**Comment by RabsRincon** [comment]
We have had this now for a while thanks to the great @partouf, now every compiler has a "popular arguments" button which tell you what most people use
![imagen](https://user-images.githubusercontent.com/5364255/58572806-afc3bc80-823c-11e9-984b-2e0aef80c0b0.png)
