### ISSUE TITLE
Add a command-line option to disable all caching

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#801]
If one's experimenting with external libraries then both in-browser caches and in-node caching should be made disableable behind a switch.

Requested via twitter: https://twitter.com/Eric01/status/959532612384518144

**Comment by EricWF** [comment]
I'm willing to submit a PR if someone can point me in the right direction. I've been hacking on the JS, and haven't found an easy way to disable caching that works.

Ideally I would like to delete a character, re-type the same character, and have the entire compilation repeated anew.

**Comment by mattgodbolt** [comment]
There's a button in the UI to re-submit (at the bottom right).

To disable the caching you'll need to do something like:

* add a command-line option in `app.js` near the top of the file
* pass it as a configuration option to the browser; add it to `options` around https://github.com/mattgodbolt/compiler-explorer/blob/master/app.js#L268
* Server-side, use the config to indicate to `lib/compilation-env.js` that its `cacheGet` should always return `undefined` (or similar)
* Browser-side use the config set in step 2 above to disable the cache in `CompilerService` (`static/compiler-service.js`)

**Comment by RabsRincon** [comment]
So: I've added an EXTRA_ARG that disables all caching, server & client side. But as you might have guessed, this is not going to be used in the live site (For obvious reasons!) so locally, simply running `make EXTRA_ARGS="--noCache"` should do the trick.

:)
