### ISSUE TITLE
Editor font looks ugly (in specific version of OS).

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [mattgodbolt/compiler-explorer#803]
Currently the `font-family` of `div.view-lines` is `monospace`, which is reasonable, but on Chinese version Windows, the browser will choose a very very ugly font `SimSun` for '`monospace`'. It looks very bad because the font displays space in incorrect width and then breaks all indentation.

My suggestion is adding `Consolas` to `font-family`.

![image](https://user-images.githubusercontent.com/12868093/35798206-09b4a1fa-0a9d-11e8-8e55-d2e83956bad1.png)

**Comment by RabsRincon** [comment]
Hi! We have had some issues with the editor fonts in the past, but you're right, we should force something so it looks the same for everyone. (Or better yet, make it into a configurable setting)
Client-side code is somewhat locked down right now, but once it can be worked on, I'll see what I can do.

Thanks for your suggestion :)

**Comment by MichaelSuen-thePointer** [comment]
That's fine, For now my workaround is using chrome extension `Stylish` to overwrite the CSS.

**Comment by RabsRincon** [comment]
This is something we can do! Indeed, it should hit the live site once we push the new version to the site

**Comment by brainplot** [comment]
That's great, thanks!
