### ISSUE TITLE
Compiler config sent to clients is overly long

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#804]
Currently the `compilerExplorerOptions` sent to the client is pretty large. Mostly it's due to the number of compilers we now have (which is fine), but we can trim down the options a bit.

e.g. we don't need to send things like `compilerType`, `objdumper`, `options`, `postProcess` and so on (only the backend needs these).

**Comment by RabsRincon** [comment]
An early tests shows a 18% size reduction (17,9KB -> 14,7KB) for the exported options when unnecesary stuff is removed. Pretty cool

**Comment by mattgodbolt** [comment]
Cool! Thanks for checking. Still dwarfed by some other things we load, but
anything to reduce the index.html helps (as that's not as aggressively
cached as the versioned assets)
