### ISSUE TITLE
clang 5.0 compilation fails, gcc 7.3 succeeds, on a pretty simple program

### ISSUE THREAD

**Issue by eyalroz** [mattgodbolt/compiler-explorer#808]
I just tried the website with this program:

```
#include <string>
class C {
    std::string s_;
public:
    C(std::string s) : s_(s) { };
    void bar();
};
void foo()
{
    std::string hello { 
        "The quick brown fox jumped over the lazy dog" };
    C c { hello };
    c.bar();
}
```
and to my chagrin, clang 5.0 compilation supposedly [failed](https://godbolt.org/g/ecSb4W). Well, it doesn't fail on my machine... so I guess this is a bug.

**Comment by eyalroz** [comment]
Ok, it's probably due to lack of --std=c++14. You can close if you agree.

**Comment by mattgodbolt** [comment]
Indeed. If you open the output window you'll see clang's error is:

```
<source>:13:22: error: expected ';' at end of declaration
    std::string hello { 
                     ^
                     ;
```

**Comment by eyalroz** [comment]
Have you guys considered making "compilation failed" a link to the compilation errors? Or have it trigger the output?

**Comment by mattgodbolt** [comment]
A link...no, thanks for the idea. Triggering: I'd definitely not want that. Most of the time the inline warnings in the editor (also hit F8 to see them) are what I like to see. If I need loads more output I'll manually open a pane; having it pop open every time there's an error would be very annoying every time one briefly stops typing (but before code has been completed) :)

**Comment by RabsRincon** [comment]
I think the best approach here is to have the UI better express that the Output button at the bottom of the compiler window probably has some useful information. #809 is something that might help but we do need some more improvements
