### ISSUE TITLE
module.js throw when running local instance

### ISSUE THREAD

**Issue by SternAndrew** [mattgodbolt/compiler-explorer#814]
I just updated using git pull for my local instance.
Now when I try to run compiler explorer locally i get a module.js throw.
I reverted back to version 5daece and had the same error.
Reverting back further to 0848c3 restores my instance to a working instance.

-------------------------Details------------------------------------------------

Checked out head here using git pull
...
Rust language support disabled
/home/user/tools/bin/node .js install
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/user/compilerexplorer/.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
make: *** [.npm-updated] Error 1
[user@localhost compilerexplorer]$ gitk --all &
[1] 3533
[user@localhost compilerexplorer]$ git checkout 5daece
Note: checking out '5daece'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5daeceb... Merge pull request #792 from mattgodbolt/fixedes6
[user@localhost compilerexplorer]$ make
which: no yarn in (/opt/compiler-explorer/node/bin:/opt/compiler-explorer/yarn/bin:/home/user/tools/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/tools/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/user/.local/bin:/home/user/bin)
which: no cargo in (/home/user/tools/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/tools/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/user/.local/bin:/home/user/bin)
Haskell language support disabled
D language support disabled
Rust language support disabled
/home/user/tools/bin/node .js install
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/user/compilerexplorer/.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
make: *** [.npm-updated] Error 1
[user@localhost compilerexplorer]$ git checkout 0848c3
Previous HEAD position was 5daeceb... Merge pull request #792 from mattgodbolt/fixedes6
HEAD is now at 0848c3c... Remove report uri
[user@localhost compilerexplorer]$ make
which: no cargo in (/home/user/tools/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/tools/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/user/.local/bin:/home/user/bin)
Haskell language support disabled
D language support disabled
Rust language support disabled
/home/user/tools/bin/npm install
up to date in 3.464s

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 5.6.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

make -C c-preload
make[1]: Entering directory `/home/user/compilerexplorer/c-preload'

**Comment by jaredwy** [comment]
That is just before the update we made to use webpack and yarn. 

Could I just check what version of node you are using?

**Comment by SternAndrew** [comment]
I'm running node version 8.9.0.  I update the source and tried again to get the same error.  I then ran 'npm install -g yarn' and tried again.  Same issue.

--details--

[user@localhost compilerexplorer]$ npm install -g yarn
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
/home/user/tools/bin/yarn -> /home/user/tools/lib/node_modules/yarn/bin/yarn.js
/home/user/tools/bin/yarnpkg -> /home/user/tools/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.3.2
updated 1 package in 0.426s
[user@localhost compilerexplorer]$ make
which: no cargo in (/home/user/tools/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/tools/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/user/.local/bin:/home/user/bin)
Haskell language support disabled
D language support disabled
Rust language support disabled
/home/user/tools/bin/node /home/user/tools/bin/yarn.js install
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/user/tools/bin/yarn.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
make: *** [.npm-updated] Error 1

**Comment by SternAndrew** [comment]
I do find yarn.js on my machine but at a different location. It is found at xxx/node_modules/yarn/bin/yarn.js .  Where xxx is on my LD_LIBRARY_PATH.  Copying yarn.js from the node_modules location to the location where it is looking for it still generates an error with cli.

/home/astern/tools/bin/node /home/astern/tools/bin/yarn.js install
module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:536:15)

**Comment by mattgodbolt** [comment]
Hi @SternAndrew - sorry you're having problems with yarn. We're looking into making this work better, or at all in your case! The recommendation is to install using your native method (like the `npm -g` says), though at home I don't do this (I have it installed in `/opt/compiler-explorer/yarn` - but that's specific to my setup).

We moved to yarn as `npm` has been deprecated and the recommended upgrade  is `yarn`.

**Comment by mattgodbolt** [comment]
Argh, hadn't finished writing that previous comment. We'll keep diggin on our side. It's my hope we can make this all transparent to the end user (maybe through fetching `yarn` with `npm` or something crazy like that!)

**Comment by mattgodbolt** [comment]
I have a branch which _hopefully_ fixes this. @SternAndrew if you can try out the `install_yarn` branch and let us know if it solves your problems that'd be ace!

**Comment by SternAndrew** [comment]
Works perfectly.  Thank you.  BTW thought your video from cppcon 2017 was great.  Like to see more in the future.

**Comment by mattgodbolt** [comment]
Thanks for checking the solution. We still may yet use a different method to fix the issue (@jaredwy has some better ideas), so we may ask you to test `master` again in future. I'll leave this bug open til we either merge the branch or solve it another way.

Thanks for the kind words about the cppcon video! I've recorded some others (search my name on YouTube); and I plan on doing more when I can.

**Comment by RabsRincon** [comment]
`yarn_install` branch has been merged. :+1:
