### ISSUE TITLE
Graph view only shows "No Output"

### ISSUE THREAD

**Issue by itsZN** [mattgodbolt/compiler-explorer#819]
Adding a graph output on a compiler window creates a window that only every says "No Output" in the center.

This happens on both clang and gcc compilers, and when both using x86-64 and -m32 for just x86.

Also the title of the window says `Compiler #undefined` which may be related to what is causing this issue.

This happens on both the normal and beta sites.

**Comment by RabsRincon** [comment]
Hi! Thanks for letting us know. This should have not happened, we're sorry! :$
