### ISSUE TITLE
Eigen trunk appears broken

### ISSUE THREAD

**Issue by dbeurle** [mattgodbolt/compiler-explorer#821]
Eigen trunk seems to be broken for this minimal example:

```cpp
#include <Eigen/Dense>
```
You can check this by switching from stable to trunk.  Adding the path listed [here](https://github.com/mattgodbolt/compiler-explorer/wiki/Installed-libraries) in the compiler command line doesn't help either.

Thanks for the tool!

**Comment by RabsRincon** [comment]
Hi! Thanks for noticing this. Something went wrong and we added trunk to the UI but not to the backend! I'll fix this right now. :)

**Comment by dbeurle** [comment]
Rockstar - thanks!

**Comment by RabsRincon** [comment]
This should now be fixed. 👍
