### ISSUE TITLE
GCC tree/rtl dump forces refresh of assembly and resets position

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#824]
When using the GCC dump view, each time the pass is changed, the assembly is refreshed (because a new compilation is triggered) and editor's position is reset (ie. scrolled back to the top). Problem particularly painful for big assembly files...

**Comment by RabsRincon** [comment]
Hi! The recompilation is not something we worry too much about. Now, I would like to solve the editor getting reset, but just so we're on the same page, you meant the compiler output, not the editor one, right?

**Comment by dkm** [comment]
Yes, I meant the compiler output :)

**Comment by RabsRincon** [comment]
In that case, it's now fixed! :smile: 
Thanks for noticing it. I might add some other small tweaks now that I'm at it.

:)

**Comment by dkm** [comment]
Wow, that was quick, thanks !
