### ISSUE TITLE
ENOENT on some queries

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#827]
papertrail is showing a fair number of these: https://papertrailapp.com/groups/1243314/events?q=ENOENT

```
Feb 19 21:40:50 f8777c727a34 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-55-1hiu32v.t8nt/output.s' 
Feb 19 21:41:43 f8777c727a34 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-55-tf53r.fjkjjg/output.s' 
Feb 19 21:41:46 f8777c727a34 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-55-1wmxvbj.1x4i/output.s' 
Feb 19 21:46:52 182135c0bb51 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-63-1va18qs.zf82/output.s' 
Feb 19 22:20:15 f8777c727a34 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-55-pjox1l.5xc8/output.s' 
Feb 19 22:20:24 698ab96e72b5 unified:  error: Error during compilation Error: ENOENT: no such file or directory, stat '/tmp/compiler-explorer-compiler118120-63-1rkyafy.dsxh/output.s' 
```

From the surrounding logs it _seems_ like it's a `nasm21302` compilation causing the issue: the following line is a `POST` to compile for nasm.

**Comment by RabsRincon** [comment]
Seems like there's something wrong with the assembly stuff. All of them ENOENT for me on the live site

**Comment by partouf** [comment]
Hmm


Could it have somethings to do with that binarymode seems off on the UI?

Haven’t looked indepth

**Comment by partouf** [comment]
I can't figure it out with source+commits, I'll have to test and debug why this is happening

**Comment by partouf** [comment]
Did some digging and found out the culprit.

Because the assembler.js is in charge of all assemblers, we can't really control the output file parameters, so default parameters are used and the getGeneratedOutputfilename() function returns the actual output file.

I suppose the best solution is to adding getGeneratedOutputfilename() to the base-compiler so the stat() will resolve.
