### ISSUE TITLE
rust: empty lines shown to generate instructions

### ISSUE THREAD

**Issue by matthiaskrgr** [mattgodbolt/compiler-explorer#832]
Hi,
https://godbolt.org/g/wMYUbx

It looks like the first line is reponsible for some instructions altough it's empty which is quite weird.
I saw this happening across all opt-levels (0,1,2,3,s,z).

![godbolt_rust](https://user-images.githubusercontent.com/476013/36527946-bd8b4648-17b3-11e8-9a46-8e116e2bdfe2.png)

**Comment by mattgodbolt** [comment]
`rustc` is emitting blocks like:

```asm
  .loc 10 0 0 is_stmt 0
  mov rbx, rax
  lea rdi, [rbp - 32]
  .loc 10 9 0
  call _ZN4core3ptr13drop_in_place17h465e2c220b767e9fE
  mov rdi, rbx
  call _Unwind_Resume@PLT
  ud2
```
... the `.loc 10 0 0` indicates the instructions are on line zero of file 10. File 10 in this case is the original source.

Seems odd that it would emit these. We could probably ignore "line 0" markers to get around this, but we perhaps should mention it to some Rust folks. We don't see this on other llvm-based compilers.

**Comment by mattgodbolt** [comment]
https://godbolt.org/g/1hAvDG and search for `loc 10 0 0`, for example.

**Comment by dotdash** [comment]
It's a problem in LLVM. Same problem with C++: https://godbolt.org/g/doMWzu

**Comment by dotdash** [comment]
https://reviews.llvm.org/D43093 takes care of it

**Comment by mattgodbolt** [comment]
LLVM issue: and fixed in newer LLVMs. Closing
