### ISSUE TITLE
"make dev" mode doesn't pick up image assets

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#835]
Running `make dev` gives 404s for all image assets.

**Comment by jaredwy** [comment]
Back from holiday! This is known :) its a problem
With the directory and the way we serve assets in prod.

Will have to pre parse the pug templates to put in image assets from
webpack to solve it.

**Comment by mattgodbolt** [comment]
No worries :) low priority!
