### ISSUE TITLE
Support LLVM as a library

### ISSUE THREAD

**Issue by LebedevRI** [mattgodbolt/compiler-explorer#841]
LLVM has a lot of internal 'Adaptive Data Types'
It would be quite useful to be able to be able to include those llvm headers, and see into what code they compile to, just like with normal C++ std:: stuff.

**Comment by mattgodbolt** [comment]
So, I put this up on the beta site: https://godbolt.org/g/yRoz3B but...

llvm isn't header only (it seems); relying on some process to generate `llvm/Support/DataTypes.h` (seemingly from `llvm/Support/DataTypes.h.cmake`). This makes it trickier to install - I can't just unpack things from the tarball.

Will continue to look into this though.

**Comment by LebedevRI** [comment]
Thank you!

**Comment by LebedevRI** [comment]
Since the clang trunk is present already, is the trunk version of LLVM planned, too?

**Comment by mattgodbolt** [comment]
clang the compiler is built using a very different system. I can add support for llvm trunk separately though.

**Comment by LebedevRI** [comment]
It seems this has landed, and can be closed?

**Comment by mattgodbolt** [comment]
Yes! Thanks for reminding me!
