### ISSUE TITLE
Go 1.10 Support

### ISSUE THREAD

**Issue by vcabbage** [mattgodbolt/compiler-explorer#842]
Thank you so much for this project!

I'd like to request support for Go 1.10, which was [released recently](https://blog.golang.org/go1.10).

There have also been a couple patch releases to 1.8 and 1.9, latest of those releases are 1.8.7 and 1.9.4.

**Comment by RabsRincon** [comment]
Hi! Thanks for letting us know about this. It's not easy to track new releases of as many compilers as we have. I'll add them today, and if everything goes well, they should hit the live site later in the day :)

**Comment by RabsRincon** [comment]
Ok, so I've added the new versions. They should hit the site in a bit. Thanks again for the heads up! :)
