### ISSUE TITLE
Consider adding DJGPP cross compiler support 

### ISSUE THREAD

**Issue by zemasoft** [mattgodbolt/compiler-explorer#844]
DJGPP cross compiler is a gcc based compiler producing DOS executables. I guess it should not be a big problem to integrate it. Please see https://github.com/andrewwutw/build-djgpp for details.

**Comment by zemasoft** [comment]
Works out-of-the-box when tested locally. The only thing needed was to point the CE to the compiler.

The main portion of work would therefore have to be done on CE Image side.

**Comment by RabsRincon** [comment]
Ey @zemasoft thanks for testing locally. 
First of all, I'm sorry we dropped the ball on this issue and did not get back to you sooner. Unfortunately this got initially overshadowed by more pressing issues and then forgotten. 

We'd love to have DJGPP available on the site (If it's possible, which I'm not knowledgeable enough to confirm), and we can point whoever wants to add them in the right directions on what to edit/add in the sister repo, but I doubt we would implement this ourselves in the near future. (Again, more pressing issues ahead!)

**Comment by zemasoft** [comment]
No need to apologize. I definitely wasn't expecting any quick action. And I understand this is a minor thing.

**Regarding licensing:**

1) I haven't found any license information attached to the latest DJGPPs but since they are GCC-based (GPL) I wouldn't expect issues.
2) DJ states [here](http://www.delorie.com/users/dj/resume/): "all the software I write is GPL'd".
3) I've asked DJ himself whether he is OK with iterating DJGPP into Compiler Explorer and.... he is :-)

So I think we are good to go here.

I'll try to find some time and spirit to do this in the near future...
