### ISSUE TITLE
Support glm as a library

### ISSUE THREAD

**Issue by realazthat** [mattgodbolt/compiler-explorer#846]
https://github.com/g-truc/glm

Would be interesting to see what glm's (supposedly) optimized routines compile to in different compilers, especially in context of larger snippets.

**Comment by RabsRincon** [comment]
Hi there! Sorry we took this long to answer, it's been a rather busy week. I'm just letting you know that I've started work on this and it should be available in the site soon™️ 
:)

**Comment by RabsRincon** [comment]
I spoke too soon. It has been easier that I thought. The library should be there after the next site bounce!

**Comment by realazthat** [comment]
Thanks!
