### ISSUE TITLE
Can  you please support ia32? 

### ISSUE THREAD

**Issue by GusSand** [mattgodbolt/compiler-explorer#847]
My students are learning 32 bit assembly for our Operating systems course and having your tool to try things out would be fantastic. 

thanks for all the good work!!

**Comment by cppchedy** [comment]
Hi,
you could pass `-m32` to gcc(assuming you are using C or C++) and get 32 bit assembly output as shown [here](https://godbolt.org/g/Hz6YWy).

thank you for using CE in your class, glad we are helping!

**Comment by mattgodbolt** [comment]
We might be missing some headers, as I'm not 100% sure how that fits together. Let us know what you're having problems with, we'd be glad to help as @RabsRincon says!

**Comment by mattgodbolt** [comment]
@GusSand can you confirm whether `-m32` works for you?

**Comment by pcordes** [comment]
I use `-m32` fairly often and it works fine with most of the x86 compilers for asm source output.  Many of them are broken for binary + disassembly output, e.g. gcc7.2 binary mode with a trivial input says:

```
/opt/compiler-explorer/gcc-7.2.0/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lstdc++
/opt/compiler-explorer/gcc-7.2.0/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgcc_s
/opt/compiler-explorer/gcc-7.2.0/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../x86_64-linux-gnu/bin/ld: skipping incompatible /opt/compiler-explorer/gcc-7.2.0/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/libgcc.a when searching for -lgcc
/opt/compiler-explorer/gcc-7.2.0/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgcc

collect2: error: ld returned 1 exit status
Compiler returned: 1
```

gcc6.3 is similarly broken , and I stopped checking there.

Even more of them are broken for binary mode with `-mx32`, but IIRC most work for asm source with that option.

Please do *not* clutter the compiler list more with x86 versions of the x86-64 compilers.

**Comment by mattgodbolt** [comment]
Closing this: I think for most compilers `-m32` works now (file specific bugs for those that it doesn't that you need), and we have a separate `C` language now to even get around the `-x c`.

**Comment by mattgodbolt** [comment]
@pcordes actually I will file for GCCs 6 and 7 as they're contemporary enough I think
