### ISSUE TITLE
Security Bug: possibility to read server files

### ISSUE THREAD

**Issue by cedriczirtacic** [mattgodbolt/compiler-explorer#854]
Tested on: **https://godbolt.org**

**Comment by jaredwy** [comment]
Howdy.
Thanks so much for the report! 

I edited your bug, just to remove the details from the public while we look into a solution.

**Comment by cedriczirtacic** [comment]
Also, might want to disable unneeded cc.py arguments (eg. --report or --text-report) as they can create files outside **/compiler-explorer** (eg.: /tmp)

**Comment by RabsRincon** [comment]
We have now pushed a fix for the server, but will wait a week to post the original report. Thanks @cedriczirtacic for letting us know :)

**Comment by cedriczirtacic** [comment]
Found another one. This one lets you read the whole file. Any email I could use to send the info?

**Comment by RabsRincon** [comment]
Sure! I've emailed you. Thanks for taking the time to improve CE :)

**Comment by cedriczirtacic** [comment]
Issue sent. Thanks!

**Comment by mattgodbolt** [comment]
Just to reiterate @rabsrincon here: thanks for taking the time to report this issue (and the others).

We're working on a new isolation technique for both compilation and execution. When that's in place we'd very much appreciate your help in trying to find weaknesses too!

**Comment by SoniEx2** [comment]
Oh yes I can read /etc/passwd ok. Where do I submit this?

**Comment by mattgodbolt** [comment]
Hi @SoniEx2 - you can read `/etc/passwd` by design (as the compiler itself has to be able to read it to get some basic user facts). There's nothing particularly sensitive about the `/etc/passwd` you're looking at: it's not the password file of the node you're running on (it's a docker instance inside of the node).

If you're able to read a sensitive file (`/etc/shadow` or something like that), I'd love to find out how. You can always email us at compiler-explorer-admin@googlegroups.com or directly matt@godbolt.org

**Comment by SoniEx2** [comment]
Well, if I can read /etc/passwd, what's to say I can't read /tmp files i.e. other ppl's code?

**Comment by mattgodbolt** [comment]
That's a really good point - thanks!

At the moment the only thing stopping you doing that is being able to guess the randomly-named temporary directory where code is held while it's compiled. That's not impossible of course: I'm not using a cryptographically secure RNG. It's not an attack vector I'm too worried about right now, however.

With the isolation technique I'm planning on using soon (e.g. `firejail` or similar) I hope to isolate even that - so there's no way to read anything other than the temporary directory your particular compile is in.

**Comment by SoniEx2** [comment]
All you really need is a whole botnet.

**Comment by mattgodbolt** [comment]
If someone unleashes a botnet on Compiler Explorer, information leakage is only one of the problems I'd face. The temporary filenames are of the form `/tmp/compiler-explorer-compiler118213-29772-18k4o60.sz18msfw29` so there's quite a search space. The files only exist during compilation, and there's multiple CE nodes running (with separate `/tmp` directories). It's definitely possible, but pretty unlikely. My instinct is a botnet would crush the ability to compile well before you got lucky and found another user's in-progress compilation.
