### ISSUE TITLE
Support font size on the output window

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#858]
We should probably use a Monaco editor for the output window anyway...

Requested at embo: https://twitter.com/janwilmans/status/972115489605541889

**Comment by RabsRincon** [comment]
Why do you think we should switch the output to be a Monaco editor?

**Comment by RabsRincon** [comment]
Closed by d20e6be

**Comment by RabsRincon** [comment]
Available now on the site
