### ISSUE TITLE
Support of cursorline/textbox/bold highlighting of current assembly instructions

### ISSUE THREAD

**Issue by SiteshSahoo** [mattgodbolt/compiler-explorer#859]
Hi,

It would be nice if the corresponding asm instructions of the code (under mouse/curosr) can be highlighted with a "cursorline" or a "text box" or by "making the font bold".

I am aware of the colored distinction, but this suggestion would make browsing/code walkthrough more intuitive as it[the highlight] will follow the current code in real time in asm window.

Please ignore if something similar is already in your backlog.

Thanks in adv!

**Comment by mattgodbolt** [comment]
We already highlight that under the mouse...but obviously it's not that clear. We can improve this for sure! Thanks :)

**Comment by Noviv** [comment]
@RabsRincon I don't see highlighting under the mouse on the live site, should I take a swing at this? If I'm understanding the issue correctly, the goal here is simply to make the hovered ASM command bold (or distinguish it some other way).
