### ISSUE TITLE
Intel compiler in C mode?

### ISSUE THREAD

**Issue by rainwoodman** [mattgodbolt/compiler-explorer#862]
Currently the Intel compilers are only available in C++ mode. Would be nice if there is also one in C mode. 
Are there any differences between these modes?

Thanks! 

cc @sbird

**Comment by mattgodbolt** [comment]
Good point! To get some idea you can pass `-x c` to the compiler in C++ mode to see it build C code, though we should really add `icc` to the C compiler list too.

**Comment by RabsRincon** [comment]
Hi! I've added ICC to C. It should reach the live site later today. Let us know if you find any problems using them :)

**Comment by rainwoodman** [comment]
Thanks for the update. But I don't think it is live on the site yet. Perhaps I shall wait a bit longer?

**Comment by RabsRincon** [comment]
Yes, we have not updated the live site yet. It will happen either later today or early tomorrow tho :)

**Comment by RabsRincon** [comment]
The site has been updated with this change. Sorry for the delay!

**Comment by rainwoodman** [comment]
Thanks you!
