### ISSUE TITLE
Source comments on #include line cause error in C++ mode

### ISSUE THREAD

**Issue by OldWolf2** [mattgodbolt/compiler-explorer#874]
In C++ (x86-64 gcc 7.2), the following program:

    #include <cmath>       // std::(sin, cos, atan, ..., log)

gives an error: 

    <stdin>:1:1: no absolute or relative includes please

I suppose it is attempting to prevent `#include <../foo>` but used a naive parsing.

**Comment by mattgodbolt** [comment]
Doops yes, very naive parsing, and more to put people off than the real protection (which is more in depth than a bit of text parsing!)
