### ISSUE TITLE
Binary output doesn't respect chosen font size

### ISSUE THREAD

**Issue by MulleDK19** [mattgodbolt/compiler-explorer#885]
The binary output is tiny no matter which font size I choose.

![image](https://user-images.githubusercontent.com/3169809/37933787-96ad10b2-314c-11e8-8495-3c704da23581.png)

**Comment by RabsRincon** [comment]
Hi! This was a known problem in which we had to wait for the Monaco editor devs to fix it for us, but I've found a way to force a better behaviour.
Note that this relies on internal API and might stop working at some point, but this seems to be the only solution available. 
I'm so sorry this took so long to get sorted :)

**Comment by MulleDK19** [comment]
@RabsRincon Cool, thanks. Any idea when this'll be live on godbolt.org?

**Comment by RabsRincon** [comment]
It should behave correctly now. :D
