### ISSUE TITLE
CFG view incomplete for LDC

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#887]
For this code:
```d
int foo(int i) {
    if (i) {
        return 1;
    }
    return 0;
}
```

The CFG view shows an incorrect/incomplete graph for `foo`. 
https://godbolt.org/g/Q2bCvN

Looking at the assembly output and comparing it with Clang, perhaps the problem is caused by two `ret` instructions in the D output?

**Comment by RabsRincon** [comment]
Hi Johan! What are you seeing?
I'm getting...
![image](https://user-images.githubusercontent.com/5364255/38058325-b7eaa522-32e2-11e8-8b83-33ce9d9c036c.png)
which is indeed missing a link, but do you refer to anything else?

**Comment by JohanEngelen** [comment]
exactly what I meant. (cool that you can embed images here)

**Comment by mattgodbolt** [comment]
Seems the CFG view relies on there being a label at every basic block, which isn't the case here. I imagine we could find C++ examples that generate similar code (though I just had a go and it's not as straightforward as I thought).

**Comment by JohanEngelen** [comment]
> Seems the CFG view relies on there being a label at every basic block

What exactly do you mean? The C++ also doesn't have a label for the fallthrough after the conditional jump, right?

Example with two almost identical pieces of code C++ and D:

https://godbolt.org/g/Yru92F

In the D asm, there is a label for the unlinked basicblock. Is it that the numbering is off?
I'll need to have a look at the Asm->CFG parser/generator code.

**Comment by mattgodbolt** [comment]
@JohanEngelen you're absolutely right! I'm talking rubbish here :blush: Thanks for noticing and calling me on this...

I'll defer to @cppchedy for his comments on what the problem might be!!

**Comment by JohanEngelen** [comment]
@partouf Can you reopen this bug? It is not fixed by your recent change: there is still an arrow missing from the starting basicblock to the "fall-through" basic block after the `je .LBB0_2`.

**Comment by karliss** [comment]
Here is one more test case not fixed by changes above, might be the same as what @JohanEngelen refers to. https://godbolt.org/z/ywm0vP

**Comment by partouf** [comment]
> Here is one more test case not fixed by changes above, might be the same as what @JohanEngelen refers to. https://godbolt.org/z/ywm0vP

The arrow was behind and obscured by the rest in this case https://godbolt.org/z/GJgfzn

I think the original problem was fixed as well, but I closed the issue before the change went live

**Comment by karliss** [comment]
Adding trim to `removeComments` in cfg.js helps.

**Comment by karliss** [comment]
Can this be closed now?
