### ISSUE TITLE
Wording Suggestion

### ISSUE THREAD

**Issue by adah1972** [mattgodbolt/compiler-explorer#888]
The following sentence in README is a bit confusing:

> If you want to point it at your own GCC or similar binaries, either edit the `etc/config/compiler-explorer.defaults.properties` or else make a new one with the name `compiler-explorer.local.properties`.

It is especially so because the file `etc/config/compiler-explorer.defaults.properties` exists, but contains no compiler-specific information. Only after looking around for a while did I realize that it was files like `etc/config/c.defaults.properties` that I should check. So I think it might be better to say:

> If you want to point it at your own GCC or similar binaries, either edit _etc/config/**language**.defaults.properties_ or else make a new one with the name _**language**.local.properties_.

**Comment by RabsRincon** [comment]
Hi! Thanks for the heads up. You are 100% right, the wording was a bit confusing. That's now fixed.

:)
