### ISSUE TITLE
Add Vc library

### ISSUE THREAD

**Issue by hassec** [mattgodbolt/compiler-explorer#893]
I was wondering if an addition of the [Vc library (1.3.3)](https://github.com/VcDevel/Vc/releases) would be possible?    
It would be nice to be able to compare it directly with xsimd for example.

**Comment by RabsRincon** [comment]
Hi! Sorry this is taking so long! We are all a bit busy lately.
As far as I can see, it needs to go thru an installation process with CMake which might make the whole thing a bit more tedious to set up, but it should not take too long (I think there are already some libs being installed with CMake)
If noone gives this a shot, I'll try to do it early next week (But no promises!)

**Comment by hassec** [comment]
Closing this as VC can simply be included as github link as shown in their compiler explorer examples.
