### ISSUE TITLE
Rust: add more targets

### ISSUE THREAD

**Issue by gnzlbg** [mattgodbolt/compiler-explorer#898]
Adding new targets should be a `rustup target add ${TARGET_NAME}` away. It would be cool if the following targets could be added:

* i586-unknown-linux-gnu
* i686-unknown-linux-gnu
* aarch64-unknown-linux-gnu
* armv7-unknown-linux-gnueabihf
* powerpc-unknown-linux-gnu
* powerpcle-unknown-linux-gnu
* powerpc64-unknown-linux-gnu
* powerpc64le-unknown-linux-gnu
* mips-unknown-linux-gnu
* mipsle-unknown-linux-gnu
* mips64-unknown-linux-gnuabi64
* mips64el-unknown-linux-gnuabi64

Rust is a great cross-compilation toolchain on linux, one just needs to pass it `--target=${TARGET_NAME}` and voila, everything just works. 

I wanted to fill in a couple of code-generation bugs in LLVM for aarch64 and armv7 and was kind of blocked by this.

**Comment by RabsRincon** [comment]
As discussed on Slack, we don't use rustup for the installation process as we need to control where things end up.
But! @jaredwy mentioned the existence of `RUSTUP_HOME` which seems like something we would need to take a look at.
If anyone feels up to the task to try if it would work, we would be happy to support and help where needed 
:)

**Comment by gnzlbg** [comment]
Following up on the slack conversation:

@mattgodbolt 

> We need to be able to install rustc in a well known location, in this case on a network drive

So you can use `RUSTUP_HOME` and `CARGO_HOME` to set the directories in which you want to install things. One has to set these before doing `rustup init` for the first time.

By default, `rustup` uses `~/.rustup` and the directory structure looks like this:

* `~/.rustup` (or `RUSTUP_HOME`): rustup only puts stuff in here
  * `downloads/`: artifacts are downloaded here
  * `tmp/`: rustup's directory for temporary operations, only non-empty while initializing and updating rustup IIRC
  * `toolcains/`: all toolchains are installed here, the name follows a schema `toolchain-triple`, on my machine for example I have:
    * `nightly-x86_64-apple-darwin`:
        * `lib/rustlib/`: cross-compilation components, on my machine I have:
                * aarch64-unknown-linux-gnu
                * armv7-unknown-linux-gnueabihf
                * powerpc64-unknown-linux-gnu
                * x86_64-unknown-linux-gnu
    * `stable-x86_64-apple-darwin`: ...

There are a couple of things to note. First, `stable`, `nightly`, `stable-1.14.0-`,... those are the different toolchains. The cross-compilation targets are part of each toolchain, so I can use a nightly or a stable toolchain to cross-compile to powerpc64-unknown-linux-gnu for example.

Typically, one uses `rustup default toolchain` to switch toolchains, but because godbolt has multiple  windows open potentially with multiple toolchains compiling the same snippet, I wouldn't use rustup for that. What can be done is "scan" the toolchain directory for all toolchains, and just list those. When the user selects one, then just use the `rustc` of that particular toolchain, which knows where its standard library and cross-compilation components are.

**Comment by mattgodbolt** [comment]
Thanks @gnzlbg ! Looks like @mjbshaw might be able to take a look.

**Comment by mjbshaw** [comment]
I'm (literally) currently looking at adding pretty much all available targets. I'll update this issue in the next ~36 hours with some additional details.

**Comment by gnzlbg** [comment]
#94 is not a PR, it is an issue.

Allowing specifying `--target=$TARGET` to `rustc` doesn't help if the `$TARGET` has not been installed. 

The correct fix for this issue is probably to just use `rustup target add all` to install all available cross-compilation targets for a particular toolchain, instead of hardcoding lists of these manually everywhere and keeping them up-to-date, which is an error prone process that would require constant maintenance.

**Comment by mjbshaw** [comment]
@gnzlbg Sorry, it's 94 in another repo: mattgodbolt/compiler-explorer-image#94

As I mentioned above, I would have liked to use `rustup` but the compiler explorer uses/assumes a different directory structure than what `rustup` uses. Using it would have required deeper and more invasive changes to the compiler explorer.
