### ISSUE TITLE
Diff view

### ISSUE THREAD

**Issue by lhayhurst** [mattgodbolt/compiler-explorer#9]
When I 
- change the compiler options, or 
- change my code in the editor pane 

show me the assembly diffs from the previous run.  (Or have history of runs upon which I can generate diffs.)

**Comment by Olsonist** [comment]
It would be helpful to have output assembly or IR diffs between two compiler versions.

It would be helpful to have source code diffs between source files of two compiler versions.

**Comment by mattgodbolt** [comment]
This is actually in progress now thanks to @Voxelf - I'm now in the last stages of merging his patch into the new UI.

**Comment by mattgodbolt** [comment]
New UI available in beta...

**Comment by mattgodbolt** [comment]
[e.g. https://godbolt.org/g/bgRAHX ]

**Comment by mattgodbolt** [comment]
Pretty happy with the feature. Some finess required, tracking in #268 and #269.

**Comment by Olsonist** [comment]
I saw this Intel article from 2011 on Branch Prediction, static and
dynamic. It mentions prefixes which was a Pentium 4 thing. I thought you
might be interested.

https://software.intel.com/en-us/articles/branch-and-loop-reorganization-to-prevent-mispredicts


Myself, I'm trying to figure out indirect branches. The Intel Optimization
Reference Manual says:

*Assembly/Compiler Coding Rule 14. (M impact, L generality) When indirect
branches are present, try to put the most likely target of an indirect
branch immediately following the indirect branch. Alternatively, if
indirect branches are common but they cannot be predicted by branch
prediction hardware, then follow the indirect branch with a UD2
instruction, which will stop the processor from decoding down the
fall-through path*


I'm looking at appending UD2 after *jmp reg *instructions. It's not clear
to me what Intel is saying and whether this will help on a second jmp after
the instruction is in the ustore.

thanks,

Chris

**Comment by mattgodbolt** [comment]
Hi @Olsonist  - I appreciate your message: did you mean to post it here? I don't believe it's related to this bug?

If you meant it as a personal email -- thank you! I always appreciate interesting article. I'd be happy to opine on this more if you email me directly so we don't spam all the folks watching the Compiler Explorer project!

**Comment by nwu-ableton** [comment]
In case someone stumbles on this issue while googling for "godbolt diff view", and is wondering how to enable it - there's an "Add..." button on the top left of the page.
