### ISSUE TITLE
Go jump target output is confusing/wrong

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#901]
Consider: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,lang:go,source:'//+Type+your+code+here,+or+load+an+example.%0A//+Your+function+name+should+start+with+a+capital+letter.%0Apackage+io%0A%0Afunc+Fun()+%7B%0A%09for+i+:%3D+0%3B+i+%3C+10%3B+i%2B%2B+%7B%0A%0A++++%7D%0A%7D%0A%0A'),l:'5',n:'0',o:'Go+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gl1100,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',trim:'0'),lang:go,libs:!(),options:'',source:1),l:'5',n:'0',o:'x86+gc+1.10+(Editor+%231,+Compiler+%231)+Go',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4 

The jump targets (`jmp 7`, `jlt 4`) don't seem to refer to anywhere in the file. Also the execution seems to fall off the end of the function. Seems the asm filterer is confused.

**Comment by mattgodbolt** [comment]
From the `go` tool directly:

```
go tool compile -S test.go
"".Fun STEXT nosplit size=14 args=0x0 locals=0x0
	0x0000 00000 (test.go:3)	TEXT	"".Fun(SB), NOSPLIT, $0-0
	0x0000 00000 (test.go:3)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (test.go:3)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (test.go:3)	XORL	AX, AX
	0x0002 00002 (test.go:4)	JMP	7
	0x0004 00004 (test.go:4)	INCQ	AX
	0x0007 00007 (test.go:4)	CMPQ	AX, $10
	0x000b 00011 (test.go:4)	JLT	4
	0x000d 00013 (<unknown line number>)	RET
	0x0000 31 c0 eb 03 48 ff c0 48 83 f8 0a 7c f7 c3        1...H..H...|..
go.info."".Fun SDWARFINFO size=32
	0x0000 02 22 22 2e 46 75 6e 00 00 00 00 00 00 00 00 00  ."".Fun.........
	0x0010 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01 00  ................
	rel 8+8 t=1 "".Fun+0
	rel 16+8 t=1 "".Fun+14
	rel 26+4 t=29 gofile../workspace/go/src/gopractice/io/test.go+0
go.range."".Fun SDWARFRANGE size=0
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
```

Seems we need to treat each line as a label, and handle the `ret` with no file and line associated with it.

**Comment by partouf** [comment]
Do you mean we should be creating labels when these kinds of jumps are being used? How would we name them?

**Comment by mattgodbolt** [comment]
I think if we treated each address as a label with the bane being just "4" or whatever then the find used labels code might just work

**Comment by mattgodbolt** [comment]
We might have to rewrite then as addr4 etc I guess (and the jumps too to be JLT addr4). I'm thinking out loud here

**Comment by partouf** [comment]
the direct jumps are now rewritten to labels by #1194 and thus completes the fix
