### ISSUE TITLE
Gcc Dump seems to get in the way when compiler crashes

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#913]
When using CE for gcc dev, I often hit gcc crashes (...) and need to track how IR is transformed along the different passes to find the problem. But CE has the following behavior:

- gcc dump disabled: I get a nice crash log in the compiler output (good)
- if i enable gcc dump to start digging the problem, I get:
  - `<Remote compilation failed: undefined>` in the assembly output pane
  - `Compiler returned: -1` in the compiler output pane
  - `<No output, this view is only supported on GCC compilers>` in the gcc dump pane

I guess the error handling is broken by gcc dump. I know I should be the one investigating as it's probably my own bug, but I also know that I won't have time for this in the near future, so I at least log the issue here...

**Comment by RabsRincon** [comment]
Don't worry about not having time to investigate it, I'll take a look at it this evening. You're right in that it's probably a bug somehwere. I'll get back to you as soon as I find anything :)

**Comment by dkm** [comment]
Thanks !

**Comment by RabsRincon** [comment]
I've tried some ICE reports from the gcc bugzilla but I've only been able to reproduce the 3rd bullet point. Can you give me an example where the other 2 points happen? Thanks!

**Comment by dkm** [comment]
It's a bit hard as I'm working on an internal version of gcc. I'll try to see how to reproduce using a more normal setup !

**Comment by mattgodbolt** [comment]
@RabsRincon you could try pointing CE at a bash script that shells out to gcc...unless there's `--crash` on in its arguments, then it just `kill -SEGV`'s itself? Then you can test?

**Comment by RabsRincon** [comment]
Disregarding the fact that a0b34e4 completely broke the pane, feel free to give it a try now @dkm. let me know if it's still broken

**Comment by dkm** [comment]
@RabsRincon ok, sure, I'll try that on monday !

**Comment by dkm** [comment]
Sorry for the delay, I've been busy debugging other things. Now, back to this issue, after rebasing my local change and cleaning everything, I can confirm that I can't reproduce the original behavior.
Now, the compiler crashes, I can get the nice stack trace and GCC dump still reports empty results.

The problem now is that even when having an ICE, we should still be able to get some dump files (up until the crash). I'll try to see why that's not the case.

**Comment by dkm** [comment]
Ok, I think I found an easy way to fix the last issue addressed here (see associated PR)

**Comment by RabsRincon** [comment]
Thanks for reporting, confirming and improving this. 
As always, we do really appreciate it :)

**Comment by dkm** [comment]
Wow, that was quick :+1: You were quicker than me eating for adding the comment, thanks !
