### ISSUE TITLE
Wrong lines coloring in the dissasembly view for clang 6

### ISSUE THREAD

**Issue by lberserq** [mattgodbolt/compiler-explorer#916]
Steps to reproduce:
https://godbolt.org/g/YHVKwA
See screenshot in the attachments
Actual result:
 The first include line is highlighted with red
Expected result:
It shouldn't be highlighted

![image](https://user-images.githubusercontent.com/5302672/39673200-87a26e46-5140-11e8-82b3-f52df077d5a8.png)

**Comment by RabsRincon** [comment]
Hi!
After some looking around, I've found that clang does indeed mark line 0 as the source of that line of assembly.
I've improved how we handle cases like this one, so assembly is at least not wrongly attributed to an unreleated line in cases like this.

Thanks for taking the time to report this :)

(P.S: I see you're using a dark theme on your browser, you might want to check out our dark theme. You can change it on `Settings > Theme: Dark`)
