### ISSUE TITLE
GCC 8.1 missing for C

### ISSUE THREAD

**Issue by ojeda** [mattgodbolt/compiler-explorer#917]
GCC 8.1 is available for C++ and Assembly; however, it is missing for C.

**Comment by RabsRincon** [comment]
Hi! Thanks for reporting this! It's true that we're missing GCC 8.1 due to a typo in our config. I'll fix it right now

:)

**Comment by ojeda** [comment]
Confirmed, it is there. Astonishingly quick resolution, thanks a lot! :)
