### ISSUE TITLE
Defaulting libs in c++ properties

### ISSUE THREAD

**Issue by Wentzell** [mattgodbolt/compiler-explorer#918]
Is there any way to enable a library by default in the c++ properties files?

**Comment by RabsRincon** [comment]
Hi @Wentzell! Up until now, there was no way to do what you asked, but I saw no reason not to have it, so here it is!
On the properties file, create a key named `defaultLibs`.
It expects a 0 or more elements with a structure of `libKey.libVersion` You can add more than 1 by separating the pairs with `:`

An example is probably easier:

`defaultLibs=boost.167:abseil.trunk:fmt.410`
Note that it's _undefined :tm:_ to repeat a libKey more than once and that the site won't complain if you specify a bad lib/version pair.

I hope you find it useful :)
