### ISSUE TITLE
Can't use llvm libraries with -fsanitize=address because they try to include <sanitizer/asan_interface.h>

### ISSUE THREAD

**Issue by filcab** [mattgodbolt/compiler-explorer#920]
It's what it says on the tin. If you're compiling llvm, maybe we're missing compiler-rt header installation?

Example: https://godbolt.org/g/PU4ZqH

**Comment by mattgodbolt** [comment]
Is this specific to the llvm library? It looks like it should be shipped as part of the compiler itself. https://godbolt.org/g/yFveRK (perhaps that's what you're saying here, but we don't need to involve the LLVM library to see the problem :))

Looks like we need to add `compiler-rt` like you say to our build scripts: https://github.com/mattgodbolt/compiler-explorer-image/blob/master/clang/build/build.sh

**Comment by filcab** [comment]
I singled-out llvm libraries because they will include it when being compiled with ASan enabled. But yes: In a clang installation with sanitizers, the compiler-rt headers should be installed and available. Adding compiler-rt to your script should work.

**Comment by mattgodbolt** [comment]
Got it! Thanks @filcab -- will get on it! At first it'll just be clang-trunk that gets this, it'll take a while to backfill the older clangs

**Comment by mattgodbolt** [comment]
`clang-trunk` now has this, the example linked above now works. Yay. Will backfill 5.0.0 and 6.0.0

**Comment by mattgodbolt** [comment]
Have now backfilled 5.0.0 and 6.0.0 too. Closing; feel free to suggest more compilers to backfill. 5.0.0 doesn't seem to build llvm as it is, but at least it has the sanitizer headers :)

**Comment by filcab** [comment]
Cool, thanks a lot!
