### ISSUE TITLE
Chain output of compiler into llvm-mca etc

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#925]
https://twitter.com/zeuxcg/status/995044763014320128?s=19

**Comment by RabsRincon** [comment]
I've been meaning to do this for a while! I just need to find some free time for it first.
I do wonder if creating a "tools" (or similar) submenu in the "Add new..." dropdown would work, both functionally and visually. I do feel that if we keep adding items to that dropdown, will bloat it quite fast

**Comment by mattgodbolt** [comment]
I'm thinking a tool is better "add new..." as a dropdown from, the compiler output as you describe. I'm not too worried too much about the bloat: having a "tools" option and then in the tool window having the pick of IACA/llvm-mca etc works for me.

**Comment by LebedevRI** [comment]
It would also be able to chain "compiler" invocations, like https://godbolt.org/g/9zMbm8
I.e. we first run `opt` on the source, and then run `llc` on the `opt` output.
I'm not sure if it can be done already in LLVM, but it seems pretty straight-forward regardless...

**Comment by Trass3r** [comment]
Looks like this is up and running now.
The only problem is it happily pipes complete or even several functions into mca while the tool expects something like a single loop iteration and implicitly creates a loop around it.

**Comment by zeux** [comment]
Thank you! Even with the single-function restriction, this is so much nicer than copying assembly around multiple godbolt windows.

**Comment by partouf** [comment]
As described in the documentation, you can put markers around sections of code to isolate the analysis
https://www.llvm.org/docs/CommandGuide/llvm-mca.html#using-markers-to-analyze-specific-code-blocks
