### ISSUE TITLE
add new language?

### ISSUE THREAD

**Issue by yuanshuoastro** [mattgodbolt/compiler-explorer#929]
Dear all,
How to add new language?
What about add Fortran90 into the explorer?
There are gfortran (GCC) and ifort (Intel) being Fortran compilers.

Thank you.

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to add new features to CE, we really appreciate it.

Adding a new language is currently not too well documented (We should improve that)

Basically, you want to first define the new language  in `libs/languajes.js`. Next, add a file under `etc` called `{LANGID}.default.properties` where `{LANGID}` is the language id you defined in the `libs/languajes.js` file.

You can take a look at C++ default file, that should give you an idea on what to add there. 
To add a compiler, you can follow `docs/AddingACompiler.md` which explains the process. 

Feel free to ask any doubt you have, should any come up in the process of adding the new language.

Thanks again for your time :)

**Comment by partouf** [comment]
Hi, Fortran is now added as a separate language thanks to @dbroemmel 's efforts! let us know if you have any trouble with it
