### ISSUE TITLE
[clang] `--target=thumbv7-eabi` doesn't compile

### ISSUE THREAD

**Issue by vesim987** [mattgodbolt/compiler-explorer#934]
Hi, passing `--target=thumbv7-eabi` to clang(all versions) compiler options cause that error:
```
clang-6.0: warning: argument unused during compilation: '--gcc-toolchain=/opt/compiler-explorer/gcc-7.2.0' [-Wunused-command-line-argument]
clang-6.0: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang-6.0: error: ld.lld command failed with exit code 1 (use -v to see invocation)
Compiler returned: 1```

**Comment by rehwinkel** [comment]
On Ubuntu I solved this issue by running ```sudo apt install lld-8```.

**Comment by mattgodbolt** [comment]
@vesim987 we don't support linking, but if you disable the link (untick the `11010` button) it should work. @rehwinkel we don't use `apt` to manage linkers etc, everything is built from source. We'd need to work out how to get `ld.lld` built: the `ld` in the `gcc toolchain` isn't being used as it's not the right architecture. We don't have `binutils` built for all the various architectures.
