### ISSUE TITLE
Get a link for compile job using API

### ISSUE THREAD

**Issue by dkm** [mattgodbolt/compiler-explorer#938]
For automating some task, I wanted to write a script that parsed GCC's testsuite log files and create a brief report, including links to our internal CE instance.

Having the link as a field of the result object would be the easier way to handle it, but the compilation job can be seen as useless/waste of CPU in this case.

I tried to have a quick look but could not find a way to quick-patch this. I'll definitely do this one day as this pops regularly... But maybe someone else can provide a patch quicker :)

**Comment by mattgodbolt** [comment]
We've wanted a way to do this for a while. The URL format is complex and not user friendly; but having a simple "just make a link with one compiler and one editor" would be handy: either as an alternative link format, or as an API call one POSTs to to get a URL.

The latter is possibly better, as it opens the door to short URLs. Though that then asks the question of where all the short URLs end up being stored (and for how long). At my previous employer we had the notion of "short-lived" short URLs that were cleaned up after a few days. Though that might be unnecessarily complex.

See also #581 which would benefit from this.

Perhaps the first solution is best. In fact, the URL format isn't that egregious: both @lefticus, @cor3ntin and I have made scripts to generate URLs. It's not all that awesome but take a look at: https://github.com/mattgodbolt/cppnow-talk/blob/master/compiler-explorer.js#L32 onward which makes a URL to a local instance. (I used it in a presentation, auto-making CE links to all the code present).

**Comment by dkm** [comment]
Ok, I'll have a look at your links and see what I can make to fit our setup. I was also thinking of linking our bts (phabricator) to CE so that bug reports can have automatic links to CE when some fields are filled. That would be great :D

**Comment by mattgodbolt** [comment]
Let us know how you get on @dkm -- it may be that we supply a JS library to make URLs that we can serve up, I guess. Or else a well-documented URL format, instead of what we currently have.

**Comment by dkm** [comment]
I'll try to test some options today if possible. If I do anything, I'll update this issue !

**Comment by dkm** [comment]
@mattgodbolt thanks for the pointer. I've been able to really quickly create links form a source file. I'll probably need to have better interaction with CE to make it more user proof (eg. get list of compilers).
But for the moment, it will be enough.

I've also looked into adding a phabricator url shortener backend, but I'm really not fluent enough in nodejs/js to really understand what I'm doing: making the first POST is easy, but I'm not sure about the best way to make the 2nd one (I end up having some spaghetti callbacks code).

I'll stick to the simple cli url creator for now:
https://gist.github.com/dkm/8e5b7e35c5bec88991c040c238c12e9b

**Comment by dkm** [comment]
Looks like someone is doing a nice job for a cli interface for CE. I guess I should see how to contribute there instead of redoing the same thing on my own:
 https://github.com/ethanhs/cce#cce---command-line-compiler-explorer https://www.reddit.com/comments/8oksc8

**Comment by mattgodbolt** [comment]
The CLI interface actually compiles: it doesn't get URLs to viewable documents. I imagine collaborating with @ethanhs to add support for generating viewable links would be a great idea though!

**Comment by dkm** [comment]
That's what I had in mind :)

**Comment by ethanhs** [comment]
PRs welcome :)

**Comment by dkm** [comment]
Sure, will try something tomorrow 😃

**Comment by mattgodbolt** [comment]
Any word on this?

**Comment by partouf** [comment]
Considering there has been added a simpler API for this; https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/API.md#post-shortener---saves-given-state-forever-to-a-shortlink-and-returns-the-unique-id-for-the-link

I think we can close this issue.
