### ISSUE TITLE
Add clang-tidy 

### ISSUE THREAD

**Issue by andjo403** [mattgodbolt/compiler-explorer#939]
Do not know it this is a good idea but maybe it is possible to add clang-tidy as a "compiler" for c++ to be able to see usage of new tidy checks and make it easy to write tickets for fault in clang-tidy.
but maybe it is strange to have lint like tools that only generate warnings in compiler explorer

**Comment by RabsRincon** [comment]
What we can do is to add it to the new "Tools" language that was added when we added llvm-mca. I don't know what others might think, but I find that this is a good idea.
Thanks for sharing it with us!

:)

**Comment by mattgodbolt** [comment]
https://twitter.com/twmatrim/status/1053946542888046592?s=19 also requests. Maybe it could be added as a compiler in its own right: or maybe as a subwindow like "execution" may end up being

**Comment by partouf** [comment]
oh I didn't see this issue before, 
hi @andjo403 this is now in CE under the Compiler's window Add Tool button!
