### ISSUE TITLE
Issue with the compiler-wrapper and Clang

### ISSUE THREAD

**Issue by AaronBallman** [mattgodbolt/compiler-explorer#944]
I am getting a core dump when trying to run Clang trunk. Other versions of Clang seem to be working.

https://godbolt.org/g/TRnJ9V

/compiler-explorer/c-preload/compiler-wrapper: line 21: 26388 Segmentation fault      (core dumped) "$@"

Compiler returned: 139

**Comment by mattgodbolt** [comment]
Investigating right now, thanks.

**Comment by mattgodbolt** [comment]
Something in llvm has changed and it doesn't like being [upx](https://upx.github.io/) packed any more. This affected both rust trunk and clang trunk.

I'm hastily rebuilding clang compilers without `upx`-ing them.

**Comment by mattgodbolt** [comment]
Building is taking an extraordinarily long time...well, it's stuck at `Installing...` - hopefully it'll finish up soon...

**Comment by mattgodbolt** [comment]
It was the `xz` to tar up the clangs that was taking so long... the `.tar.xz` is now 394 GB (!!!)

**Comment by mattgodbolt** [comment]
Slight improvement, now a `glibc` version issue. Continuing to work on this...

**Comment by mattgodbolt** [comment]
`glibc` woes fixed. Testing and works in beta, now restarting prod, ETA 10 minutes or so.

Thanks all for your patience...

**Comment by mattgodbolt** [comment]
And it should be fixed!

**Comment by AaronBallman** [comment]
Thank you, Matt, you're a wizard! Verified that it's working again for me as well.
