### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by DesWurstes** [mattgodbolt/compiler-explorer#954]
```
g++: internal compiler error: Segmentation fault signal terminated program as
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

Compiler returned: 4

https://godbolt.org/g/4Sw7ij

**Comment by mattgodbolt** [comment]
Seems this is a problem with the binary output of the latest compiler. Can someone try again tomorrow and see if it was a momentary issue with the trunk compiler, or indeed see if it's a problem with other GCC versions in binary output?

If it's just trunk GCC we need to see if it's a build issue with GCC (or objdump), else it might be a GCC bug itself.

**Comment by DesWurstes** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86150

**Comment by amonakov** [comment]
This is the *assembler* segfaulting; assembly from gcc-trunk is not different from gcc-8.

According to the log, the assembler is invoked via
```
/opt/compiler-explorer/gcc-trunk-20180611/x86_64-linux-gnu/bin/as
```

It looks like it's somehow broken.

**Comment by mattgodbolt** [comment]
We do try to crunch the executables with a compression tool which has started causing problems with LLVM. Maybe it's upsetting `as` too

**Comment by amonakov** [comment]
If the goal is to save space, may I suggest using compressed filesystems instead of self-unpacking executables? It should be both more efficient and more robust.

E.g. if workers can mount `squashfs` filesystems, it may be as simple as preparing a squashfs image for `gcc-trunk-YYYYMMDD` subtree, distributing and mounting it in the worker.

**Comment by mattgodbolt** [comment]
Thanks, but the goal is to reduce network bandwidth and storage. All the compilers are held on an NFS server shared amongst all the computer nodes. Even with compression that's about 90GB of compilers. I'd love to move to a model where each compiler node has its own local filesystem, but the unpacking of that much data, and / or synching that data at node startup is prohibitive. At least I think it is!  A solution would solve the bug that we have that says "compilation timeout" (am on cell phone so can't look it up right now).

**Comment by amonakov** [comment]
In that case I think you can share a file holding a squashfs image over NFS, and mount that file/image on each node.

**Comment by mattgodbolt** [comment]
Thanks: we'll have to take a look at that. Might require some retooling on our side, and still may not solve the issue I mentioned (I found it now : #730 ), but thanks for the pointer!

**Comment by mattgodbolt** [comment]
Back to the original issue:

```
ubuntu@admin-node ~> /opt/compiler-explorer/gcc-trunk-20180611/x86_64-linux-gnu/bin/as
fish: '/opt/compiler-explorer/gcc-trun…' terminated by signal SIGSEGV (Address boundary error)
```

Definitely looks like a bad build/`upx` compressed executable. Via gdb it looks like it's crashing super early in the loader.

I just decompressed it, and it's now running OK. I think I'll remove `upx` from all the compiler builds going forward.

**Comment by mattgodbolt** [comment]
I'm closing this bug now as all traces of `upx` are excised. In the next few weeks I'll separately experiment with alternative ways of reducing network traffic. Thanks for all the thoughts here.
