### ISSUE TITLE
Reports of issues with new glibc and libclang

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#961]
Reported over email, building with some unspecified clang and:

```#include <random> ```

or

```#include <iostream>```

with flags `-stdlib=libc++  -O0 -std=c++14`

Apparently shows the issue.

I've had issues building older clangs on the new Ubuntu nodes, requiring a hand-picked patch to fiddle the xlocale.h include.

The bug report over email included these links:

https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

https://www.linuxquestions.org/questions/slackware-14/no-luck-with-libc-on-current-xlocale-h-missing-4175612648/

https://github.com/llvm-mirror/libcxx/commit/6e02e89f65ca1ca1d6ce30fbc557563164dd327e

Which I haven't looked at as I'm away from decent Internet.

**Comment by RabsRincon** [comment]
A conf view @ https://godbolt.org/g/MYrCnb shows that from 5.0.0 it seems to work, but older ones seem to be affected

**Comment by mattgodbolt** [comment]
Gonna close this one...we have "enough" newer clangs to cover us I think. Happy to reopen if someone is still hurtin' from this.

**Comment by avikivity** [comment]
This is back with clang trunk: https://src.fedoraproject.org/rpms/openldap/c/09678ce9b0de890a82cbaeab54f0dc0d798a121d?branch=rawhide

**Comment by avikivity** [comment]
This is back with clang trunk: https://godbolt.org/z/GcncG9MGa

**Comment by mattgodbolt** [comment]
@avikivity can you be more specific here - I'm afraid I'm unable to decode my own original bug report (!)  and the link you shared compiles and runs but asserts? I don't recall that being the failure mode before (which is a compile issue relating to locales?)

**Comment by avikivity** [comment]
It's fixed again. The assert failure is the expected behavior (until [1] is fixed). The behavior I saw when reporting was a compilation failure.

[1] https://bugs.llvm.org/show_bug.cgi?id=48857
