### ISSUE TITLE
\s+ mode shouldn't be on by default

### ISSUE THREAD

**Issue by pcordes** [mattgodbolt/compiler-explorer#963]
Squashing spaces makes compiler output harder to read, sometimes *much* harder.  It's not helpful at all for most screen sizes unless an advanced user creates multiple output panes.

Some StackOverflow questions/answers that include compiler asm output get posted with this de-indented output, making it harder for *other people* to read the code (so the bad default has negatively affected me directly), but it would help people for their own use, too.

e.g. this ICC18 output: https://godbolt.org/g/G3KKGh

```
strlen_1(char const*):
  xor eax, eax #6.8
  cmp BYTE PTR [rdi], 0 #6.28
  je ..B1.6 # Prob 10% #6.28
  mov rdx, rax #6.4
..B1.3: # Preds ..B1.4 ..B1.2
  inc rdx #6.4
  lea rcx, QWORD PTR [rdx+rdx] #6.41
  cmp BYTE PTR [-1+rdi+rcx], 0 #6.28
  lea rax, QWORD PTR [-1+rdx*2] #6.41
  je ..B1.6 # Prob 18% #6.28
  mov rax, rcx #6.41
  cmp BYTE PTR [rdi+rcx], 0 #6.28
  jne ..B1.3 # Prob 82% #6.28
..B1.6: # Preds ..B1.3 ..B1.4 ..B1.1
  ret #7.11
```

(ICC puts comments on every line.  With color highlighting it's merely bad, not unintelligible.)

It's bad for other compilers with long mnemonics (e.g. x86 SIMD instructions like vpunpcklqdq) mixed with short instructions like `dec rdi`.

**Comment by RabsRincon** [comment]
Thanks for the feedback. I don't have any opinions for nor against this, and it's a 1 line change. So I'll default to whatever @mattgodbolt decides. But that can take a while, as he is currently with limited internet access

**Comment by mattgodbolt** [comment]
Great example of why `\s+` isn't a good default, @pcordes ! Thanks for the feedback. I personally like the squashed output for GCC etc, but you're right, it makes a right mess of `icc`'s lovely indented output.

Let's change the default to being off. It will still be on by default for embedded views, and of course it can be toggled on and off if individuals like the look of it.
