### ISSUE TITLE
Support MSVC compiling as C

### ISSUE THREAD

**Issue by ojeda** [mattgodbolt/compiler-explorer#969]
MSVC supports [compiling code as C](https://docs.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type).

Currently, one can achieve it by using one of the MSVC compilers available for C++ and specifying `/TC`. However, it might be useful to have the compilers shown in the C list.

**Comment by RabsRincon** [comment]
Hi! Thanks for your suggestion, it's a great idea. I plan to merge [mattgodbolt/compiler-explorer/tree/msvcc](https://github.com/mattgodbolt/compiler-explorer/tree/msvcc) tomorrow after ensuring everything works as expected. 
The demangler gets a bit confused right now, but that's something we can probably fix. (cc @partouf)

:)

**Comment by ojeda** [comment]
You're welcome! And thanks for implementing it up so quickly. :)

**Comment by partouf** [comment]
@RabsRincon it seems to me undname.exe is C++ only, so I would suggest reverting to c++filt

**Comment by RabsRincon** [comment]
Sounds like a good solution. Thank you both. Msvc should appear in the C compilers "soon" (sometime this week)
