### ISSUE TITLE
GDPR policy link on all pages

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#971]
https://dsgvo-muster-datenschutzerklaerung.dg-datenschutz.de/?lang=en

Need to fill this in and do linkage for GDPR compliance. Also reconsider google analytics and Twitter link

**Comment by mattgodbolt** [comment]
May also need to disable short URLs if people disagree. See #972 too

**Comment by RabsRincon** [comment]
I just read this
> May also need to disable short URLs if people disagree

Does it need to be done? It does not seem like something that falls under the gdpr stuff for me, but I'm by no means an expert.

Also, regarding embed views, how do we need to handle that? Do we not keep showing the popup?? I'm not sure at all of what to do there

**Comment by mattgodbolt** [comment]
> > May also need to disable short URLs if people disagree

> Does it need to be done? It does not seem like something that falls under the gdpr stuff for me, but I'm by no means an expert.

Hmm: good question. No. I think not. As long as the user has at some point had a chance to read the privacy policy, they will have had a chance to understand how the short URLs work.

**Comment by mattgodbolt** [comment]
Closed by numerous changes in the EU branch, merging and testing now.
