### ISSUE TITLE
Cookie law

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#972]
Need to ask before using local storage and or cookies
 Needs more research to see quite what is needed by EU law.

- [x] Change prod loggin format
- [x] Ensure we don't store access logs for too long
- [x] Turn on Google Analytics IP anonymization
- [x] Remove FullStory
- [x] Use simpler, compilant, twitter buttons ([Shariff](https://github.com/heiseonline/shariff)?)
- [x] Write cookie/privacy policy statements 
- [x] How do we store the consent?
- [ ] How do we log that we have been granted consent?

**Comment by RabsRincon** [comment]
http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2 mentions two usecases exempt from consent:
> user‑interface customisation cookies such as language or font preferences, for the duration of a session (or slightly longer)
> third‑party social plug‑in content‑sharing cookies, for logged‑in members of a social network.

The first one specifies "for the duration of a session or slightly longer" which is not what we do, so we probably still need to ask for consent there.
The second one probably saves us from the need to disable the share via Twitter button in case the user does not consent, but I'm not a lawyer, so better be safe than sorry?

**Comment by bugwelle** [comment]
> The second one probably saves us from the need to disable the share via Twitter button in case the user does not consent, but I'm not a lawyer, so better be safe than sorry?

Social media buttons were seen critical in Germany even before the EU GDPR existed. 

I would have a look at e.g. "Shariff - Give Social Media Buttons Some Privacy"
 - Project on GitHub: https://github.com/heiseonline/shariff
 - Background information (German article): https://www.heise.de/ct/artikel/Shariff-Social-Media-Buttons-mit-Datenschutz-2467514.html

The twitter button loads a bunch of javascript files that aren't really necessary. A button that links to twitter should be enough. Referrer and content of the tweet are encoded into the URL. Example

`https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fgodbolt.org%2F&ref_src=twsrc%5Etfw&text=Compiler%20Explorer&tw_p=tweetbutton&url=https%3A%2F%2Fgodbolt.org%2F%23&via=mattgodbolt`

with an image:

[![screenshot_20180627_083246](https://user-images.githubusercontent.com/1667306/41956665-b4270946-79e4-11e8-826c-d9476df1e519.png)](https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fgodbolt.org%2F&ref_src=twsrc%5Etfw&text=Compiler%20Explorer&tw_p=tweetbutton&url=https%3A%2F%2Fgodbolt.org%2F%23&via=mattgodbolt)

We shouldn't send user data to third party sites (which includes embedding a tweet button) unless it's essential to the project (e.g. Google URL shortener) and that's what the GDPR wants us to do.

Let me know if I missed something. :)

**Comment by RabsRincon** [comment]
Thanks for the lengthy explanation @bugwelle 
I'll take a look at shariff, it seems to be super useful, thanks for the tip :)

Logfiles are currently handled by Papertrail, so _at least_ that last point is ok.
Now, the rest of them... Well, not much, but it should not be hard to fix.

> Unnecessary identifiers should not be logged – these include source port number, timestamps, transport protocol numbers, and destination port numbers; and

Does the timestamp bit refer to when the request was made? That's a bit of a letdown, but we have to comply so..


Again, thanks for the information given, it's extremely useful.

**Comment by bugwelle** [comment]
I'm unsure about the timestamp part. If the IP address is already anonymized it should already be enough (I simply copied the list from theregister.co). At least that's what I do for my private websites.

----------------

Plugins like [uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/) block a lot of scripts. If I open uMatrix on godbolt.org, it gives me following table:

![screenshot_20180627_184258](https://user-images.githubusercontent.com/1667306/41987655-0e9add26-7a3a-11e8-89bf-e14e2215cb53.png)

I'd say you're good to go if fullstory and twitter are removed.
Google Analytics can be used in a GDPR compliant way. A quick search lists for example https://www.cookiebot.com/en/google-analytics-gdpr/ (see checklist in that article)
You should also add a paragraph about Google Analytics to your privacy policy (just a simple page that explains how you store data). *Note:* I haven't worked with Google Analytics myself (I use [Matomo](https://matomo.org/)).

If Papertrail processes IP addresses you should also mention it. :) 

----------------

The "Tweet" button really just redirects to twitter. Replacing it with an image or just a link will have the same result but won't load any scripts. "Shariff" might be overkill for godbolt.org.


Regards,
Andre
