### ISSUE TITLE
ARMv6 compilation failure

### ISSUE THREAD

**Issue by Cyan4973** [mattgodbolt/compiler-explorer#99]
On https://gcc.godbolt.org,
when selecting GCC ARM v4.8.2
and specifying `-march=armv6` (or any similar variant) on the compiler flag line,
it generates the following error :

```
In file included from /usr/arm-linux-gnueabihf/include/features.h:374:0,
from /usr/arm-linux-gnueabihf/include/memory.h:25,
from /tmp/gcc-explorer-compiler116119-74-29lxj8/example.cpp:1:
/usr/arm-linux-gnueabihf/include/string.h: In function 'void* memchr(void*, int, size_t)':
/usr/arm-linux-gnueabihf/include/string.h:83:41: sorry, unimplemented: Thumb-1 hard-float VFP ABI
memchr (void *__s, int __c, size_t __n) __THROW
```

Same program works fine with GCC ARM v4.6 and v4.5 with `-march=armv6`.
Same program works fine with default march settings or `-march=armv7`.

Seems to be a problem specific to installed configuration of GCC 4.8 && armv6

**Comment by mattgodbolt** [comment]
I seem to have lost ARM 4.8.4 gcc, but all the other compilers now work with this setting.
