### ISSUE TITLE
Source <=> LLVM IR line highlighting

### ISSUE THREAD

**Issue by bugwelle** [mattgodbolt/compiler-explorer#991]
This project is awesome! :tada: 
I've been watching for quite some time now. I often refer to it in discussions when arguing about whether "X is better/worse than Y". It's also great for developers working on compilers! Having a side by side view with lines highlighted makes development a lot easier.

I'd say that many languages (may they be real languages or some languages implemented just for fun or at universities) use LLVM and its intermediate representation. And here comes my proposal/question: I think many people interested in compiler construction would love it if "Compiler Explorer" (CE) also adds color highlighting for LLVM IR (e.g. `CPP > LLVM IR`).

As far as I can tell, CE is "hard coded" for assembler which makes me wonder: 
Is this something that could be supported by CE or should maybe a fork of CE handle this?

I experimented with LLVM IR and CE and implemented some basic highlighting (see screenshot below).

![llvm-ir-highlighting](https://user-images.githubusercontent.com/1667306/42341706-45da5a54-8094-11e8-920b-768dd8003cda.png)

This would be awesome to have on CE! I really don't know anything about LLVM IR and just started learning it, so my "implementation" is quick and dirty. :smiley: 
But it is definitely possible although it may take quite some work.

*Note:* I formatted my example (see below) on purpose in that way because LLVM debug information also includes column information which is not yet supported by CE. If I it were normally formatted, my current solution would mark almost all IR code the same color.

```cpp
void maxArray(
    double* x, 
    double* y)
{
    for (
        int i = 0; 
        i < 65536; 
        i++)
    {
        if (y[i] > 
            x[i])
        {
                x[i] = 
                y[i];
        }
    }
}


```

Example code with LLVM IR output on CE: https://godbolt.org/g/rq9n6t

*I found some issues regarding LLVM highlighting but all of those meant syntax highlighting in the editor.* :smile: 

I'd love to hear your thoughts on this. :)

Regards,
Andre

**Comment by mattgodbolt** [comment]
Hi there!

I very much welcome having better LLVM IR support. We already support compiling _from_ IR, but tagging the output and syntax highlighting it "properly" would be great.

The basic ASM highlighting sort-of works for LLVM IR already; though all the annotations (`%13 = ...` etc) looks horrible. It would be better to use monarch's built-in highlighting and change the editor to use that (as we do between input languages). See example modes like https://github.com/mattgodbolt/compiler-explorer/blob/master/static/asm-mode.js for example. There's an online syntax highlighter editor at https://microsoft.github.io/monaco-editor/monarch.html

Having a different "asm" parser for LLVM IR would be fine by me, to support the different line-tracking code. 

The biggest trick is "detecting" LLVM output: there's no definite way in general to notice the assembly output is actually LLVM IR, we'd need a regex-based heuristic to note it and select both the alternative ASM processor on the server, as well as notify the client to use the different syntax highlighter.

I think this would be a fantastic addition!

**Comment by bugwelle** [comment]
Thanks for your reply! :smiley: 

> The biggest trick is "detecting" LLVM output

True. I wonder if detecting whether it's ASM or LLVM IR just before selecting the proper processor is too late. There's a bunch of filters and options (binary output/executing,...) that are valid for ASM output but would most likely fail or be unnecessary for LLVM IR.  

I thought about a per compiler flag whether LLVM IR is supported and maybe a switch between ASM and LLVM IR. But then again: Automatically detecting the correct format may prove to be more elegant (I'd expect LLVM IR when setting `-emit-llvm`, etc.).

**Comment by bugwelle** [comment]
Discussion on how to implement this  has moved to my PR :)
https://github.com/mattgodbolt/compiler-explorer/pull/992

**Comment by mattgodbolt** [comment]
Thanks to @bugwelle this is now in `master`!

**Comment by mattgodbolt** [comment]
So so sorry this took so many months to get merged in. I am now trying my hardest to ensure PRs like yours don't get lost. This is an excellent feature that CE could have been benefiting from for nearly 3 months now. @bugwelle - do you have a Twitter handle I can tweet out to when we release this?

**Comment by bugwelle** [comment]
@mattgodbolt No need to apologize. Thanks for merging this feature. :smile: 

My Twitter handle is @bugwellen (German plural; my GitHub username is taken by a bot there...)
My handle on reddit is u/bugwelle just as my GitHub one. :-)

**Comment by bugwelle** [comment]
Works like a charm! Thanks!

Demo: https://godbolt.org/beta/z/rWb89T

**Comment by bugwelle** [comment]
And Rust works as well: https://godbolt.org/z/JyYFnt :)
