### ISSUE TITLE
Arm gcc 7.2.1 (none) uses cdefs.h from incorrect architecture

### ISSUE THREAD

**Issue by lucazader** [mattgodbolt/compiler-explorer#994]
Maybe a duplicate of #989 

It seems that when a user utilities some std libraries that includes a file from `sys` the compiler explorer looks for these under the host cpu architecture, rather than from the sys folder inside the arm-eabi-none directory.

The error as presented by gcc:
```
In file included from /opt/compiler-explorer/arm/gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/time.h:11:0,
                 from /opt/compiler-explorer/arm/gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/c++/7.2.1/ctime:42,
                 from /opt/compiler-explorer/arm/gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/c++/7.2.1/chrono:41,
                 from <source>:1:

/usr/include/x86_64-linux-gnu/sys/cdefs.h:23:11: fatal error: features.h: No such file or directory
 # include <features.h>
```

As you can see when trying to use the `arm-none-eabi/include/time.h` file, the compiler looks for the `sys/cdefs.h` include in an incorrect location. It should look under `gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/sys/

Below is the code that I was trying when i first encountered this issue.
https://godbolt.org/g/czc3RB

Let me know if there is anything else that I can provide to help diagnose this issue, or if there is anything that i have missed out.

**Comment by cmuellner** [comment]
I ran into this issue as well today (after updating compiler-explorer).
In my case I have an aarch64 cross-compiler (with its own sysroot including all required headers).
I can confirm, that compilation works on command line.
Therefore I assume that there is an issue with adding system include path (which must not happen for cross compilers).

**Comment by mattgodbolt** [comment]
@cmuellner can you clarify what you mean - are you running a local compiler-explorer? Are you suggesting there might be an issue in the way CE executes compilers that might explain why we're not getting the right sysroot? It's quite possible -- if you have a local instance that works from the command-line but not from within a local Compiler Explorer we can hopefully use your system to work out what's going on!

**Comment by cmuellner** [comment]
@mattgodbolt Yes, I'm running a local compiler-explorer instance.
What I'd like to have is a way to see the whole compiled source code and the whole command line that is executed to compile it. I get some info from the '!' in the web frontend, but that's not complete and the there mentioned `/tmp/compiler-explorer.../example.cpp` does not exist (anymore?). Logs just output the HTTP requests.

I'm running CE git master HEAD (`95befee`) with no changes at all.

The code I'm compiling is the following:

```
#if 1
#include <stdint.h>
#else
typedef unsigned long uint64_t;
typedef unsigned char uint8_t;
#endif

uint64_t myadd(uint64_t a, uint64_t b)
{
    return a + b;
}
```

I can successfully compile this with the following command line (inspired by the information the web frontend provides):
`~/compilers/crosstools/amp-7.3.0-20180630/bin/aarch64-amp-linux-gnu-gcc -g -o myadd.s -S -fdiagnostics-color=always -O3 myadd.c`.

When compiling with CE, then I get the following error:

```
In file included from /home/cexplorer/compilers/crosstools/amp-7.3.0-20180630/aarch64-amp-linux-gnu/sysroot/usr/include/features.h:452:0,
                 from /home/cexplorer/compilers/crosstools/amp-7.3.0-20180630/aarch64-amp-linux-gnu/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /home/cexplorer/compilers/crosstools/amp-7.3.0-20180630/aarch64-amp-linux-gnu/sysroot/usr/include/stdint.h:26,
                 from /home/cexplorer/compilers/crosstools/amp-7.3.0-20180630/lib/gcc/aarch64-amp-linux-gnu/7.3.0/include/stdint.h:9,
                 from <source>:2:
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
           ^~~~~~~~~~~~~~~~
compilation terminated.
Compiler returned: 1
```

My host CE host is a x86_64 machine running Debian with node 8 LTS.
My toolchain is a aarch64 cross-compiler for x86_64, which supports multiarch (LP64 and ILP32) based on GCC 7.3.0. I can reproduce the problem with `gcc` and `g++`.
In my CE config I just added the compiler `.exe` and `.name`.

In case you want to test with the toolchain, you can download it from here (amp-7.3.0-20180630/amp-7.3.0-20180630-crosstools.tar.xz): `https://www.theobroma-systems.com/go/amp-7.3.0`.

**Comment by RabsRincon** [comment]
Hi @cmullner.
Specifically regarding:
> I get some info from the '!' in the web frontend, but that's not complete and the there mentioned /tmp/compiler-explorer.../example.cpp does not exist (anymore?).

I have two questions. The UI `!` icon should be reporting every option sent to the compiler by CE. Can you please confirm if this is not the case for you?

You also mention the temp file. Note that:
 - Its contents are just what you type into the editor
 - It gets deleted by CE after compilation is done.
Were you expecting any of this to happen differently? We'd be very happy to know about different use cases and how this current CE behaviour affects said cases

:)

**Comment by cmuellner** [comment]
The `!` gives me: `-g -o /tmp/compiler-explorer-compiler118614-26166-1oiohla.zpo7/output.s -S -fdiagnostics-color=always -O3 /tmp/compiler-explorer-compiler118614-26166-1oiohla.zpo7/example.cpp`. CE says, that compilation fails (see previous post).

When I invoke `~/compilers/crosstools/amp-7.3.0-20180630/bin/aarch64-amp-linux-gnu-gcc -g -o myadd.s -S -fdiagnostics-color=always -O3 myadd.c` on the command line the compilation works fine (with myadd.c containing the code in my previous comment above).

So what can be wrong here? I see two possible causes: I) CE adds additional include paths (e.g. by adding `-I` flags to the command line), II) CE adds additional includes to the source.

I cannot confirm that CE does not add anything to the source or to the compiler invocation. The reason is, that I haven't found out yet, how to do so. Any hints are appreciated.

When you tell me, that CE does not add additional includes to the source code, that's fine.
But then I wonder, what else CE is doing different than my working command line invocation.

And of course I don't expect that CE does not delete temporary files. But doing so would help me to debug the problem.

**Comment by mattgodbolt** [comment]
Very peculiar indeed.

Something else that CE does though, is manipulate the environment. I think this is what's going on! Hooray, you've got it!

So, to handle some weird ubuntu compilation issues, we run the local compiler (/bin/gcc) and see if it has mult-arch. If so, and if the compiler being run is configured (default: yes!) then we also put in the multi-arch directories using `INCLUDE_PATH` etc:  https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/compilation-env.js#L65

So, we need to configure all the cross-compilers to not be `needsMulti`. That will definitely help (if not fix!) some of the issues!

**Comment by mattgodbolt** [comment]
More interestingly, I think that actually multi-arch is unnecessary on the CE nodes now (we no longer have a weird situation of some compilers built on RH6, some on Ubuntu)...so, I think I will get rid of it for the live site.

**Comment by mattgodbolt** [comment]
Removed in f6d0d77a753504c51915394111714606d9f57615; will do some testing then do a site update.

**Comment by cmuellner** [comment]
@mattgodbolt Thank's for pointing to that. Works now. Thank's a lot.
One last question: how to clean the cached compilation results?

**Comment by cmuellner** [comment]
Found it (UI -> Compilation Results -> Circle symbol in lower right corner).
And sorry if the original issue of this ticket is not related to my problem (i.e. for hijacking it).

**Comment by mattgodbolt** [comment]
no problem @cmuellner .
