### ISSUE TITLE
Relatively large template parameter list brings down the whole site

### ISSUE THREAD

**Issue by murderotica** [mattgodbolt/compiler-explorer#995]
From what I understand there are some guards that terminate compilation when certain time/memory threshold has been reached, however, I've found an edge case that brings down the whole site to a grind (either **502 Bad Gateway** or even makes the whole site unresponsive)

Here's the repro:

```c++
#include <type_traits>
#include <utility>

template<size_t I>
struct Idx{};

template<size_t Count>
struct make_idx
{
    template<typename... Ts>
    struct idx_t{
        static constexpr void test() {}
    };

    template<size_t... Is>
    static constexpr auto get_type_impl(std::index_sequence<Is...>)
    {
        return idx_t<Idx<Is>...>{};
    }
    using type = decltype(get_type_impl(std::make_index_sequence<Count>{}));
};

int main()
{
    using large_template = make_idx<10000>::type;
    large_template::test();
}
```

Use large **Count** (>10000)

**Comment by bugwelle** [comment]
I tried this locally. Node (and GCC) take 100% CPU and I can't reload the site. Node doesn't respond to requests anymore either.

I closed the browser tab 10 minutes ago and both gcc and node still run at 100% CPU.
I had to kill the process.

**Comment by RabsRincon** [comment]
Hi @murderotica Thanks for the report. Just in case, I've redacted the offending code from the post until we get a chance to look into it later today.

We'll keep you updated

**Comment by mattgodbolt** [comment]
"Relatively large" hehe :)

I compiled the snippet:

```
$ /opt/compiler-explorer/gcc-8.1.0/bin/g++ -g -o /tmp/foo.s -masm=intel -S -std=c++1z /tmp/foo.cc
```

There's a call to a template function whose mangled name is...pretty large:

```
$ grep call /tmp/foo.s | wc -c
118937
```

The line starts something like:

```
        call    _ZN8make_idxILm10000EE5idx_tIJ3IdxILm0EES2_ILm1EES2_ILm2EES2_ILm3EES2_ILm4EES2_ILm5EES2_ILm6EES2_ILm7EES2_ILm8EES2_ILm9EES2_ILm10EES2_ILm11EES2_ILm12EES2_ILm13EES2_ILm14EES2_ILm15EES2_ILm16EES2_ILm17EES2_ILm18EES2_ILm19EES2_ILm20EES2_ILm21EES2_ILm22EES2_ILm23EES2_ILm24EES2_ILm25EES2_ILm26EES2_ILm27EES2_ILm28EES2_ILm29EES2_ILm30EES2_ILm31EES2_ILm32EES2_ILm33EES2_ILm34EES2_ILm35EES2_ILm36EES2_ILm37EES2_ILm38EES2_ILm39EES2_ILm40EES2_ILm41EES2_ILm42EES2_ILm43EES2_ILm44EES2_ILm45EES2_ILm46EES2_ILm47EES2_ILm48EES2_ILm49EES2_ILm50EES2_ILm51EES2_ILm52EES2_ILm53EES2_ILm54EES2_ILm55EES2_ILm56EES2_ILm57EES2_ILm58EES2_ILm59EES2_ILm60EES2_ILm61EES2_ILm62EES2_ILm63EES2_ILm64EES2_ILm65EES2_ILm66EES2_ILm67EES2_ILm68EES2_ILm69EES2_ILm70EES2_ILm71EES2_ILm72EES2_ILm73EES2_ILm74EES2_ILm75EES2_ILm76EES2_ILm77EES2_ILm78EES2_ILm79EES2_ILm80EES2_ILm81EES2_ILm82EES2_ILm83EES2_ILm84EES2_ILm85EES2_ILm86EES2_ILm87EES2_ILm88EES2_ILm89EES2_ILm90EES2_ILm91EES2_ILm92EES2_ILm93EES2_ILm94EES2_ILm95EES2_ILm96EES2_ILm97EES2_ILm98EES2_ILm99EES2_ILm100EES2_ILm101EES2_ILm102EES2_ILm103EES2_ILm104EES2_ILm105EES2_ILm106EES2_ILm107EES2_ILm108EES2_ILm109EES2_ILm110EES2_ILm111EES2_ILm112EES2_ILm113EES2_ILm114EES2_ILm115EES2_ILm116EES2_ILm117EES2_ILm118EES2_ILm119EES2_ILm120EES2_ILm121EES2_ILm122EES2_ILm123EES2_ILm124EES2_ILm125EES2_ILm126EES2_ILm127EES2_ILm128EES2_ILm129EES2_ILm130EES2_ILm131EES2_ILm132EES2_ILm133EES2_ILm134EES2_ILm135EES2_ILm136EES2_ILm137EES2_ILm138EES2_ILm139EES2_ILm140EES2_ILm141EES2_ILm142EES2_ILm143EES2_ILm144EES2_ILm145EES2_ILm146EES2_ILm147EES2_ILm148EES2_ILm149EES2_ILm150EES2_ILm151EES2_ILm152EES2_ILm153EES2_ILm154EES2_ILm155EES2_ILm156EES2_ILm157EES2_ILm158EES2_ILm159EES2_ILm160EES2_ILm161EES2_ILm162EES2_ILm163EES2_...
```

Will dig as to why the demangler stage croaks on this though!

**Comment by mattgodbolt** [comment]
It's not the demangler. As well as having that one giant line there are many labels and I think there's some interaction between the O(N^2 or worse) "find dead code" and this...

**Comment by mattgodbolt** [comment]
Also @bugwelle I don't see GCC taking 100% CPU when I run locally - are you sure it took 100% CPU? GCC runs just fine and completes, and then node.js chokes on the input.

**Comment by mattgodbolt** [comment]
Ok traced back to a very dodgy regular expression in AsmParser.js:

/.*\.(entry|func)\s+(?:\([^)]*\)\s*)?([.a-zA-Z_$][a-zA-Z0-9$_.]*)\($/

Which takes an astronomically long time on the long line :)  Will fix...

**Comment by mattgodbolt** [comment]
Turns out starting your regex with `.*` isn't a great idea for performance...

**Comment by bugwelle** [comment]
> Also @bugwelle I don't see GCC taking 100% CPU when I run locally - are you sure it took 100% CPU? GCC runs just fine and completes, and then node.js chokes on the input.

Sorry, my bad. I must have mixed it up with another process that was running on my machine (I just had a quick look at it using `htop`). Only node had a high workload. :)

**Comment by bugwelle** [comment]
There are seven Regex in `./lib` that start with `const re = /.* ...`. Can't we simply remove `.*` as the regex will essentially still be the same (it just won't match the characters before the actual regex which isn't a problem as we don't process them anyway). Maybe I'm missing edge cases but that's what I think with my current understanding of JavaScript regex. :)

**Comment by mattgodbolt** [comment]
@bugwelle absolutely. Unless the `match` needs the whole matching line then it's equivalent. In 478ac62 I do the main ones that matter for this bug.

**Comment by RabsRincon** [comment]
Compiling the code sample now works as expected. 
Thanks!

For the record, I've readded the code to the issue
@bugwelle let us know if we can help in something if you decide to open a PR for those remaining regexes :)
