### ISSUE TITLE
rustc nightly compiler disappears occasionally

### ISSUE THREAD

**Issue by mjbshaw** [mattgodbolt/compiler-explorer#997]
For the past several hours, there has been no `rustc nightly` compiler. Only the `beta` and `1.0.0`-`1.26.0` compilers.

This isn't the first time that the `rustc nightly` compiler has disappeared. I've noticed it has disappeared in the past a few times per week (after which it magically reappears).

I've wondered if this is perhaps a problem with the script that updates the nightly compiler version, but I haven't been able to figure out how Compiler Explorer updates its `rustc nightly` compiler version. I'm happy to poke around and investigate this further, but don't know where to start.

**Comment by RabsRincon** [comment]
Hi @mjbshaw , thanks for the report, it seems you're onto something.
For reference, the scripts that build the nightly compilers are placed on the sister repo at [https://github.com/mattgodbolt/compiler-explorer-image](mattgodbolt/compiler-explorer-image).
Specifically, the installation is done by the `update_compilers/install_compilers.sh` file 

Now, regarding this issue, I can see the nightly builds failling on the rust compiler with the following debug output:
```
+ PATCHELF=/opt/compiler-explorer/patchelf-0.8/src/patchelf
+ [[ ! -f /opt/compiler-explorer/patchelf-0.8/src/patchelf ]]
+ install_nightly
+ [[ nightly = \n\i\g\h\t\l\y ]]
+ return 0
+ install_new_rust nightly '1 day'
+ local NAME=nightly
+ local 'FORCE=1 day'
+ local DIR=rust-nightly
+ [[ -n 1 day ]]
+ [[ -d rust-nightly ]]
++ date -d 'now - 1 day' +%s
+ local time_from=1531278302
++ date -r rust-nightly +%s
+ local dir_time=1531191981
+ ((  dir_time > time_from  ))
+ [[ -n 1 day ]]
+ echo Forcing install of nightly
+ rm -rf rust-nightly
+ [[ -d rust-nightly ]]
+ echo Installing rust nightly
+ do_rust_install rust-nightly-x86_64-unknown-linux-gnu rust-nightly
+ local DIR=rust-nightly-x86_64-unknown-linux-gnu
+ local INSTALL=rust-nightly
+ pushd /tmp
+ tar zxvf -
+ fetch http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
+ curl -s -L http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

I wonder what's happening there

**Comment by mattgodbolt** [comment]
Good spot @RabsRincon (and @mjbshaw ) I'll manually retry the installation process in case it was a transient error. If it starts happening a lot we will have to do a more defensive update process.

**Comment by mjbshaw** [comment]
Nice, thanks for the quick investigation and the pointer to compiler-explorer-image!

I can think of two ways to fix this, one short term and one long term:

1. Short term: Modify the script so it only executes `rm -rf rust-${NAME}` *after* successfully downloading the new `.tar.gz`.
2. Long term: Move to something like rustup (which would also help address #898, #786, and #496, all of which I'm personally interested in).

I actually use Compiler Explorer for Rust a lot, and it's been an incredibly valuable tool (thank you so much Matt & Co.!). It seems only fair for me to try to invest a little bit of my time into helping in any way I can.

I'm happy to write a patch with the short-term fix, as well as tinker with using rustup (if you're open to it) to add additional targets. Monkeying with `install_compilers.sh` looks easy enough, but I'm not sure how to test the modifications. Are there any guidelines on how to test modifications to `install_compilers.sh`?

> If it starts happening a lot we will have to do a more defensive update process.

I use Compiler Explorer with nightly Rust frequently enough that I see this pretty often, though it usually resolves relatively quickly (which probably means I'm just unfortunate and am hitting the server when it's in the middle of updating (after the `rm -rf`, but before the installation completes)).

**Comment by RabsRincon** [comment]
Hi @mjbshaw thanks for showing intereset in helping us out :)
> I'm happy to write a patch with the short-term fix, as well as tinker with using rustup (if you're open to it) to add additional targets
Yes to both! Most of the requested features that have not been yet done are partially because we lack the time, so it would be awesome to get some help on the Rust side 👍 

Some tips to test compiler explorer scripts:
The scripts work on the `/opt/compiler-explorer/` dir, which is where most of the CE stuff resides.
The downside is that, as it stands, `install_compilers.sh` will try to download ~80GB of compilers, which might not be desirable, so I recommend you strip out unrelated compilers when testing.
Note that in order to get the nightly compilers installed, you should call `install_compilers.sh nightly`.

After that, it's then just a matter of running a local instance of the site if needed (For example, if you need to test the compilers installed with rustup) [The README has more info on this](https://github.com/mattgodbolt/compiler-explorer/blob/master/README.md#developing)

Do let us know if we can help, and we'll try our best :)


Thanks again for taking the time to improve CE

**Comment by mattgodbolt** [comment]
We would be happy if you split it into a install_rust.sh or similar too: then you could test just by running that one script locally. We would then update the daily tasks to run the rust job too. It's already unwieldy with all the compilers in one installation file...

**Comment by weiby3** [comment]
I found that the nightly rust compiler disappeared again. Is this problem solved?

**Comment by mjbshaw** [comment]
Yeah, I've been noticing this too lately. I wonder if a more robust way to do this would be to install the compiler into a temporary directory, and then perform a couple directory renames to replace the old nightly with the new nightly (and then after the renames are done, delete the old nightly). Alternatively, symlinks could be used to make this properly atomic.
